import { useEffect, useRef, useState } from "react";
import { api } from "../../api/client";
import { CcButton } from "../../components/cc-button";
import { CcField } from "../../components/cc-field";
import { CcSelect } from "../../components/cc-select";
import { CcNotice } from "../../components/cc-notice";
import { CcRecordEditorModal } from "../../components/cc-record-editor";
import { useLanguage } from "../../i18n/i18n";
const messages = {
 en:{title:"Capability suspension",active:"Capability blocked",restored:"Capability restored",next:"Provide cause, impact, repair and regression evidence. A separate person must verify the package before the owner restores this scope.",boundary:"Restoration requires new grants. Stopped work needs fresh context and replanning. Owner changes are never undone automatically.",create:"Classify serious incident and suspend",close:"Close",refresh:"Refresh",choose:"Choose",empty:"No suspensions in this scope.",history:"Decision and evidence history",reason:"Reason",scopeProof:"Evidence of affected scope",broaderReason:"Owner justification for the whole task operation",incidentId:"Incident",taskId:"Task and application",applicationId:"Application",issuerUserId:"Suspended by",operation:"Operation",agentId:"Agent (optional)",credentialId:"Credential (optional)",hostId:"Host (optional)",cause:"Cause",impact:"Impact",remediation:"Repair",regressionProof:"Regression proof and observed result",limitations:"Limits of the proof",repairAuthorUserId:"Repair author",assessment:"Independent assessment",evidence:"Record a new evidence version",verify:"Verify evidence independently",restore:"Owner: restore capability",reject:"Owner: reject evidence",reopen:"Owner: reopen suspension",manual_intervention:"Owner: record manual intervention",review_decision:"Review decision",return_to_executor:"Return to executor",create_specialist_task:"Create specialist task",runtime_execute:"Run native execution",save:"Record decision",error:"Could not record or load the current state. Refresh and check your authority, version and evidence.",loading:"Loading suspension state",saved:"Recorded",truncated:"The display is limited. Open the relevant task or incident for a narrower view.",discard:"Discard unsaved evidence?",stay:"Keep editing",leave:"Discard",version:"Version",scope:"Affected scope",optional:"No additional restriction",broad:"Without agent or host restriction, the owner must justify blocking this operation for the whole task.",confirm:"I confirm this explicit decision for the displayed scope and evidence version.",blockedHint:"An active suspension applies to this task. Inspect its exact operation and principal before acting."},
 pl:{title:"Zawieszenie uprawnień",active:"Uprawnienie zablokowane",restored:"Uprawnienie przywrócone",next:"Zapisz przyczynę, wpływ, naprawę i dowód regresji. Osobna osoba musi zweryfikować pakiet, zanim właściciel przywróci uprawnienie w tym zakresie.",boundary:"Przywrócenie wymaga nowych grantów. Zatrzymana praca wymaga świeżego kontekstu i przeplanowania. Zmiany właściciela nigdy nie są automatycznie cofane.",create:"Oznacz poważny incydent i zawieś",close:"Zamknij",refresh:"Odśwież",choose:"Wybierz",empty:"Brak zawieszeń w tym zakresie.",history:"Historia decyzji i dowodów",reason:"Powód",scopeProof:"Dowód zakresu wpływu",broaderReason:"Uzasadnienie właściciela dla całej operacji w zadaniu",incidentId:"Incydent",taskId:"Zadanie i aplikacja",applicationId:"Aplikacja",issuerUserId:"Uprawnienie zawiesił",operation:"Operacja",agentId:"Agent (opcjonalnie)",credentialId:"Poświadczenie (opcjonalnie)",hostId:"Host (opcjonalnie)",cause:"Przyczyna",impact:"Wpływ",remediation:"Naprawa",regressionProof:"Dowód regresji i zaobserwowany wynik",limitations:"Ograniczenia dowodu",repairAuthorUserId:"Autor naprawy",assessment:"Niezależna ocena",evidence:"Zapisz nową wersję dowodów",verify:"Zweryfikuj dowody niezależnie",restore:"Właściciel: przywróć uprawnienie",reject:"Właściciel: odrzuć dowody",reopen:"Właściciel: wznów zawieszenie",manual_intervention:"Właściciel: zapisz ręczną interwencję",review_decision:"Decyzja recenzenta",return_to_executor:"Zwrot do wykonawcy",create_specialist_task:"Utworzenie zadania specjalisty",runtime_execute:"Wykonanie natywne",save:"Zapisz decyzję",error:"Nie udało się zapisać lub pobrać aktualnego stanu. Odśwież i sprawdź uprawnienia, wersję oraz dowody.",loading:"Wczytywanie stanu zawieszenia",saved:"Zapisano",truncated:"Widok ma limit. Otwórz właściwe zadanie lub incydent, aby zawęzić zakres.",discard:"Odrzucić niezapisane dowody?",stay:"Kontynuuj edycję",leave:"Odrzuć",version:"Wersja",scope:"Zakres wpływu",optional:"Bez dodatkowego ograniczenia",broad:"Bez wskazania agenta lub hosta właściciel musi uzasadnić blokadę tej operacji dla całego zadania.",confirm:"Potwierdzam jawną decyzję dla widocznego zakresu i wersji dowodów.",blockedHint:"To zadanie ma aktywne zawieszenie. Przed działaniem sprawdź jego operację i wskazanego wykonawcę."}
};
export function SuspensionNotice({items,onOpen}:{items:any[];onOpen:()=>void}){
 const {locale}=useLanguage(),c=messages[locale==="pl"?"pl":"en"];
 return items?.some(s=>s.active)?<CcNotice tone="warning" title={c.active}><p>{c.blockedHint}</p><CcButton size="sm" variant="outline" onClick={onOpen}>{c.title}</CcButton></CcNotice>:null;
}
export function CapabilitySuspensionModal({taskId,incidentId,onClose}:{taskId?:string;incidentId?:string;onClose:()=>void}){
 const {locale}=useLanguage(),c=messages[locale==="pl"?"pl":"en"],label=(key:string)=>(c as any)[key]??key;
 const [list,setList]=useState<any>(null),[detail,setDetail]=useState<any>(null),[catalog,setCatalog]=useState<any>(null),[creating,setCreating]=useState(false);
 const [busy,setBusy]=useState(true),[error,setError]=useState(false),[saved,setSaved]=useState(false),[draft,setDraft]=useState<Record<string,string>>({operation:"review_decision",incidentId:incidentId??""}),[action,setAction]=useState("evidence"),[dirty,setDirty]=useState(false),[leave,setLeave]=useState(false),[confirmed,setConfirmed]=useState(false);
 const mounted=useRef(true),request=useRef<{signature:string;id:string}|null>(null),notice=useRef<HTMLDivElement>(null),root="/v1/agent-runtime/capability-suspensions";
 async function load(id?:string){setBusy(true);setError(false);try{const r=await api<any>(id?`${root}/${id}`:`${root}?${new URLSearchParams({...taskId?{taskId}:{},...incidentId?{incidentId}:{}})}`);if(mounted.current){id?setDetail(r.data):setList(r.data);}}catch{if(mounted.current)setError(true);}finally{if(mounted.current)setBusy(false);}}
 useEffect(()=>{mounted.current=true;void load();return()=>{mounted.current=false;};},[taskId,incidentId]);
 function edit(key:string,value:string){setDraft(d=>({...d,[key]:value,...key==="agentId"?{credentialId:""}:key==="operation"?{credentialId:"",hostId:""}:{}}));setDirty(true);setSaved(false);setConfirmed(false);}
 function close(){if(busy)return;dirty?setLeave(true):onClose();}
 async function create(){setBusy(true);setError(false);try{const r=await api<any>(root+"/catalog"+(taskId?"?taskId="+taskId:""));if(mounted.current){setCatalog(r.data);setCreating(true);setDetail(null);setDraft({operation:"review_decision",incidentId:incidentId??"",taskId:r.data.tasks.find((t:any)=>t.id===taskId)?`${taskId}:${r.data.tasks.find((t:any)=>t.id===taskId).applicationId}`:""});}}catch{if(mounted.current)setError(true);}finally{if(mounted.current)setBusy(false);}}
 const evidence=detail?.history.find((h:any)=>h.action==="evidence");
 const verification=evidence&&detail?.history.find((h:any)=>h.action==="verify"&&h.evidenceId===evidence.id);
 const staleEvidence=evidence&&detail.history.some((h:any)=>h.version>evidence.version&&["reject","reopen","manual_intervention"].includes(h.action));
 const canVerify=detail?.active!==false&&evidence&&!staleEvidence&&evidence.actorUserId!==detail.currentUserId&&evidence.payload.repairAuthorUserId!==detail.currentUserId;
 const actions=detail?[...(detail.suspension.active&&detail.canEdit?["evidence",...canVerify?["verify"]:[]]:[]),...(detail.canDecide?[...(detail.suspension.active&&verification&&!staleEvidence?["restore"]:[]),"reject","reopen","manual_intervention"]:[])]:[];
 const chosen=actions.includes(action)?action:actions[0];
 const field=(key:string,required=true)=><CcField key={key} label={label(key)} required={required}>{({id,describedBy})=><textarea id={id} aria-describedby={describedBy} className="textarea textarea-bordered min-h-24 w-full" required={required} minLength={required?3:undefined} maxLength={2000} disabled={busy} value={draft[key]??""} onChange={e=>edit(key,e.target.value)}/>}</CcField>;
 const select=(key:string,options:any[],required=false)=><CcField key={key} label={label(key)} required={required}>{({id})=><CcSelect id={id} disabled={busy} required={required} value={draft[key]??""} onChange={e=>edit(key,e.target.value)}><option value="">{required?c.choose:c.optional}</option>{options.map(o=><option key={o.id} value={o.id}>{o.label??o.name??o.title??o.id}</option>)}</CcSelect>}</CcField>;
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;let input:any,url=root;
  if(creating){const [selectedTask,applicationId]=String(draft.taskId).split(":");input={taskId:selectedTask,applicationId,incidentId:draft.incidentId,operation:draft.operation,reason:draft.reason,scopeProof:draft.scopeProof,...draft.agentId?{agentId:draft.agentId}:{},...draft.credentialId&&draft.operation!=="runtime_execute"?{credentialId:draft.credentialId}:{},...draft.hostId&&draft.operation==="runtime_execute"?{hostId:draft.hostId}:{},...!draft.agentId&&!draft.hostId?{broaderReason:draft.broaderReason}:{}};}
  else{url+=`/${detail.suspension.id}/actions`;input={expectedVersion:detail.suspension.version,action:chosen,...chosen==="evidence"?Object.fromEntries(["cause","impact","remediation","regressionProof","limitations","repairAuthorUserId"].map(k=>[k,draft[k]])):chosen==="verify"?{evidenceId:evidence.id,assessment:draft.assessment}:chosen==="restore"?{evidenceId:evidence.id,reason:draft.reason}:{reason:draft.reason}};}
  const signature=JSON.stringify({url,input});if(request.current?.signature!==signature)request.current={signature,id:crypto.randomUUID()};setBusy(true);setError(false);
  try{const r=await api<any>(url,{method:"POST",body:JSON.stringify({...input,requestId:request.current.id})});if(!mounted.current)return;setDetail(r.data);setCreating(false);setDraft({});setDirty(false);setConfirmed(false);setSaved(true);request.current=null;await load();}
  catch{if(mounted.current){setError(true);requestAnimationFrame(()=>notice.current?.focus());}}finally{if(mounted.current)setBusy(false);}
 }
 if(leave)return <CcRecordEditorModal titleId="suspension-discard" title={c.discard} closeLabel={c.stay} onClose={()=>setLeave(false)} onSubmit={e=>{e.preventDefault();onClose();}} actions={<><CcButton onClick={()=>setLeave(false)}>{c.stay}</CcButton><CcButton type="submit" variant="warning">{c.leave}</CcButton></>}>{c.boundary}</CcRecordEditorModal>;
 return <CcRecordEditorModal titleId="suspension-title" title={c.title} description={c.boundary} closeLabel={c.close} onClose={close} onSubmit={submit} maxWidthClassName="max-w-4xl" actions={<><CcButton variant="ghost" disabled={busy} onClick={close}>{c.close}</CcButton>{creating||detail&&actions.length?<CcButton type="submit" variant="warning" disabled={busy||!confirmed}>{creating?c.create:c.save}</CcButton>:null}</>}>
  <div className="grid min-w-0 gap-5 [overflow-wrap:anywhere]">
   <div ref={notice} tabIndex={-1}>{error?<CcNotice tone="error" title={c.error} live/>:saved?<CcNotice tone="success" title={c.saved} live/>:null}</div>
   {busy&&!list?<CcNotice tone="loading" title={c.loading}/>:null}
   <div className="flex flex-wrap gap-2"><CcButton variant="outline" disabled={busy||dirty} onClick={()=>void load(detail?.suspension.id)}>{c.refresh}</CcButton>{list?.canCreate&&!creating?<CcButton variant="outline" disabled={busy||dirty} onClick={()=>void create()}>{c.create}</CcButton>:null}</div>
   {!creating&&!detail&&list?.suspensions.map((s:any)=><div key={s.id} className="flex flex-wrap items-center justify-between gap-2 border-b border-base-300 py-3"><span>{s.active?c.active:c.restored} · {label(s.operation)}</span><CcButton variant="outline" size="sm" disabled={busy} onClick={()=>{setDraft({});void load(s.id);}}>{c.scope} · {s.id.slice(0,8)}</CcButton></div>)}
   {!creating&&!detail&&!list?.suspensions.length&&!busy?<p>{c.empty}</p>:null}
   {creating&&catalog?<section className="grid gap-4 sm:grid-cols-2">
    {select("incidentId",incidentId?[{id:incidentId,label:catalog.incidents.find((i:any)=>i.id===incidentId)?.title??incidentId}]:catalog.incidents,true)}
    {select("taskId",catalog.tasks.filter((t:any)=>!taskId||t.id===taskId).map((t:any)=>({id:`${t.id}:${t.applicationId}`,label:`${t.title} · ${t.applicationLabel}`})),true)}
    {select("operation",["review_decision","return_to_executor","create_specialist_task","runtime_execute"].map(id=>({id,label:label(id)})),true)}
    {select("agentId",catalog.agents)}{draft.operation==="runtime_execute"?select("hostId",catalog.hosts):select("credentialId",catalog.credentialChoices.filter((k:any)=>k.boundAgentId===draft.agentId).map((k:any)=>({id:k.id,label:k.keyPrefix})))}
    {field("reason")}{field("scopeProof")}{!draft.agentId&&!(draft.operation==="runtime_execute"&&draft.hostId)?<div className="grid gap-3 sm:col-span-2"><p>{c.broad}</p>{catalog.canBroaden?field("broaderReason"):<CcNotice tone="warning" title={c.broad}/>}</div>:null}
   </section>:null}
   {detail?<>
    <CcNotice tone={detail.suspension.active?"warning":"success"} title={detail.suspension.active?c.active:c.restored}>{detail.suspension.active?c.next:c.boundary}</CcNotice>
    <section className="grid gap-3"><h3 className="font-bold">{c.scope} · {label(detail.suspension.operation)}</h3><p>{detail.suspension.reason}</p><p>{detail.suspension.scopeProof}</p><dl className="grid gap-3 text-sm sm:grid-cols-2">{["incidentId","taskId","applicationId","agentId","credentialId","hostId","issuerUserId"].filter(k=>detail.suspension[k]).map(k=><div key={k}><dt>{label(k)}</dt><dd className="break-all">{detail.suspension[k]}</dd></div>)}</dl><p>{c.version}: {detail.suspension.version} · {new Date(detail.suspension.createdAt).toLocaleString(locale)}</p></section>
    {actions.length?<section className="grid gap-4 border-t border-base-300 pt-4"><CcField label={c.save}>{({id})=><CcSelect id={id} disabled={busy} value={chosen} onChange={e=>{setAction(e.target.value);setDraft({});setDirty(true);setConfirmed(false);}}>{actions.map(a=><option key={a} value={a}>{label(a)}</option>)}</CcSelect>}</CcField>
     {chosen==="evidence"?<>{["cause","impact","remediation","regressionProof","limitations"].map(k=>field(k))}{select("repairAuthorUserId",detail.members.map((m:any)=>({id:m.userId,label:m.label})),true)}</>:chosen==="verify"?field("assessment"):field("reason")}
     {(chosen==="verify"||chosen==="restore")&&evidence?<p>{c.version}: {evidence.version} · {c.repairAuthorUserId}: {detail.members.find((m:any)=>m.userId===evidence.payload.repairAuthorUserId)?.label??evidence.payload.repairAuthorUserId}</p>:null}
    </section>:null}
    <section className="grid gap-3 border-t border-base-300 pt-4"><h3 className="font-bold">{c.history}</h3>{detail.history.map((h:any)=><details key={h.id} className="border-b border-base-300 pb-3"><summary className="cursor-pointer py-2">{c.version} {h.version} · {label(h.action)} · {new Date(h.createdAt).toLocaleString(locale)}</summary><p>{detail.members.find((m:any)=>m.userId===h.actorUserId)?.label??h.actorUserId}</p><dl className="grid gap-2 text-sm">{Object.entries(h.payload).map(([k,v])=><div key={k}><dt className="font-semibold">{label(k)}</dt><dd className="whitespace-pre-wrap">{k==="repairAuthorUserId"?(detail.members.find((m:any)=>m.userId===v)?.label??String(v)):String(v)}</dd></div>)}</dl></details>)}</section>
   </>:null}
   {creating||detail&&actions.length?<label className="flex items-start gap-3 py-2"><input type="checkbox" className="checkbox" checked={confirmed} disabled={busy} onChange={e=>{setConfirmed(e.target.checked);setDirty(true);}}/><span>{c.confirm}</span></label>:null}
   {list?.truncated||detail?.truncated||catalog?.truncated?<CcNotice tone="warning" title={c.truncated}/>:null}
  </div>
 </CcRecordEditorModal>;
}
