import { FormEvent, useMemo, useState } from "react";
import { api, AppApiError } from "../../api/client";
import { CcButton } from "../../components/cc-button";
import { CcConfirmDialog } from "../../components/cc-confirm-dialog";
import { CcDataTable, type CcTableColumn } from "../../components/cc-data-table";
import { CcField } from "../../components/cc-field";
import { CcMultiSelect } from "../../components/cc-multi-select";
import { CcNotice } from "../../components/cc-notice";
import { CcPageHeader } from "../../components/cc-page-header";
import { CcRecordEditorModal, CcRecordEditorSection } from "../../components/cc-record-editor";
import { CcSelect } from "../../components/cc-select";
import { useOwnerPacket } from "../../hooks/use-owner-packet";
import { useLanguage } from "../../i18n/i18n";
import type { CoreAreaKey } from "../../types";
import { departmentLabel } from "./department-labels";
import { humanizeBusinessValue, useTranslatedTableLabels } from "./shared";

type Department = { id: string; key: CoreAreaKey; name: string };
type Decision = { id: string; title: string; context?: string | null; problem?: string | null; decision?: string | null; rationale?: string | null; alternatives?: unknown[]; consequences?: string | null; outcome?: string | null; authorType?: string | null; authorId?: string | null; status: string; supersedesId?: string | null; supersedes?: { id: string; title: string } | null; organizationalContext?: { ownerDepartment?: Department | null; relatedDepartments?: Department[]; scopes?: Array<{ type: string }> } };
type Draft = { title: string; context: string; problem: string; decision: string; rationale: string; alternatives: string; consequences: string; outcome: string; authorType: string; authorId: string; status: string; supersedesId: string; ownerDepartmentKey: string; relatedDepartmentKeys: string[]; companyWide: boolean };

function draftFor(row: Decision | null, departmentKey: CoreAreaKey): Draft {
  return { title: row?.title || "", context: row?.context || "", problem: row?.problem || "", decision: row?.decision || "", rationale: row?.rationale || "", alternatives: (row?.alternatives || []).map((value) => typeof value === "string" ? value : JSON.stringify(value)).join("\n"), consequences: row?.consequences || "", outcome: row?.outcome || "", authorType: row?.authorType || "human", authorId: row?.authorId || "", status: row?.status || "proposed", supersedesId: row?.supersedesId || "", ownerDepartmentKey: row?.organizationalContext?.ownerDepartment?.key || departmentKey, relatedDepartmentKeys: row?.organizationalContext?.relatedDepartments?.map((item) => item.key) || [], companyWide: Boolean(row?.organizationalContext?.scopes?.some((scope) => scope.type === "company")) };
}

function DecisionEditor({ row, departmentKey, departments, decisions, onClose, onSaved }: { row: Decision | null; departmentKey: CoreAreaKey; departments: Department[]; decisions: Decision[]; onClose: () => void; onSaved: () => void }) {
  const { locale, t } = useLanguage(); const polish = locale === "pl"; const [draft, setDraft] = useState(() => draftFor(row, departmentKey)); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const departmentOptions = departments.map((item) => ({ value: item.key, label: departmentLabel(item.key, t) }));
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(null); try { await api(row ? `/v1/decisions/${row.id}` : "/v1/decisions", { method: row ? "PATCH" : "POST", body: JSON.stringify({ title: draft.title, context: draft.context || null, problem: draft.problem || null, decision: draft.decision || null, rationale: draft.rationale || undefined, alternatives: draft.alternatives.split("\n").map((value) => value.trim()).filter(Boolean), consequences: draft.consequences || null, outcome: draft.outcome || undefined, authorType: draft.authorType || null, authorId: draft.authorId || null, status: draft.status, supersedesId: draft.supersedesId || null, organizationalContext: { ownerDepartmentKey: draft.ownerDepartmentKey, relatedDepartmentKeys: draft.relatedDepartmentKeys.filter((key) => key !== draft.ownerDepartmentKey), applicableDepartmentKeys: [], scopes: draft.companyWide ? [{ type: "company" }] : [{ type: "department", entityId: draft.ownerDepartmentKey }] } }) }); onSaved(); } catch (caught) { setError(caught instanceof AppApiError ? caught.code : "request_failed"); } finally { setBusy(false); } }
  return <CcRecordEditorModal actions={<><CcButton onClick={onClose} variant="ghost">{t("common.cancel")}</CcButton><CcButton loading={busy} type="submit" variant="primary">{t("common.save")}</CcButton></>} description={polish ? "Jedna globalna decyzja może być właścicielska dla jednego działu i kontekstowo widoczna w innych." : "One global decision can be owned by one department and visible contextually in others."} eyebrow={polish ? "Rejestr decyzji" : "Decision register"} onClose={onClose} onSubmit={submit} title={row ? polish ? "Edytuj decyzję" : "Edit decision" : polish ? "Zapisz decyzję" : "Record decision"} titleId="decision-editor-title">
    {error ? <CcNotice live tone="error" title={humanizeBusinessValue(error)} /> : null}
    <CcRecordEditorSection title={polish ? "Treść decyzji" : "Decision content"}><div className="grid gap-4 md:grid-cols-2">
      <CcField label={polish ? "Tytuł" : "Title"} required>{({ id }) => <input className="input input-bordered w-full" id={id} onChange={(event) => setDraft({ ...draft, title: event.target.value })} required value={draft.title} />}</CcField>
      <CcField label="Status">{({ id }) => <CcSelect id={id} onChange={(event) => setDraft({ ...draft, status: event.target.value })} value={draft.status}>{["proposed", "accepted", "rejected", "superseded", "archived"].map((value) => <option key={value} value={value}>{humanizeBusinessValue(value, undefined, locale)}</option>)}</CcSelect>}</CcField>
      <CcField label={polish ? "Kontekst" : "Context"}>{({ id }) => <textarea className="textarea textarea-bordered min-h-24 w-full" id={id} onChange={(event) => setDraft({ ...draft, context: event.target.value })} value={draft.context} />}</CcField>
      <CcField label={polish ? "Problem" : "Problem"}>{({ id }) => <textarea className="textarea textarea-bordered min-h-24 w-full" id={id} onChange={(event) => setDraft({ ...draft, problem: event.target.value })} value={draft.problem} />}</CcField>
      <CcField label={polish ? "Decyzja" : "Decision"} required>{({ id }) => <textarea className="textarea textarea-bordered min-h-28 w-full" id={id} onChange={(event) => setDraft({ ...draft, decision: event.target.value })} value={draft.decision} />}</CcField>
      <CcField label={polish ? "Uzasadnienie" : "Rationale"}>{({ id }) => <textarea className="textarea textarea-bordered min-h-28 w-full" id={id} onChange={(event) => setDraft({ ...draft, rationale: event.target.value })} value={draft.rationale} />}</CcField>
      <CcField label={polish ? "Alternatywy (jedna na wiersz)" : "Alternatives (one per line)"}>{({ id }) => <textarea className="textarea textarea-bordered min-h-24 w-full" id={id} onChange={(event) => setDraft({ ...draft, alternatives: event.target.value })} value={draft.alternatives} />}</CcField>
      <CcField label={polish ? "Konsekwencje" : "Consequences"}>{({ id }) => <textarea className="textarea textarea-bordered min-h-24 w-full" id={id} onChange={(event) => setDraft({ ...draft, consequences: event.target.value })} value={draft.consequences} />}</CcField>
      <CcField label={polish ? "Wynik / obserwacja" : "Outcome / observation"}>{({ id }) => <textarea className="textarea textarea-bordered min-h-20 w-full" id={id} onChange={(event) => setDraft({ ...draft, outcome: event.target.value })} value={draft.outcome} />}</CcField>
      <CcField label={polish ? "Zastępuje decyzję" : "Supersedes"}>{({ id }) => <CcSelect id={id} onChange={(event) => setDraft({ ...draft, supersedesId: event.target.value })} value={draft.supersedesId}><option value="">—</option>{decisions.filter((item) => item.id !== row?.id).map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</CcSelect>}</CcField>
      <CcField label={polish ? "Typ autora" : "Author type"}>{({ id }) => <CcSelect id={id} onChange={(event) => setDraft({ ...draft, authorType: event.target.value })} value={draft.authorType}><option value="human">Human</option><option value="agent">Agent</option><option value="system">System</option></CcSelect>}</CcField>
      <CcField label={polish ? "Identyfikator autora" : "Author identifier"}>{({ id }) => <input className="input input-bordered w-full" id={id} onChange={(event) => setDraft({ ...draft, authorId: event.target.value })} value={draft.authorId} />}</CcField>
    </div></CcRecordEditorSection>
    <CcRecordEditorSection title={polish ? "Kontekst organizacyjny" : "Organizational context"}><div className="grid gap-4 md:grid-cols-2"><CcField label={polish ? "Dział właścicielski" : "Owner department"}>{({ id }) => <CcSelect id={id} onChange={(event) => setDraft({ ...draft, ownerDepartmentKey: event.target.value })} value={draft.ownerDepartmentKey}>{departmentOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</CcSelect>}</CcField><CcField label={polish ? "Powiązane działy" : "Related departments"}>{({ id }) => <CcMultiSelect id={id} name="decisionRelatedDepartments" onChange={(value) => setDraft({ ...draft, relatedDepartmentKeys: value })} options={departmentOptions.filter((option) => option.value !== draft.ownerDepartmentKey)} value={draft.relatedDepartmentKeys} />}</CcField><label className="flex min-h-11 items-center gap-3 rounded-company border border-base-300 px-3 py-2 text-sm font-bold md:col-span-2"><input checked={draft.companyWide} className="checkbox checkbox-primary checkbox-sm" onChange={(event) => setDraft({ ...draft, companyWide: event.target.checked })} type="checkbox" />{polish ? "Zakres całej firmy" : "Company-wide scope"}</label></div></CcRecordEditorSection>
  </CcRecordEditorModal>;
}

export function DecisionsWorkbench({ departmentKey, canonical = false }: { departmentKey: CoreAreaKey; canonical?: boolean }) {
  const { locale, t } = useLanguage(); const polish = locale === "pl"; const requestedDepartment = canonical ? new URLSearchParams(window.location.search).get("department") as CoreAreaKey | null : departmentKey; const scoped = Boolean(requestedDepartment); const effectiveDepartment = requestedDepartment || departmentKey; const [refreshKey, setRefreshKey] = useState(0); const [editing, setEditing] = useState<Decision | null | undefined>(undefined); const [archiving, setArchiving] = useState<Decision | null>(null); const [busy, setBusy] = useState(false); const packet = useOwnerPacket<Decision[]>(`/v1/decisions${scoped ? `?departmentKey=${effectiveDepartment}&includeCompanyWide=true&` : "?"}refresh=${refreshKey}`, true, t); const allDecisions = useOwnerPacket<Decision[]>(`/v1/decisions?allRefresh=${refreshKey}`, true, t); const departments = useOwnerPacket<{ departments: Department[] }>(`/v1/departments?refresh=${refreshKey}`, true, t); const rows = packet.data || []; const labels = useTranslatedTableLabels();
  const columns = useMemo<Array<CcTableColumn<Decision>>>(() => [{ key: "decision", header: polish ? "Decyzja" : "Decision", sortable: true, searchValue: (row) => `${row.title} ${row.problem || ""} ${row.decision || ""}`, cell: (row) => <button className="grid text-left" onClick={() => setEditing(row)} type="button"><strong>{row.title}</strong><span className="line-clamp-2 text-xs text-company-muted">{row.decision || row.problem || row.context || "—"}</span></button> }, { key: "owner", header: polish ? "Dział" : "Department", filterable: true, filterValue: (row) => row.organizationalContext?.ownerDepartment?.key || "unassigned", cell: (row) => <span className="text-sm text-company-muted">{row.organizationalContext?.ownerDepartment ? departmentLabel(row.organizationalContext.ownerDepartment.key, t) : "—"}</span> }, { key: "status", header: "Status", filterable: true, filterValue: (row) => row.status, cell: (row) => <span className="badge badge-outline">{humanizeBusinessValue(row.status, undefined, locale)}</span> }, { key: "author", header: polish ? "Autor" : "Author", cell: (row) => <span className="text-sm text-company-muted">{[row.authorType, row.authorId].filter(Boolean).join(": ") || "—"}</span> }, { key: "actions", header: t("table.actions"), cell: (row) => <div className="flex justify-end gap-1"><CcButton ariaLabel="Edit" iconLeft="ph-pencil-simple" onClick={() => setEditing(row)} size="xs" variant="ghost"><span className="sr-only">Edit</span></CcButton><CcButton ariaLabel="Archive" iconLeft="ph-archive" onClick={() => setArchiving(row)} size="xs" variant="ghost"><span className="sr-only">Archive</span></CcButton></div> }], [locale, polish, t]);
  function refresh() { setEditing(undefined); setRefreshKey((value) => value + 1); }
  async function archive() { if (!archiving) return; setBusy(true); try { await api(`/v1/decisions/${archiving.id}`, { method: "DELETE" }); setArchiving(null); refresh(); } finally { setBusy(false); } }
  return <><CcPageHeader actions={<>{scoped ? <CcButton href="/areas?area=01-strategia&view=decisions" iconLeft="ph-x" size="sm" variant="outline">{polish ? "Pokaż wszystkie dostępne" : "Show all accessible decisions"}</CcButton> : null}<CcButton iconLeft="ph-plus" onClick={() => setEditing(null)} size="sm" variant="primary">{polish ? "Zapisz decyzję" : "Record decision"}</CcButton></>} description={scoped ? polish ? "Kontekstowy widok globalnego rejestru decyzji." : "Contextual view of the global decision register." : polish ? "Kanoniczny rejestr decyzji firmy z historią zastępowania." : "Canonical company decision register with supersession history."} eyebrow={scoped ? departmentLabel(effectiveDepartment, t) : departmentLabel(departmentKey, t)} title={scoped ? `${polish ? "Decyzje" : "Decisions"}: ${departmentLabel(effectiveDepartment, t)}` : polish ? "Rejestr decyzji" : "Decision register"} /><CcDataTable columns={columns} rows={rows} emptyDetail={polish ? "Zapisz decyzję wraz z kontekstem, alternatywami i konsekwencjami." : "Record a decision with its context, alternatives, and consequences."} emptyTitle={polish ? "Brak decyzji" : "No decisions"} error={packet.status === "error" ? packet.error : null} getRowLabel={(row) => row.title} labels={labels} loading={packet.status === "loading"} mobileMode="cards" />{editing !== undefined ? <DecisionEditor decisions={allDecisions.data || []} departmentKey={effectiveDepartment} departments={departments.data?.departments || []} onClose={() => setEditing(undefined)} onSaved={refresh} row={editing} /> : null}{archiving ? <CcConfirmDialog busy={busy} confirmIcon="ph-archive" confirmLabel={polish ? "Archiwizuj" : "Archive"} confirmTone="warning" description={polish ? "Decyzja pozostanie w historii i może być wskazana jako zastąpiona." : "The decision remains in history and can be referenced as superseded."} detail={<strong>{archiving.title}</strong>} eyebrow={polish ? "Decyzje" : "Decisions"} onCancel={() => setArchiving(null)} onConfirm={archive} title={polish ? "Zarchiwizować decyzję?" : "Archive decision?"} /> : null}</>;
}
