import { useEffect,useRef,useState } from "react";
import { api,AppApiError } from "../../api/client";
import { useLanguage } from "../../i18n/i18n";
import { CcButton } from "../../components/cc-button";
import { CcField } from "../../components/cc-field";
import { CcSelect } from "../../components/cc-select";
import { CcNotice } from "../../components/cc-notice";
import { CcConfirmDialog } from "../../components/cc-confirm-dialog";
import { CcRecordEditorModal,CcRecordEditorSection } from "../../components/cc-record-editor";
import { TaskRiskAdmissionModal } from "./task-risk-admission";
import { DecisionAuthorityFields, DecisionAuthorityDetails, DelegatedMandatesModal } from "./decision-authority";

const words:Record<string,[string,string]>={proposed:["Propozycja","Proposed"],pending:["Oczekuje na decyzję","Pending decision"],accepted:["Zaakceptowana","Accepted"],deferred:["Odroczona","Deferred"],contradicts:["Sprzeczne postanowienie","Contradicting provision"],narrows:["Zawężenie","Narrowing"],replaces:["Zastąpienie","Replacement"],budget:["Budżet","Budget"],infrastructure:["Infrastruktura","Infrastructure"],resource_available:["Potwierdzona dostępność zasobu","Confirmed resource availability"],configuration_changed:["Zmiana konfiguracji","Configuration change"],owner_signal:["Świadomy sygnał właściciela","Explicit owner signal"],deadline:["Termin wybrany przez właściciela","Owner-selected date"],task:["Zadanie","Task"],application:["Aplikacja","Application"],project:["Projekt","Project"],procedure:["Procedura","Procedure"],company_record:["Kontekst","Context"],resource:["Zasób","Resource"],decision:["Decyzja","Decision"],context:["Kontekst powiązania","Related context"],revalidation:["Wymaga ponownej walidacji","Revalidation required"]};
function useCopy(){const {locale}=useLanguage();const pl=locale==='pl';return {pl,label:(k:string)=>words[k]?.[pl?0:1]??k};}
const read=async(path:string)=>(await api<any>(path)).data;
const errorCode=(e:unknown)=>e instanceof AppApiError?e.code:'request_failed';

export function DecisionDeferralModal({targetType,targetId,onClose,review=false}:{targetType:'decision'|'interview';targetId:string;onClose:()=>void;review?:boolean}){
 const {pl,label}=useCopy(),[data,setData]=useState<any>(null),[reason,setReason]=useState('budget'),[condition,setCondition]=useState('owner_signal'),[referenceId,setReferenceId]=useState(''),[dueAt,setDueAt]=useState(''),[explanation,setExplanation]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[discard,setDiscard]=useState(false);const key=useRef(crypto.randomUUID());
 async function refresh(){try{setData(await read('/v1/decisions/governance'));setError('');}catch(e){setError(errorCode(e));}}
 useEffect(()=>{void refresh();},[]);
 const close=()=>explanation?setDiscard(true):onClose();
 async function save(){setBusy(true);setError('');try{await api('/v1/decisions/deferrals',{method:'POST',body:JSON.stringify({requestId:key.current,expectedVersion:data.expectedVersion,targetType,targetId,reason,explanation,condition:{type:condition,...(condition==='deadline'?{dueAt:new Date(dueAt).toISOString()}:['resource_available','configuration_changed'].includes(condition)?{referenceId}:{})}})});onClose();}catch(e){setError(errorCode(e));}finally{setBusy(false);}}
 async function reopen(f:any){setBusy(true);setError('');try{await api('/v1/decisions/reopening-events',{method:'POST',body:JSON.stringify({requestId:key.current,expectedVersion:data.expectedVersion,deferralId:f.id,type:f.condition.type,explanation,...(f.referenceRevision?{referenceRevision:f.referenceRevision}:{})})});key.current=crypto.randomUUID();setExplanation('');await refresh();}catch(e){setError(errorCode(e));}finally{setBusy(false);}}
 if(review)return <><CcRecordEditorModal titleId="decision-reopening-title" eyebrow={pl?'Decyzje':'Decisions'} title={pl?'Warunki powrotu i zdarzenia':'Reopening conditions and events'} description={pl?'Potwierdzone zdarzenie przywraca pytanie do oczekujących. Odpowiedź i akceptacja pozostają osobnymi krokami.':'A confirmed event returns the question to pending. Answering and accepting remain separate steps.'} onClose={close} actions={<><CcButton onClick={close} variant="ghost">{pl?'Wróć':'Back'}</CcButton><CcButton onClick={()=>void refresh()} variant="outline">{pl?'Odśwież warunki':'Refresh conditions'}</CcButton></>}>
  {error?<CcNotice tone="error" title={pl?'Zdarzenie nie zostało przyjęte. Odśwież i sprawdź warunek.':'Event not accepted. Refresh and check the condition.'} detail={error}/>:null}
  {!data?<CcNotice title={pl?'Wczytywanie warunków…':'Loading conditions…'}/>:!data.deferrals.some((f:any)=>f.targetType===targetType&&f.targetId===targetId)?<CcNotice title={pl?'To odłożenie nie ma zapisanego warunku zdarzenia.':'This deferral has no recorded event condition.'}/>:<><CcField label={pl?'Potwierdzenie rzeczywistego zdarzenia':'Confirmation of the actual event'}>{({id})=><textarea id={id} className="textarea textarea-bordered w-full" value={explanation} onChange={e=>setExplanation(e.target.value)}/>}</CcField>{data.deferrals.filter((f:any)=>f.targetType===targetType&&f.targetId===targetId).map((f:any)=><div key={f.id} className="border-b border-base-300 py-4"><strong>{label(f.reason)} · {label(f.condition.type)}</strong><p className="my-2 whitespace-pre-wrap text-sm">{f.explanation}</p>{f.condition.referenceId?<p className="text-sm">{[...data.resourceCatalog,...data.configurationCatalog].find((r:any)=>r.id===f.condition.referenceId)?.title??data.resourceCatalog.find((r:any)=>r.id===f.condition.referenceId)?.name??f.condition.referenceId}</p>:null}{f.condition.dueAt?<p>{new Date(f.condition.dueAt).toLocaleString()}</p>:null}{f.eventId?<p>{pl?'Ponownie otwarto':'Reopened'} · {new Date(f.reopenedAt).toLocaleString()}</p>:<CcButton onClick={()=>void reopen(f)} variant="outline" loading={busy} disabled={!data.canWrite||explanation.trim().length<3}>{pl?'Potwierdź zdarzenie i otwórz ponownie':'Confirm event and reopen'}</CcButton>}</div>)}</>}
 </CcRecordEditorModal>{discard?<CcConfirmDialog eyebrow={pl?'Decyzje':'Decisions'} title={pl?'Odrzucić niezapisane zmiany?':'Discard unsaved changes?'} description="" confirmLabel={pl?'Odrzuć':'Discard'} onCancel={()=>setDiscard(false)} onConfirm={onClose}/>:null}</>;
 return <><CcRecordEditorModal titleId="decision-deferral-title" eyebrow={pl?'Decyzje':'Decisions'} title={pl?'Odrocz do konkretnego zdarzenia':'Defer until a specific event'} description={pl?'Brak odpowiedzi nie zmienia decyzji. Powrót do pytania wymaga potwierdzonego zdarzenia; nie ma codziennych przypomnień.':'Silence does not change the decision. Reopening requires a confirmed event; there are no daily reminders.'} onClose={close} onSubmit={e=>{e.preventDefault();void save();}} actions={<><CcButton onClick={close} variant="ghost">{pl?'Wróć':'Back'}</CcButton><CcButton type="submit" variant="primary" loading={busy} disabled={!data?.canWrite}>{pl?'Zapisz odroczenie':'Record deferral'}</CcButton></>}>
  {error?<CcNotice tone="error" title={pl?'Nie zapisano. Odśwież warunki i sprawdź uprawnienia.':'Not saved. Refresh conditions and check authority.'} detail={error}/>:null}
  <CcButton onClick={()=>void refresh()} variant="outline" className="mb-4">{pl?'Odśwież warunki':'Refresh conditions'}</CcButton><div className="grid gap-4 md:grid-cols-2"><CcField label={pl?'Powód':'Reason'}>{({id})=><CcSelect id={id} value={reason} onChange={e=>setReason(e.target.value)}>{['budget','infrastructure'].map(k=><option key={k} value={k}>{label(k)}</option>)}</CcSelect>}</CcField>
  <CcField label={pl?'Warunek ponownego otwarcia':'Reopening condition'}>{({id})=><CcSelect id={id} value={condition} onChange={e=>{setCondition(e.target.value);setReferenceId('');}}>{['owner_signal','resource_available','configuration_changed','deadline'].map(k=><option key={k} value={k}>{label(k)}</option>)}</CcSelect>}</CcField>
  {['resource_available','configuration_changed'].includes(condition)?<CcField label={pl?'Powiązany rekord':'Linked record'} required>{({id})=><CcSelect id={id} value={referenceId} required onChange={e=>setReferenceId(e.target.value)}><option value="">{pl?'Wybierz istniejącą zależność':'Choose an existing dependency'}</option>{(condition==='resource_available'?data?.resourceCatalog:data?.configurationCatalog)?.map((r:any)=><option key={r.id} value={r.id}>{r.title??r.name}</option>)}</CcSelect>}</CcField>:null}
  {condition==='deadline'?<CcField label={pl?'Wybrany termin (czas lokalny)':'Selected date (local time)'} required>{({id})=><input id={id} className="input input-bordered w-full" type="datetime-local" required value={dueAt} onChange={e=>setDueAt(e.target.value)}/>}</CcField>:null}
  <CcField label={pl?'Uzasadnienie odroczenia':'Deferral explanation'} required>{({id})=><textarea id={id} className="textarea textarea-bordered w-full" required minLength={3} value={explanation} onChange={e=>setExplanation(e.target.value)}/>}</CcField></div>
 </CcRecordEditorModal>{discard?<CcConfirmDialog eyebrow={pl?"Decyzje":"Decisions"} title={pl?'Odrzucić niezapisane zmiany?':'Discard unsaved changes?'} description="" confirmLabel={pl?'Odrzuć':'Discard'} onCancel={()=>setDiscard(false)} onConfirm={onClose}/>:null}</>;
}

export function DecisionGovernanceModal({decisionId,parent,onClose}:{decisionId?:string;parent?:{id:string;title:string;decision?:string|null};onClose:()=>void}){
 const [authorityDraft,setAuthorityDraft]=useState({domain:'',departmentKey:'',requesterId:'',recipientId:''}),[mandates,setMandates]=useState(false);
 const {pl,label}=useCopy(),[selectedId,setSelectedId]=useState(decisionId),[data,setData]=useState<any>(null),[root,setRoot]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false),[discard,setDiscard]=useState(false),[defer,setDefer]=useState(false),[riskTask,setRiskTask]=useState<string|null>(null);
 const [draft,setDraft]=useState({title:'',context:'',decision:'',rationale:'',consequences:'',scopeReason:'',taskId:'',kind:'contradicts',oldProvision:'',newProvision:'',explanation:''});
 const [eventReason,setEventReason]=useState('');const key=useRef(crypto.randomUUID()),sequence=useRef(0);
 const dirty=(!selectedId&&(Object.entries(draft).some(([k,v])=>k!=='kind'&&v!=='')||!!authorityDraft.domain))||!!eventReason;
 const close=()=>dirty?setDiscard(true):onClose();
 async function load(){const ticket=++sequence.current;try{const base=await read('/v1/decisions/governance'),detail=selectedId?await read(`/v1/decisions/${selectedId}/governance`):base;if(ticket===sequence.current){setRoot(base);setData(detail);setError('');}}catch(e){if(ticket===sequence.current)setError(errorCode(e));}}
 useEffect(()=>{void load();return()=>{sequence.current++;};},[selectedId]);
 async function create(){if(!root)return;setBusy(true);setError('');try{const body={requestId:key.current,expectedVersion:root.expectedVersion,...Object.fromEntries(['title','context','decision','rationale','consequences','scopeReason'].map(k=>[k,(draft as any)[k]])),authority:{domain:authorityDraft.domain,departmentKey:authorityDraft.departmentKey,...(authorityDraft.domain==='ordinary_domain'?{requesterId:authorityDraft.requesterId,recipientId:authorityDraft.recipientId}:{}),entities:[{type:'task',id:draft.taskId}]},scope:[{type:'task',id:draft.taskId}],supersedesId:parent?.id??null,conflicts:parent?[{kind:draft.kind,oldProvision:draft.oldProvision,newProvision:draft.newProvision,explanation:draft.explanation}]:[]};const result=await readPost('/v1/decisions/governance/proposals',body);key.current=crypto.randomUUID();setSelectedId(result.record.id);}catch(e){setError(errorCode(e));}finally{setBusy(false);}}
 async function action(kind:string){setBusy(true);setError('');try{await readPost(`/v1/decisions/${selectedId}/governance/actions`,{requestId:key.current,expectedVersion:data.expectedVersion,action:kind,...(kind==='accept'?{previewId:data.previews[0]?.id}:{})});key.current=crypto.randomUUID();setConfirm(false);await load();}catch(e){setError(errorCode(e));}finally{setBusy(false);}}
 async function reopen(f:any){setBusy(true);setError('');try{await readPost('/v1/decisions/reopening-events',{requestId:key.current,expectedVersion:root.expectedVersion,deferralId:f.id,type:f.condition.type,explanation:eventReason,...(f.referenceRevision?{referenceRevision:f.referenceRevision}:{})});key.current=crypto.randomUUID();setEventReason('');await load();}catch(e){setError(errorCode(e));}finally{setBusy(false);}}
 const field=(name:keyof typeof draft,title:string,area=true)=><CcField key={name} label={title} required>{({id})=>area?<textarea id={id} className="textarea textarea-bordered min-h-24 w-full" required minLength={3} value={draft[name]} onChange={e=>setDraft({...draft,[name]:e.target.value})}/>:<input id={id} className="input input-bordered w-full" required minLength={3} value={draft[name]} onChange={e=>setDraft({...draft,[name]:e.target.value})}/>}</CcField>;
 if(defer&&selectedId)return <DecisionDeferralModal targetType="decision" targetId={selectedId} onClose={()=>{setDefer(false);void load();}}/>;
 if(riskTask)return <TaskRiskAdmissionModal taskId={riskTask} initialOperation="decision_supersede" onClose={()=>{setRiskTask(null);void load();}}/>;
 if(mandates)return <DelegatedMandatesModal onClose={()=>{setMandates(false);void load();}}/>;
 const proposal=data?.selected,impact=data?.impact??data?.previews?.[0]?.impact;
 return <><CcRecordEditorModal titleId="decision-governance-title" eyebrow={pl?'Rejestr decyzji':'Decision register'} title={proposal?.body.title??(parent?pl?'Propozycja zastępująca decyzję':'Propose a replacement decision':pl?'Propozycja decyzji i jej wpływ':'Decision proposal and impact')} description={pl?'Najpierw sprawdź postanowienia i zakres wpływu. Akceptacja jest osobną czynnością uprawnionego decydenta.':'Review the provisions and impact scope first. Acceptance is a separate action by the authorized decision maker.'} onClose={close} onSubmit={e=>{e.preventDefault();if(!selectedId)void create();}} actions={<><CcButton onClick={close} variant="ghost">{pl?'Wróć':'Back'}</CcButton>{selectedId?<><CcButton onClick={()=>void load()} variant="outline">{pl?'Odśwież':'Refresh'}</CcButton>{proposal?.state==='pending'&&(data?.canWrite||data?.canAccept)?<><CcButton disabled={!data.canWrite} onClick={()=>setDefer(true)} variant="outline">{pl?'Odrocz':'Defer'}</CcButton><CcButton onClick={()=>setConfirm(true)} variant="primary" disabled={!data.canAccept||!data.current||data.gates.some((g:any)=>!g.seal)}>{pl?'Przejrzyj i zaakceptuj':'Review and accept'}</CcButton></>:null}</>:<CcButton type="submit" variant="primary" loading={busy} disabled={!data?.canWrite||!authorityDraft.domain||!authorityDraft.departmentKey}>{pl?'Zapisz propozycję':'Record proposal'}</CcButton>}</>}>
  {error?<CcNotice tone="error" title={pl?'Operacja nie powiodła się. Odśwież kontekst i sprawdź wskazany warunek.':'The operation failed. Refresh context and check the indicated condition.'} detail={error}/>:null}
  {!data?<CcNotice tone="info" title={pl?'Wczytywanie decyzji i zależności…':'Loading decisions and dependencies…'}/>:null}
  {data&&!data.canWrite&&!data.canAccept?<CcNotice tone="info" title={pl?'Tylko aktualny właściciel może zmieniać ten zapis.':'Only a current owner may change this record.'}/>:null}
  {data?.truncated?<CcNotice tone="warning" title={pl?'Widok jest ograniczony. Doprecyzuj zakres w rejestrze.':'This view is bounded. Refine the scope in the register.'}/>:null}
  {!selectedId?<><DecisionAuthorityFields value={authorityDraft} onChange={setAuthorityDraft} catalog={root?.authorityCatalog}/><CcRecordEditorSection title={pl?'Postanowienie i najwęższy zakres':'Provision and narrowest scope'}><div className="grid gap-4 md:grid-cols-2">{field('title',pl?'Tytuł':'Title',false)}<CcField label={pl?'Zadanie objęte decyzją':'Task covered by the decision'} required>{({id})=><CcSelect id={id} required value={draft.taskId} onChange={e=>setDraft({...draft,taskId:e.target.value})}><option value="">{pl?'Wybierz':'Choose'}</option>{root?.catalog.map((n:any)=><option key={n.id} value={n.id}>{n.title}</option>)}</CcSelect>}</CcField>{field('context',pl?'Kontekst':'Context')}{field('decision',pl?'Nowe postanowienie':'New provision')}{field('rationale',pl?'Uzasadnienie propozycji':'Proposal rationale')}{field('consequences',pl?'Konsekwencje':'Consequences')}{field('scopeReason',pl?'Dlaczego ten zakres jest najwęższy':'Why this scope is the narrowest')}</div></CcRecordEditorSection>
   {parent?<CcRecordEditorSection title={pl?'Konflikt z poprzednią decyzją':'Conflict with the previous decision'}><p className="mb-4 whitespace-pre-wrap text-sm">{parent.title}: {parent.decision}</p><div className="grid gap-4 md:grid-cols-2"><CcField label={pl?'Rodzaj konfliktu':'Conflict type'}>{({id})=><CcSelect id={id} value={draft.kind} onChange={e=>setDraft({...draft,kind:e.target.value})}>{['contradicts','narrows','replaces'].map(k=><option key={k} value={k}>{label(k)}</option>)}</CcSelect>}</CcField>{field('oldProvision',pl?'Dokładny cytat wcześniejszego postanowienia':'Exact previous provision')}{field('newProvision',pl?'Dokładny cytat nowego postanowienia':'Exact new provision')}{field('explanation',pl?'Na czym polega konflikt':'Explain the conflict')}</div></CcRecordEditorSection>:null}
   {root?.revisions.length?<CcRecordEditorSection title={pl?'Zapisane propozycje':'Recorded proposals'}><div className="divide-y divide-base-300">{root.revisions.map((r:any)=><CcButton key={r.id} onClick={()=>setSelectedId(r.id)} variant="ghost">{r.title} · {label(r.state)}</CcButton>)}</div></CcRecordEditorSection>:null}</>:null}
  {proposal?<><DecisionAuthorityDetails authority={data.acceptance?.authority??data.authority} catalog={root?.authorityCatalog} onMandates={()=>setMandates(true)}/><CcRecordEditorSection title={`${label(proposal.state)} · ${pl?'wersja':'version'} ${proposal.version}`}><p className="whitespace-pre-wrap">{proposal.body.decision}</p><p className="mt-3 text-sm">{proposal.body.rationale}</p><p className="mt-3 text-sm">{proposal.body.scopeReason}</p><p className="mt-3 text-sm">{proposal.body.consequences}</p></CcRecordEditorSection>
   {proposal.body.conflicts.length?<CcRecordEditorSection title={pl?'Dokładne sprzeczności':'Exact conflicts'}>{proposal.body.conflicts.map((c:any,i:number)=><div key={i} className="border-b border-base-300 py-3"><strong>{label(c.kind)}</strong><p className="mt-2 whitespace-pre-wrap">{pl?'Wcześniej':'Previous'}: {c.oldProvision}</p><p className="mt-2 whitespace-pre-wrap">{pl?'Propozycja':'Proposed'}: {c.newProvision}</p><p className="mt-2 text-sm">{c.explanation}</p></div>)}</CcRecordEditorSection>:null}
   <CcRecordEditorSection title={pl?'Obliczony wpływ na zależności':'Computed downstream impact'}>{!data.impact?<CcNotice tone="warning" title={pl?'Nie można obliczyć aktualnego wpływu. Poniżej zapisany przegląd historyczny.':'Current impact is unavailable. The recorded historical review is shown below.'}/>:null}{!data.current&&proposal.state!=='accepted'?<CcNotice tone="warning" title={pl?'Zależności się zmieniły. Zapisz nowy przegląd wpływu i ponów wymagane weryfikacje.':'Dependencies changed. Record a new impact review and repeat required checks.'}/>:null}<ul className="divide-y divide-base-300">{impact.nodes.map((n:any)=><li key={n.type+n.id} className="py-3"><strong>{n.title}</strong><span className="ml-2 text-sm text-company-muted">{label(n.type)}</span>{proposal.state==='accepted'?<p className="text-sm">{n.type==='task'&&data.taskStates.find((t:any)=>t.id===n.id)?.executionReadiness?.status==='ready'?(pl?'Ponownie zwalidowano':'Revalidated'):label('revalidation')}</p>:null}</li>)}</ul><div className="mt-3 space-y-2 text-sm">{impact.contexts.map((n:any)=><p key={n.type+n.id}>{label(n.type)}: {n.title} · {label(n.effect)}</p>)}<p>{pl?'Granty / przekazania / otwarte wywiady':'Grants / handoffs / open interviews'}: {impact.grants.length} / {impact.handoffs.length} / {impact.interviews.length}</p><details><summary className="cursor-pointer py-2">{pl?'Powiązane zapisy i uprawnienia':'Related records and grants'}</summary>{(['grants','handoffs','interviews'] as const).map(k=><ul key={k} className="divide-y divide-base-300">{impact[k].map((r:any)=><li key={r.id} className="break-words py-2">{k==='grants'?(pl?'Uprawnienie':'Grant'):k==='handoffs'?(pl?'Przekazanie':'Handoff'):(pl?'Wywiad':'Interview')}: {data.taskStates.find((t:any)=>t.id===r.taskId)?.title} · {r.operation??r.status??''}<span className="block text-xs text-company-muted">{r.id}</span></li>)}</ul>)}</details></div>{proposal.state!=='accepted'?<CcButton className="mt-4" onClick={()=>void action('review_impact')} variant="outline" loading={busy} disabled={!data.canWrite}>{pl?'Zapisz aktualny przegląd wpływu':'Record current impact review'}</CcButton>:null}</CcRecordEditorSection>
   <CcRecordEditorSection title={pl?'Bramki ryzyka dla tej operacji':'Risk gates for this operation'}>{data.gates.map((g:any)=><div key={g.taskId} className="flex flex-wrap items-center justify-between gap-3 border-b border-base-300 py-3"><span>{data.taskStates.find((t:any)=>t.id===g.taskId)?.title} · {g.seal?(pl?'Spełnione':'Satisfied'):(pl?'Wymagana weryfikacja':'Verification required')}</span><CcButton onClick={()=>setRiskTask(g.taskId)} variant="outline">{pl?'Otwórz warunki dopuszczenia':'Open admission requirements'}</CcButton></div>)}</CcRecordEditorSection>
   <CcRecordEditorSection title={pl?'Linia decyzji i historia':'Decision lineage and history'}>{data.supersededBy?.map((a:any)=><p key={a.id} className="border-b border-base-300 py-3">{pl?'Zastępująca propozycja':'Successor proposal'}: {a.title} · {label(a.status)}</p>)}{data.ancestors.map((a:any)=><p key={a.id} className="border-b border-base-300 py-3">{a.title}: {a.decision}</p>)}{data.previews.map((p:any)=><p key={p.id} className="py-2 text-sm">{pl?'Przegląd wpływu':'Impact review'} {p.version} · {new Date(p.createdAt).toLocaleString()}</p>)}{data.acceptance?<p>{pl?'Jawna akceptacja':'Explicit acceptance'} · {new Date(data.acceptance.createdAt).toLocaleString()}</p>:null}</CcRecordEditorSection></>:null}
  {root?.deferrals?.filter((f:any)=>!selectedId||f.targetId===selectedId).length?<CcRecordEditorSection title={pl?'Warunki powrotu i zdarzenia':'Reopening conditions and events'}><CcField label={pl?'Potwierdzenie rzeczywistego zdarzenia':'Confirmation of the actual event'}>{({id})=><textarea id={id} className="textarea textarea-bordered w-full" value={eventReason} onChange={e=>setEventReason(e.target.value)}/>}</CcField>{root.deferrals.filter((f:any)=>!selectedId||f.targetId===selectedId).map((f:any)=><div key={f.id} className="border-b border-base-300 py-4"><strong>{label(f.reason)} · {label(f.condition.type)}</strong><p className="my-2 text-sm">{f.explanation}</p>{f.condition.dueAt?<p>{new Date(f.condition.dueAt).toLocaleString()}</p>:null}{f.eventId?<p>{pl?'Ponownie otwarto':'Reopened'} · {new Date(f.reopenedAt).toLocaleString()}</p>:<CcButton onClick={()=>void reopen(f)} variant="outline" loading={busy} disabled={!root.canWrite||eventReason.trim().length<3}>{pl?'Potwierdź zdarzenie i otwórz ponownie':'Confirm event and reopen'}</CcButton>}</div>)}</CcRecordEditorSection>:null}
 </CcRecordEditorModal>{confirm?<CcConfirmDialog eyebrow={pl?"Decyzje":"Decisions"} busy={busy} title={pl?'Zaakceptować dokładnie ten wpływ?':'Accept exactly this impact?'} description={pl?'Dotknięta gotowość i uprawnienia zostaną unieważnione, a aktywna praca zatrzymana. Pozostała praca zachowa swój stan.':'Affected readiness and grants will be invalidated and active work stopped. Other work retains its state.'} detail={<p>{impact?.nodes.map((n:any)=>n.title).join(', ')}</p>} confirmLabel={pl?'Akceptuję wskazany zakres':'Accept the listed scope'} onCancel={()=>setConfirm(false)} onConfirm={()=>void action('accept')}/>:null}{discard?<CcConfirmDialog eyebrow={pl?"Decyzje":"Decisions"} title={pl?'Odrzucić niezapisane zmiany?':'Discard unsaved changes?'} description="" confirmLabel={pl?'Odrzuć':'Discard'} onCancel={()=>setDiscard(false)} onConfirm={onClose}/>:null}</>;
}
async function readPost(path:string,body:any){return (await api<any>(path,{method:'POST',body:JSON.stringify(body)})).data;}
