import { useEffect, useRef, useState } from "react";
import { api } from "../../api/client";
import { useLanguage } from "../../i18n/i18n";
import { CcButton } from "../../components/cc-button";
import { CcField } from "../../components/cc-field";
import { CcSelect } from "../../components/cc-select";
import { CcNotice } from "../../components/cc-notice";
import { CcConfirmDialog } from "../../components/cc-confirm-dialog";
import { CcRecordEditorModal, CcRecordEditorSection } from "../../components/cc-record-editor";

export const authorityLabels: Record<string, [string, string]> = {
  product_direction: ["Kierunek produktu", "Product direction"], money: ["Pieniądze", "Money"], legal: ["Prawo", "Legal"],
  critical_risk: ["Ryzyko krytyczne", "Critical risk"], mandate_change: ["Zmiana mandatu", "Mandate change"], ordinary_domain: ["Zwykła decyzja dziedzinowa", "Ordinary domain decision"],
  owner_reserved: ["Zastrzeżona dla właściciela", "Reserved for the owner"], delegated: ["Jawny mandat", "Explicit mandate"], blocked: ["Wymaga decyzji właściciela", "Owner decision required"],
  unclassified_owner: ["Klasyfikacja do potwierdzenia przez właściciela", "Classification requires owner confirmation"],
  authority_mandate_missing: ["Brak dokładnego, aktualnego mandatu", "No exact, current mandate"], authority_mandate_ambiguous: ["Więcej niż jeden pasujący mandat", "More than one matching mandate"],
  hierarchy_missing_principal: ["Brakuje aktywnego uczestnika ścieżki", "An active participant is missing"], hierarchy_missing_supervisor: ["Brakuje bezpośredniego przełożonego", "A direct supervisor is missing"],
  hierarchy_department_ambiguous: ["Brak jednego odpowiedzialnego działu", "A single accountable department is missing"], hierarchy_manager_ambiguous: ["Sprzeczne linie odpowiedzialności", "Conflicting reporting lines"],
  hierarchy_cycle: ["Cykl w hierarchii", "Reporting cycle"], hierarchy_director_not_peer: ["Dyrektor ma sprzeczną relację zwierzchnictwa", "A director has a conflicting superior relationship"],
  hierarchy_director_ambiguous: ["Niejednoznaczny dyrektor działu", "Ambiguous department director"], hierarchy_department_bypass: ["Ścieżka pomija odpowiedzialność działów", "The route bypasses department accountability"],
  authority_human_response_required: ["Ten wywiad wymaga uprawnionego człowieka", "This interview requires an authorized human"], authority_catalog_incomplete: ["Katalog uprawnień przekracza bezpieczny zakres", "The authority catalog exceeds the safe bound"], authority_scope_invalid: ["Zakres zawiera niedostępny rekord", "The scope contains an unavailable record"], authority_declaration_invalid: ["Uzupełnij klasyfikację i zakres", "Complete classification and scope"], hierarchy_too_large: ["Ścieżka przekracza bezpieczny zakres", "The route exceeds the safe bound"], hierarchy_ambiguous: ["Niejednoznaczna hierarchia", "Ambiguous hierarchy"], hierarchy_missing_common_level: ["Brak wspólnego poziomu odpowiedzialności", "No common accountability level"], authority_risk_missing: ["Najpierw uzupełnij ocenę ryzyka", "Complete the risk assessment first"], authority_scope_incomplete: ["Mandat musi jawnie obejmować wszystkie dotknięte zadania", "The mandate must explicitly cover every affected task"],
  active: ["Aktywny", "Active"], suspended: ["Zawieszony", "Suspended"], revoked: ["Odwołany", "Revoked"], low: ["Niskie", "Low"], medium: ["Średnie", "Medium"], high: ["Wysokie", "High"],
  accept_decision: ["Akceptacja decyzji", "Accept a decision"], supersede_decision: ["Zastąpienie decyzji", "Supersede a decision"], answer_interview: ["Odpowiedź w wywiadzie", "Answer an interview"], accept_interview: ["Akceptacja wywiadu", "Accept an interview"], review_decision: ["Niezależne review", "Independent review"], delegate_work: ["Delegowanie pracy", "Delegate work"]
};
const domains = ["product_direction", "money", "legal", "critical_risk", "mandate_change", "ordinary_domain"];
const operations = ["accept_decision", "supersede_decision", "answer_interview", "accept_interview"];
const localDate = (value: string) => { const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); };
function useAuthorityCopy() { const { locale } = useLanguage(); const pl = locale === "pl"; return { pl, label: (key: string) => authorityLabels[key]?.[pl ? 0 : 1] ?? (pl ? "Sprawdź zapisane warunki uprawnień" : "Check the recorded authority conditions") }; }

export function DecisionAuthorityFields({ value, onChange, catalog }: { value: any; onChange: (value: any) => void; catalog: any }) {
  const { pl, label } = useAuthorityCopy();
  return <CcRecordEditorSection title={pl ? "Kto może podjąć decyzję" : "Who may make this decision"}>
    <div className="grid gap-4 md:grid-cols-2">
      <CcField label={pl ? "Dziedzina decyzji" : "Decision domain"} required>{({ id }) => <CcSelect id={id} value={value.domain} onChange={event => onChange({ ...value, domain: event.target.value })}><option value="">{pl ? "Wybierz dziedzinę" : "Choose a domain"}</option>{domains.map(domain => <option key={domain} value={domain}>{label(domain)}</option>)}</CcSelect>}</CcField>
      <CcField label={pl ? "Odpowiedzialny dział" : "Accountable department"} required>{({ id }) => <CcSelect id={id} value={value.departmentKey} onChange={event => onChange({ ...value, departmentKey: event.target.value })}><option value="">{pl ? "Wybierz dział" : "Choose a department"}</option>{catalog?.departments?.map((department: any) => <option key={department.key} value={department.key}>{department.name}</option>)}</CcSelect>}</CcField>
      {value.domain === "ordinary_domain" ? ["requesterId", "recipientId"].map(key => <CcField key={key} label={key === "requesterId" ? (pl ? "Zgłaszający" : "Requester") : (pl ? "Odbiorca pracy" : "Work recipient")} required>{({ id }) => <CcSelect id={id} value={value[key]} onChange={event => onChange({ ...value, [key]: event.target.value })}><option value="">{pl ? "Wybierz osobę lub agenta" : "Choose a person or agent"}</option>{catalog?.workforce?.filter((worker: any) => worker.active && worker.principal).map((worker: any) => <option key={worker.id} value={worker.id}>{worker.name}</option>)}</CcSelect>}</CcField>) : null}
    </div>
    <p className="mt-3 text-sm text-company-muted">{value.domain === "ordinary_domain" ? (pl ? "Roost wskaże najbliższego uprawnionego decydenta na zapisanej ścieżce. Brak mandatu wymaga decyzji właściciela." : "Roost selects the nearest authorized decision maker on the recorded route. A missing mandate requires an owner decision.") : (pl ? "Ta dziedzina wymaga jawnej akceptacji aktualnego właściciela firmy." : "This domain requires explicit acceptance by the current workspace owner.")}</p>
  </CcRecordEditorSection>;
}

export function DecisionAuthorityDetails({ authority, catalog, onMandates }: { authority: any; catalog?: any; onMandates?: () => void }) {
  const { pl, label } = useAuthorityCopy(); if (!authority) return null;
  const workerName = (id: string) => catalog?.workforce?.find((worker: any) => worker.id === id || worker.principal?.id === id)?.name ?? id;
  const entityName = (entity: any) => catalog?.entityCatalog?.find((item: any) => item.type === entity.type && item.id === entity.id)?.name ?? entity.id;
  const mandate = authority.mandate;
  return <CcRecordEditorSection title={pl ? "Uprawnienia do tej decyzji" : "Authority for this decision"}>
    <CcNotice tone={authority.status === "blocked" ? "warning" : "info"} title={label(authority.status)} detail={authority.reason === "exact_mandate" ? undefined : label(authority.reason)} />
    {authority.principal ? <p className="my-3 break-words text-sm"><strong>{pl ? "Decydent" : "Decision maker"}:</strong> {workerName(authority.principal.id)}<span className="block text-xs text-company-muted">{authority.principal.kind === "agent" ? (pl ? "Agent" : "Agent") : (pl ? "Człowiek" : "Human")} · {authority.principal.id}</span></p> : null}
    {mandate ? <div className="my-3 space-y-2 text-sm [overflow-wrap:anywhere]"><p><strong>{pl ? "Mandat" : "Mandate"}:</strong> {mandate.id} · {pl ? "wersja" : "version"} {mandate.version}</p><p>{label(mandate.status)} · {pl ? "Limit ryzyka" : "Risk limit"}: {label(mandate.maxRisk)}</p><p>{new Date(mandate.startsAt).toLocaleString()} — {mandate.endsAt ? new Date(mandate.endsAt).toLocaleString() : (pl ? "bez terminu końcowego" : "no end date")}</p><p>{mandate.operations.map(label).join(" · ")}</p><p>{pl ? "Zakres" : "Scope"}: {mandate.entities.map((entity: any) => entityName(entity)).join(", ")}</p><p>{pl ? "Wyłączenia" : "Exclusions"}: {mandate.exclusionReason}</p>{mandate.exclusions?.map((entity: any) => <p key={entity.type + entity.id}>{entityName(entity)}</p>)}</div> : null}
    {authority.path?.length ? <><h3 className="mt-4 font-medium">{pl ? "Najkrótsza prawidłowa ścieżka" : "Shortest valid route"}</h3><ol className="mt-2 divide-y divide-base-300">{authority.path.map((id: string, index: number) => <li className="break-words py-2 text-sm" key={id}>{index + 1}. {workerName(id)}<span className="block text-xs text-company-muted">{id}</span></li>)}</ol></> : null}
    {authority.missingId ? <p className="mt-2 break-words text-sm">{pl ? "Sprawdź uczestnika" : "Check participant"}: {workerName(authority.missingId)}</p> : null}
    {onMandates ? <CcButton className="mt-4" variant="outline" onClick={onMandates}>{pl ? "Mandaty i historia uprawnień" : "Mandates and authority history"}</CcButton> : null}
  </CcRecordEditorSection>;
}

const newMandateDraft = () => ({ workforceId: "", departmentKey: "", sourceDecisionId: "", entityType: "task", entityId: "", entities: [], exclusions: [], operations: ["accept_decision"], maxRisk: "low", startsAt: "", endsAt: "", status: "active", exclusionReason: "", reason: "" });
export function TaskDecisionAuthorityHistory({ records }: { records?: any[] }) {
  const { pl } = useAuthorityCopy();
  if (!records?.length) return null;
  return <section className="my-4 min-w-0 space-y-3">
    {records.some(record => !record.current) ? <CcNotice tone="warning" title={pl ? "Uprawnienia do zależnej decyzji wygasły lub zmieniły się. Praca wymaga ponownej autoryzacji." : "Authority for a dependent Decision expired or changed. Work requires reauthorization."} /> : null}
    {records.map(record => <details key={record.decisionId} className="border-b border-base-300 py-3"><summary>{pl ? "Zapisane uprawnienia do decyzji" : "Recorded Decision authority"} · {record.title ?? record.decisionId}</summary><DecisionAuthorityDetails authority={record.acceptedAuthority}/></details>)}
  </section>;
}

export function DelegatedMandatesModal({ onClose }: { onClose: () => void }) {
  const { pl, label } = useAuthorityCopy();
  const [data, setData] = useState<any>(null), [error, setError] = useState(false), [busy, setBusy] = useState(false), [selected, setSelected] = useState<any>(null), [dirty, setDirty] = useState(false), [discard, setDiscard] = useState(false);
  const [draft, setDraft] = useState<any>(newMandateDraft);
  const [saved, setSaved] = useState(false);
  const key = useRef(crypto.randomUUID());
  const update = (patch: any) => { setDraft({ ...draft, ...patch }); setDirty(true); setSaved(false); key.current = crypto.randomUUID(); };
  async function refresh() { try { setData((await api<any>("/v1/decisions/mandates")).data); setError(false); } catch { setError(true); } }
  useEffect(() => { void refresh(); }, []);
  const close = () => dirty ? setDiscard(true) : onClose();
  function edit(mandate: any) { setSelected(mandate); setDraft({ ...mandate, workforceId: mandate.workforceId, entityType: "task", entityId: "", startsAt: localDate(mandate.startsAt), endsAt: mandate.endsAt ? localDate(mandate.endsAt) : "", sourceDecisionId: "", reason: "" }); key.current = crypto.randomUUID(); setDirty(false); }
  async function save() {
    const worker = data?.workforce.find((worker: any) => worker.id === draft.workforceId); const holder = selected?.holder ?? worker?.principal; if (!holder) return;
    setBusy(true); setError(false);
    try {
      const body = { holder, departmentKey: draft.departmentKey, entities: draft.entities, decisionDomains: ["ordinary_domain"], operations: draft.operations, exclusions: draft.exclusions, exclusionReason: draft.exclusionReason,
        maxRisk: draft.maxRisk, startsAt: new Date(draft.startsAt).toISOString(), endsAt: draft.endsAt ? new Date(draft.endsAt).toISOString() : null, status: draft.status, sourceDecisionId: draft.sourceDecisionId, reason: draft.reason };
      await api("/v1/decisions/mandates", { method: "POST", body: JSON.stringify({ requestId: key.current, expectedVersion: data.expectedVersion, mandateId: selected?.id ?? null, body }) });
      key.current = crypto.randomUUID(); setDirty(false); setSelected(null); setDraft(newMandateDraft()); await refresh(); setSaved(true);
    } catch { setError(true); } finally { setBusy(false); }
  }
  return <><CcRecordEditorModal titleId="delegated-mandates-title" eyebrow={pl ? "Decyzje" : "Decisions"} title={pl ? "Delegowane mandaty" : "Delegated mandates"} description={pl ? "Każda zmiana wymaga zaakceptowanej decyzji właściciela. Poprzednie wersje pozostają w historii." : "Every change requires an accepted owner Decision. Previous versions remain in history."} onClose={close} onSubmit={event => { event.preventDefault(); void save(); }} actions={<><CcButton variant="ghost" onClick={close}>{pl ? "Wróć" : "Back"}</CcButton><CcButton variant="outline" onClick={() => void refresh()}>{pl ? "Odśwież uprawnienia" : "Refresh authority"}</CcButton><CcButton variant="primary" type="submit" loading={busy} disabled={busy || !dirty || !data?.canWrite || !draft.entities.length || !draft.operations.length || selected?.status === "revoked"}>{pl ? "Zapisz wersję mandatu" : "Record mandate version"}</CcButton></>}>
    {saved ? <CcNotice tone="success" title={pl ? "Zapisano wersję mandatu." : "Mandate version recorded."} live /> : null}
    {data?.truncated ? <CcNotice tone="warning" title={pl ? "Pokazano ograniczony katalog. Brak rekordu wymaga zawężenia zakresu w źródle." : "The catalog is limited. A missing record requires a narrower source scope."} /> : null}
    {error ? <CcNotice tone="error" title={pl ? "Nie zapisano mandatu. Odśwież uprawnienia i sprawdź źródłową decyzję." : "Mandate not recorded. Refresh authority and check the source Decision."} /> : null}
    {!data ? <CcNotice title={pl ? "Wczytywanie mandatów…" : "Loading mandates…"} /> : !data.canWrite ? <CcNotice title={pl ? "Mandaty może zmieniać tylko aktualny właściciel." : "Only the current owner may change mandates."} /> : null}
    {data?.mandates.length ? <CcRecordEditorSection title={pl ? "Aktualne mandaty" : "Current mandates"}>{data.mandates.map((mandate: any) => <div className="flex flex-wrap items-center justify-between gap-3 border-b border-base-300 py-3" key={mandate.id}><span>{data.workforce.find((worker: any) => worker.id === mandate.workforceId)?.name} · {label(mandate.status)} · {pl ? "wersja" : "version"} {mandate.version}</span><CcButton variant="outline" onClick={() => edit(mandate)} disabled={dirty}>{pl ? "Pokaż / następna wersja" : "Inspect / next version"}</CcButton></div>)}</CcRecordEditorSection> : null}
    {!data?.mandates.length && data ? <CcNotice title={pl ? "Brak delegowanych mandatów." : "No delegated mandates."} /> : null}
    <fieldset disabled={busy || !data?.canWrite || selected?.status === "revoked"} className="min-w-0 [overflow-wrap:anywhere]">
    <CcRecordEditorSection title={selected ? (pl ? "Następna wersja" : "Next version") : (pl ? "Nowy mandat" : "New mandate")}><div className="grid gap-4 md:grid-cols-2">
      <CcField label={pl ? "Posiadacz mandatu" : "Mandate holder"} required>{({ id }) => <CcSelect id={id} required value={draft.workforceId} disabled={!!selected} onChange={event => update({ workforceId: event.target.value })}><option value="">{pl ? "Wybierz" : "Choose"}</option>{data?.workforce.filter((worker: any) => (worker.id === selected?.workforceId || worker.active && worker.principal && worker.principal.id !== data.ownerUserId)).map((worker: any) => <option key={worker.id} value={worker.id}>{worker.name}</option>)}</CcSelect>}</CcField>
      <CcField label={pl ? "Dział" : "Department"} required>{({ id }) => <CcSelect id={id} required value={draft.departmentKey} onChange={event => update({ departmentKey: event.target.value })}><option value="">{pl ? "Wybierz" : "Choose"}</option>{data?.departments?.map((department: any) => <option key={department.key} value={department.key}>{department.name}</option>)}</CcSelect>}</CcField>
      <CcField label={pl ? "Zaakceptowana decyzja o zmianie mandatu" : "Accepted mandate-change Decision"} required>{({ id }) => <CcSelect id={id} required value={draft.sourceDecisionId} onChange={event => update({ sourceDecisionId: event.target.value })}><option value="">{pl ? "Wybierz nową decyzję właściciela" : "Choose a new owner Decision"}</option>{data?.sources.filter((source: any) => source.id !== selected?.sourceDecisionId).map((source: any) => <option key={source.id} value={source.id}>{source.title}</option>)}</CcSelect>}</CcField>
      <CcField label={pl ? "Stan" : "Status"}>{({ id }) => <CcSelect id={id} value={draft.status} onChange={event => update({ status: event.target.value })}>{["active", "suspended", "revoked"].map(status => <option key={status} value={status}>{label(status)}</option>)}</CcSelect>}</CcField>
      <CcField label={pl ? "Maksymalne ryzyko" : "Maximum risk"}>{({ id }) => <CcSelect id={id} value={draft.maxRisk} onChange={event => update({ maxRisk: event.target.value })}>{["low", "medium", "high"].map(risk => <option key={risk} value={risk}>{label(risk)}</option>)}</CcSelect>}</CcField>
      {["startsAt", "endsAt"].map(field => <CcField key={field} label={field === "startsAt" ? (pl ? "Ważny od (czas lokalny)" : "Valid from (local time)") : (pl ? "Ważny do (opcjonalnie)" : "Valid until (optional)")} required={field === "startsAt"}>{({ id }) => <input id={id} className="input input-bordered w-full" type="datetime-local" required={field === "startsAt"} value={draft[field]} onChange={event => update({ [field]: event.target.value })} />}</CcField>)}
      {["exclusionReason", "reason"].map(field => <CcField key={field} label={field === "reason" ? (pl ? "Uzasadnienie zmiany" : "Reason for change") : (pl ? "Opis wyłączeń" : "Exclusions explanation")} required>{({ id }) => <textarea id={id} className="textarea textarea-bordered w-full" required minLength={3} value={draft[field]} onChange={event => update({ [field]: event.target.value })} />}</CcField>)}
    </div><fieldset className="mt-4"><legend className="mb-2 font-medium">{pl ? "Dozwolone operacje" : "Allowed operations"}</legend><div className="grid gap-3 md:grid-cols-2">{operations.map(operation => <label key={operation} className="flex items-center gap-2 text-sm"><input className="checkbox checkbox-sm" type="checkbox" checked={draft.operations.includes(operation)} onChange={event => update({ operations: event.target.checked ? [...draft.operations, operation] : draft.operations.filter((value: string) => value !== operation) })} />{label(operation)}</label>)}</div></fieldset></CcRecordEditorSection>
    <CcRecordEditorSection title={pl ? "Dokładny zakres i wyłączenia" : "Exact scope and exclusions"}><div className="grid gap-4 md:grid-cols-2"><CcField label={pl ? "Typ rekordu" : "Record type"}>{({ id }) => <CcSelect id={id} value={draft.entityType} onChange={event => update({ entityType: event.target.value, entityId: "" })}>{["task", "application", "project", "procedure"].map(type => <option key={type} value={type}>{({ task: pl ? "Zadanie" : "Task", application: pl ? "Aplikacja" : "Application", project: pl ? "Projekt" : "Project", procedure: pl ? "Procedura" : "Procedure" })[type]}</option>)}</CcSelect>}</CcField><CcField label={pl ? "Rekord w zakresie" : "Scope record"}>{({ id }) => <CcSelect id={id} value={draft.entityId} onChange={event => update({ entityId: event.target.value })}><option value="">{pl ? "Wybierz rekord" : "Choose a record"}</option>{data?.entityCatalog?.filter((entity: any) => entity.type === draft.entityType).map((entity: any) => <option key={entity.id} value={entity.id}>{entity.name}</option>)}</CcSelect>}</CcField></div><div className="mt-3 flex flex-wrap gap-3">{["entities", "exclusions"].map(field => <CcButton key={field} variant="outline" disabled={!/^[a-f0-9-]{36}$/i.test(draft.entityId) || draft[field].length >= 32 || draft[field].some((entity: any) => entity.type === draft.entityType && entity.id === draft.entityId)} onClick={() => update({ [field]: [...draft[field], { type: draft.entityType, id: draft.entityId }], entityId: "" })}>{field === "entities" ? (pl ? "Dodaj do zakresu" : "Add to scope") : (pl ? "Dodaj wyłączenie" : "Add exclusion")}</CcButton>)}</div>{["entities", "exclusions"].map(field => <ul key={field} className="mt-3 divide-y divide-base-300">{draft[field].map((entity: any, index: number) => <li key={entity.type + entity.id} className="flex flex-wrap items-center justify-between gap-3 break-words py-2 text-sm"><span>{field === "entities" ? (pl ? "Zakres" : "Scope") : (pl ? "Wyłączenie" : "Exclusion")}: {data?.entityCatalog?.find((item: any) => item.type === entity.type && item.id === entity.id)?.name ?? entity.id}</span><CcButton variant="ghost" onClick={() => update({ [field]: draft[field].filter((_: any, position: number) => position !== index) })}>{pl ? "Usuń z wersji" : "Remove from version"}</CcButton></li>)}</ul>)}</CcRecordEditorSection>
    </fieldset>
    <CcRecordEditorSection title={pl ? "Historia mandatów" : "Mandate history"}>{data?.history.filter((mandate: any) => !selected || mandate.id === selected.id).map((mandate: any) => <div key={mandate.versionId} className="break-words border-b border-base-300 py-3 text-sm"><strong>{label(mandate.status)} · {pl ? "wersja" : "version"} {mandate.version}</strong><p>{mandate.reason}</p><p>{new Date(mandate.createdAt).toLocaleString()} · {pl ? "Wystawca" : "Issuer"}: {mandate.issuer.id}</p><p>{pl ? "Decyzja źródłowa" : "Source Decision"}: {data?.sources.find((source: any) => source.id === mandate.sourceDecisionId)?.title ?? mandate.sourceDecisionId}</p><details className="mt-3"><summary>{pl ? "Warunki tej wersji" : "Conditions of this version"}</summary><DecisionAuthorityDetails authority={{status:"delegated",reason:"exact_mandate",principal:mandate.holder,mandate}} catalog={data}/></details></div>)}</CcRecordEditorSection>
  </CcRecordEditorModal>{discard ? <CcConfirmDialog eyebrow={pl ? "Mandaty" : "Mandates"} title={pl ? "Odrzucić niezapisane zmiany?" : "Discard unsaved changes?"} description="" confirmLabel={pl ? "Odrzuć" : "Discard"} onCancel={() => setDiscard(false)} onConfirm={onClose} /> : null}</>;
}
