import { FormEvent, useEffect, useMemo, useState } from "react";
import { api, AppApiError } from "../../api/client";
import { CcButton } from "../../components/cc-button";
import { CcField } from "../../components/cc-field";
import { CcNotice } from "../../components/cc-notice";
import { CcPageHeader } from "../../components/cc-page-header";
import { CcRecordEditorModal, CcRecordEditorSection } from "../../components/cc-record-editor";
import { CcSelect } from "../../components/cc-select";
import { useOwnerPacket } from "../../hooks/use-owner-packet";
import { useLanguage } from "../../i18n/i18n";
import { humanizeBusinessValue } from "./shared";

type SearchResult = { entityType: string; id: string; title: string; subtitle?: string | null; recordType?: string };
type EntityPacket = {
  entityType: string; record: Record<string, unknown> & { id: string }; organizationalContext?: { ownerDepartment?: { key: string; name: string } | null; relatedDepartments?: Array<{ key: string; name: string }>; applicableDepartments?: Array<{ key: string; name: string }>; scopes?: Array<{ type: string; label?: string | null }> };
  relations: Array<{ id: string; dependencyType: string; fromEntityType?: string | null; fromEntityId?: string | null; toEntityType?: string | null; toEntityId?: string | null; status: string }>;
  related: Array<{ entityType: string; entityId: string; record: Record<string, unknown> }>;
  evidence: Array<{ id: string; type: string; reference: string; verificationStatus: string; observedAt: string; description?: string | null }>;
};

function text(record: Record<string, unknown>, ...keys: string[]) { for (const key of keys) if (typeof record[key] === "string" && record[key]) return String(record[key]); return ""; }
function entityTitle(record: Record<string, unknown>) { return text(record, "title", "name", "key") || "Company object"; }
function entityHref(type: string, id: string) { return `/areas?area=00-ogolny&view=entity&type=${encodeURIComponent(type)}&id=${encodeURIComponent(id)}`; }
function visibleFields(record: Record<string, unknown>) {
  const excluded = new Set(["id", "workspaceId", "createdAt", "updatedAt", "metadata", "steps", "children", "parent"]);
  return Object.entries(record).filter(([key, value]) => !excluded.has(key) && value !== null && value !== "" && typeof value !== "object").slice(0, 18);
}

function RelationEditor({ entityType, entityId, onClose, onSaved }: { entityType: string; entityId: string; onClose: () => void; onSaved: () => void }) {
  const { t } = useLanguage(); const [query, setQuery] = useState(""); const [results, setResults] = useState<SearchResult[]>([]); const [selected, setSelected] = useState<SearchResult | null>(null); const [relationType, setRelationType] = useState("related_to"); const [direction, setDirection] = useState("outgoing"); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { const value = query.trim(); if (value.length < 2) { setResults([]); return; } const controller = new AbortController(); const timer = window.setTimeout(() => { void api<{ data: SearchResult[] }>(`/v1/company-intelligence/search?q=${encodeURIComponent(value)}`, { signal: controller.signal }).then((response) => setResults(response.data.filter((item) => !(item.entityType === entityType && item.id === entityId)).slice(0, 12))).catch(() => setResults([])); }, 180); return () => { window.clearTimeout(timer); controller.abort(); }; }, [entityId, entityType, query]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; setBusy(true); setError(null); const current = { entityType, entityId }; const target = { entityType: selected.recordType === "requirement" ? "requirement" : selected.entityType, entityId: selected.id }; try { await api("/v1/entity-relations", { method: "POST", body: JSON.stringify({ dependencyType: relationType, from: direction === "outgoing" ? current : target, to: direction === "outgoing" ? target : current }) }); onSaved(); } catch (caught) { setError(caught instanceof AppApiError ? caught.code : "request_failed"); } finally { setBusy(false); } }
  return <CcRecordEditorModal actions={<><CcButton onClick={onClose} variant="ghost">{t("common.cancel")}</CcButton><CcButton disabled={!selected} loading={busy} type="submit" variant="primary">{t("common.save")}</CcButton></>} description="Create one typed Company Graph edge. Both objects remain canonical and independently owned." eyebrow="Company Graph" onClose={onClose} onSubmit={submit} title="Link another company object" titleId="entity-relation-editor-title">
    {error ? <CcNotice live tone="error" title={humanizeBusinessValue(error)} /> : null}
    <CcRecordEditorSection title="Relationship"><div className="grid gap-4 md:grid-cols-2"><CcField label="Relationship type">{({ id }) => <CcSelect id={id} onChange={(event) => setRelationType(event.target.value)} value={relationType}>{["depends_on", "blocks", "implements", "consumes", "exposes", "affects", "requires", "owned_by", "validated_by", "governed_by", "supersedes", "related_to"].map((value) => <option key={value} value={value}>{humanizeBusinessValue(value)}</option>)}</CcSelect>}</CcField><CcField label="Direction">{({ id }) => <CcSelect id={id} onChange={(event) => setDirection(event.target.value)} value={direction}><option value="outgoing">This object → target</option><option value="incoming">Target → this object</option></CcSelect>}</CcField></div></CcRecordEditorSection>
    <CcRecordEditorSection title="Target object"><CcField label="Search company objects">{({ id }) => <input autoComplete="off" className="input input-bordered w-full" id={id} onChange={(event) => { setQuery(event.target.value); setSelected(null); }} placeholder="Task, project, requirement, resource…" value={selected ? selected.title : query} />}</CcField>{results.length && !selected ? <div className="mt-2 grid max-h-64 gap-1 overflow-y-auto rounded-company border border-base-300 bg-base-100 p-2">{results.map((result) => <button className="flex items-center justify-between rounded-company px-3 py-2 text-left hover:bg-base-200" key={`${result.entityType}:${result.id}`} onClick={() => { setSelected(result); setQuery(result.title); setResults([]); }} type="button"><span><strong>{result.title}</strong><small className="block text-company-muted">{humanizeBusinessValue(result.recordType || result.entityType)} · {result.subtitle}</small></span><i className="ph-bold ph-plus" aria-hidden="true"></i></button>)}</div> : null}</CcRecordEditorSection>
  </CcRecordEditorModal>;
}

export function EntityInspectorRoute() {
  const { locale, t } = useLanguage(); const params = new URLSearchParams(window.location.search); const type = params.get("type") || "company_record"; const id = params.get("id") || ""; const [refreshKey, setRefreshKey] = useState(0); const [linking, setLinking] = useState(false);
  const packet = useOwnerPacket<EntityPacket>(id ? `/v1/company-intelligence/entities/${encodeURIComponent(type)}/${encodeURIComponent(id)}?refresh=${refreshKey}` : "", Boolean(id), t); const data = packet.data; const title = data ? entityTitle(data.record) : "Company object"; const fields = useMemo(() => data ? visibleFields(data.record) : [], [data]);
  if (!id) return <CcNotice tone="error" title="Missing entity identifier" detail="Open an object from search or Company Graph." />;
  return <><CcPageHeader actions={<><CcButton href="/areas?area=00-ogolny&view=company-graph" iconLeft="ph-graph" size="sm" variant="outline">Company Graph</CcButton><CcButton iconLeft="ph-link" onClick={() => setLinking(true)} size="sm" variant="primary">Link object</CcButton></>} description={text(data?.record || {}, "description", "businessPurpose", "purpose") || "Canonical company object with organizational, relationship and evidence context."} eyebrow={humanizeBusinessValue(data?.entityType || type, undefined, locale)} title={title} />
    {packet.status === "loading" ? <CcNotice live tone="loading" title="Loading company context…" /> : null}{packet.status === "error" ? <CcNotice live tone="error" title={packet.error || "Entity could not load."} /> : null}
    {data ? <div className="grid gap-4 xl:grid-cols-[minmax(0,1.2fr)_minmax(20rem,.8fr)]">
      <div className="grid gap-4"><section className="roost-work-panel rounded-company p-5"><h2 className="text-lg font-black">Record state</h2><dl className="mt-4 grid gap-x-6 gap-y-4 sm:grid-cols-2">{fields.map(([key, value]) => <div key={key}><dt className="text-xs font-black uppercase tracking-wide text-company-muted">{humanizeBusinessValue(key, undefined, locale)}</dt><dd className="mt-1 break-words text-sm font-semibold text-company-ink">{typeof value === "boolean" ? (value ? "Yes" : "No") : String(value)}</dd></div>)}</dl></section>
      <section className="roost-work-panel rounded-company p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="text-lg font-black">Relationships</h2><p className="text-sm text-company-muted">Typed edges in the shared Company Graph.</p></div><span className="badge badge-outline">{data.relations.length}</span></div><div className="mt-4 grid gap-2">{data.relations.length ? data.relations.map((relation) => { const outgoing = relation.fromEntityId === id; const related = data.related.find((item) => item.entityId === (outgoing ? relation.toEntityId : relation.fromEntityId)); return <a className="flex items-center gap-3 rounded-company border border-base-300 p-3 transition-colors hover:border-primary" href={related ? entityHref(related.entityType, related.entityId) : "#"} key={relation.id}><i className={`ph-bold ${outgoing ? "ph-arrow-right" : "ph-arrow-left"}`} aria-hidden="true"></i><span className="min-w-0 flex-1"><strong className="block truncate">{related ? entityTitle(related.record) : "Related object"}</strong><small className="text-company-muted">{humanizeBusinessValue(relation.dependencyType)} · {humanizeBusinessValue(related?.entityType || "entity")}</small></span></a>; }) : <CcNotice tone="empty" title="No relationships yet" detail="Link this object to its goal, project, requirements, components, tasks, resources or decisions." />}</div></section></div>
      <aside className="grid content-start gap-4"><section className="roost-work-panel rounded-company p-5"><h2 className="text-lg font-black">Organizational context</h2><div className="mt-4 grid gap-3 text-sm"><div><span className="text-company-muted">Owner department</span><strong className="block">{data.organizationalContext?.ownerDepartment?.name || "Unassigned"}</strong></div><div><span className="text-company-muted">Related departments</span><div className="mt-1 flex flex-wrap gap-1">{data.organizationalContext?.relatedDepartments?.length ? data.organizationalContext.relatedDepartments.map((department) => <span className="badge badge-outline" key={department.key}>{department.name}</span>) : "—"}</div></div><div><span className="text-company-muted">Applicable departments</span><div className="mt-1 flex flex-wrap gap-1">{data.organizationalContext?.applicableDepartments?.length ? data.organizationalContext.applicableDepartments.map((department) => <span className="badge badge-outline" key={department.key}>{department.name}</span>) : "—"}</div></div><div><span className="text-company-muted">Scopes</span><div className="mt-1 flex flex-wrap gap-1">{data.organizationalContext?.scopes?.length ? data.organizationalContext.scopes.map((scope, index) => <span className="badge badge-outline" key={`${scope.type}:${index}`}>{humanizeBusinessValue(scope.type)}{scope.label ? ` · ${scope.label}` : ""}</span>) : "—"}</div></div></div></section>
      <section className="roost-work-panel rounded-company p-5"><div className="flex items-center justify-between"><h2 className="text-lg font-black">Evidence</h2><span className="badge badge-outline">{data.evidence.length}</span></div><div className="mt-4 grid gap-2">{data.evidence.length ? data.evidence.map((evidence) => <article className="rounded-company border border-base-300 p-3" key={evidence.id}><div className="flex justify-between gap-2"><strong>{humanizeBusinessValue(evidence.type)}</strong><span className="badge badge-outline">{humanizeBusinessValue(evidence.verificationStatus)}</span></div><p className="mt-1 text-sm text-company-muted">{evidence.reference}</p></article>) : <p className="text-sm text-company-muted">No evidence has been attached to this object.</p>}</div></section></aside>
    </div> : null}
    {linking ? <RelationEditor entityId={id} entityType={type === "requirement" ? "requirement" : type} onClose={() => setLinking(false)} onSaved={() => { setLinking(false); setRefreshKey((value) => value + 1); }} /> : null}
  </>;
}
