import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { api, AppApiError } from "../../api/client";
import { CcButton } from "../../components/cc-button";
import { CcField } from "../../components/cc-field";
import { CcSelect } from "../../components/cc-select";
import { CcTextInput } from "../../components/cc-text-input";
import { CcNotice } from "../../components/cc-notice";
import { useLanguage } from "../../i18n/i18n";

const terms:Record<string,[string,string]>={
  prepare_adjudication:["Eskaluj konflikt do właściciela","Escalate conflict to owner"],adjudicator:["Niezależny rozstrzygający","Independent adjudicator"],propose_merge:["Wskaż możliwy duplikat","Suggest a duplicate"],resolve_merge:["Rozpatrz scalenie","Resolve merge"],otherId:["Drugie zgłoszenie","Other finding"],candidateId:["Propozycja scalenia","Merge proposal"],mergeVerdict:["Rozstrzygnięcie","Resolution"],distinct:["Odrębne zgłoszenia","Distinct findings"],merge_records:["Scal z drugim zgłoszeniem","Merge into other finding"],occurrence:["Dodaj wystąpienie lub dowód naprawy","Add occurrence or fix evidence"],purpose:["Rodzaj zapisu","Record purpose"],observation:["Obserwacja","Observation"],fix:["Dowód naprawy mojego autorstwa","Fix evidence authored by me"],deferral:["Odroczenie","Deferral"],referenceRevision:["Wersja zasobu lub konfiguracji","Resource or configuration revision"],explanation:["Wyjaśnienie","Explanation"],reproducibility:["Odtwarzalność","Reproducibility"],reproduced:["Odtworzone","Reproduced"],intermittent:["Występuje okresowo","Intermittent"],not_reproduced:["Nie odtworzono","Not reproduced"],sourceTask:["Zadanie źródłowe dla mandatów","Source task for mandates"],author:["Autor wersji","Version author"],credential:["Poświadczenie agenta","Agent credential"],grant_form:["Nadaj jedno uprawnienie","Grant one operation"],operation:["Operacja","Operation"],mandate:["Mandat i droga odpowiedzialności","Mandate and responsibility path"],dependencies:["Zależności — identyfikatory zadań, po jednym w wierszu","Dependencies — task IDs, one per line"],selectionHint:["Możesz zaznaczyć kilka źródeł i dowodów.","You can select multiple sources and evidence records."],
  findings:["Zgłoszenia i weryfikacja","Findings and verification"],new:["Nowe zgłoszenie","New finding"],save:["Zapisz","Save"],cancel:["Anuluj","Cancel"],loading:["Wczytywanie zgłoszeń…","Loading findings…"],empty:["Brak zgłoszeń dla tej aplikacji.","No findings for this application."],refresh:["Odśwież","Refresh"],
  defect:["Błąd","Defect"],unfinished_function:["Niedokończona funkcja","Unfinished function"],stale_documentation:["Nieaktualna dokumentacja","Stale documentation"],missing_assumption:["Brakujące założenie","Missing assumption"],improvement:["Usprawnienie","Improvement"],
  observed:["Zaobserwowane","Observed"],deduplication_pending:["Sprawdzenie duplikatów","Deduplication pending"],verification_pending:["Oczekuje na weryfikację","Verification pending"],verified:["Potwierdzone","Verified"],rejected:["Odrzucone","Rejected"],inconclusive:["Nierozstrzygnięte","Inconclusive"],triage_pending:["Oczekuje na triage","Triage pending"],converted_to_task:["Powiązane z zadaniem","Converted to task"],converted_to_decision:["Powiązane z decyzją","Converted to decision"],deferred:["Odroczone","Deferred"],merged:["Scalone","Merged"],
  title:["Tytuł","Title"],classification:["Klasa zgłoszenia","Finding class"],scope:["Dokładny zakres","Exact scope"],excluded:["Poza zakresem","Excluded scope"],expected:["Oczekiwane zachowanie","Expected behavior"],observedBehavior:["Zaobserwowane zachowanie","Observed behavior"],impact:["Wpływ","Impact"],steps:["Kroki odtworzenia (po jednym w wierszu)","Reproduction steps (one per line)"],limitations:["Ograniczenia dowodów","Evidence limitations"],build:["Wersja kompilacji","Build version"],environment:["Środowisko","Environment"],competencies:["Wymagane kompetencje (oddzielone przecinkiem)","Required competencies (comma separated)"],risk:["Znane ryzyko","Known risk"],low:["Niskie","Low"],medium:["Średnie","Medium"],high:["Wysokie","High"],critical:["Krytyczne","Critical"],
  source:["Źródło","Source"],evidence:["Dowód","Evidence"],component:["Komponent","Component"],requester:["Pracownik zgłaszający potrzebę","Requesting worker"],recipient:["Odbiorca w hierarchii","Hierarchy recipient"],decisionNeed:["Potrzebna decyzja","Decision needed"],none:["Rozwiązanie jest znane","Solution is known"],material_unknown:["Brak materialnego założenia","Material assumption missing"],product_direction:["Kierunek produktu","Product direction"],money:["Pieniądze","Money"],legal:["Prawo","Legal"],critical_risk:["Ryzyko krytyczne","Critical risk"],mandate_change:["Zmiana mandatu","Mandate change"],
  history:["Historia","History"],versions:["Wersje i autorzy","Versions and authors"],occurrences:["Wystąpienia","Occurrences"],fingerprint:["Sygnatura dokładnego duplikatu","Exact duplicate fingerprint"],verifier:["Niezależny weryfikator","Independent verifier"],manager:["Osoba odpowiedzialna za triage","Triage owner"],reason:["Uzasadnienie","Reason"],method:["Metoda weryfikacji","Verification method"],confirmed:["Potwierdzam","Confirmed"],verify:["Zapisz weryfikację","Record verification"],queue_deduplication:["Rozpocznij sprawdzenie duplikatów","Queue deduplication"],deduplicate:["Zakończ sprawdzenie duplikatów","Complete deduplication"],queue_triage:["Przekaż do triage","Queue triage"],prepare_task:["Przygotuj jedno zadanie","Prepare one task"],convert_task:["Potwierdź konwersję po Ready","Finalize after Ready"],prepare_decision:["Przygotuj decyzję właściciela","Prepare owner decision"],prepare_interview:["Przygotuj wywiad","Prepare interview"],convert_decision:["Powiąż zaakceptowaną decyzję","Link accepted decision"],defer:["Odrocz do zdarzenia","Defer until an event"],reopen:["Wznów po zdarzeniu","Reopen after an event"],revise:["Nowa wersja zgłoszenia","Revise finding"],correctionReason:["Powód korekty","Correction reason"],grant:["Nadaj jednorazowe uprawnienie","Issue one-use capability"],finding_verify:["Weryfikacja zgłoszenia","Finding verification"],finding_triage:["Triage zgłoszenia","Finding triage"],
  choose:["Wybierz…","Choose…"],canonical:["Język danych workspace","Workspace data language"],languageRequired:["Przed pierwszym zgłoszeniem administrator ustala język danych workspace.","An administrator must set the workspace data language before the first finding."],languageHint:["Treść zgłoszenia zapisuj w języku danych workspace. Etykiety konsoli zależą od języka użytkownika.","Write finding content in the workspace data language. Console labels follow the user language."],stale:["Weryfikacja wymaga odnowienia. Utwórz nową wersję z aktualnymi dowodami.","Verification needs renewal. Create a revision with current evidence."],blocked:["Brakuje aktualnego mandatu, kompetencji lub zakresu. Uzupełnij kontekst w istniejącym rejestrze zadań i mandatów.","A current mandate, competencies or scope is missing. Complete context in the existing task and mandate records."],failed:["Operacja nie została wykonana. Sprawdź blokady i odśwież dane.","The operation was not applied. Check blockers and refresh."],truncated:["Lista osiągnęła limit. Zawęź kontekst przed podjęciem decyzji.","The list reached its limit. Narrow the context before deciding."],
  outcome:["Jeden wynik zadania","One task outcome"],project:["Projekt","Project"],executor:["Wykonawca","Executor"],procedure:["Procedura","Procedure"],acceptance:["Kryteria akceptacji (po jednym w wierszu)","Acceptance criteria (one per line)"],tests:["Wymagane testy (po jednym w wierszu)","Required tests (one per line)"],branch:["Gałąź pracy","Work branch"],statement:["Proponowana decyzja","Proposed decision"],rationale:["Uzasadnienie decyzji","Decision rationale"],consequences:["Konsekwencje","Consequences"],recommendation:["Rekomendacja","Recommendation"],question:["Pytanie do właściciela","Question for the owner"],budget:["Budżet","Budget"],infrastructure:["Infrastruktura","Infrastructure"],category:["Powód odroczenia","Deferral category"],owner_signal:["Jawny sygnał właściciela","Explicit owner signal"],deadline:["Termin","Deadline"],resource_available:["Zasób stał się dostępny","Resource became available"],configuration_changed:["Zmieniła się konfiguracja","Configuration changed"],condition:["Zdarzenie wznowienia","Reopening event"],date:["Termin (UTC)","Deadline (UTC)"],task:["Otwórz zadanie","Open task"],decision:["Otwórz decyzje","Open decisions"],reservation:["Szkic jest przypisany do tego zgłoszenia. Uzupełnij jego kontekst i przejdź przez Ready.","The draft is reserved for this finding. Complete its context and pass Ready."],merge:["Kandydaci do scalenia","Merge candidates"],challenge:["Zgłoś sprzeczny dowód","Challenge with contrary evidence"],adjudicate:["Rozstrzygnij na podstawie decyzji","Adjudicate under a decision"],decisionId:["Identyfikator zaakceptowanej decyzji","Accepted decision ID"]
};
type Ref={type:string;id:string;label:string;revision:string};
type Worker={id:string;name:string;principal:{kind:string;id:string};departmentKeys:string[]};
type Catalog={application:{id:string;name:string};workspaceId:string;canonicalLanguage:"pl"|"en"|null;records:Ref[];workforce:Worker[];truncated:boolean};
type FindingRow={id:string;title:string;classification:string;state:string;version:number;scope:string;occurrences:number};
type Detail={expectedVersion:string;version:any;state:string;verification:any;verificationCurrent:boolean;verifyAuthority:any;triageAuthority:any;output:any;history:any[];versions:any[];occurrences:any[];mergeCandidates:any[];grants:any[];blockers:string[];truncated:boolean;canManageGrants?:boolean;credentialOptions:any[];deferrals:any[]};

export function FindingWorkbench({applicationId}:{applicationId:string}) {
  const {locale}=useLanguage(),tr=(key:string)=>terms[key]?.[locale==="pl"?0:1]??key;
  const [catalog,setCatalog]=useState<Catalog|null>(null),[rows,setRows]=useState<FindingRow[]>([]),[selected,setSelected]=useState<string|null>(null),[detail,setDetail]=useState<Detail|null>(null);
  const [editor,setEditor]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(true);
  const loadSequence=useRef(0);
  const [deferCondition,setDeferCondition]=useState("owner_signal");
  const root="/v1/product-engineering",fetchData=async<T,>(path:string)=>(await api<{data:T}>(path)).data;
  const load=useCallback(async(id?:string|null)=>{
    const sequence=++loadSequence.current;setLoading(true);setError(null);try{const [list,cat,record]=await Promise.all([fetchData<{items:FindingRow[]}>(`${root}/applications/${applicationId}/findings`),fetchData<Catalog>(`${root}/applications/${applicationId}/findings/catalog`),id?fetchData<Detail>(`${root}/findings/${id}`):null]);if(sequence!==loadSequence.current)return;setRows(list.items);setCatalog(cat);setDetail(record);}catch(e){if(sequence===loadSequence.current)setError(e instanceof AppApiError?e.code:"network_error");}finally{if(sequence===loadSequence.current)setLoading(false);}
  },[applicationId]);
  useEffect(()=>{const id=new URLSearchParams(window.location.search).get("findingId");const valid=id&&/^[a-f0-9]{8}(-[a-f0-9]{4}){3}-[a-f0-9]{12}$/i.test(id)?id:null;setSelected(valid);setEditor(null);void load(valid);},[load]);
  async function write(path:string,body:unknown,method="POST"){
    setBusy(true);setError(null);try{const result=await api<{data:any}>(path,{method,body:JSON.stringify(body)});const id=editor==="new"?result.data.record.id:selected;setSelected(id);setEditor(null);await load(id);return result.data;}catch(e){setError(e instanceof AppApiError?e.code:"network_error");return null;}finally{setBusy(false);}
  }
  const text=(name:string,label=name,value?:string,required=true)=><CcField key={name} label={tr(label)} required={required}>{({id})=><CcTextInput id={id} name={name} defaultValue={value??""} minLength={required?(name==="build"?1:name==="environment"?2:3):undefined} maxLength={name==="build"?160:2000} required={required}/>}</CcField>;
  const area=(name:string,label=name,value?:string)=><CcField key={name} label={tr(label)} required>{({id})=><textarea id={id} name={name} defaultValue={value??""} className="textarea textarea-bordered min-h-20 w-full" minLength={3} maxLength={["steps","acceptance","tests"].includes(name)?16000:2000} required/>}</CcField>;
  const select=(name:string,label:string,options:{id:string;label:string}[],value="",required=true)=><CcField key={name} label={tr(label)} required={required}>{({id})=><CcSelect id={id} name={name} defaultValue={value} required={required}><option value="">{tr("choose")}</option>{options.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</CcSelect>}</CcField>;
  const multi=(name:string,label:string,options:Ref[],values:string[]=[]) => <fieldset className="grid max-h-52 gap-2 overflow-auto rounded-lg border border-base-300 p-3"><legend className="px-1 text-sm font-medium">{tr(label)}</legend>{options.map(ref=><label key={`${ref.type}:${ref.id}`} className="flex items-start gap-2 text-sm"><input type="checkbox" name={name} value={ref.id} defaultChecked={values.includes(ref.id)} className="checkbox checkbox-sm"/><span className="break-words">{ref.label}</span></label>)}</fieldset>;
  const options=(keys:string[])=>keys.map(id=>({id,label:tr(id)})),refs=(type:string)=>catalog?.records.filter(r=>r.type===type)??[];
  const principalName=(authority:any)=>catalog?.workforce.find(w=>w.principal?.kind===authority?.principal?.kind&&w.principal?.id===authority?.principal?.id)?.name??tr("blocked");
  const actorName=(record:any)=>catalog?.workforce.find(worker=>worker.principal?.kind===record.actorKind&&worker.principal?.id===record.actorId)?.name??`${record.actorKind}: ${record.actorId}`;
  const grantId=(operation:string)=>detail?.grants.find(g=>g.operation===operation&&g.status==="active")?.id;
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!catalog)return;const form=new FormData(event.currentTarget),s=(key:string)=>String(form.get(key)??"").trim(),lines=(key:string)=>s(key).split(/\r?\n/).map(v=>v.trim()).filter(Boolean),ref=(key:string)=>catalog.records.find(r=>r.id===s(key))!;
    const requestId=crypto.randomUUID(),selectedRefs=(name:string)=>form.getAll(name).map(id=>catalog.records.find(ref=>ref.id===id)).filter((ref):ref is Ref=>!!ref).map(({type,id,revision})=>({type,id,revision}));
    if(editor==="new"||editor==="revise"){
      const sources=selectedRefs("source"),evidence=selectedRefs("evidence"),component=ref("component"),application=refs("application")[0],recipient=catalog.workforce.find(w=>w.id===s("recipient"));
      if(!sources.length||!evidence.length){setError("finding_content_invalid");return;}
      const body={title:s("title"),classification:s("classification"),language:catalog.canonicalLanguage,taskId:s("sourceTask")||null,componentId:component.id,departmentKey:recipient?.departmentKeys[0],requesterId:s("requester"),recipientId:s("recipient"),scope:s("scope"),excluded:s("excluded"),observed:s("observedBehavior"),expected:s("expected"),reproducibility:{status:s("reproducibility"),steps:lines("steps"),limitations:s("limitations")},sources,evidence,environment:{key:s("environment"),build:s("build"),applicationRevision:application.revision,componentRevision:component.revision,contextRevision:sources[0].revision},impact:s("impact"),knownRisk:s("risk"),requiredCompetencies:s("competencies").split(",").map(v=>v.trim()).filter(Boolean),decisionNeed:s("decisionNeed"),procedureId:s("procedure")||null,...(editor==="revise"?{correctionReason:s("correctionReason")}: {})};
      await write(editor==="new"?`${root}/applications/${applicationId}/findings`:`${root}/findings/${selected}/versions`,{requestId,body,...(editor==="revise"?{expectedVersion:detail?.expectedVersion}:{})});return;
    }
    if(!detail)return;
    if(editor==="grant_form"){const operation=s("operation"),authority=operation==="finding_verify"?detail.verifyAuthority:detail.triageAuthority;await write(`${root}/findings/${selected}/grants`,{requestId,expectedVersion:detail.expectedVersion,operation,principal:authority.principal,credentialId:authority.principal.kind==="agent"?s("credential"):null,validUntil:new Date(Date.now()+600000).toISOString(),reason:s("reason")});return;}
    if(editor==="occurrence"){const source=ref("source");await write(`${root}/findings/${selected}/occurrences`,{requestId,expectedVersion:detail.expectedVersion,purpose:s("purpose"),source:{type:source.type,id:source.id,revision:source.revision},evidence:selectedRefs("evidence"),explanation:s("reason")});return;}
    const action=editor!,verification=["verify","challenge","adjudicate"].includes(action),payload:any={requestId,expectedVersion:detail.expectedVersion,action,reason:s("reason"),...(grantId(verification?"finding_verify":"finding_triage")?{grantId:grantId(verification?"finding_verify":"finding_triage")}: {})};
    if(verification){const evidence=ref("evidence");payload.verification={verdict:s("verdict"),method:s("method"),environment:s("environment"),evidence:[{type:evidence.type,id:evidence.id,revision:evidence.revision}],observed:s("observedBehavior"),limitations:s("limitations")};if(action==="adjudicate")payload.decisionId=s("decisionId");}
    if(action==="prepare_task"){const evidence=ref("evidence");payload.task={title:s("title"),outcome:s("outcome"),scope:s("scope"),excluded:s("excluded"),projectId:s("project"),executorId:s("executor"),procedureId:s("procedure"),acceptanceCriteria:lines("acceptance"),requiredTests:lines("tests"),dependencies:lines("dependencies"),context:[{type:evidence.type,id:evidence.id,revision:evidence.revision}]};}
    if(action==="prepare_decision")Object.assign(payload,{statement:s("statement"),rationale:s("rationale"),consequences:s("consequences")});
    if(action==="prepare_interview")Object.assign(payload,{recommendation:s("recommendation"),questions:[{field:"required_assumption",type:"decision",question:s("question"),requiresHuman:true,options:[]}]});
    if(action==="defer")Object.assign(payload,{category:s("category"),condition:{type:s("condition"),...(s("condition")==="deadline"?{dueAt:new Date(s("date")).toISOString()}: {}),...(["resource_available","configuration_changed"].includes(s("condition"))?{referenceId:s("referenceId")}: {})}});
    if(action==="prepare_adjudication")Object.assign(payload,{principal:catalog.workforce.find(worker=>worker.id===s("adjudicator"))?.principal,statement:s("statement"),rationale:s("rationale"),consequences:s("consequences")});
    if(action==="propose_merge")payload.otherId=s("otherId");
    if(action==="resolve_merge")Object.assign(payload,{candidateId:s("candidateId"),verdict:s("mergeVerdict")});
    if(action==="reopen"){const deferral=detail.deferrals.find(item=>item.id===s("deferral"));Object.assign(payload,{deferralId:deferral.id,eventType:deferral.condition.type,...(s("referenceRevision")?{referenceRevision:s("referenceRevision")}:{})});}
    await write(`${root}/findings/${selected}/actions`,payload);
  }
  const body=editor==="revise"?detail?.version.body:null;
  const evidenceOptions=catalog?.records.filter(r=>["company_record","application_evidence","run"].includes(r.type))??[];
  const fieldOptions=(items:{id:string;label?:string;name?:string}[])=>items.map(item=>({id:item.id,label:item.label??item.name??item.id}));
  const actions=detail?({observed:["queue_deduplication"],deduplication_pending:["deduplicate"],verification_pending:["verify"],verified:["queue_triage","challenge","resolve_merge"],triage_pending:[...(detail.output?[detail.output.taskId?"convert_task":"convert_decision"]:detail.version.body.classification==="missing_assumption"||detail.version.body.decisionNeed==="material_unknown"?["prepare_interview"]:detail.version.body.knownRisk==="critical"||detail.version.body.decisionNeed!=="none"?["prepare_decision"]:["prepare_task"]),"defer","challenge","resolve_merge"],inconclusive:["prepare_adjudication","adjudicate"],deferred:["reopen"],converted_to_task:["challenge"],converted_to_decision:["challenge"]} as Record<string,string[]>)[detail.state]??[]:[];
  return <section className="grid min-w-0 gap-4" aria-label={tr("findings")}>
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-bold">{tr("findings")}</h3><p className="text-sm text-company-muted">{tr("languageHint")}</p></div><div className="flex gap-2"><CcButton onClick={()=>void load(selected)} disabled={busy}>{tr("refresh")}</CcButton><CcButton variant="primary" onClick={()=>setEditor("new")} disabled={busy||!catalog?.canonicalLanguage}>{tr("new")}</CcButton></div></div>
    {error?<CcNotice tone="error" title={tr("failed")}><span className="text-xs">{error}</span></CcNotice>:null}
    {catalog&&!catalog.canonicalLanguage?<div className="grid gap-2"><CcNotice title={tr("languageRequired")}/><div className="flex gap-2">{["pl","en"].map(language=><CcButton key={language} disabled={busy} onClick={()=>void write(`/v1/workspaces/${catalog.workspaceId}`,{canonicalLanguage:language},"PATCH")}>{language==="pl"?"Polski":"English"}</CcButton>)}</div></div>:null}
    {catalog?.canonicalLanguage?<p className="text-xs text-company-muted">{tr("canonical")}: {catalog.canonicalLanguage==="pl"?"Polski":"English"}</p>:null}
    {loading?<p role="status">{tr("loading")}</p>:null}
    {catalog?.truncated||detail?.truncated?<CcNotice title={tr("truncated")}/>:null}
    {editor&&catalog?<form onSubmit={submit} className="grid gap-4 border-y border-base-300 py-4" aria-label={tr(editor)}>
      <h4 className="font-bold">{tr(editor)}</h4>
      <div className="grid items-start gap-4 md:grid-cols-2">
      {editor==="new"||editor==="revise"?<>
        {text("title","title",body?.title)}{select("classification","classification",options(["defect","unfinished_function","stale_documentation","missing_assumption","improvement"]),body?.classification)}
        {select("component","component",fieldOptions(refs("component")),body?.componentId)}{select("sourceTask","sourceTask",fieldOptions(refs("task")),body?.taskId??"",false)}{select("procedure","procedure",fieldOptions(refs("procedure")),body?.procedureId??"",false)}
        {multi("source","source",catalog.records.filter(r=>["audit","task","application","project","procedure","run"].includes(r.type)),body?.sources.map((ref:any)=>ref.id))}{multi("evidence","evidence",evidenceOptions,body?.evidence.map((ref:any)=>ref.id))}{select("requester","requester",fieldOptions(catalog.workforce),body?.requesterId)}{select("recipient","recipient",fieldOptions(catalog.workforce),body?.recipientId)}
        {select("reproducibility","reproducibility",options(["reproduced","intermittent","not_reproduced"]),body?.reproducibility.status)}
        {area("scope","scope",body?.scope)}{area("excluded","excluded",body?.excluded)}{area("observedBehavior","observedBehavior",body?.observed)}{area("expected","expected",body?.expected)}{area("steps","steps",body?.reproducibility.steps.join("\n"))}{area("limitations","limitations",body?.reproducibility.limitations)}{area("impact","impact",body?.impact)}
        {text("environment","environment",body?.environment.key)}{text("build","build",body?.environment.build)}{text("competencies","competencies",body?.requiredCompetencies.join(", "))}{select("risk","risk",options(["low","medium","high","critical"]),body?.knownRisk)}{select("decisionNeed","decisionNeed",options(["none","material_unknown","product_direction","money","legal","critical_risk","mandate_change"]),body?.decisionNeed)}{editor==="revise"?area("correctionReason"):null}
      </>:<>
        {area("reason")}
        {["verify","challenge","adjudicate"].includes(editor)?<>{select("verdict","verify",options(["confirmed","rejected","inconclusive"]))}{text("method")}{text("environment")}{select("evidence","evidence",fieldOptions(evidenceOptions))}{area("observedBehavior")}{area("limitations")}{editor==="adjudicate"?text("decisionId"):null}</>:null}
        {editor==="prepare_task"?<>{text("title")}{area("outcome")}{area("scope")}{area("excluded")}{select("project","project",fieldOptions(refs("project")))}{select("executor","executor",fieldOptions(catalog.workforce))}{select("procedure","procedure",fieldOptions(refs("procedure")))}{select("evidence","evidence",fieldOptions(evidenceOptions))}{area("acceptance")}{area("tests")}{text("dependencies","dependencies",undefined,false)}</>:null}
        {["prepare_decision","prepare_adjudication"].includes(editor)?<>{area("statement")}{area("rationale")}{area("consequences")}{editor==="prepare_adjudication"?select("adjudicator","adjudicator",fieldOptions(catalog.workforce)):null}</>:null}
        {editor==="prepare_interview"?<>{area("recommendation")}{area("question")}</>:null}
        {editor==="defer"?<>{select("category","category",options(["budget","infrastructure"]))}<CcField label={tr("condition")} required>{({id})=><CcSelect id={id} name="condition" value={deferCondition} onChange={event=>setDeferCondition(event.target.value)}>{options(["owner_signal","deadline","resource_available","configuration_changed"]).map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</CcSelect>}</CcField>{deferCondition==="deadline"?<CcField label={tr("date")} required>{({id})=><CcTextInput id={id} name="date" type="datetime-local" required/>}</CcField>:null}{["resource_available","configuration_changed"].includes(deferCondition)?select("referenceId","source",fieldOptions(refs(deferCondition==="resource_available"?"resource":"company_record"))):null}</>:null}
        {editor==="occurrence"?<>{select("purpose","purpose",options(["observation","fix"]))}{select("source","source",fieldOptions(catalog.records.filter(r=>["audit","task","application","project","procedure","run"].includes(r.type))))}{multi("evidence","evidence",evidenceOptions)}</>:null}
        {editor==="propose_merge"?select("otherId","otherId",rows.filter(row=>row.id!==selected&&row.state!=="merged").map(row=>({id:row.id,label:row.title}))):null}
        {editor==="resolve_merge"?<>{select("candidateId","candidateId",(detail?.mergeCandidates??[]).filter(row=>row.action==="propose_merge"&&row.observationId===selected).map(row=>({id:row.id,label:row.body.reason})))}{select("mergeVerdict","mergeVerdict",[{id:"merge",label:tr("merge_records")},{id:"distinct",label:tr("distinct")}])}</>:null}
        {editor==="reopen"?<>{select("deferral","deferral",(detail?.deferrals??[]).map(row=>({id:row.id,label:row.explanation+" · "+tr(row.condition.type)})))}{text("referenceRevision","referenceRevision",undefined,false)}</>:null}
        {editor==="grant_form"?<>{select("operation","operation",options(["finding_verify","finding_triage"].filter(op=>(op==="finding_verify"?detail?.verifyAuthority:detail?.triageAuthority)?.status==="delegated")))}{select("credential","credential",(detail?.credentialOptions??[]).map(key=>({id:key.id,label:key.name})),"",false)}</>:null}
      </>}
      </div><div className="flex gap-2"><CcButton type="submit" variant="primary" disabled={busy}>{tr("save")}</CcButton><CcButton onClick={()=>setEditor(null)} disabled={busy}>{tr("cancel")}</CcButton></div>
    </form>:null}
    <div className="grid min-w-0 gap-5 xl:grid-cols-[minmax(220px,1fr)_minmax(0,2fr)]">
      <div className="min-w-0 divide-y divide-base-300">{!loading&&!rows.length?<p className="py-5 text-company-muted">{tr("empty")}</p>:rows.map(row=><button key={row.id} className={`grid w-full gap-1 px-3 py-3 text-left hover:bg-base-200 ${selected===row.id?"bg-base-200":""}`} onClick={()=>{setSelected(row.id);setEditor(null);void load(row.id);}}><strong>{row.title}</strong><span className="text-xs text-company-muted">{tr(row.classification)} · {tr(row.state)} · v{row.version}</span><span className="truncate text-sm">{row.scope}</span></button>)}</div>
      {detail?<div className="grid min-w-0 content-start gap-4">
        <div><h4 className="font-bold">{detail.version.body.title}</h4><p>{tr(detail.state)} · v{detail.version.version}</p></div>
        <p className="break-words text-sm text-company-muted">{tr("author")}: {actorName(detail.version)} · {tr("component")}: {catalog?.records.find(ref=>ref.id===detail.version.body.componentId)?.label??detail.version.body.componentId}</p>
        {detail.blockers.length?<CcNotice title={tr("stale")}/>:null}
        <dl className="grid gap-3 text-sm">{[["scope",detail.version.body.scope],["observedBehavior",detail.version.body.observed],["expected",detail.version.body.expected],["impact",detail.version.body.impact],["risk",tr(detail.version.body.knownRisk)],["verifier",principalName(detail.verifyAuthority)],["manager",principalName(detail.triageAuthority)]].map(([key,value])=><div key={key}><dt className="font-semibold">{tr(key)}</dt><dd className="whitespace-pre-wrap break-words text-company-muted">{value}</dd></div>)}</dl>
        {detail.verifyAuthority.status!=="delegated"||detail.triageAuthority.status!=="delegated"?<CcNotice title={tr("blocked")}/>:null}
        <div className="flex flex-wrap gap-2">{actions.map(action=><CcButton key={action} variant={action===actions[0]?"primary":"neutral"} disabled={busy} onClick={()=>setEditor(action)}>{tr(action)}</CcButton>)}{detail.state!=="merged"?["revise","occurrence","propose_merge"].map(action=><CcButton key={action} disabled={busy} onClick={()=>setEditor(action)}>{tr(action)}</CcButton>):null}</div>
        {detail.canManageGrants?<CcButton disabled={busy} onClick={()=>setEditor("grant_form")}>{tr("grant_form")}</CcButton>:null}
        <details><summary className="cursor-pointer font-semibold">{tr("mandate")}</summary>{[detail.verifyAuthority,detail.triageAuthority].map((authority,index)=><div key={index} className="py-2 text-sm"><p>{tr(index===0?"verifier":"manager")}: {principalName(authority)}</p><p className="break-all">{authority.mandate?.id??tr("blocked")}</p><p>{authority.path?.map((id:string)=>catalog?.workforce.find(worker=>worker.id===id)?.name??id).join(" → ")}</p></div>)}</details>
        <details><summary className="cursor-pointer font-semibold">{tr("source")}</summary><div className="grid gap-2 py-2 text-sm"><p>{tr("environment")}: {detail.version.body.environment.key} · {detail.version.body.environment.build}</p><p>{tr("reproducibility")}: {tr(detail.version.body.reproducibility.status)}</p><ol>{detail.version.body.reproducibility.steps.map((step:string,index:number)=><li key={index}>{index+1}. {step}</li>)}</ol><p>{detail.version.body.reproducibility.limitations}</p>{detail.version.body.sources.map((ref:any)=><p key={ref.id} className="break-all">{catalog?.records.find(item=>item.id===ref.id)?.label??ref.type} · {ref.revision}</p>)}</div></details>
        {detail.deferrals?.length?<details><summary className="cursor-pointer font-semibold">{tr("deferral")}</summary>{detail.deferrals.map(row=><p key={row.id}>{row.explanation} · {tr(row.condition.type)} {row.condition.dueAt??""}</p>)}</details>:null}
        {detail.output?<div className="grid gap-2 border-l-2 border-primary pl-3"><p className="text-sm">{tr("reservation")}</p><a className="link" href={detail.output.taskId?`/areas?area=04-operacje&view=tasks&taskId=${detail.output.taskId}`:"/areas?area=01-strategia&view=decisions"}>{tr(detail.output.taskId?"task":"decision")}</a></div>:null}
        <details><summary className="cursor-pointer font-semibold">{tr("evidence")}</summary><div className="grid gap-2 py-2">{detail.version.body.evidence.map((ref:any)=><p key={ref.id} className="break-all text-sm">{catalog?.records.find(r=>r.id===ref.id)?.label??ref.type} · {ref.id}</p>)}{detail.verification?<><p>{tr("verifier")}: {actorName(detail.verification)}</p><p>{detail.verification.body.verification.method}</p><p>{detail.verification.body.verification.observed}</p><p>{detail.verification.body.verification.limitations}</p></>:null}<p className="break-all text-xs">{tr("fingerprint")}: {detail.version.fingerprint}</p></div></details>
        <details><summary className="cursor-pointer font-semibold">{tr("occurrences")} ({detail.occurrences.length})</summary>{detail.occurrences.map(row=><p key={row.id} className="my-2 text-sm">{row.body.explanation} · {row.actorKind} {row.actorId} · {new Date(row.createdAt).toLocaleString(locale)}</p>)}</details>
        <details><summary className="cursor-pointer font-semibold">{tr("versions")}</summary>{detail.versions.map(row=><p key={row.id} className="my-2 break-words text-sm">v{row.version} · {row.actorKind} {row.actorId} · {row.body.correctionReason??row.body.title}</p>)}</details>
        <details><summary className="cursor-pointer font-semibold">{tr("merge")}</summary>{detail.mergeCandidates.map(row=><p key={row.id} className="my-2 break-all text-sm">{row.body.reason} · {row.body.otherId??row.body.candidateId}</p>)}</details>
        <details><summary className="cursor-pointer font-semibold">{tr("history")}</summary><ol className="divide-y divide-base-300">{detail.history.map(row=><li key={row.id} className="py-2 text-sm"><strong>{tr(row.state)}</strong><p>{row.body.reason}</p><p className="break-all text-xs text-company-muted">{row.actorKind} {row.actorId} · {new Date(row.createdAt).toLocaleString(locale)}</p></li>)}</ol></details>
      </div>:null}
    </div>
  </section>;
}
