import { FormEvent, useMemo, useState } from "react";
import { api } from "../../api/client";
import { CcButton } from "../../components/cc-button";
import { CcConfirmDialog } from "../../components/cc-confirm-dialog";
import { CcDataTable, type CcTableColumn } from "../../components/cc-data-table";
import { CcField } from "../../components/cc-field";
import { CcMultiSelect } from "../../components/cc-multi-select";
import { CcPageHeader } from "../../components/cc-page-header";
import { CcRecordEditorModal, CcRecordEditorSection } from "../../components/cc-record-editor";
import { CcSelect } from "../../components/cc-select";
import { useOwnerPacket } from "../../hooks/use-owner-packet";
import { useLanguage } from "../../i18n/i18n";
import type { CoreAreaKey } from "../../types";
import { departmentLabel } from "./department-labels";
import { humanizeBusinessValue, useTranslatedTableLabels } from "./shared";

type Department = { id: string; key: CoreAreaKey; name: string };
type Project = { id: string; name: string; description?: string | null; status: string; updatedAt: string; organizationalContext?: { ownerDepartment?: Department | null; relatedDepartments?: Department[]; scopes?: Array<{ type: string }> } };

function ProjectEditor({ project, departmentKey, departments, onClose, onSaved }: { project: Project | null; departmentKey: CoreAreaKey; departments: Department[]; onClose: () => void; onSaved: () => void }) {
  const { t } = useLanguage(); const [name, setName] = useState(project?.name || ""); const [description, setDescription] = useState(project?.description || ""); const [status, setStatus] = useState(project?.status || "active"); const [owner, setOwner] = useState(project?.organizationalContext?.ownerDepartment?.key || departmentKey); const [related, setRelated] = useState(project?.organizationalContext?.relatedDepartments?.map((item) => item.key) || []); const [companyWide, setCompanyWide] = useState(Boolean(project?.organizationalContext?.scopes?.some((scope) => scope.type === "company"))); const [busy, setBusy] = useState(false);
  const options = departments.map((department) => ({ value: department.key, label: departmentLabel(department.key, t) }));
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); try { await api(project ? `/v1/projects/${project.id}` : "/v1/projects", { method: project ? "PATCH" : "POST", body: JSON.stringify({ name, description: description || undefined, status, organizationalContext: { ownerDepartmentKey: owner, relatedDepartmentKeys: related.filter((key) => key !== owner), applicableDepartmentKeys: [], scopes: companyWide ? [{ type: "company" }] : [{ type: "department", entityId: owner }] } }) }); onSaved(); } finally { setBusy(false); } }
  return <CcRecordEditorModal actions={<><CcButton onClick={onClose} variant="ghost">{t("common.cancel")}</CcButton><CcButton loading={busy} type="submit" variant="primary">{t("common.save")}</CcButton></>} description="One global project can cross departments, applications, clients and task lists without being copied." eyebrow="Shared projects" onClose={onClose} onSubmit={submit} title={project ? `Edit ${project.name}` : "Create project"} titleId="project-editor-title"><CcRecordEditorSection title="Project definition"><div className="grid gap-4 md:grid-cols-2"><CcField label="Name" required>{({ id }) => <input className="input input-bordered w-full" id={id} onChange={(event) => setName(event.target.value)} required value={name} />}</CcField><CcField label="Status">{({ id }) => <CcSelect id={id} onChange={(event) => setStatus(event.target.value)} value={status}>{["active", "planned", "on_hold", "completed"].map((value) => <option key={value} value={value}>{humanizeBusinessValue(value)}</option>)}</CcSelect>}</CcField><div className="md:col-span-2"><CcField label="Description">{({ id }) => <textarea className="textarea textarea-bordered min-h-24 w-full" id={id} onChange={(event) => setDescription(event.target.value)} value={description} />}</CcField></div></div></CcRecordEditorSection><CcRecordEditorSection title="Organizational context"><div className="grid gap-4 md:grid-cols-2"><CcField label="Owner department">{({ id }) => <CcSelect id={id} onChange={(event) => setOwner(event.target.value as CoreAreaKey)} value={owner}>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</CcSelect>}</CcField><CcField label="Related departments">{({ id }) => <CcMultiSelect id={id} name="relatedDepartments" onChange={(value) => setRelated(value as CoreAreaKey[])} options={options.filter((option) => option.value !== owner)} value={related} />}</CcField><label className="flex min-h-11 items-center gap-3 rounded-company border border-base-300 px-3 py-2 text-sm font-bold"><input checked={companyWide} className="checkbox checkbox-primary checkbox-sm" onChange={(event) => setCompanyWide(event.target.checked)} type="checkbox" />Company-wide scope</label></div></CcRecordEditorSection></CcRecordEditorModal>;
}

export function ProjectsWorkbench({ departmentKey }: { departmentKey: CoreAreaKey }) {
  const { t } = useLanguage(); const [refreshKey, setRefreshKey] = useState(0); const [editing, setEditing] = useState<Project | null | undefined>(undefined); const [archiving, setArchiving] = useState<Project | null>(null); const [busy, setBusy] = useState(false); const packet = useOwnerPacket<Project[]>(`/v1/projects?departmentKey=${departmentKey}&includeCompanyWide=true&refresh=${refreshKey}`, true, t); const departments = useOwnerPacket<{ departments: Department[] }>(`/v1/departments?refresh=${refreshKey}`, true, t); const labels = useTranslatedTableLabels();
  const columns = useMemo<Array<CcTableColumn<Project>>>(() => [{ key: "name", header: "Project", sortable: true, searchValue: (row) => `${row.name} ${row.description || ""}`, cell: (row) => <a className="grid" href={`/areas?area=11-innowacje&view=project-workspace&projectId=${row.id}`}><strong>{row.name}</strong><span className="text-xs text-company-muted">{row.description || "Open the central project workspace"}</span></a> }, { key: "owner", header: "Owner", filterable: true, filterValue: (row) => row.organizationalContext?.ownerDepartment?.key || "unassigned", cell: (row) => row.organizationalContext?.ownerDepartment ? departmentLabel(row.organizationalContext.ownerDepartment.key, t) : "—" }, { key: "status", header: t("table.status"), filterable: true, filterValue: (row) => row.status, cell: (row) => <span className="badge badge-outline">{humanizeBusinessValue(row.status)}</span> }, { key: "actions", header: t("table.actions"), cell: (row) => <div className="flex justify-end gap-1"><CcButton ariaLabel="Project graph context" href={`/areas?area=00-ogolny&view=entity&type=project&id=${row.id}`} iconLeft="ph-share-network" size="xs" variant="ghost"><span className="sr-only">Project graph context</span></CcButton><CcButton ariaLabel="Edit" iconLeft="ph-pencil-simple" onClick={() => setEditing(row)} size="xs" variant="ghost"><span className="sr-only">Edit</span></CcButton><CcButton ariaLabel="Archive" iconLeft="ph-archive" onClick={() => setArchiving(row)} size="xs" variant="ghost"><span className="sr-only">Archive</span></CcButton></div> }], [t]);
  function refresh() { setEditing(undefined); setRefreshKey((value) => value + 1); }
  async function confirmArchive() { if (!archiving) return; setBusy(true); try { await api(`/v1/projects/${archiving.id}`, { method: "DELETE" }); setArchiving(null); refresh(); } finally { setBusy(false); } }
  return <><CcPageHeader actions={<CcButton iconLeft="ph-plus" onClick={() => setEditing(null)} size="sm" variant="primary">Create project</CcButton>} description={departmentKey === "11-innowacje" ? "Canonical project portfolio shared by applications, clients, goals and task lists." : "The shared project portfolio filtered to this department's ownership, relationships and company-wide scope."} eyebrow={departmentLabel(departmentKey, t)} title={departmentKey === "11-innowacje" ? "All projects" : "Department projects"} /><CcDataTable columns={columns} rows={packet.data || []} emptyDetail="Create or relate a shared project to this department." emptyTitle="No projects in this context" error={packet.status === "error" ? packet.error : null} labels={labels} loading={packet.status === "loading"} mobileMode="cards" />{editing !== undefined ? <ProjectEditor departmentKey={departmentKey} departments={departments.data?.departments || []} onClose={() => setEditing(undefined)} onSaved={refresh} project={editing} /> : null}{archiving ? <CcConfirmDialog busy={busy} confirmLabel="Archive" confirmTone="warning" description="The project remains auditable but leaves active views." detail={<strong>{archiving.name}</strong>} eyebrow="Project" onCancel={() => setArchiving(null)} onConfirm={confirmArchive} title="Archive project?" /> : null}</>;
}
