import { useMemo, useState } from "react";
import { CcButton } from "../../components/cc-button";
import { CcNotice } from "../../components/cc-notice";
import { CcPageHeader } from "../../components/cc-page-header";
import { useOwnerPacket } from "../../hooks/use-owner-packet";
import { useLanguage } from "../../i18n/i18n";
import { humanizeBusinessValue } from "./shared";

type Entity = { id: string; title?: string; name?: string; description?: string | null; status?: string; recordType?: string; verificationState?: string; functionalState?: string; reference?: string; verificationStatus?: string; type?: string; category?: string; createdAt?: string };
type ProjectWorkspace = {
  schemaVersion: string; project: Entity; organizationalContext?: { ownerDepartment?: { key: string; name: string } | null; relatedDepartments?: Array<{ key: string; name: string }>; scopes?: Array<{ type: string }> };
  health: { status: string; openTasks: number; blockedTasks: number; requirements: number; verifiedRequirements: number; evidence: number; verifiedEvidence: number };
  intent: { goals: Entity[] }; delivery: { taskLists: Entity[]; tasks: Entity[] }; applications: Entity[]; records: Entity[]; requirements: Entity[]; deliverables: Entity[]; issues: Entity[]; incidents: Entity[];
  product: { capabilities: Entity[]; features: Entity[]; architecture: Entity[]; repositories: Entity[]; interfaces: Entity[]; technologies: Entity[]; dependencies: Entity[] };
  procedures: Entity[]; decisions: Entity[]; resources: Entity[]; risks: Entity[]; metrics: Entity[]; relations: Entity[]; evidence: Entity[]; activity: Entity[];
};
type WorkspaceView = "overview" | "product" | "delivery" | "governance" | "evidence";

function title(item: Entity) { return item.title || item.name || item.reference || "Company object"; }
function href(type: string, item: Entity) { return `/areas?area=00-ogolny&view=entity&type=${encodeURIComponent(item.recordType === "requirement" ? "requirement" : type)}&id=${encodeURIComponent(item.id)}`; }

function EntitySection({ title: sectionTitle, description, items, entityType, empty, linkable = true }: { title: string; description: string; items: Entity[]; entityType: string; empty: string; linkable?: boolean }) {
  return <section className="roost-work-panel rounded-company p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-black text-company-ink">{sectionTitle}</h2><p className="mt-1 text-sm text-company-muted">{description}</p></div><span className="badge badge-outline">{items.length}</span></div><div className="mt-4 grid gap-2">{items.length ? items.slice(0, 30).map((item) => {
    const content = <><span className="min-w-0"><strong className="block truncate">{title(item)}</strong><small className="text-company-muted">{humanizeBusinessValue(item.recordType || item.type || item.status || entityType)}</small></span>{item.status || item.verificationState || item.verificationStatus ? <span className="badge badge-outline shrink-0">{humanizeBusinessValue(item.verificationState || item.verificationStatus || item.status || "")}</span> : linkable ? <i className="ph-bold ph-caret-right text-company-muted" aria-hidden="true"></i> : null}</>;
    const className = "flex items-center justify-between gap-3 rounded-company border border-base-300 bg-base-100/20 p-3";
    return linkable ? <a className={`${className} transition-colors hover:border-primary hover:bg-primary/5`} href={href(entityType, item)} key={item.id}>{content}</a> : <article className={className} key={item.id}>{content}</article>;
  }) : <p className="rounded-company border border-dashed border-base-300 p-3 text-sm text-company-muted">{empty}</p>}</div></section>;
}

export function ProjectWorkspaceRoute() {
  const { t } = useLanguage(); const projectId = new URLSearchParams(window.location.search).get("projectId") || ""; const packet = useOwnerPacket<ProjectWorkspace>(projectId ? `/v1/projects/${encodeURIComponent(projectId)}/workspace` : "", Boolean(projectId), t); const [view, setView] = useState<WorkspaceView>("overview"); const data = packet.data;
  const recordGroups = useMemo(() => data ? { capabilities: [...data.product.capabilities, ...data.records.filter((item) => item.recordType === "capability")], features: [...data.product.features, ...data.records.filter((item) => item.recordType === "feature")], components: [...data.product.architecture, ...data.records.filter((item) => item.recordType === "component")], environments: data.records.filter((item) => item.recordType === "environment") } : { capabilities: [], features: [], components: [], environments: [] }, [data]);
  if (!projectId) return <CcNotice tone="error" title="Missing project identifier" detail="Open a project from the shared project portfolio." />;
  if (packet.status === "loading") return <CcNotice live tone="loading" title="Building project workspace…" detail="Joining intent, product structure, delivery, governance, evidence and activity around one Project ID." />;
  if (packet.status === "error" || !data) return <CcNotice live tone="error" title={packet.error || "Project workspace could not load."} />;
  const tabs: Array<{ key: WorkspaceView; label: string; icon: string }> = [{ key: "overview", label: "Overview", icon: "ph-gauge" }, { key: "product", label: "Product model", icon: "ph-cube" }, { key: "delivery", label: "Delivery", icon: "ph-list-checks" }, { key: "governance", label: "Governance", icon: "ph-shield-check" }, { key: "evidence", label: "Evidence & activity", icon: "ph-seal-check" }];
  return <><CcPageHeader actions={<><CcButton href="/areas?area=11-innowacje&view=projects" iconLeft="ph-arrow-left" size="sm" variant="outline">Project portfolio</CcButton><CcButton href={`/areas?area=00-ogolny&view=entity&type=project&id=${projectId}`} iconLeft="ph-share-network" size="sm" variant="primary">Full graph context</CcButton></>} description={data.project.description || "Central workspace for intent, product structure, delivery, governance, evidence and activity."} eyebrow="11 Innovation · Project Workspace" title={title(data.project)} />
    <section className="roost-work-panel rounded-company p-3"><nav aria-label="Project workspace views" className="flex gap-2 overflow-x-auto">{tabs.map((tab) => <button aria-current={view === tab.key ? "page" : undefined} className={`btn btn-sm shrink-0 ${view === tab.key ? "btn-primary" : "btn-ghost"}`} key={tab.key} onClick={() => setView(tab.key)} type="button"><i className={`ph-bold ${tab.icon}`} aria-hidden="true"></i>{tab.label}</button>)}</nav></section>
    {view === "overview" ? <div className="mt-4 grid gap-4"><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{[["Open tasks", data.health.openTasks, "ph-list-checks"], ["Blocked", data.health.blockedTasks, "ph-hand-palm"], ["Requirements", data.health.requirements, "ph-list-magnifying-glass"], ["Verified requirements", data.health.verifiedRequirements, "ph-check-circle"], ["Evidence", data.health.evidence, "ph-seal-check"], ["Verified evidence", data.health.verifiedEvidence, "ph-shield-check"]].map(([label, value, icon]) => <article className="roost-work-panel rounded-company p-4" key={String(label)}><i className={`ph-bold ${icon} text-primary`} aria-hidden="true"></i><strong className="mt-2 block text-2xl">{value}</strong><span className="text-xs font-bold text-company-muted">{label}</span></article>)}</section><div className="grid gap-4 lg:grid-cols-2"><EntitySection description="Objectives and outcomes this project implements." empty="Link a shared Goal to express project intent." entityType="goal" items={data.intent.goals} title="Objectives" /><EntitySection description="Applications delivered by this shared project." empty="Link an application from Product Engineering." entityType="application" items={data.applications} title="Applications" /><EntitySection description="Canonical deliverables, not task aliases." empty="Define the outputs this project must produce." entityType="company_record" items={data.deliverables} title="Deliverables" /><section className="roost-work-panel rounded-company p-4"><h2 className="font-black">Organizational context</h2><dl className="mt-4 grid gap-3 text-sm"><div><dt className="text-company-muted">Owner department</dt><dd className="font-bold">{data.organizationalContext?.ownerDepartment?.name || "Unassigned"}</dd></div><div><dt className="text-company-muted">Related departments</dt><dd className="mt-1 flex flex-wrap gap-1">{data.organizationalContext?.relatedDepartments?.length ? data.organizationalContext.relatedDepartments.map((department) => <span className="badge badge-outline" key={department.key}>{department.name}</span>) : "—"}</dd></div><div><dt className="text-company-muted">Health state</dt><dd><span className="badge badge-outline">{humanizeBusinessValue(data.health.status)}</span></dd></div></dl></section></div></div> : null}
    {view === "product" ? <div className="mt-4 grid gap-4 lg:grid-cols-2"><EntitySection description="Expected behavior and acceptance criteria." empty="No requirements linked to this project." entityType="requirement" items={data.requirements} title="Requirements" /><EntitySection description="Business capabilities delivered by the project and its applications." empty="No capabilities recorded yet." entityType="company_record" items={recordGroups.capabilities} linkable={false} title="Capabilities" /><EntitySection description="User-visible or operational features across linked applications." empty="No feature records linked yet." entityType="company_record" items={recordGroups.features} linkable={false} title="Features" /><EntitySection description="Frontend, backend, API, database, workers and infrastructure." empty="No component records linked yet." entityType="company_record" items={recordGroups.components} linkable={false} title="Architecture & components" /><EntitySection description="Local, development, testing, staging, production and sandbox." empty="No environments linked yet." entityType="company_record" items={recordGroups.environments} title="Environments" /><EntitySection description="Source repositories declared by linked applications." empty="No repositories linked yet." entityType="resource" items={data.product.repositories} linkable={false} title="Repositories" /><EntitySection description="Services, APIs, databases and other company resources." empty="No resources linked yet." entityType="resource" items={data.resources} title="Resources" /><EntitySection description="Application APIs, events, commands and other integration surfaces." empty="No interfaces linked yet." entityType="application_interface" items={data.product.interfaces} linkable={false} title="Interfaces" /><EntitySection description="Technology definitions used by application components." empty="No technology stack recorded yet." entityType="technology" items={data.product.technologies} linkable={false} title="Technology stack" /></div> : null}
    {view === "delivery" ? <div className="mt-4 grid gap-4 lg:grid-cols-2"><EntitySection description="Reusable execution groupings owned across departments." empty="No task lists belong to this project." entityType="task_list" items={data.delivery.taskLists} title="Task lists" /><EntitySection description="State-changing work with canonical task identity." empty="No project tasks." entityType="task" items={data.delivery.tasks} title="Tasks" /><EntitySection description="Applicable execution and verification instructions." empty="Relate a global procedure to this project." entityType="procedure" items={data.procedures} title="Procedures" /><EntitySection description="Known work-state problems that require resolution." empty="No known issues." entityType="company_record" items={data.issues} title="Issues" /><EntitySection description="Observed service or production disruptions." empty="No incidents recorded." entityType="company_record" items={data.incidents} title="Incidents" /></div> : null}
    {view === "governance" ? <div className="mt-4 grid gap-4 lg:grid-cols-2"><EntitySection description="Context, rationale, alternatives and consequences." empty="No decisions linked." entityType="decision" items={data.decisions} title="Decisions" /><EntitySection description="Potential threats and their controls." empty="No project risks linked." entityType="risk" items={data.risks} title="Risks" /><EntitySection description="Targets and observed project performance." empty="No metrics linked." entityType="metric" items={data.metrics} title="Metrics" /><EntitySection description="Typed cross-entity dependencies for this project." empty="No graph dependencies linked." entityType="dependency" items={data.relations} linkable={false} title="Dependencies" /></div> : null}
    {view === "evidence" ? <div className="mt-4 grid gap-4 lg:grid-cols-2"><EntitySection description="Implementation, tests, runtime observations and approvals." empty="No evidence attached to project work." entityType="evidence" items={data.evidence} linkable={false} title="Evidence ledger" /><EntitySection description="Auditable events emitted by project changes." empty="No project activity recorded." entityType="event" items={data.activity} linkable={false} title="Activity" /></div> : null}
  </>;
}
