import { useEffect, useRef, useState, type FormEvent } from "react";
import { api, AppApiError } from "../../api/client";
import { CcButton } from "../../components/cc-button";
import { CcField } from "../../components/cc-field";
import { CcNotice } from "../../components/cc-notice";
import { CcRecordEditorModal } from "../../components/cc-record-editor";
import { CcSelect } from "../../components/cc-select";
import { useLanguage } from "../../i18n/i18n";

import { TaskRiskAdmissionModal } from "./task-risk-admission";

const dimensions=["money","data","security","availability","legal","reversibility","users"];
const levels=["low","medium","high","critical"];
const messages={
 en:{staleProof:"Evidence changed. Review its current revision before replacing the reference.",refreshProof:"Use current evidence revision",component:"Same application component",objective:"Common goal",release_set:"Explicit common change set",lineage:"Correction lineage",title:"Task risk assessment",boundary:"Assess the prepared task and its native execution, review and correction operations. The server computes the result; this assessment grants no execution or release authority.",close:"Close",prepare:"Prepare current scope",save:"Record joint assessment",refresh:"Refresh context",choose:"Choose",evidence:"Evidence",rationale:"Impact and rationale",uncertainty:"Uncertainty",reasons:"Uncertainty reasons",contradictions:"Contradictions (one per line)",joint:"Joint impact and splitting justification",release:"Common release / change set",noneRelease:"No explicit change set",related:"Related tasks",missing:"Prepare every related task before a joint assessment.",blocked:"Needs context or decision",valid:"Current computed assessment",old:"Historical assessment — cannot authorize Ready",history:"Assessment history",empty:"No assessment recorded",readOnly:"Read only",dirty:"There are unsaved changes.",discard:"Discard unsaved risk assessment?",stay:"Keep editing",leave:"Discard and close",error:"The assessment could not be saved. Refresh context and review the prepared scope and evidence.",saved:"Assessment recorded. Return to the task and submit the reviewed contract.",money:"Money",data:"Data",security:"Security",availability:"Availability",legal:"Legal",reversibility:"Reversibility",users:"Users",low:"Low",medium:"Medium",high:"High",critical:"Critical",none:"None, supported by evidence",bounded:"Bounded — raises risk one tier",unverifiable:"Unverifiable — requires a decision",cumulative:"Related changes raise the cumulative impact",escalation:"Uncertainty raises the result",group_limit:"More than 50 related tasks: narrow or reconcile the change set.",scope_missing:"Some related tasks have no prepared scope.",assessment_missing_or_stale:"A complete current joint assessment is required.",contradictory_evidence:"Contradictory evidence requires a decision.",uncertainty_unverifiable:"Unverifiable uncertainty requires a decision.",noScope:"Prepare the task scope to assess its impact.",loading:"Loading assessment…",limited:"The evidence catalog is limited to 500 records.",proof:"Evidence must document this impact and match the current record revision."},
 pl:{staleProof:"Dowód się zmienił. Sprawdź jego aktualną wersję przed zastąpieniem odwołania.",refreshProof:"Użyj aktualnej wersji dowodu",component:"Ten sam komponent aplikacji",objective:"Wspólny cel",release_set:"Jawny wspólny zestaw zmian",lineage:"Powiązanie korekty",title:"Ocena ryzyka zadania",boundary:"Oceń przygotowane zadanie oraz jego wykonanie, weryfikację i korekty w Roost. Serwer oblicza wynik; ocena nie nadaje uprawnień do wykonania ani wydania.",close:"Zamknij",prepare:"Przygotuj aktualny zakres",save:"Zapisz wspólną ocenę",refresh:"Odśwież kontekst",choose:"Wybierz",evidence:"Dowód",rationale:"Wpływ i uzasadnienie",uncertainty:"Niepewność",reasons:"Przyczyny niepewności",contradictions:"Sprzeczności (po jednej w wierszu)",joint:"Łączny wpływ i uzasadnienie podziału",release:"Wspólne wydanie / zestaw zmian",noneRelease:"Brak jawnego zestawu zmian",related:"Powiązane zadania",missing:"Przygotuj każde powiązane zadanie przed wspólną oceną.",blocked:"Wymaga kontekstu lub decyzji",valid:"Aktualna obliczona ocena",old:"Ocena historyczna — nie pozwala przyjąć Ready",history:"Historia ocen",empty:"Nie zapisano oceny",readOnly:"Tylko odczyt",dirty:"Są niezapisane zmiany.",discard:"Odrzucić niezapisaną ocenę ryzyka?",stay:"Kontynuuj edycję",leave:"Odrzuć i zamknij",error:"Nie udało się zapisać oceny. Odśwież kontekst i sprawdź przygotowany zakres oraz dowody.",saved:"Ocena zapisana. Wróć do zadania i przekaż sprawdzony kontrakt do wykonania.",money:"Pieniądze",data:"Dane",security:"Bezpieczeństwo",availability:"Dostępność",legal:"Prawo",reversibility:"Odwracalność",users:"Użytkownicy",low:"Niskie",medium:"Średnie",high:"Wysokie",critical:"Krytyczne",none:"Brak, potwierdzony dowodami",bounded:"Ograniczona — podnosi ryzyko o poziom",unverifiable:"Nieweryfikowalna — wymaga decyzji",cumulative:"Powiązane zmiany zwiększają łączny wpływ",escalation:"Niepewność podnosi wynik",group_limit:"Ponad 50 powiązanych zadań: zawęź lub uzgodnij zestaw zmian.",scope_missing:"Część powiązanych zadań nie ma przygotowanego zakresu.",assessment_missing_or_stale:"Wymagana jest kompletna aktualna wspólna ocena.",contradictory_evidence:"Sprzeczne dowody wymagają decyzji.",uncertainty_unverifiable:"Nieweryfikowalna niepewność wymaga decyzji.",noScope:"Przygotuj zakres zadania, aby ocenić jego wpływ.",loading:"Wczytywanie oceny…",limited:"Katalog dowodów ograniczono do 500 rekordów.",proof:"Dowód musi opisywać ten wpływ i odpowiadać aktualnej wersji rekordu."}
};
export function TaskRiskModal({taskId,input,onClose,onSaved}:{taskId:string;input?:any;onClose:()=>void;onSaved?:()=>void}) {
 const [admissionOpen,setAdmissionOpen]=useState(false);
 const {locale}=useLanguage(), c:any=messages[locale==="pl"?"pl":"en"];
 const [data,setData]=useState<any>(null),[entries,setEntries]=useState<any[]>([]),[joint,setJoint]=useState(""),[release,setRelease]=useState("");
 const [busy,setBusy]=useState(false),[error,setError]=useState(false),[saved,setSaved]=useState(false),[dirty,setDirty]=useState(false),[leave,setLeave]=useState(false);
 const mounted=useRef(true),command=useRef<{body:string;id:string}|null>(null),base=`/v1/agent-runtime/tasks/${taskId}/risk`;
 function apply(value:any,preserve=false) {
  setData(value);
  if (!preserve) {
   const previous=value.history[0];
   setEntries(value.members.map((m:any)=>previous?.entries.find((e:any)=>e.taskId===m.id)??{taskId:m.id,dimensions:Object.fromEntries(dimensions.map(d=>[d,{level:"",rationale:"",evidence:[]}])),uncertainty:{level:"",reasons:"",evidence:[]},contradictions:[]}));
   setJoint(previous?.jointRationale??"");setRelease(value.members.find((m:any)=>m.id===taskId)?.releaseSetId??"");setDirty(false);
  } else setEntries(rows=>value.members.map((m:any)=>rows.find(e=>e.taskId===m.id)??{taskId:m.id,dimensions:Object.fromEntries(dimensions.map(d=>[d,{level:"",rationale:"",evidence:[]}])),uncertainty:{level:"",reasons:"",evidence:[]},contradictions:[]}));
 }
 async function load(preserve=false) {setBusy(true);setError(false);try {const r=await api<{data:any}>(base);if(mounted.current)apply(r.data,preserve);}catch{if(mounted.current)setError(true);}finally{if(mounted.current)setBusy(false);}}
 useEffect(()=>{mounted.current=true;void load();return()=>{mounted.current=false;};},[taskId]);
 function close(){if(busy)return;if(dirty)setLeave(true);else onClose();}
 function change(index:number,update:any){setEntries(rows=>rows.map((row,i)=>i===index?update:row));setDirty(true);setSaved(false);}
 async function send(path:string,body:any) {
  const encoded=JSON.stringify({path,body});if(command.current?.body!==encoded)command.current={body:encoded,id:crypto.randomUUID()};
  return api<{data:any}>(`${base}/${path}`,{method:"POST",body:JSON.stringify({...body,requestId:command.current.id})});
 }
 async function prepare(){if(busy||!data?.canAssess)return;setBusy(true);setError(false);setSaved(false);try{
  const scope=input??data.members.find((m:any)=>m.id===taskId)?.scope;
  const ref=data.evidence.find((e:any)=>e.id===release);
  const {applicationId,contract,prompt,baseBranch}=scope??{};
  const r=await send("scope",{applicationId,contract,prompt:prompt??null,baseBranch:baseBranch??null,releaseSet:ref?{id:ref.id,revision:ref.revision}:null,expectedVersion:data.expectedVersion});
  if(mounted.current){apply(r.data,true);command.current=null;onSaved?.();}
 }catch{if(mounted.current)setError(true);}finally{if(mounted.current)setBusy(false);}}
 async function submit(e:FormEvent){e.preventDefault();if(busy||!data?.canAssess)return;setBusy(true);setError(false);setSaved(false);try{
  const r=await send("assessments",{expectedVersion:data.expectedVersion,entries,jointRationale:joint});
  if(mounted.current){apply(r.data);command.current=null;setSaved(true);onSaved?.();}
 }catch(caught){if(mounted.current){setError(true);if(caught instanceof AppApiError && caught.code==="task_risk_stale")command.current=null;}}finally{if(mounted.current)setBusy(false);}}
 function proof(value:any,onChange:(refs:any[])=>void,applicationId:string) {
  const current=data.evidence.find((r:any)=>r.id===value[0]?.id),stale=value.length&&(!current||current.revision!==value[0].revision);
  return <div className="grid gap-2"><CcField label={c.evidence} hint={c.proof} error={stale?c.staleProof:undefined} required>{({id})=><CcSelect id={id} required value={value[0]?.id??""} onChange={e=>{const ref=data.evidence.find((r:any)=>r.id===e.target.value);onChange(ref?[{id:ref.id,revision:ref.revision}]:[]);}}><option value="">{c.choose}</option>{data.evidence.filter((r:any)=>!r.applicationId||r.applicationId===applicationId).map((r:any)=><option key={r.id} value={r.id}>{r.label}</option>)}</CcSelect>}</CcField>{stale&&current&&data.canAssess?<CcButton variant="outline" size="sm" onClick={()=>onChange([{id:current.id,revision:current.revision}])}>{c.refreshProof}</CcButton>:null}</div>;
 }

 if(admissionOpen)return <TaskRiskAdmissionModal taskId={taskId} onClose={()=>setAdmissionOpen(false)}/>;
 if(leave)return <CcRecordEditorModal titleId="risk-discard" title={c.discard} onClose={()=>setLeave(false)} closeLabel={c.stay} onSubmit={e=>{e.preventDefault();onClose();}} actions={<><CcButton onClick={()=>setLeave(false)}>{c.stay}</CcButton><CcButton type="submit" variant="warning">{c.leave}</CcButton></>}>{c.dirty}</CcRecordEditorModal>;
 const current=data?.history.find((h:any)=>h.id===data.currentId),shown=current??data?.history[0],complete=data&&data.members.length<=50&&data.members.every((m:any)=>m.scopeId);
 return <CcRecordEditorModal titleId="risk-title" title={c.title} eyebrow={data?.task.title} description={c.boundary} closeLabel={c.close} onClose={close} onSubmit={submit} maxWidthClassName="max-w-5xl" actions={<><CcButton disabled={busy} onClick={close} variant="ghost">{c.close}</CcButton>{data?.canAssess&&complete?<CcButton disabled={busy} type="submit" variant="primary">{c.save}</CcButton>:null}</>}>
  {busy?<p role="status">{c.loading}</p>:null}{error?<CcNotice live tone="error" title={c.error}/>:null}{saved?<CcNotice live tone={data?.currentId?"success":"warning"} title={data?.currentId?c.saved:c.blocked}/>:null}
  <div className="flex flex-wrap gap-2"><CcButton disabled={busy} onClick={()=>void load(dirty)} variant="outline">{c.refresh}</CcButton><CcButton disabled={busy||dirty} onClick={()=>setAdmissionOpen(true)} variant="outline">{locale==="pl"?"Warunki dopuszczenia":"Admission requirements"}</CcButton></div>
  {data?<>
   {!data.canAssess?<CcNotice tone="info" title={c.readOnly}/>:null}
   <section className="grid gap-3 border-b border-base-300 pb-4" aria-label={c.valid}>
    <h3 className="font-bold">{current?c.valid:c.blocked}</h3>
    {shown?<><p className="text-lg font-bold">{shown.result.level?c[shown.result.level]:c.blocked}</p>{!current?<p className="text-sm text-warning">{c.old}</p>:null}<dl className="grid grid-cols-2 gap-3 sm:grid-cols-4">{dimensions.map(d=><div key={d}><dt className="text-company-muted">{c[d]}</dt><dd>{c[shown.result.dimensions[d]]}</dd></div>)}</dl>{shown.result.cumulativeEscalation?<p>{c.cumulative} (+{shown.result.cumulativeEscalation})</p>:null}{shown.result.uncertaintyEscalation?<p>{c.escalation} (+{shown.result.uncertaintyEscalation})</p>:null}{shown.result.reasons.filter((r:string)=>c[r]).map((r:string)=><p key={r}>{c[r]}</p>)}</>:<p>{c.empty}</p>}
    {data.blockers.map((b:string)=><p key={b} className="text-sm text-warning">{c[b]??c.blocked}</p>)}
   </section>
   <section className="grid gap-2"><h3 className="font-bold">{c.related} ({data.members.length})</h3>{data.members.map((m:any)=><div key={m.id} className="border-b border-base-300 py-2"><p className="font-medium">{m.title}</p><p className="text-sm text-company-muted">{m.objective??c.noScope}</p><p className="text-xs text-company-muted">{m.relatedBy?.map((r:string)=>c[r]).join(" · ")}</p></div>)}{!complete?<p className="text-warning">{c.missing}</p>:null}</section>
   {data.canAssess?<section className="grid gap-3 border-b border-base-300 pb-4"><CcField label={c.release}>{({id})=><CcSelect id={id} disabled={busy} value={release} onChange={e=>{setRelease(e.target.value);setDirty(true);}}><option value="">{c.noneRelease}</option>{data.evidence.filter((r:any)=>r.applicationId===(input?.applicationId??data.members.find((m:any)=>m.id===taskId)?.applicationId)).map((r:any)=><option value={r.id} key={r.id}>{r.label}</option>)}</CcSelect>}</CcField><CcButton disabled={busy||!input&&!data.members.find((m:any)=>m.id===taskId)?.scope} onClick={()=>void prepare()} variant="outline">{c.prepare}</CcButton></section>:null}
   {data.evidenceTruncated?<p>{c.limited}</p>:null}
   {complete?<fieldset disabled={!data.canAssess||busy} className="grid min-w-0 gap-4">{entries.map((entry,index)=>{
    const member=data.members.find((m:any)=>m.id===entry.taskId);
    return <section key={entry.taskId} className="grid min-w-0 gap-4"><h3 className="font-bold">{member?.title}</h3>{dimensions.map(d=><section className="grid gap-3 border-t border-base-300 pt-4" key={d}><h4 className="font-bold">{c[d]}</h4><div className="grid gap-3 sm:grid-cols-2"><CcField label={c[d]} required>{({id})=><CcSelect id={id} required value={entry.dimensions[d].level} onChange={e=>change(index,{...entry,dimensions:{...entry.dimensions,[d]:{...entry.dimensions[d],level:e.target.value}}})}><option value="">{c.choose}</option>{levels.map(l=><option key={l} value={l}>{c[l]}</option>)}</CcSelect>}</CcField>{proof(entry.dimensions[d].evidence,refs=>change(index,{...entry,dimensions:{...entry.dimensions,[d]:{...entry.dimensions[d],evidence:refs}}}),member.applicationId)}</div><CcField label={c.rationale} required>{({id})=><textarea id={id} required minLength={3} maxLength={2000} className="textarea textarea-bordered w-full" value={entry.dimensions[d].rationale} onChange={e=>change(index,{...entry,dimensions:{...entry.dimensions,[d]:{...entry.dimensions[d],rationale:e.target.value}}})}/>}</CcField></section>)}
     <div className="grid gap-3 sm:grid-cols-2"><CcField label={c.uncertainty} required>{({id})=><CcSelect id={id} required value={entry.uncertainty.level} onChange={e=>change(index,{...entry,uncertainty:{...entry.uncertainty,level:e.target.value}})}><option value="">{c.choose}</option>{["none","bounded","unverifiable"].map(l=><option value={l} key={l}>{c[l]}</option>)}</CcSelect>}</CcField>{proof(entry.uncertainty.evidence,refs=>change(index,{...entry,uncertainty:{...entry.uncertainty,evidence:refs}}),member.applicationId)}</div>
     <CcField label={c.reasons} required>{({id})=><textarea id={id} required minLength={3} maxLength={2000} className="textarea textarea-bordered w-full" value={entry.uncertainty.reasons} onChange={e=>change(index,{...entry,uncertainty:{...entry.uncertainty,reasons:e.target.value}})}/>}</CcField>
     <CcField label={c.contradictions}>{({id})=><textarea id={id} maxLength={40000} className="textarea textarea-bordered w-full" value={entry.contradictions.join("\n")} onChange={e=>change(index,{...entry,contradictions:e.target.value.split("\n").filter(Boolean)})}/>}</CcField>
    </section>;
   })}<CcField label={c.joint} required>{({id})=><textarea id={id} required minLength={3} maxLength={2000} className="textarea textarea-bordered w-full" value={joint} onChange={e=>{setJoint(e.target.value);setDirty(true);}}/>}</CcField></fieldset>:null}
   <details className="border-t border-base-300 pt-4"><summary className="cursor-pointer font-bold">{c.history}</summary>{data.history.map((h:any)=><div key={h.id} className="border-b border-base-300 py-3 text-sm"><p>{new Date(h.createdAt).toLocaleString(locale)} · {h.result.level?c[h.result.level]:c.blocked}</p><p>{h.jointRationale}</p><p className="break-all font-mono text-xs">{h.assessorId} · {data.algorithm} · {h.version}</p></div>)}</details>
  </>:null}
 </CcRecordEditorModal>;
}
