export const capabilityMessages = {
  en: {interview_prepare:"Prepare decision questions",clarification_send:"Send clarification",clarification_reply:"Reply / acknowledge",handoff_create:"Create handoff",handoff_accept:"Accept handoff",handoff_reject:"Reject handoff",
    title: "Task grants", boundary: "Authorize one agent operation for this task and its current result. A grant can be used once and lasts at most one hour.",
    operation: "Agent and operation", choose: "Choose an operation", reason: "Authorization reason", from: "Valid from", until: "Valid until", issue: "Issue grant", revoke: "Revoke grant", confirm: "Confirm revocation", revokeReason: "Revocation reason", close: "Back to review", refresh: "Refresh", loading: "Loading task grants…", error: "Could not complete the request. Refresh to check the current scope or retry the same request.", saved: "Grant history updated.", empty: "No grants for this task.", unavailable: "No eligible operation. The current result needs valid agent roles and an active bound credential. Completed or interrupted tasks cannot receive grants.", history: "Grant history", issuer: "Authorized by", credential: "Credential", application: "Application", used: "Use recorded", older: "Older grants", cancel: "Cancel", discard: "Discard unsaved changes?", stay: "Keep editing", leave: "Discard changes", window: "Choose a future expiry within one hour and before the credential expires.",
    review_decision: "Record review decision", return_to_executor: "Return correction to executor", create_specialist_task: "Create specialist correction task",
    suspended: "Suspended after serious incident", active: "Active", pending: "Not yet valid", consumed: "Used", revoked: "Revoked", expired: "Expired", invalidated: "Scope changed", invalidatedHint: "The task, result, roles, application or credential changed. A new grant is required.", revokedHint: "Revocation prevents further use and replay.",
  },
  pl: {interview_prepare:"Przygotuj pytania do decyzji",clarification_send:"Wyślij doprecyzowanie",clarification_reply:"Odpowiedz / potwierdź",handoff_create:"Utworzenie przekazania",handoff_accept:"Przyjęcie przekazania",handoff_reject:"Odrzucenie przekazania",
    title: "Granty zadania", boundary: "Zezwól agentowi na jedną operację dla tego zadania i jego aktualnego wyniku. Grant jest jednorazowy i ważny najwyżej godzinę.",
    operation: "Agent i operacja", choose: "Wybierz operację", reason: "Uzasadnienie uprawnienia", from: "Ważny od", until: "Ważny do", issue: "Wydaj grant", revoke: "Cofnij grant", confirm: "Potwierdź cofnięcie", revokeReason: "Powód cofnięcia", close: "Wróć do oceny", refresh: "Odśwież", loading: "Wczytywanie grantów zadania…", error: "Nie udało się wykonać żądania. Odśwież aktualny zakres albo ponów to samo żądanie.", saved: "Historia grantów została zaktualizowana.", empty: "To zadanie nie ma grantów.", unavailable: "Brak dostępnej operacji. Aktualny wynik wymaga poprawnych ról agentów i aktywnego powiązanego poświadczenia. Zadania zakończone lub wstrzymane nie mogą otrzymać grantów.", history: "Historia grantów", issuer: "Uprawnienia nadał", credential: "Poświadczenie", application: "Aplikacja", used: "Użycie zapisane", older: "Starsze granty", cancel: "Anuluj", discard: "Odrzucić niezapisane zmiany?", stay: "Kontynuuj edycję", leave: "Odrzuć zmiany", window: "Wybierz przyszły termin w ciągu godziny, przed wygaśnięciem poświadczenia.",
    review_decision: "Zapisanie decyzji oceny", return_to_executor: "Zwrot korekty do wykonawcy", create_specialist_task: "Utworzenie zadania korekty dla specjalisty",
    suspended: "Zawieszony po poważnym incydencie", active: "Aktywny", pending: "Jeszcze nieważny", consumed: "Użyty", revoked: "Cofnięty", expired: "Wygasły", invalidated: "Zmieniony zakres", invalidatedHint: "Zadanie, wynik, role, aplikacja lub poświadczenie uległy zmianie. Potrzebny jest nowy grant.", revokedHint: "Cofnięcie blokuje dalsze użycie i ponowienie komendy.",
  },
};
