import { FormEvent, useMemo, useState } from "react";
import { api, AppApiError } from "../../api/client";
import { CcButton } from "../../components/cc-button";
import { CcConfirmDialog } from "../../components/cc-confirm-dialog";
import { CcDataTable, type CcTableColumn } from "../../components/cc-data-table";
import { CcField } from "../../components/cc-field";
import { CcMultiSelect } from "../../components/cc-multi-select";
import { CcNotice } from "../../components/cc-notice";
import { CcPageHeader } from "../../components/cc-page-header";
import { CcRecordEditorModal, CcRecordEditorSection } from "../../components/cc-record-editor";
import { CcSelect } from "../../components/cc-select";
import { useOwnerPacket } from "../../hooks/use-owner-packet";
import { useLanguage } from "../../i18n/i18n";
import type { CoreAreaKey } from "../../types";
import { departmentLabel } from "./department-labels";
import { humanizeBusinessValue, useTranslatedTableLabels } from "./shared";

type Department = { id: string; key: CoreAreaKey; name: string };
type Task = { id: string; title: string; description?: string | null; status: string; priority?: string | null; dueDate?: string | null; taskList?: { id: string; name: string } | null; project?: { id: string; name: string } | null; organizationalContext?: { ownerDepartment?: Department | null; relatedDepartments?: Department[]; scopes?: Array<{ type: string }> } };
type Draft = { title: string; description: string; status: string; priority: string; dueDate: string; ownerDepartmentKey: string; relatedDepartmentKeys: string[]; companyWide: boolean };
function draftFor(task: Task | null, departmentKey: CoreAreaKey): Draft { return { title: task?.title || "", description: task?.description || "", status: task?.status || "todo", priority: task?.priority || "normal", dueDate: task?.dueDate?.slice(0, 10) || "", ownerDepartmentKey: task?.organizationalContext?.ownerDepartment?.key || departmentKey, relatedDepartmentKeys: task?.organizationalContext?.relatedDepartments?.map((department) => department.key) || [], companyWide: Boolean(task?.organizationalContext?.scopes?.some((scope) => scope.type === "company")) }; }

function TaskEditor({ task, departmentKey, departments, onClose, onSaved }: { task: Task | null; departmentKey: CoreAreaKey; departments: Department[]; onClose: () => void; onSaved: () => void }) {
  const { locale, t } = useLanguage(); const polish = locale === "pl"; const [draft, setDraft] = useState(() => draftFor(task, departmentKey)); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const options = departments.map((department) => ({ value: department.key, label: departmentLabel(department.key, t) }));
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(null); try { await api(task ? `/v1/tasks/${task.id}` : "/v1/tasks", { method: task ? "PATCH" : "POST", body: JSON.stringify({ title: draft.title, description: draft.description || undefined, status: draft.status, priority: draft.priority, dueDate: draft.dueDate ? new Date(`${draft.dueDate}T12:00:00.000Z`).toISOString() : undefined, organizationalContext: { ownerDepartmentKey: draft.ownerDepartmentKey, relatedDepartmentKeys: draft.relatedDepartmentKeys.filter((key) => key !== draft.ownerDepartmentKey), applicableDepartmentKeys: [], scopes: draft.companyWide ? [{ type: "company" }] : [{ type: "department", entityId: draft.ownerDepartmentKey }] } }) }); onSaved(); } catch (caught) { setError(caught instanceof AppApiError ? caught.code : "request_failed"); } finally { setBusy(false); } }
  return <CcRecordEditorModal actions={<><CcButton onClick={onClose} variant="ghost">{t("common.cancel")}</CcButton><CcButton loading={busy} type="submit" variant="primary">{t("common.save")}</CcButton></>} description={polish ? "To ten sam globalny Task, widoczny w odpowiednich działach przez kontekst." : "This is the same global Task, shown in relevant departments through context."} eyebrow={polish ? "Zadania" : "Tasks"} onClose={onClose} onSubmit={submit} title={task ? polish ? "Edytuj zadanie" : "Edit task" : polish ? "Utwórz zadanie" : "Create task"} titleId="task-editor-title">
    {error ? <CcNotice live tone="error" title={humanizeBusinessValue(error)} /> : null}
    <CcRecordEditorSection title={polish ? "Zadanie" : "Task"}><div className="grid gap-4 md:grid-cols-2">
      <CcField label={polish ? "Tytuł" : "Title"} required>{({ id }) => <input className="input input-bordered w-full" id={id} onChange={(event) => setDraft({ ...draft, title: event.target.value })} required value={draft.title} />}</CcField>
      <CcField label={polish ? "Opis" : "Description"}>{({ id }) => <textarea className="textarea textarea-bordered min-h-24 w-full" id={id} onChange={(event) => setDraft({ ...draft, description: event.target.value })} value={draft.description} />}</CcField>
      <div className="grid grid-cols-2 gap-3"><CcField label="Status">{({ id }) => <CcSelect id={id} onChange={(event) => setDraft({ ...draft, status: event.target.value })} value={draft.status}>{["todo", "in_progress", "blocked", "done"].map((value) => <option key={value} value={value}>{humanizeBusinessValue(value, undefined, locale)}</option>)}</CcSelect>}</CcField><CcField label={polish ? "Priorytet" : "Priority"}>{({ id }) => <CcSelect id={id} onChange={(event) => setDraft({ ...draft, priority: event.target.value })} value={draft.priority}>{["critical", "high", "normal", "low"].map((value) => <option key={value}>{humanizeBusinessValue(value, undefined, locale)}</option>)}</CcSelect>}</CcField></div>
      <CcField label={polish ? "Termin" : "Due date"}>{({ id }) => <input className="input input-bordered w-full" id={id} onChange={(event) => setDraft({ ...draft, dueDate: event.target.value })} type="date" value={draft.dueDate} />}</CcField>
    </div></CcRecordEditorSection>
    <CcRecordEditorSection title={polish ? "Kontekst organizacyjny" : "Organizational context"}><div className="grid gap-4 md:grid-cols-2"><CcField label={polish ? "Dział właścicielski" : "Owner department"}>{({ id }) => <CcSelect id={id} onChange={(event) => setDraft({ ...draft, ownerDepartmentKey: event.target.value })} value={draft.ownerDepartmentKey}>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</CcSelect>}</CcField><CcField label={polish ? "Powiązane działy" : "Related departments"}>{({ id }) => <CcMultiSelect id={id} name="taskRelatedDepartments" onChange={(value) => setDraft({ ...draft, relatedDepartmentKeys: value })} options={options.filter((option) => option.value !== draft.ownerDepartmentKey)} value={draft.relatedDepartmentKeys} />}</CcField><label className="flex min-h-11 items-center gap-3 rounded-company border border-base-300 px-3 py-2 text-sm font-bold md:col-span-2"><input checked={draft.companyWide} className="checkbox checkbox-primary checkbox-sm" onChange={(event) => setDraft({ ...draft, companyWide: event.target.checked })} type="checkbox" />{polish ? "Zakres całej firmy" : "Company-wide scope"}</label></div></CcRecordEditorSection>
  </CcRecordEditorModal>;
}

export function TasksWorkbench({ departmentKey, canonical = false }: { departmentKey: CoreAreaKey; canonical?: boolean }) {
  const { locale, t } = useLanguage(); const polish = locale === "pl"; const [refreshKey, setRefreshKey] = useState(0); const [editing, setEditing] = useState<Task | null | undefined>(undefined); const [archiving, setArchiving] = useState<Task | null>(null); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState<{ tone: "success" | "error"; title: string } | null>(null);
  const packet = useOwnerPacket<Task[]>(`/v1/tasks${canonical ? "?" : `?departmentKey=${departmentKey}&includeCompanyWide=true&` }refresh=${refreshKey}`, true, t); const departments = useOwnerPacket<{ departments: Department[] }>(`/v1/departments?refresh=${refreshKey}`, true, t); const rows = packet.data || []; const labels = useTranslatedTableLabels();
  const columns = useMemo<Array<CcTableColumn<Task>>>(() => [
    { key: "task", header: polish ? "Zadanie" : "Task", sortable: true, searchValue: (row) => `${row.title} ${row.description || ""}`, cell: (row) => <button className="grid text-left" onClick={() => setEditing(row)} type="button"><strong>{row.title}</strong><span className="text-xs text-company-muted">{row.project?.name || row.taskList?.name || row.description || "—"}</span></button> },
    { key: "owner", header: polish ? "Dział" : "Department", filterable: true, filterValue: (row) => row.organizationalContext?.ownerDepartment?.key || "unassigned", cell: (row) => <span className="text-sm text-company-muted">{row.organizationalContext?.ownerDepartment ? departmentLabel(row.organizationalContext.ownerDepartment.key, t) : "—"}</span> },
    { key: "status", header: "Status", filterable: true, filterValue: (row) => row.status, cell: (row) => <span className="badge badge-outline">{humanizeBusinessValue(row.status, undefined, locale)}</span> },
    { key: "priority", header: polish ? "Priorytet" : "Priority", filterable: true, filterValue: (row) => row.priority || "normal", cell: (row) => <span className="text-sm text-company-muted">{humanizeBusinessValue(row.priority || "normal", undefined, locale)}</span> },
    { key: "actions", header: t("table.actions"), cell: (row) => <div className="flex justify-end gap-1"><CcButton ariaLabel="Run with Codex" iconLeft="ph-terminal-window" onClick={() => void runWithCodex(row)} size="xs" variant="ghost"><span className="sr-only">Run with Codex</span></CcButton><CcButton ariaLabel="Edit" iconLeft="ph-pencil-simple" onClick={() => setEditing(row)} size="xs" variant="ghost"><span className="sr-only">Edit</span></CcButton><CcButton ariaLabel="Archive" iconLeft="ph-archive" onClick={() => setArchiving(row)} size="xs" variant="ghost"><span className="sr-only">Archive</span></CcButton></div> }
  ], [locale, polish, t]);
  function refresh() { setEditing(undefined); setRefreshKey((value) => value + 1); }
  async function runWithCodex(task: Task) { setBusy(true); setNotice(null); try { await api("/v1/agent-runtime/executions", { method: "POST", body: JSON.stringify({ taskId: task.id }) }); setNotice({ tone: "success", title: polish ? "Zadanie czeka na lokalnego Codexa." : "Task queued for local Codex." }); } catch (caught) { setNotice({ tone: "error", title: humanizeBusinessValue(caught instanceof AppApiError ? caught.code : "request_failed", undefined, locale) }); } finally { setBusy(false); } }
  async function archive() { if (!archiving) return; setBusy(true); try { await api(`/v1/tasks/${archiving.id}`, { method: "DELETE" }); setArchiving(null); refresh(); } finally { setBusy(false); } }
  return <><CcPageHeader actions={<><CcButton href="/areas?area=06-kadry&view=executions" iconLeft="ph-terminal-window" size="sm" variant="outline">Codex runs</CcButton><CcButton iconLeft="ph-plus" onClick={() => setEditing(null)} size="sm" variant="primary">{polish ? "Utwórz" : "Create"}</CcButton></>} description={canonical ? polish ? "Wszystkie zadania firmy w jednym systemie wykonawczym." : "All company tasks in one execution system." : polish ? "Kontekstowy filtr globalnych zadań — bez drugiego task managera." : "A contextual filter over global tasks — not another task manager."} eyebrow={departmentLabel(departmentKey, t)} title={canonical ? polish ? "Wszystkie zadania" : "All tasks" : `${polish ? "Zadania" : "Tasks"}: ${departmentLabel(departmentKey, t)}`} />
    {notice ? <CcNotice live tone={notice.tone} title={notice.title} /> : null}
    <CcDataTable columns={columns} rows={rows} emptyDetail={polish ? "Utwórz zadanie lub przypisz istniejącemu kontekst tego działu." : "Create a task or assign this department context to an existing one."} emptyTitle={polish ? "Brak zadań" : "No tasks"} error={packet.status === "error" ? packet.error : null} getRowLabel={(row) => row.title} labels={labels} loading={packet.status === "loading"} mobileMode="cards" />
    {editing !== undefined ? <TaskEditor departmentKey={departmentKey} departments={departments.data?.departments || []} onClose={() => setEditing(undefined)} onSaved={refresh} task={editing} /> : null}
    {archiving ? <CcConfirmDialog busy={busy} confirmIcon="ph-archive" confirmLabel={polish ? "Archiwizuj" : "Archive"} confirmTone="warning" description={polish ? "Zadanie pozostanie w historii i audycie." : "The task remains in history and audit."} detail={<strong>{archiving.title}</strong>} eyebrow={polish ? "Zadania" : "Tasks"} onCancel={() => setArchiving(null)} onConfirm={archive} title={polish ? "Zarchiwizować zadanie?" : "Archive task?"} /> : null}</>;
}
