export const reviewMessages = {
  en: {
    capability_grant_required: "This agent needs an active grant for the exact task operation. A workspace administrator can issue it in Task grants.",
    title: "Result review", open: "Review result", close: "Close review", refresh: "Refresh current result", loading: "Loading result and responsibilities…", error: "The command was not accepted. Refresh the result and check your current responsibility.", saved: "Decision recorded in task history.",
    boundary: "Review records evidence and a decision. Approval does not release or close the task. A rejection needs a separate manager decision before correction.",
    no_result: "No completed result is available for review.", stale_result: "This result is no longer current. Reconcile the task and review the latest completed attempt.", roles_need_context: "Role evidence needs context. Current roles, membership and mandates must match the accepted contract.", verifier_required: "Only the assigned independent verifier can decide. Agent profiles require proven identity binding to use this command.", manager_required: "Rejected — awaiting the accountable manager.", action_recorded: "Correction disposition recorded. A fresh Submit is still required.", approved: "Approved for this result version. Release remains separate.",
    material: "Material under review", version: "Result version", attempt: "Execution attempt", verifier: "Verifier", manager: "Accountable manager", details: "Reported result and checks", decision: "Review decision", approve: "Approve result", reject: "Reject result", summary: "Assessment", reference: "Evidence or test reference", testResult: "Evidence or test result", reproduction: "Reproduction steps", expected: "Expected behavior", observed: "Observed behavior", scope: "Required correction scope", excluded: "Excluded changes", outcome: "One required correction outcome", competencies: "Required specialist competencies", lines: "One item per line. Use redacted evidence; never include credentials or sensitive logs.",
    disposition: "Manager decision", return_to_executor: "Return to original executor", create_specialist_task: "Create dependent specialist task", specialist: "Competent specialist", choose: "Choose a specialist", selection: "Select correction items. The manager may narrow the rejected scope.", recordReview: "Record review decision", recordAction: "Record correction disposition", history: "Review history", older: "Load older decisions", child: "Dependent correction task", draft: "Draft — requires a reviewed contract and explicit Submit", limited: "The specialist catalog is limited to 500 profiles.", discard: "Discard unsaved assessment?", stay: "Keep editing", leave: "Discard and close"
  },
  pl: {
    capability_grant_required: "Agent potrzebuje aktywnego grantu na tę operację w zadaniu. Administrator obszaru może go wydać w panelu Granty zadania.",
    title: "Ocena wyniku", open: "Oceń wynik", close: "Zamknij ocenę", refresh: "Odśwież aktualny wynik", loading: "Wczytywanie wyniku i odpowiedzialności…", error: "Komenda nie została przyjęta. Odśwież wynik i sprawdź swoją aktualną odpowiedzialność.", saved: "Decyzja została zapisana w historii zadania.",
    boundary: "Ocena zapisuje dowody i decyzję. Akceptacja nie wydaje ani nie zamyka zadania. Odrzucenie wymaga osobnej decyzji managera przed poprawką.",
    no_result: "Brak zakończonego wyniku do oceny.", stale_result: "Ten wynik nie jest już aktualny. Uzgodnij zadanie i oceń najnowszą zakończoną próbę.", roles_need_context: "Dowody ról wymagają kontekstu. Aktualne role, członkostwo i mandaty muszą odpowiadać przyjętemu kontraktowi.", verifier_required: "Decyzję może podjąć tylko przypisany niezależny weryfikator. Profil agenta wymaga potwierdzonego powiązania tożsamości dla tej komendy.", manager_required: "Odrzucono — oczekiwanie na odpowiedzialnego managera.", action_recorded: "Sposób korekty został zapisany. Nadal wymagany jest nowy Submit.", approved: "Zaakceptowano tę wersję wyniku. Wydanie pozostaje osobną decyzją.",
    material: "Materiał podlegający ocenie", version: "Wersja wyniku", attempt: "Próba wykonania", verifier: "Weryfikator", manager: "Odpowiedzialny manager", details: "Zgłoszony wynik i testy", decision: "Decyzja oceny", approve: "Zaakceptuj wynik", reject: "Odrzuć wynik", summary: "Uzasadnienie oceny", reference: "Odnośnik do dowodu lub testu", testResult: "Wynik dowodu lub testu", reproduction: "Kroki reprodukcji", expected: "Oczekiwane zachowanie", observed: "Zaobserwowane zachowanie", scope: "Wymagany zakres korekty", excluded: "Wykluczone zmiany", outcome: "Jeden wymagany wynik korekty", competencies: "Wymagane kompetencje specjalisty", lines: "Jeden element w wierszu. Używaj zredagowanych dowodów; nigdy nie wpisuj poświadczeń ani wrażliwych logów.",
    disposition: "Decyzja managera", return_to_executor: "Zwróć pierwotnemu wykonawcy", create_specialist_task: "Utwórz zależne zadanie specjalisty", specialist: "Kompetentny specjalista", choose: "Wybierz specjalistę", selection: "Wybierz elementy korekty. Manager może zawęzić odrzucony zakres.", recordReview: "Zapisz decyzję oceny", recordAction: "Zapisz sposób korekty", history: "Historia ocen", older: "Wczytaj starsze decyzje", child: "Zależne zadanie korekty", draft: "Szkic — wymaga sprawdzonego kontraktu i jawnego Submit", limited: "Katalog specjalistów jest ograniczony do 500 profili.", discard: "Odrzucić niezapisaną ocenę?", stay: "Kontynuuj edycję", leave: "Odrzuć i zamknij"
  }
};
