import { useEffect, useRef, useState } from "react";
import { api } from "../../api/client";
import { CcButton } from "../../components/cc-button";
import { CcField } from "../../components/cc-field";
import { CcSelect } from "../../components/cc-select";
import { CcNotice } from "../../components/cc-notice";
import { CcRecordEditorModal } from "../../components/cc-record-editor";
import { useLanguage } from "../../i18n/i18n";
import { TaskCapabilityModal } from "./task-capability";
const types=["question","answer","evidence_request","evidence_response","constraint_notice","status_update"];
const copy={
 en:{result:"Recorded result",branch:"Branch",tree:"Working tree",clean:"Clean",dirty:"Uncommitted changes",tests:"Recorded tests",changes:"Changed paths",limited:"History and reference catalogs are bounded. Older receipts remain in their source workbench.",title:"Task clarification",boundary:"Messages provide context. Changes to scope, priority or authority require the formal task or decision workflow.",close:"Close",refresh:"Refresh",loading:"Loading conversation…",error:"Not recorded. Check the current context, recipient and exact grant, then retry.",saved:"Recorded in immutable history.",start:"New conversation",history:"Conversation",none:"No conversations yet",linked:"Task to clarify with",same:"This task",sender:"Your task role",recipient:"Recipient role",choose:"Choose",type:"Message type",text:"Clarification",question:"Question",answer:"Answer",evidence_request:"Evidence request",evidence_response:"Evidence response",constraint_notice:"Constraint notice",status_update:"Status update",read:"Read receipt",all:"All types",filter:"Filter messages",expected:"Expected response",optional:"No response requested",instruction:"Response requested",due:"Response due (optional)",material:"Material assumption or constraint needs formal review",reason:"Why formal review is needed",signal:"Requires formal review",signalHint:"This observation has not changed the task contract. Use the existing task editor, Submit or decision workflow.",refs:"Recorded references (up to 8)",send:"Send clarification",reply:"Reply",ack:"Acknowledge this version",correct:"Correct with a new message",supersedes:"Corrects message",cancel:"Cancel reply",older:"Older messages",stale:"Context changed. History remains available; prepare a new conversation using the current formal context.",blocked:"Current task roles and operation admission are required before sending.",summary:"Execution summary",summaryHint:"Summary from recorded execution receipts. Test results are reported observations. Conversation text is not evidence.",unavailable:"No complete execution receipt is available.",details:"Receipt details",grants:"Agent grants",discard:"Discard unsaved message?",stay:"Keep editing",leave:"Discard",requester:"Requester",accountableManager:"Accountable manager",executor:"Executor",verifier:"Verifier",releaser:"Release authority"},
 pl:{result:"Zapisany wynik",branch:"Gałąź",tree:"Stan plików",clean:"Czysty",dirty:"Niezacommitowane zmiany",tests:"Zapisane testy",changes:"Zmienione ścieżki",limited:"Historia i katalogi referencji mają limity. Starsze potwierdzenia pozostają w źródłowym panelu.",title:"Doprecyzowanie zadania",boundary:"Wiadomości dostarczają kontekst. Zmiana zakresu, priorytetu lub mandatu wymaga formalnej edycji zadania albo decyzji.",close:"Zamknij",refresh:"Odśwież",loading:"Wczytywanie rozmowy…",error:"Nie zapisano. Sprawdź aktualny kontekst, odbiorcę i dokładny grant, a następnie ponów.",saved:"Zapisano w niezmiennej historii.",start:"Nowa rozmowa",history:"Rozmowa",none:"Brak rozmów",linked:"Zadanie do doprecyzowania",same:"To zadanie",sender:"Twoja rola w zadaniu",recipient:"Rola odbiorcy",choose:"Wybierz",type:"Typ wiadomości",text:"Doprecyzowanie",question:"Pytanie",answer:"Odpowiedź",evidence_request:"Prośba o dowód",evidence_response:"Odpowiedź z dowodem",constraint_notice:"Informacja o ograniczeniu",status_update:"Informacja o stanie",read:"Potwierdzenie odczytu",all:"Wszystkie typy",filter:"Filtr wiadomości",expected:"Oczekiwana odpowiedź",optional:"Bez oczekiwanej odpowiedzi",instruction:"Prośba do odbiorcy",due:"Termin odpowiedzi (opcjonalny)",material:"Materialne założenie lub ograniczenie wymaga formalnej oceny",reason:"Dlaczego potrzebna jest formalna ocena",signal:"Wymaga formalnej oceny",signalHint:"Ta obserwacja nie zmieniła kontraktu zadania. Użyj istniejącego edytora zadania, Submit lub ścieżki decyzji.",refs:"Zapisane referencje (maks. 8)",send:"Wyślij doprecyzowanie",reply:"Odpowiedz",ack:"Potwierdź odczyt tej wersji",correct:"Popraw nową wiadomością",supersedes:"Koryguje wiadomość",cancel:"Anuluj odpowiedź",older:"Starsze wiadomości",stale:"Kontekst się zmienił. Historia pozostaje dostępna; przygotuj nową rozmowę na podstawie aktualnego formalnego kontekstu.",blocked:"Wysłanie wymaga aktualnych ról i dopuszczenia operacji.",summary:"Podsumowanie wykonania",summaryHint:"Podsumowanie pochodzi z zapisanych potwierdzeń wykonania. Wyniki testów są zgłoszonymi obserwacjami. Treść rozmowy nie jest dowodem.",unavailable:"Brak kompletnego potwierdzenia wykonania.",details:"Szczegóły potwierdzenia",grants:"Granty agenta",discard:"Odrzucić niezapisaną wiadomość?",stay:"Kontynuuj edycję",leave:"Odrzuć",requester:"Zlecający",accountableManager:"Odpowiedzialny manager",executor:"Wykonawca",verifier:"Weryfikator",releaser:"Odpowiedzialny za wydanie"}
};
const key=(p:any)=>`${p.taskId}:${p.role}`;
export function TaskClarificationModal({taskId,onClose}:{taskId:string;onClose:()=>void}){
 const {locale}=useLanguage(),c=copy[locale==="pl"?"pl":"en"],label=(k:string)=>(c as any)[k]??k;
 const [data,setData]=useState<any>(null),[busy,setBusy]=useState(true),[error,setError]=useState(false),[saved,setSaved]=useState(false),[dirty,setDirty]=useState(false),[leave,setLeave]=useState(false),[grants,setGrants]=useState(false);
 const [other,setOther]=useState(taskId),[threadId,setThreadId]=useState(""),[fresh,setFresh]=useState(true),[filter,setFilter]=useState("all"),[sender,setSender]=useState(""),[recipient,setRecipient]=useState("");
 const [type,setType]=useState("question"),[text,setText]=useState(""),[expected,setExpected]=useState(""),[instruction,setInstruction]=useState(""),[due,setDue]=useState(""),[material,setMaterial]=useState(false),[reason,setReason]=useState(""),[refs,setRefs]=useState<string[]>([]),[reply,setReply]=useState<any>(null);
 const alive=useRef(true),request=useRef<any>(null),form=useRef<HTMLDivElement>(null);
 const root=`/v1/agent-runtime/tasks/${taskId}/clarifications`;
 async function load(selected=threadId,related=other,before?:number){setBusy(true);setError(false);try{const query=new URLSearchParams({relatedTaskId:related,...(selected?{threadId:selected}:{}),...(before?{before:String(before)}:{})});const r=await api<{data:any}>(`${root}?${query}`);if(alive.current)setData((old:any)=>before&&old?{...r.data,selected:{...r.data.selected,entries:[...old.selected.entries,...r.data.selected.entries]}}:r.data);}catch{if(alive.current)setError(true);}finally{if(alive.current)setBusy(false);}}
 useEffect(()=>{alive.current=true;void load();return()=>{alive.current=false};},[taskId]);
 const selected=data?.selected,own=data?.senderChoices??[],senderChoices=own.filter((p:any)=>p.taskId===taskId),recipientChoices=(data?.recipientChoices??[]).filter((p:any)=>p.taskId===other);
 const edit=()=>{setDirty(true);setSaved(false);};
 const reset=()=>{setText("");setInstruction("");setExpected("");setDue("");setMaterial(false);setReason("");setRefs([]);setReply(null);setDirty(false);};
 const close=()=>{if(!busy)dirty?setLeave(true):onClose();};
 const selectThread=(id:string)=>{if(dirty)return;setFresh(false);setThreadId(id);setReply(null);void load(id);};
 const mine=(p:any)=>own.some((o:any)=>key(o)===key(p));
 const bindingFor=(action:string,target?:any)=>{const a=action==="send"?senderChoices.find((p:any)=>key(p)===sender):[selected.sender,selected.recipient].find(mine),r=action==="send"?recipientChoices.find((p:any)=>key(p)===recipient):[selected.sender,selected.recipient].find((p:any)=>!mine(p));return a&&r?{sender:{taskId:a.taskId,role:a.role},recipient:{taskId:r.taskId,role:r.role},threadId:action==="send"?null:selected.id,entryId:target?.id??null,action}:null;};
 // JSON key order from PostgreSQL is not an identity contract.
 const matchingGrant=(b:any)=>data?.grants.find((g:any)=>g.status==="active"&&g.binding.action===b?.action&&g.binding.threadId===b?.threadId&&g.binding.entryId===b?.entryId&&key(g.binding.sender)===key(b?.sender??{})&&key(g.binding.recipient)===key(b?.recipient??{}));
 const agentActing=(b:any)=>own.find((p:any)=>key(p)===key(b?.sender??{}))?.principal.kind==="agent";
 async function send(action:"send"|"reply"|"read",target?:any){
  const binding=bindingFor(action,target);if(!binding||busy)return;
  const grant=matchingGrant(binding),base={expectedVersion:action==="send"?data.expectedVersion:selected.expectedVersion,contextVersion:action==="send"?data.contextVersion:selected.contextVersion,...(grant?{grantId:grant.id}:{})};
  const content={type,text,references:(data.summary.references as any[]).filter(r=>refs.includes(`${r.kind}:${r.id}`)).map(({data:_,...r})=>r),expectedResponse:expected?{kind:expected,instruction,dueAt:due?new Date(due).toISOString():null}:null,material:material||type==="constraint_notice"?{category:"constraint",reason}:null};
  const input=action==="send"?{...base,sender:binding.sender,recipient:binding.recipient,content}:{...base,threadId:selected.id,entryId:target.id,entryVersion:target.version,...(action==="reply"?{supersedes:reply?.correcting?target.id:null,content}:{})};
  const route=action==="send"?root:`/v1/agent-runtime/tasks/${selected.taskId}/clarifications/actions/${action}`,signature=JSON.stringify({route,input});if(request.current?.signature!==signature)request.current={signature,id:crypto.randomUUID()};
  setBusy(true);setError(false);try{const r=await api<{data:any}>(route,{method:"POST",body:JSON.stringify({...input,requestId:request.current.id})});if(alive.current){reset();setSaved(true);setFresh(false);setThreadId(r.data.entry.threadId);await load(r.data.entry.threadId);}}catch{if(alive.current)setError(true);}finally{if(alive.current)setBusy(false);}
 }
 const valid=text.trim().length>=3&&text.length<=2000&&(!expected||instruction.trim().length>=3)&&(!(material||type==="constraint_notice")||reason.trim().length>=3)&&(type!=="evidence_response"||refs.length>0);
 const action=fresh?"send":"reply",binding=data&&(fresh?bindingFor("send"):reply&&bindingFor("reply",reply.entry));
 const canWrite=Boolean(binding&&(fresh?data?.canSend:selected?.canReply)&&(!agentActing(binding)||matchingGrant(binding)));
 if(grants)return <TaskCapabilityModal taskId={selected?.taskId??taskId} onClose={()=>{setGrants(false);void load();}}/>;
 return <CcRecordEditorModal titleId="task-clarification-title" eyebrow={locale==="pl"?"Zadanie":"Task"} title={c.title} onClose={close} closeLabel={c.close} onSubmit={e=>{e.preventDefault();if(valid&&canWrite)void send(action,reply?.entry);}} actions={<CcButton onClick={close} disabled={busy}>{c.close}</CcButton>}>
  <div className="space-y-5"><p className="text-sm text-company-muted">{c.boundary}</p><div className="flex flex-wrap gap-2"><CcButton disabled={busy||dirty} onClick={()=>void load()}>{c.refresh}</CcButton><CcButton disabled={busy||dirty} onClick={()=>{setFresh(true);setReply(null);setSaved(false);void load("",other);}}>{c.start}</CcButton>{data?.canManageGrants&&<CcButton disabled={busy} onClick={()=>setGrants(true)}>{c.grants}</CcButton>}</div>
  {error&&<CcNotice tone="error" title={c.error}/>}{saved&&<CcNotice tone="success" title={c.saved}/>}{busy&&<p role="status">{c.loading}</p>}
  {data&&<><CcField label={c.history}>{({id})=><CcSelect id={id} aria-label={c.history} value={fresh?"":selected?.id??""} disabled={busy||dirty} onChange={e=>selectThread(e.target.value)}><option value="">{c.none}</option>{data.threads.map((h:any)=><option key={h.id} value={h.id}>{label(h.sender.role)} → {label(h.recipient.role)} · {h.id.slice(0,8)}</option>)}</CcSelect>}</CcField>
  {!fresh&&selected&&<><div className="flex flex-wrap items-center gap-3"><CcField label={c.filter}>{({id})=><CcSelect id={id} aria-label={c.filter} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">{c.all}</option>{[...types,"read"].map(t=><option key={t} value={t}>{label(t)}</option>)}</CcSelect>}</CcField><span className="text-xs text-company-muted">{selected.id.slice(0,8)} · v{Math.max(...selected.entries.map((e:any)=>e.version),1)}</span></div>
   {!selected.current&&<CcNotice tone="warning" title={c.stale}/>}
   <ol className="divide-y divide-company-border">{[...selected.entries].sort((a,b)=>a.version-b.version).filter(e=>filter==="all"||(e.kind==="read"?"read":e.content.type)===filter).map(e=><li key={e.id} className="space-y-2 py-4"><div className="flex flex-wrap gap-x-3 text-xs text-company-muted"><span>v{e.version} · {label(e.kind==="read"?"read":e.content.type)}</span><span>{label(e.author.role)} → {label(e.recipient.role)}</span><time>{new Date(e.createdAt).toLocaleString(locale)}</time></div>{e.supersedes&&<p className="text-xs">{c.supersedes}: {e.supersedes.slice(0,8)}</p>}<p className="whitespace-pre-wrap break-words text-sm">{e.content.text}</p>{e.content.material&&<CcNotice tone="warning" title={c.signal}><p>{e.content.material.reason}</p><p>{c.signalHint}</p></CcNotice>}{e.content.expectedResponse&&<p className="text-sm"><strong>{c.expected}: </strong>{e.content.expectedResponse.instruction}{e.content.expectedResponse.dueAt&&` · ${new Date(e.content.expectedResponse.dueAt).toLocaleString(locale)}`}</p>}{e.kind==="message"&&<div className="flex flex-wrap gap-2">{mine(e.recipient)&&<><CcButton disabled={busy||dirty||!selected.canReply||selected.entries.some((r:any)=>r.kind==="read"&&r.replyTo===e.id)||agentActing(bindingFor("read",e))&&!matchingGrant(bindingFor("read",e))} onClick={()=>void send("read",e)}>{c.ack}</CcButton><CcButton disabled={busy||dirty||!selected.canReply} onClick={()=>{setReply({entry:e});setType("answer");requestAnimationFrame(()=>form.current?.scrollIntoView({block:"nearest"}));}}>{c.reply}</CcButton></>}{mine(e.author)&&<CcButton disabled={busy||dirty||!selected.canReply} onClick={()=>{setReply({entry:e,correcting:true});setText(e.content.text);setType(e.content.type);edit();}}>{c.correct}</CcButton>}</div>}</li>)}</ol>{selected.nextBefore&&<CcButton disabled={busy} onClick={()=>void load(selected.id,other,selected.nextBefore)}>{c.older}</CcButton>}
  </>}
  {(fresh||reply)&&<div ref={form} className="space-y-4 border-t border-company-border pt-4">
   {fresh&&<div className="grid gap-4 sm:grid-cols-3"><CcField label={c.linked}>{({id})=><CcSelect id={id} aria-label={c.linked} value={other} disabled={busy||dirty} onChange={e=>{setOther(e.target.value);setRecipient("");void load("",e.target.value);}}>{data.relatedTaskIds.map((id:string)=><option key={id} value={id}>{id===taskId?c.same:id.slice(0,8)}</option>)}</CcSelect>}</CcField><CcField label={c.sender}>{({id})=><CcSelect id={id} aria-label={c.sender} value={sender} onChange={e=>{setSender(e.target.value);edit();}}><option value="">{c.choose}</option>{senderChoices.map((p:any)=><option key={key(p)} value={key(p)}>{label(p.role)} · {p.principal.id.slice(0,8)}</option>)}</CcSelect>}</CcField><CcField label={c.recipient}>{({id})=><CcSelect id={id} aria-label={c.recipient} value={recipient} onChange={e=>{setRecipient(e.target.value);edit();}}><option value="">{c.choose}</option>{recipientChoices.map((p:any)=><option key={key(p)} value={key(p)}>{label(p.role)} · {p.principal.id.slice(0,8)}</option>)}</CcSelect>}</CcField></div>}
   <CcField label={c.type}>{({id})=><CcSelect id={id} aria-label={c.type} value={type} onChange={e=>{setType(e.target.value);edit();}}>{types.map(t=><option key={t} value={t}>{label(t)}</option>)}</CcSelect>}</CcField><CcField label={c.text}>{({id})=><textarea id={id} aria-label={c.text} className="textarea textarea-bordered w-full" rows={4} required minLength={3} maxLength={2000} value={text} onChange={e=>{setText(e.target.value);edit();}}/>}</CcField>
   <CcField label={c.expected}>{({id})=><CcSelect id={id} aria-label={c.expected} value={expected} onChange={e=>{setExpected(e.target.value);edit();}}><option value="">{c.optional}</option>{["answer","evidence_response","read"].map(t=><option key={t} value={t}>{label(t)}</option>)}</CcSelect>}</CcField>{expected&&<div className="grid gap-4 sm:grid-cols-2"><CcField label={c.instruction}>{({id})=><input id={id} aria-label={c.instruction} className="input input-bordered w-full" value={instruction} maxLength={2000} required minLength={3} onChange={e=>{setInstruction(e.target.value);edit();}}/>}</CcField><CcField label={c.due}>{({id})=><input id={id} aria-label={c.due} className="input input-bordered w-full" type="datetime-local" value={due} onChange={e=>{setDue(e.target.value);edit();}}/>}</CcField></div>}
   <label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={material||type==="constraint_notice"} disabled={type==="constraint_notice"} onChange={e=>{setMaterial(e.target.checked);edit();}}/>{c.material}</label>{(material||type==="constraint_notice")&&<CcField label={c.reason}>{({id})=><textarea id={id} aria-label={c.reason} className="textarea textarea-bordered w-full" required minLength={3} maxLength={2000} value={reason} onChange={e=>{setReason(e.target.value);edit();}}/>}</CcField>}
   <details><summary className="cursor-pointer py-2 text-sm font-semibold">{c.refs}</summary><div className="space-y-2">{data.summary.references.map((r:any)=><label className="flex gap-2 break-all text-xs" key={`${r.kind}:${r.id}`}><input type="checkbox" checked={refs.includes(`${r.kind}:${r.id}`)} disabled={refs.length>=8&&!refs.includes(`${r.kind}:${r.id}`)} onChange={e=>{setRefs(old=>e.target.checked?[...old,`${r.kind}:${r.id}`]:old.filter(k=>k!==`${r.kind}:${r.id}`));edit();}}/>{r.kind} · {r.id.slice(0,8)} · {r.revision.slice(0,8)}</label>)}</div></details>
   {!canWrite&&<CcNotice tone="warning" title={c.blocked}/>}<div className="flex gap-2"><CcButton type="submit" variant="primary" disabled={busy||!valid||!canWrite}>{fresh?c.send:c.reply}</CcButton>{reply&&<CcButton disabled={busy} onClick={reset}>{c.cancel}</CcButton>}</div>
  </div>}
  <section className="border-t border-company-border pt-4"><h3 className="font-semibold">{c.summary}</h3><p className="py-2 text-sm text-company-muted">{c.summaryHint}</p>{!data.summary.executionAvailable&&<p className="text-sm">{c.unavailable}</p>}<div className="grid gap-3 py-3 sm:grid-cols-2">{data.summary.references.filter((r:any)=>r.kind==="result"||r.kind==="test").map((r:any)=><article className="min-w-0 rounded-xl border border-company-border p-3 text-sm" key={`${r.kind}:${r.id}`}><h4 className="font-semibold">{r.kind==="result"?c.result:c.tests} · {r.taskId.slice(0,8)}</h4>{r.kind==="result"?<><code title={r.data.commit} className="block break-all py-2">Commit: {r.data.commit?.slice(0,12)}</code><p className="break-all">{c.branch}: {r.data.branch}</p><p>{c.tree}: {label(r.data.workingTree)}</p><p>{c.changes}: {r.data.changedPaths?.length??0}</p></>:<ul className="space-y-1 py-2">{(r.data.commands??[]).map((t:any,i:number)=><li className="break-words" key={i}><code>{t.command}</code> · {t.status??r.data.state} · {t.exitCode??"—"}</li>)}</ul>}</article>)}</div><p className="text-xs text-company-muted">{c.limited}</p><details><summary className="cursor-pointer py-2 text-sm">{c.details}</summary><ul className="divide-y divide-company-border">{data.summary.references.map((r:any)=><li key={`${r.kind}:${r.id}`} className="py-3"><p className="text-xs font-semibold">{r.kind} · {r.id.slice(0,8)} · {r.revision.slice(0,8)}</p><pre className="mt-2 whitespace-pre-wrap break-words text-xs">{JSON.stringify(r.data,null,2)}</pre></li>)}</ul></details></section>
  </>}{leave&&<CcNotice tone="warning" title={c.discard}><div className="flex gap-2"><CcButton onClick={()=>setLeave(false)}>{c.stay}</CcButton><CcButton onClick={onClose}>{c.leave}</CcButton></div></CcNotice>}</div>
 </CcRecordEditorModal>;
}
