import { useEffect, useRef, useState, type FormEvent } from "react";
import { api } from "../../api/client";
import { CcButton } from "../../components/cc-button";
import { CcField } from "../../components/cc-field";
import { CcSelect } from "../../components/cc-select";
import { CcNotice } from "../../components/cc-notice";
import { CcRecordEditorModal } from "../../components/cc-record-editor";
import { useLanguage } from "../../i18n/i18n";
import { TaskCapabilityModal } from "./task-capability";

const messages={
 pl:{handoffContent:"Treść przekazania",result:"Wynik wykonania",packet:"Przypięty pakiet",roles:"Aktualne role",current_source:"Aktualne źródła",title:"Przekazanie pracy",boundary:"Przyjęcie potwierdza odbiór tej wersji. Zgoda na review, wydanie i wykonanie wymaga osobnej decyzji.",close:"Zamknij",refresh:"Odśwież",loading:"Wczytywanie przekazań…",error:"Nie zapisano. Sprawdź aktualny kontekst i spróbuj ponownie.",saved:"Zapisano w historii przekazania.",source:"1. Źródło i odbiorca",content:"2. Kompletność",preview:"3. Podgląd",sender:"Rola nadawcy",recipient:"Odbiorca i rola",choose:"Wybierz",next:"Dalej",back:"Wstecz",create:"Zapisz przekazanie",history:"Historia wersji",empty:"Brak przekazań.",missing:"Brak aktualnego wyniku, checkpointu, ról lub dowodów. Uzupełnij kontekst zadania.",admission:"Wymagane dopuszczenie operacji przekazania w procedurze i ocenie ryzyka.",incomplete:"Uzupełnij wymagane pola",summary:"Wynik",currentState:"Aktualny stan",explanation:"Aktualne decyzje i mandaty — objaśnienie",areas:"Zmienione obszary (po jednym w wierszu)",assessment:"Ocena zapisanych testów",knownLimitations:"Znane ograniczenia",residualRisks:"Ryzyko resztkowe",reproduce:"Jak odtworzyć",continue:"Jak kontynuować",rollback:"Jak wycofać",instruction:"Oczekiwana czynność odbiorcy",kind:"Rodzaj oczekiwanej czynności",inspect:"Sprawdzenie materiału",review:"Przegląd",decide:"Podjęcie osobnej decyzji",accept:"Przyjmij tę wersję",reject:"Odrzuć tę wersję",reason:"Uzasadnienie odrzucenia",code:"Kod odrzucenia",sections:"Brakujące lub sprzeczne sekcje",pending:"Oczekuje na odbiór",accepted:"Przyjęto",rejected:"Odrzucono",stale:"Nieaktualne źródło",supersede:"Przygotuj poprawioną wersję",supersedes:"Zastępuje wersję",details:"Przypięte źródła i dowody",reported:"Commit pochodzi z odczytu hosta po pracy. Stan dirty oznacza zmiany poza commitem. Testy są zapisanym raportem; API nie uruchamia ich ponownie.",grants:"Granty agenta",older:"Starsze wersje",discard:"Odrzucić niezapisane zmiany?",stay:"Zostań",leave:"Odrzuć zmiany",missing_section:"Brak sekcji",conflicting_section:"Sprzeczna sekcja",insufficient_evidence:"Niewystarczający dowód",unclear_action:"Niejasna czynność",outcome:"Wynik i stan",context:"Kontekst",decisions:"Decyzje i mandaty",changes:"Zmiany",tests:"Testy i dowody",limits:"Ograniczenia",continuation:"Kontynuacja i wycofanie",expectedAction:"Oczekiwana czynność"},
 en:{handoffContent:"Handoff content",result:"Execution result",packet:"Pinned packet",roles:"Current roles",current_source:"Current sources",title:"Work handoff",boundary:"Acceptance acknowledges receipt of this version. Review, release and execution authorization require a separate decision.",close:"Close",refresh:"Refresh",loading:"Loading handoffs…",error:"Not saved. Check the current context and try again.",saved:"Recorded in handoff history.",source:"1. Source and recipient",content:"2. Completeness",preview:"3. Preview",sender:"Sender role",recipient:"Recipient and role",choose:"Choose",next:"Next",back:"Back",create:"Record handoff",history:"Version history",empty:"No handoffs yet.",missing:"A current result, checkpoint, roles or evidence is missing. Complete the task context.",admission:"The procedure and risk assessment must admit the handoff operation.",incomplete:"Complete the required fields",summary:"Outcome",currentState:"Current state",explanation:"Current decisions and mandates — explanation",areas:"Changed areas (one per line)",assessment:"Assessment of recorded tests",knownLimitations:"Known limitations",residualRisks:"Residual risks",reproduce:"How to reproduce",continue:"How to continue",rollback:"How to roll back",instruction:"Expected recipient action",kind:"Expected action type",inspect:"Inspect material",review:"Review",decide:"Make a separate decision",accept:"Accept this version",reject:"Reject this version",reason:"Rejection reason",code:"Rejection code",sections:"Missing or conflicting sections",pending:"Awaiting receipt",accepted:"Accepted",rejected:"Rejected",stale:"Stale source",supersede:"Prepare revised version",supersedes:"Supersedes version",details:"Pinned sources and evidence",reported:"The host observed the commit after work. A dirty tree contains changes outside that commit. Tests are recorded reports; the API does not rerun them.",grants:"Agent grants",older:"Older versions",discard:"Discard unsaved changes?",stay:"Stay",leave:"Discard changes",missing_section:"Missing section",conflicting_section:"Conflicting section",insufficient_evidence:"Insufficient evidence",unclear_action:"Unclear action",outcome:"Outcome and state",context:"Context",decisions:"Decisions and mandates",changes:"Changes",tests:"Tests and evidence",limits:"Limitations",continuation:"Continuation and rollback",expectedAction:"Expected action"}
};
const fields=["summary","currentState","explanation","areas","assessment","knownLimitations","residualRisks","reproduce","continue","rollback","instruction"] as const;
const sectionNames=["outcome","context","decisions","changes","tests","limits","continuation","expectedAction"] as const;
const initial=Object.fromEntries(fields.map(k=>[k,""])) as Record<typeof fields[number],string>;
const roles={pl:{requester:"Zlecający",accountableManager:"Odpowiedzialny manager",executor:"Wykonawca",verifier:"Weryfikator",releaser:"Zatwierdzający wydanie"},en:{requester:"Requester",accountableManager:"Accountable manager",executor:"Executor",verifier:"Verifier",releaser:"Release authority"}};

export function TaskHandoffModal({taskId,onClose}:{taskId:string;onClose:()=>void}) {
 const {locale}=useLanguage(),language=locale==="pl"?"pl":"en",c=messages[language];
 const roleLabel=(role:string)=>roles[language][role as keyof typeof roles.en]??role;
 const [data,setData]=useState<any>(null),[busy,setBusy]=useState(true),[error,setError]=useState(false),[saved,setSaved]=useState(false);
 const [draft,setDraft]=useState(initial),[sender,setSender]=useState(""),[recipient,setRecipient]=useState(""),[kind,setKind]=useState("inspect"),[step,setStep]=useState(0),[supersedes,setSupersedes]=useState<any>(null);
 const [rejecting,setRejecting]=useState<any>(null),[reason,setReason]=useState(""),[code,setCode]=useState("missing_section"),[sections,setSections]=useState<string[]>([]);
 const [dirty,setDirty]=useState(false),[leave,setLeave]=useState(false),[grants,setGrants]=useState(false);
 const mounted=useRef(true),receipt=useRef<{signature:string;id:string}|null>(null),notice=useRef<HTMLDivElement>(null);
 const root=`/v1/agent-runtime/tasks/${taskId}/handoffs`;
 async function load(cursor?:string){setBusy(true);setError(false);try{const r=await api<{data:any}>(root+(cursor?`?cursor=${cursor}`:""));if(mounted.current){setData((old:any)=>cursor&&old?{...r.data,history:[...old.history,...r.data.history]}:r.data);if(!cursor){setSender(r.data.senderRoles[0]?.role??"");}}}catch{if(mounted.current)setError(true);}finally{if(mounted.current)setBusy(false);}}
 useEffect(()=>{mounted.current=true;void load();return()=>{mounted.current=false;};},[taskId]);
 const recipientChoice=data?.recipients.find((r:any)=>r.role===recipient);
 const missing=fields.filter(k=>draft[k].trim().length<3 || k==="areas" && (draft.areas.split("\n").filter(s=>s.trim()).length>30 || draft.areas.split("\n").filter(s=>s.trim()).some(s=>s.trim().length<3)));
 const content={outcome:{summary:draft.summary,currentState:draft.currentState},decisions:{explanation:draft.explanation},changes:{areas:draft.areas.split("\n").map(s=>s.trim()).filter(Boolean)},tests:{assessment:draft.assessment},limits:{knownLimitations:draft.knownLimitations,residualRisks:draft.residualRisks},continuation:{reproduce:draft.reproduce,continue:draft.continue,rollback:draft.rollback},expectedAction:{kind,instruction:draft.instruction}};
 function edit(key:typeof fields[number],value:string){setDraft(d=>({...d,[key]:value}));setDirty(true);setSaved(false);}
 function close(){if(!busy)dirty?setLeave(true):onClose();}
 async function send(action:"create"|"accept"|"reject",h?:any){
  if(busy||!data)return;
  const input=action==="create"?{expectedVersion:data.expectedVersion,sourceVersion:data.sourceVersion,senderRole:sender,recipientRole:recipient,recipient:recipientChoice?.principal,supersedes:supersedes?.id??null,content}:
   {expectedVersion:data.expectedVersion,handoffId:h.id,handoffVersion:h.version,decision:action,...(action==="reject"?{reason,code,sections}:{})};
  const signature=JSON.stringify({action,input});if(receipt.current?.signature!==signature)receipt.current={signature,id:crypto.randomUUID()};
  setBusy(true);setError(false);setSaved(false);
  try{await api(root+(action==="create"?"":`/actions/${action}`),{method:"POST",body:JSON.stringify({...input,requestId:receipt.current.id})});if(!mounted.current)return;receipt.current=null;setDirty(false);setDraft(initial);setRejecting(null);setSupersedes(null);setStep(0);await load();setSaved(true);}catch{if(mounted.current){setError(true);requestAnimationFrame(()=>notice.current?.focus());}}finally{if(mounted.current)setBusy(false);}
 }
 function submit(e:FormEvent){e.preventDefault();if(rejecting){if(reason.trim().length>=3&&sections.length)void send("reject",rejecting);return;}if(step<2)setStep(step+1);else if(!missing.length&&recipientChoice&&sender)void send("create");}
 function revise(h:any){const b=h.content;setDraft({summary:b.outcome.summary,currentState:b.outcome.currentState,explanation:b.decisions.explanation,areas:b.changes.areas.join("\n"),assessment:b.tests.assessment,...b.limits,...b.continuation,instruction:b.expectedAction.instruction});setKind(b.expectedAction.kind);setSender(h.senderRole);setRecipient(h.recipientRole);setSupersedes(h);setStep(0);setDirty(true);}
 const sourceView=(source:any)=><details><summary className="cursor-pointer py-2 font-semibold">{c.details}</summary><p className="py-2 text-sm">{c.reported}</p><dl className="grid gap-3 text-sm sm:grid-cols-2">{["workspaceId","taskId","applicationId","executionId","attempt","materialVersion","packetRevision","contextRevision","compositionSeal","riskAssessmentId","riskAdmissionSeal","baseCommit","commit","branch","workingTree"].map(k=><div key={k}><dt className="text-company-muted">{k}</dt><dd className="break-all font-mono">{source?.[k]??"—"}</dd></div>)}</dl><ul className="py-3 text-sm">{source?.changedPaths?.map((p:string)=><li className="break-all" key={p}>{p}</li>)}</ul><pre className="whitespace-pre-wrap break-words text-xs">{JSON.stringify({resultRevision:source?.resultRevision,tests:source?.tests,evidence:source?.evidence,mandates:source?.mandates,decision:source?.reviewDecision},null,2)}</pre></details>;
 if(grants)return <TaskCapabilityModal taskId={taskId} onClose={()=>{setGrants(false);void load();}}/>;
 if(leave)return <CcRecordEditorModal titleId="handoff-discard" eyebrow={c.title} title={c.discard} closeLabel={c.stay} onClose={()=>setLeave(false)} onSubmit={e=>{e.preventDefault();onClose();}} actions={<><CcButton onClick={()=>setLeave(false)}>{c.stay}</CcButton><CcButton type="submit" variant="warning">{c.leave}</CcButton></>}>{c.boundary}</CcRecordEditorModal>;
 return <CcRecordEditorModal titleId="handoff-title" title={c.title} eyebrow={data?.task.title} description={c.boundary} closeLabel={c.close} onClose={close} onSubmit={submit} maxWidthClassName="max-w-5xl" actions={<><CcButton variant="ghost" disabled={busy} onClick={close}>{c.close}</CcButton>{rejecting?<CcButton type="submit" variant="warning" disabled={busy||reason.trim().length<3||!sections.length}>{c.reject}</CcButton>:data?.canCreate?<><CcButton disabled={busy||step===0} onClick={()=>setStep(step-1)}>{c.back}</CcButton><CcButton type="submit" variant="primary" disabled={busy||!sender||!recipientChoice||step>0&&missing.length>0}>{step===2?c.create:c.next}</CcButton></>:null}</>}>
  <div className="grid min-w-0 gap-5 [overflow-wrap:anywhere]">
   <div ref={notice} tabIndex={-1}>{error?<CcNotice tone="error" title={c.error} live/>:saved?<CcNotice tone="success" title={c.saved} live/>:null}</div>
   <div className="flex flex-wrap justify-end gap-2">{data?.canManageGrants?<CcButton disabled={busy||dirty} onClick={()=>setGrants(true)}>{c.grants}</CcButton>:null}<CcButton disabled={busy||dirty} onClick={()=>void load()}>{c.refresh}</CcButton></div>
   {!data&&busy?<CcNotice tone="loading" title={c.loading}/>:null}
   {data?.missing.length?<CcNotice tone="warning" title={c.missing}><p>{data.missing.map((key:string)=>c[key as "current_source"]??key).join(" · ")}</p></CcNotice>:data&&!data.canCreate&&data.senderRoles.length?<CcNotice tone="warning" title={c.admission}/>:null}
   {data?.canCreate&&!rejecting?<section className="grid gap-4"><ol className="flex flex-wrap gap-4 text-sm">{[c.source,c.content,c.preview].map((s,i)=><li key={s} aria-current={step===i?"step":undefined} className={step===i?"font-bold":"text-company-muted"}>{s}</li>)}</ol>
    {supersedes?<p>{c.supersedes}: {supersedes.version}</p>:null}
    {step===0?<><div className="grid gap-4 sm:grid-cols-2"><CcField label={c.sender} required>{({id})=><CcSelect id={id} required value={sender} onChange={e=>{setSender(e.target.value);setDirty(true);}}>{data.senderRoles.map((r:any)=><option key={r.role} value={r.role}>{r.label??roleLabel(r.role)} · {roleLabel(r.role)} · {r.principal.id}</option>)}</CcSelect>}</CcField><CcField label={c.recipient} required>{({id})=><CcSelect id={id} required value={recipient} onChange={e=>{setRecipient(e.target.value);setDirty(true);}}><option value="">{c.choose}</option>{data.recipients.map((r:any)=><option key={r.role} value={r.role}>{r.label??roleLabel(r.role)} · {roleLabel(r.role)} · {r.principal.id}</option>)}</CcSelect>}</CcField></div>{sourceView(data.source)}</>:null}
    {step===1?<><p role="status">{c.incomplete}: {missing.length?missing.map(k=>c[k]).join(" · "):"0"}</p><div className="grid gap-4 sm:grid-cols-2">{fields.map(k=><CcField key={k} label={c[k]} required>{({id})=><textarea id={id} className="textarea textarea-bordered min-h-24 w-full" required minLength={3} maxLength={2000} value={draft[k]} onChange={e=>edit(k,e.target.value)}/>}</CcField>)}</div><CcField label={c.kind}>{({id})=><CcSelect id={id} value={kind} onChange={e=>{setKind(e.target.value);setDirty(true);}}>{["inspect","review","continue","decide"].map(k=><option key={k} value={k}>{c[k as "inspect"]}</option>)}</CcSelect>}</CcField></>:null}
    {step===2?<><p>{roleLabel(sender)} → {roleLabel(recipient)} · {recipientChoice?.principal.id}</p>{fields.map(k=><div key={k}><h3 className="font-bold">{c[k]}</h3><p className="whitespace-pre-wrap">{draft[k]}</p></div>)}{sourceView(data.source)}</>:null}
   </section>:null}
   {rejecting?<section className="grid gap-4"><h3 className="font-bold">{c.reject} · {rejecting.version}</h3><CcField label={c.code}>{({id})=><CcSelect id={id} value={code} onChange={e=>{setCode(e.target.value);setDirty(true);}}>{["missing_section","conflicting_section","insufficient_evidence","unclear_action"].map(k=><option key={k} value={k}>{c[k as "missing_section"]}</option>)}</CcSelect>}</CcField><CcField label={c.reason} required>{({id})=><textarea id={id} className="textarea textarea-bordered w-full" required minLength={3} maxLength={2000} value={reason} onChange={e=>{setReason(e.target.value);setDirty(true);}}/>}</CcField><fieldset className="grid gap-2"><legend className="mb-2 font-semibold">{c.sections}</legend>{sectionNames.map(k=><label key={k} className="flex gap-3"><input type="checkbox" className="checkbox" checked={sections.includes(k)} onChange={e=>{setSections(a=>e.target.checked?[...a,k]:a.filter(x=>x!==k));setDirty(true);}}/>{c[k]}</label>)}</fieldset></section>:null}
   <section className="grid gap-4 border-t border-base-300 pt-5"><h3 className="font-bold">{c.history}</h3>{data&&!data.history.length?<p>{c.empty}</p>:null}{data?.history.map((h:any)=><article key={h.id} className="grid gap-3 border-b border-base-300 pb-5 text-sm"><div className="flex flex-wrap justify-between gap-2"><strong>v{h.version} · {h.decision?h.decision.decision==="accept"?c.accepted:c.rejected:h.current?c.pending:c.stale}</strong><time>{new Date(h.createdAt).toLocaleString(locale)}</time></div><p>{roleLabel(h.senderRole)} · {h.sender.id} → {roleLabel(h.recipientRole)} · {h.recipient.id}</p><p>{h.content.outcome.summary}</p><p><strong>{c.expectedAction}: </strong>{h.content.expectedAction.instruction}</p>{h.supersedes?<p>{c.supersedes}: {h.supersedes}</p>:null}
    <details><summary className="cursor-pointer py-2">{c.handoffContent}</summary>{Object.entries(h.content).map(([k,value])=><div className="py-2" key={k}><strong>{c[k as "outcome"]}</strong><p className="whitespace-pre-wrap">{Object.values(value as object).map(v=>Array.isArray(v)?v.join("\n"):String(v)).join("\n")}</p></div>)}</details>{sourceView(h.source)}
    {h.decision?<p>{h.decision.decision==="reject"?`${c[h.decision.detail.code as "missing_section"]}: ${h.decision.detail.reason} · ${h.decision.detail.sections.map((k:string)=>c[k as "context"]).join(", ")}`:c.boundary}</p>:null}
    <div className="flex flex-wrap gap-2">{h.canAccept&&!rejecting?<CcButton disabled={busy||dirty} onClick={()=>void send("accept",h)}>{c.accept}</CcButton>:null}{h.canReject&&!rejecting?<CcButton disabled={busy||dirty} onClick={()=>{setRejecting(h);setReason("");setSections([]);}}>{c.reject}</CcButton>:null}{h.decision?.decision==="reject"&&data.canCreate&&data.senderRoles.some((r:any)=>r.role===h.senderRole)&&!data.history.some((r:any)=>r.supersedes===h.id)?<CcButton disabled={busy||dirty} onClick={()=>revise(h)}>{c.supersede}</CcButton>:null}</div>
   </article>)}{data?.nextCursor?<CcButton disabled={busy||dirty} onClick={()=>void load(data.nextCursor)}>{c.older}</CcButton>:null}</section>
  </div>
 </CcRecordEditorModal>;
}
