import { TaskRiskAdmissionModal } from "./task-risk-admission";
import { DecisionDeferralModal } from "./decision-governance";
import { DecisionAuthorityDetails,DecisionAuthorityFields } from "./decision-authority";
import { useEffect,useRef,useState } from "react";
import { api,AppApiError } from "../../api/client";
import { CcConfirmDialog } from "../../components/cc-confirm-dialog";
import { CcButton } from "../../components/cc-button";
import { CcField } from "../../components/cc-field";
import { CcNotice } from "../../components/cc-notice";
import { CcSelect } from "../../components/cc-select";
import { CcRecordEditorModal,CcRecordEditorSection } from "../../components/cc-record-editor";
import { useLanguage } from "../../i18n/i18n";
export function TaskInterviewModal({taskId,onClose}:{taskId:string;onClose:()=>void}){
 const {locale}=useLanguage(),pl=locale==="pl";const [data,setData]=useState<any>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[selected,setSelected]=useState(""),[creating,setCreating]=useState(false),[draft,setDraft]=useState<any>({decisionClass:"task_scope",questions:[{field:"decision",type:"decision",question:"",requiresHuman:true,options:[]}]}),[answers,setAnswers]=useState<Record<string,string>>({}),[reason,setReason]=useState("");
 const [riskOpen,setRiskOpen]=useState(false);
 const [eventDeferral,setEventDeferral]=useState(false);
 const [leave,setLeave]=useState(false);const close=()=>{if(creating||reason||Object.keys(answers).length)setLeave(true);else onClose();};
 const request=useRef(crypto.randomUUID()),loadSequence=useRef(0);
 const labels:Record<string,string[]>= {pending:["Oczekuje","Pending"],proposed:["Propozycja","Proposed"],deferred:["Odłożone","Deferred"],accepted:["Zaakceptowane","Accepted"],task_scope:["Zakres zadania","Task scope"],product_direction:["Kierunek produktu","Product direction"],money:["Pieniądze","Money"],legal:["Kwestie prawne","Legal"],critical_risk:["Ryzyko krytyczne","Critical risk"],mandate:["Zmiana mandatu","Mandate change"]};
 labels.ordinary_domain=["Zwykła decyzja dziedzinowa","Ordinary domain decision"];labels.mandate_change=labels.mandate;
 const label=(v:string)=>labels[v]?.[pl?0:1]||v;
 async function load(caseId=""){const sequence=++loadSequence.current;try{const result=await api<{data:any}>(`/v1/agent-runtime/tasks/${taskId}/interviews${caseId?`?caseId=${caseId}`:""}`);if(sequence===loadSequence.current){setData(result.data);setError("");}}catch(e){setError(e instanceof AppApiError?e.code:"request_failed");}}
 useEffect(()=>{void load();},[taskId]);
 const cases=data?.cases?.filter((c:any)=>!c.superseded)??[],c=cases.find((c:any)=>c.id===selected)??cases.find((c:any)=>c.status!=="accepted")??cases[0];
 async function send(action:string){setBusy(true);setError("");try{
  let body:any={requestId:request.current,expectedVersion:data.expectedVersion};
  if(action==="publish"){
   const ref=data.sources.find((s:any)=>s.id===draft.sourceId);
   body={...body,...(draft.supersedesId?{supersedesId:draft.supersedesId,revisionReason:draft.revisionReason}:{}),block:{...Object.fromEntries(["topic","unknownKey","missing","impact","context","recommendation","consequences","scope","deferralEffect","decisionClass"].map(k=>[k,draft[k]])),...(draft.decisionClass==="ordinary_domain"?{authority:{...draft.authority,domain:"ordinary_domain",entities:[{type:"task",id:taskId}]}}:{}),material:true,principalId:draft.principalId||data.ownerIds[0],questions:draft.questions.map((q:any)=>({...q,options:q.options.map((o:string)=>o.trim()).filter(Boolean)})),dependencies:[{taskId,blockedPart:draft.blockedPart}],gathering:{status:"completed",checkedSources:ref?[{id:ref.id,revision:ref.revision,findings:draft.findings}]:[],remainingHumanDecision:draft.remainingHumanDecision}}};
  }else body={...body,caseId:c.id,action,reason,...(action==="answer"?{answers:c.body.questions.map((q:any)=>({field:q.field,value:answers[q.field]||""}))}:{})};
  await api(`/v1/agent-runtime/tasks/${taskId}/interviews${action==="publish"?"":"/actions/respond"}`,{method:"POST",body:JSON.stringify(body)});
  request.current=crypto.randomUUID();setCreating(false);setSelected("");setAnswers({});setReason("");await load();
 }catch(e){setError(e instanceof AppApiError?e.code:"request_failed");}finally{setBusy(false);}}
 const field=(key:string,label:string)=><CcField key={key} label={label} required>{({id})=><textarea id={id} className="textarea textarea-bordered w-full" value={draft[key]||""} onChange={e=>setDraft({...draft,[key]:e.target.value})}/>}</CcField>;
 if(riskOpen)return <TaskRiskAdmissionModal taskId={taskId} initialOperation="decision_supersede" onClose={()=>{setRiskOpen(false);void load(c?.id);}}/>;
 if(eventDeferral&&c)return <DecisionDeferralModal targetType="interview" targetId={c.id} review={c.status==="deferred"} onClose={()=>{setEventDeferral(false);void load(c.id);}}/>;
 return <><CcRecordEditorModal titleId="task-interview" title={pl?"Pytania wymagające decyzji":"Questions requiring a decision"} description={pl?"Odpowiedź zapisuje propozycję. Akceptacja jest osobnym krokiem. Odłożenie zachowuje blokadę zależnej pracy.":"An answer records a proposal. Acceptance is a separate step. Deferral keeps dependent work blocked."} onClose={close} actions={<><CcButton onClick={close} variant="ghost">{pl?"Zamknij":"Close"}</CcButton><CcButton disabled={busy} onClick={()=>void load()} variant="outline">{pl?"Odśwież":"Refresh"}</CcButton></>}>
 {error?<CcNotice tone="error" title={pl?"Nie zapisano lub nie wczytano danych. Odśwież kontekst i sprawdź uprawnienia oraz dowody.":"Could not save or load. Refresh context and check authority and evidence."}/>:null}{!data?<CcNotice title={pl?"Wczytywanie pytań":"Loading questions"}/>:<>
 <p className="text-sm text-company-muted">{data.blocking?(pl?"Zależna praca czeka na decyzję. Niezależne zbieranie faktów może trwać.":"Dependent work awaits a decision. Independent fact gathering can continue."):(pl?"Brak nierozstrzygniętych pytań blokujących to zadanie.":"No unresolved questions block this task.")}</p>
 {!creating?<><div className="flex flex-wrap gap-3"><CcSelect aria-label={pl?"Wybierz blok pytań":"Select question block"} value={c?.id||""} onChange={e=>{setSelected(e.target.value);void load(e.target.value);setAnswers({});request.current=crypto.randomUUID();}}>{cases.map((x:any)=><option key={x.id} value={x.id}>{x.body.topic} · {label(x.status)}</option>)}</CcSelect><CcButton disabled={!data.canPrepare} onClick={()=>setCreating(true)}>{pl?"Przygotuj pytania":"Prepare questions"}</CcButton></div>
 {c?.body?.questions?<CcRecordEditorSection title={c.body.topic}>
 <CcButton variant="outline" disabled={busy||!!reason||Object.keys(answers).length>0} onClick={()=>setRiskOpen(true)}>{pl?"Dowody dopuszczenia decyzji":"Decision admission evidence"}</CcButton><DecisionAuthorityDetails authority={c.status==="accepted"?(c.recordedAuthority??c.authority):c.authority} catalog={data.authorityCatalog}/><dl className="grid gap-4 md:grid-cols-2">{[[pl?"Brakująca decyzja":"Missing decision",c.body.missing],[pl?"Rekomendacja":"Recommendation",c.body.recommendation],[pl?"Konsekwencje":"Consequences",c.body.consequences],[pl?"Skutek odłożenia":"Deferral effect",c.body.deferralEffect],[pl?"Kontekst":"Context",c.body.context],[pl?"Zakres":"Scope",c.body.scope]].map(([k,v])=><div key={k}><dt className="text-sm text-company-muted">{k}</dt><dd className="whitespace-pre-wrap">{v}</dd></div>)}</dl>
 <div className="my-4"><p>{label(c.status)} · {pl?"Wersja":"Version"} {c.version}</p><CcButton variant="outline" disabled={!data.ownerIds.includes(data.principalId)} onClick={()=>{const source=c.body.gathering.checkedSources[0];setDraft({...c.body,supersedesId:c.id,sourceId:source.id,findings:source.findings,remainingHumanDecision:c.body.gathering.remainingHumanDecision,blockedPart:c.body.dependencies[0].blockedPart});setCreating(true);request.current=crypto.randomUUID();}}>{pl?"Przygotuj korektę bloku":"Revise question block"}</CcButton></div>
 <CcButton variant="outline" disabled={(c.status!=="deferred"&&!c.canRespond)||c.status==="accepted"||c.authority?.status==="delegated"} onClick={()=>setEventDeferral(true)}>{c.status==="deferred"?(pl?"Sprawdź warunek powrotu":"Review reopening condition"):(pl?"Odrocz do zdarzenia":"Defer until an event")}</CcButton>
 <p className="my-4">{c.body.dependencies.map((d:any)=>d.blockedPart).join(" · ")}</p>
 <ul className="list-disc pl-5">{c.body.gathering.checkedSources.map((s:any)=><li key={s.id}>{data.sources.find((r:any)=>r.id===s.id)?.title||s.id}: {s.findings}</li>)}</ul>
 {c.body.questions.map((q:any)=><CcField key={q.field} label={q.question}>{({id})=><><p className="text-sm text-company-muted">{q.options.join(" / ")}</p><textarea id={id} disabled={!c.canRespond||c.status==="accepted"||c.status==="proposed"} className="textarea textarea-bordered w-full" value={answers[q.field]??c.entries.find((e:any)=>e.action==="answer")?.body.answers?.find((a:any)=>a.field===q.field)?.value??""} onChange={e=>setAnswers({...answers,[q.field]:e.target.value})}/></>}</CcField>)}
 {c.canRespond&&c.status!=="accepted"?<><CcField label={pl?"Uzasadnienie":"Reason"}>{({id})=><textarea id={id} className="textarea textarea-bordered w-full" value={reason} onChange={e=>setReason(e.target.value)}/>}</CcField><div className="mt-4 flex flex-wrap gap-3"><CcButton disabled={busy||reason.trim().length<3} variant="primary" onClick={()=>void send(c.status==="proposed"?"accept":"answer")}>{c.status==="proposed"?(pl?"Akceptuj propozycję":"Accept proposal"):(pl?"Odpowiedz":"Respond")}</CcButton><CcButton disabled={busy||reason.trim().length<3||c.status==="deferred"} onClick={()=>void send("defer")} variant="outline">{pl?"Odłóż":"Defer"}</CcButton></div></>:<CcNotice title={!c.current?(pl?"Kontekst zmienił się — potrzebna nowa wersja pytań.":"Context changed — a revised block is required."):(pl?"Historia decyzji":"Decision history")}/>}
 <ol className="mt-5 space-y-2 text-sm text-company-muted">{c.entries.map((e:any)=><li key={e.id}>{e.action==="answer"?(pl?"Odpowiedź → propozycja":"Answer → proposal"):e.action==="defer"?(pl?"Odłożenie":"Deferral"):(pl?"Akceptacja":"Acceptance")}: {e.body.reason}</li>)}</ol>
 </CcRecordEditorSection>:<p>{pl?"Nie ma jeszcze pytań wymagających odpowiedzi.":"There are no questions awaiting an answer."}</p>}</>:<CcRecordEditorSection title={pl?"Jeden temat, do trzech pytań":"One topic, up to three questions"}>
 {draft.supersedesId?field("revisionReason",pl?"Powód nowej wersji":"Reason for revision"):null}<div className="grid gap-4 md:grid-cols-2">{[["topic","Temat","Topic"],["unknownKey","Stały klucz brakującej decyzji","Stable decision key"],["missing","Brakujący fakt lub decyzja","Missing fact or decision"],["impact","Wpływ na wykonanie","Execution impact"],["blockedPart","Zablokowana część zadania","Blocked task portion"],["context","Kontekst","Context"],["recommendation","Rekomendacja","Recommendation"],["consequences","Konsekwencje","Consequences"],["scope","Zakres","Scope"],["deferralEffect","Skutek odłożenia","Deferral effect"],["findings","Co ustalono w źródle","Source findings"],["remainingHumanDecision","Co wymaga decyzji człowieka","Remaining human decision"]].map(([k,p,e])=>field(k,pl?p:e))}
 <CcField label={draft.decisionClass==="ordinary_domain"?(pl?"Uprawniony decydent":"Authorized decision maker"):(pl?"Właściciel firmy":"Workspace owner")}>{({id})=><CcSelect id={id} value={draft.principalId||data.ownerIds[0]} onChange={e=>setDraft({...draft,principalId:e.target.value})}>{(draft.decisionClass==="ordinary_domain"?(data.authorityCatalog?.workforce??[]).filter((worker:any)=>worker.active&&worker.principal?.kind==="user").map((worker:any)=>worker.principal.id):data.ownerIds).map((owner:string)=><option key={owner} value={owner}>{data.authorityCatalog?.workforce?.find((worker:any)=>worker.principal?.id===owner)?.name ?? (owner===data.principalId?(pl?"Ty":"You"):owner)}</option>)}</CcSelect>}</CcField>
 <CcField label={pl?"Sprawdzone źródło":"Checked source"}>{({id})=><CcSelect id={id} value={draft.sourceId||""} onChange={e=>setDraft({...draft,sourceId:e.target.value})}><option value="">—</option>{data.sources.map((r:any)=><option key={r.id} value={r.id}>{r.title}</option>)}</CcSelect>}</CcField>
 <CcField label={pl?"Klasa decyzji":"Decision class"}>{({id})=><CcSelect id={id} value={draft.decisionClass} onChange={e=>setDraft({...draft,decisionClass:e.target.value})}>{["task_scope","product_direction","money","legal","critical_risk","mandate_change","ordinary_domain"].map(k=><option key={k} value={k}>{label(k)}</option>)}</CcSelect>}</CcField></div>
 {draft.decisionClass==="ordinary_domain"?<DecisionAuthorityFields value={draft.authority??{domain:"ordinary_domain",departmentKey:"",requesterId:"",recipientId:""}} onChange={authority=>setDraft({...draft,authority,decisionClass:authority.domain})} catalog={data.authorityCatalog}/>:null}{draft.questions.map((q:any,i:number)=><CcField key={i} label={`${pl?"Pytanie":"Question"} ${i+1}`}>{({id})=><textarea id={id} className="textarea textarea-bordered my-2 w-full" value={q.question} onChange={e=>setDraft({...draft,questions:draft.questions.map((x:any,n:number)=>n===i?{...x,question:e.target.value}:x)})}/>}</CcField>)}
 {draft.questions.map((q:any,i:number)=><div key={i} className="my-3 grid gap-3 md:grid-cols-2"><CcField label={`${pl?"Typ pytania":"Question type"} ${i+1}`}>{({id})=><CcSelect id={id} value={q.type} onChange={e=>setDraft({...draft,questions:draft.questions.map((x:any,n:number)=>n===i?{...x,type:e.target.value}:x)})}>{[["fact","Fakt","Fact"],["choice","Wybór","Choice"],["decision","Decyzja","Decision"]].map(([k,p,e])=><option key={k} value={k}>{pl?p:e}</option>)}</CcSelect>}</CcField><CcField label={`${pl?"Opcje (po jednej na wiersz)":"Options (one per line)"} ${i+1}`}>{({id})=><textarea id={id} className="textarea textarea-bordered w-full" value={q.options.join("\n")} onChange={e=>setDraft({...draft,questions:draft.questions.map((x:any,n:number)=>n===i?{...x,options:e.target.value.split("\n")}:x)})}/>}</CcField></div>)}
 <div className="mt-4 flex flex-wrap gap-3"><CcButton disabled={draft.questions.length>=3} onClick={()=>setDraft({...draft,questions:[...draft.questions,{field:`decision_${draft.questions.length+1}`,type:"decision",question:"",requiresHuman:true,options:[]}]})}>{pl?"Dodaj pytanie":"Add question"}</CcButton><CcButton disabled={busy} onClick={()=>void send("publish")} variant="primary">{pl?"Opublikuj blok pytań":"Publish question block"}</CcButton><CcButton onClick={()=>setCreating(false)} variant="ghost">{pl?"Anuluj":"Cancel"}</CcButton></div>
 </CcRecordEditorSection>}
 </>}</CcRecordEditorModal>{leave?<CcConfirmDialog title={pl?"Odrzucić niezapisane zmiany?":"Discard unsaved changes?"} description={pl?"Niezapisane odpowiedzi pozostaną poza rejestrem decyzji.":"Unsaved answers will not enter the decision register."} confirmLabel={pl?"Odrzuć":"Discard"} onConfirm={onClose} onCancel={()=>setLeave(false)}/>:null}</>;
}
