import test from 'node:test';import assert from 'node:assert/strict';import path from 'node:path';import {randomUUID}from'node:crypto';
import {releaseDigest,releaseComposeConfigAbsenceEvidenceError,releaseOutcomeError,releaseFailedClosureError,releasePublishedGitBasis,releaseHasPublishedGitBasis,createReleaseSchema,releaseIntentError,releaseApprovalError}from'../modules/agent-runtime/governed-release-contract';
const {fixture,hash}=require(path.resolve(__dirname,'../../scripts/fixtures/release-compose-contract.cjs'));const shared=require(path.resolve(__dirname,'../../scripts/lib/agent-host-release-contract.cjs'));
export function configAbsenceFixture(){const f=fixture(),s:any=f.s,releaseId=randomUUID(),hostId=randomUUID(),opId=randomUUID(),since='2026-10-04T12:02:00.000Z';
 Object.assign(s,{taskId:randomUUID(),applicationId:randomUUID(),hostId,releaserAgentId:randomUUID(),releaserCredentialId:randomUUID(),releaseExecutionId:randomUUID(),reviewId:randomUUID(),materialVersion:hash('8'),credentialVersion:1,releaserRevision:since,expiresAt:'2026-10-04T12:40:00.000Z',manifestDigest:releaseDigest(f.m)});
 const rows=f.evidence('baseline').composeTargets[0].runtime.services.map((r:any)=>Object.fromEntries(['name','role','containerId','imageDigest','mountDigest','state','health','exitCode','createdAt'].map(k=>[k,r[k]])));
 const e:any={...f.recoveryEvidence({...s,releaseId},{operationId:opId,since},'queue_absent')};delete e.composeRecovery;
 e.composeConfigAbsence={schemaVersion:'roost-compose-config-absence-v1',releaseId,operationId:opId,since,targetId:f.target.targetId,requestedCommit:s.commit,requestedTree:s.candidateTree,configuration:structuredClone(f.target.baseline.configuration),baselineCommit:s.baseCommit,baselineTree:s.baseTree,migrationSchemaVerified:true,controlPlaneQuiescent:true,noCandidateQueue:true,baselineServices:structuredClone(rows),services:rows};e.configDigest=f.m.baseline.configDigest;
 const gitEvidence=(op:string)=>({observedAt:since,remoteCommit:s.commit,remoteTree:s.candidateTree,...(op==='push'?{}:{pullRequestNumber:2,prHeadCommit:s.commit}),...(op==='review'?{reviewApproved:true}:{}),...(op==='merge'?{prMerged:true,mergedCommit:s.commit}:{})});
 const journal:any[]=['push','pr','review','merge'].map((operation,i)=>({id:randomUUID(),sequence:i+1,operation,intent:{},createdAt:since,outcome:{id:randomUUID(),status:'succeeded',evidence:gitEvidence(operation)}}));
 const operation={id:opId,sequence:5,operation:'deploy_config',createdAt:since,intent:{parameters:{commit:s.commit}},outcome:{id:randomUUID(),status:'reconciled',reconciled_status:'absent',observation_only:true,evidence:e}};journal.push(operation);
 const state:any={release:{...f.release,id:releaseId,host_id:hostId,issuer_user_id:randomUUID()},journal,revocations:[],renewals:[],failedClosures:[],expectedVersion:hash('9')};
 const body:any={requestId:randomUUID(),expectedVersion:state.expectedVersion,failedOperationId:opId,consentDigest:hash('a'),evidence:e,nativeClosure:{schemaVersion:'roost-release-owner-native-closure-v1',releaseId,operationId:opId,agentHostId:hostId,evidenceDigest:releaseDigest(e),checkpointDigest:hash('b'),controllerPid:1234,registeredChildCount:3,allChildrenClosed:true,nativeProcessesAbsent:true,writerAbsent:true,observedAt:since}};
 const receipt={...body,releaseId,failedOutcomeId:operation.outcome.id},closure={id:randomUUID(),consent_digest:body.consentDigest,closure_digest:releaseDigest(receipt),revocation_id:randomUUID(),snapshot:receipt};
 const input=structuredClone(s);Object.assign(input,{requestId:randomUUID(),reviewId:randomUUID(),materialVersion:hash('c'),releaseExecutionId:randomUUID(),releaserCredentialId:randomUUID(),baselineRestart:{releaseId,expectedVersion:state.expectedVersion,closureId:closure.id,consentDigest:closure.consent_digest}});input.manifest.baseline.observedAt='2026-10-04T12:03:00.000Z';input.manifestDigest=releaseDigest(input.manifest);
 const closed=()=>{state.failedClosures=[closure];state.revocations=[{id:closure.revocation_id}];return state;};return{...f,state,body,operation,input,closed,e,closure};}
test('exact legacy Compose config absence is a reconciled read-only observation, never deployment success',()=>{const f=configAbsenceFixture();assert.equal(releaseComposeConfigAbsenceEvidenceError({...f.s,releaseId:f.state.release.id},f.e,f.operation),null);assert.equal(releaseOutcomeError(f.state.release,f.operation,{status:'reconciled',reconciledStatus:'absent',observationOnly:true,evidence:f.e},f.state.journal),null);for(const input of [{status:'succeeded',evidence:f.e},{status:'failed',evidence:f.e},{status:'reconciled',reconciledStatus:'absent',observationOnly:false,evidence:f.e}])assert.equal(releaseOutcomeError(f.state.release,f.operation,input,f.state.journal),'release_evidence_scope_invalid');});
test('owner-attested closed native tree and exact existing Git permit truthful FAILED closure',()=>{const f=configAbsenceFixture();assert.equal(shared.closeFailedReleaseSchema.safeParse(f.body).success,true);assert.equal(releaseFailedClosureError(f.state,f.body),null);const before=structuredClone(f.state.release);f.closed();const result=releasePublishedGitBasis(f.state,f.input);assert.equal(result.error,undefined);assert.equal(result.publishedGitBasis.basisKind,'compose_config_absence');assert.deepEqual(result.publishedGitBasis.baselineDeploymentIds,[]);assert.equal(releaseHasPublishedGitBasis({...f.input,...result}),true);assert.equal(createReleaseSchema.safeParse(f.input).success,true);assert.deepEqual(f.state.release,before);});
test('no-effect proof rejects changed settings, images, mounts, containers, data, health, queue or service replacement',()=>{for(const mutate of [(e:any)=>e.composeConfigAbsence.configuration.environmentDigest=hash('e'),(e:any)=>e.composeConfigAbsence.services[0].imageDigest='sha256:'+hash('e'),(e:any)=>e.composeConfigAbsence.services[0].mountDigest=hash('e'),(e:any)=>e.composeConfigAbsence.services[0].containerId=hash('e'),(e:any)=>e.dataDigest=hash('e'),(e:any)=>e.healthDigest=hash('e'),(e:any)=>e.composeConfigAbsence.noCandidateQueue=false,(e:any)=>e.composeConfigAbsence.services[0].createdAt='2026-10-04T12:03:00.000Z',(e:any)=>e.composeConfigAbsence.services[0].health='unhealthy',(e:any)=>e.deploymentIds=[{targetId:'composeapp',deploymentId:'fake'}]]){const f=configAbsenceFixture();mutate(f.e);assert.ok(releaseComposeConfigAbsenceEvidenceError({...f.s,releaseId:f.state.release.id},f.e,f.operation));}});
test('wrong operation/release/since/candidate prevents absent receipt reuse',()=>{for(const patch of [{operationId:randomUUID()},{releaseId:randomUUID()},{since:'2026-10-04T12:01:00.000Z'},{requestedCommit:'f'.repeat(40)}]){const f=configAbsenceFixture();Object.assign(f.e.composeConfigAbsence,patch);assert.ok(releaseComposeConfigAbsenceEvidenceError({...f.s,releaseId:f.state.release.id},f.e,f.operation));}const f=configAbsenceFixture();assert.ok(releaseComposeConfigAbsenceEvidenceError({...f.s,releaseId:f.state.release.id},f.e,{...f.operation,operation:'deploy'}));});
test('closure rejects unresolved/changed Git, candidate effect, incorrect attestation and stale expected state',()=>{for(const mutate of [(f:any)=>f.state.journal[1].outcome.status='uncertain',(f:any)=>f.state.journal[2].outcome.evidence.reviewApproved=false,(f:any)=>f.state.journal[3].outcome.evidence.pullRequestNumber=3,(f:any)=>f.state.journal.push({...f.operation,operation:'deploy'}),(f:any)=>f.body.nativeClosure.writerAbsent=false,(f:any)=>f.body.nativeClosure.agentHostId=randomUUID(),(f:any)=>f.body.nativeClosure.evidenceDigest=hash('e'),(f:any)=>delete f.body.nativeClosure,(f:any)=>f.body.expectedVersion=hash('e')]){const f=configAbsenceFixture();mutate(f);assert.ok(releaseFailedClosureError(f.state,f.body));}});
test('fresh release only inherits exact Git with new credential/runtime and unchanged scope',()=>{for(const mutate of [(f:any)=>f.input.releaserCredentialId=f.s.releaserCredentialId,(f:any)=>f.input.releaseExecutionId=f.s.releaseExecutionId,(f:any)=>f.input.commit='f'.repeat(40),(f:any)=>f.input.manifest.baseline.dataDigest=hash('e'),(f:any)=>f.input.manifest.deployment.targets[0].baseline.images[0].imageDigest='sha256:'+hash('e'),(f:any)=>f.input.manifest.cleanup.protectedResourceIds=[],(f:any)=>f.input.manifest.backup.digest=hash('e'),(f:any)=>f.input.manifest.observation.seconds=121]){const f=configAbsenceFixture();f.closed();mutate(f);assert.ok(releasePublishedGitBasis(f.state,f.input).error);}});
test('inherited Git prohibits every new push/PR/review/merge effect',()=>{const f=configAbsenceFixture();f.closed();const s={...f.input,...releasePublishedGitBasis(f.state,f.input)},intent:any={operation:'deploy_config',commit:s.commit,baseCommit:s.baseCommit,manifestDigest:s.manifestDigest,observed:{commit:s.commit,baseCommit:s.commit,baseTree:s.candidateTree,manifestDigest:s.manifestDigest},parameters:{commit:s.commit,artifactSetDigest:s.manifest.deployment.artifactSetDigest,configDigest:s.manifest.deployment.configDigest,schemaDigest:s.manifest.deployment.schemaDigest}};assert.equal(releaseIntentError({snapshot:s,manifest_digest:s.manifestDigest},intent,[]),null);for(const operation of ['push','pr','review','merge'])assert.equal(releaseIntentError({snapshot:s,manifest_digest:s.manifestDigest},{...intent,operation},[]),'release_successor_git_effect_forbidden');});
import {closeFailedRelease}from'../modules/agent-runtime/governed-release';import{wire}from'../modules/agent-runtime/task-review-contract';
function closureApiFixture(nativeAt:string){const f=configAbsenceFixture(),r=f.state.release;Object.assign(r,{workspace_id:randomUUID(),application_id:f.s.applicationId,task_id:f.s.taskId,host_id:f.s.hostId});const now=new Date(Date.now()-1000).toISOString();f.e.observedAt=now;f.body.nativeClosure.evidenceDigest=releaseDigest(f.e);f.body.nativeClosure.observedAt=nativeAt;f.body.expectedVersion=releaseDigest(wire({release:r,journal:f.state.journal,revocations:[],renewals:[]}));let writes=0;const db:any={workspaceMembership:{findFirst:async()=>({role:'owner'})},$queryRaw:async(p:TemplateStringsArray)=>{const q=p.join('?');if(q.includes('pg_advisory_xact_lock'))return[];if(q.includes('FROM governed_releases'))return[r];if(q.includes('FROM governed_release_operations'))return f.state.journal;if(q.includes('FROM governed_release_revocations')||q.includes('FROM governed_release_renewals')||q.includes('FROM governed_release_failed_closures'))return[];throw Error('unexpected read');},$executeRaw:async()=>{writes++;return 1;}};const auth:any={authType:'user',workspaceId:r.workspace_id,userId:r.issuer_user_id,workspaceRole:'owner',authenticatedAt:Math.floor(Date.now()/1000)};return{...f,db,auth,writes:()=>writes};}
test('normal closure service rejects future native owner attestation without writes',async()=>{const f=closureApiFixture(new Date(Date.now()+120000).toISOString());assert.deepEqual(await closeFailedRelease(f.db,f.auth.workspaceId,f.state.release.id,f.auth,f.body),{error:'release_native_closure_stale'});assert.equal(f.writes(),0);});
test('normal closure service rejects old native receipt before current absence observation without writes',async()=>{const f=closureApiFixture(new Date(Date.now()-301000).toISOString());assert.deepEqual(await closeFailedRelease(f.db,f.auth.workspaceId,f.state.release.id,f.auth,f.body),{error:'release_failed_closure_unproven'});assert.equal(f.writes(),0);});

test('new exact independent review may retain unchanged current material without fabricating a coding basis mutation',()=>{const f=configAbsenceFixture();f.closed();f.input.materialVersion=f.s.materialVersion;assert.equal(releasePublishedGitBasis(f.state,f.input).error,undefined);});

test('unchanged still-current exact independent review is retained across no-effect credential replacement',()=>{const f=configAbsenceFixture();f.closed();f.input.reviewId=f.s.reviewId;f.input.materialVersion=f.s.materialVersion;assert.equal(releasePublishedGitBasis(f.state,f.input).error,undefined);f.input.materialVersion=hash('e');assert.equal(releasePublishedGitBasis(f.state,f.input).error,'release_restart_binding_changed');});
test('normal release approval still denies stale, changed, rejected or wrong independent exact acceptance',()=>{const f=configAbsenceFixture();const verifier=randomUUID(),executor=randomUUID(),s:any={current:true,roleIssues:[],materialVersion:f.input.materialVersion,approvalCommit:f.input.commit,execution:{applicationId:f.input.applicationId},decision:{id:f.input.reviewId,decision:'approve',materialVersion:f.input.materialVersion,evidence:{reviewedCommit:f.input.commit},verifierId:verifier},authorities:{releaser:{principal:{kind:'agent',id:f.input.releaserAgentId}}},contract:{assignment:{agentId:executor},taskRoles:{releaser:{revision:f.input.releaserRevision}}}};assert.equal(releaseApprovalError(s,f.input),null);for(const change of [(x:any)=>x.current=false,(x:any)=>x.decision.decision='reject',(x:any)=>x.decision.id=randomUUID(),(x:any)=>x.materialVersion=hash('e'),(x:any)=>x.decision.evidence.reviewedCommit='f'.repeat(40),(x:any)=>x.roleIssues=['invalid']]){const bad=structuredClone(s);change(bad);assert.equal(releaseApprovalError(bad,f.input),'release_review_stale');}});
