import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,readdirSync}from'node:fs';import {execFileSync}from'node:child_process';import{randomUUID}from'node:crypto';import{configAbsenceFixture}from'./governed-release-compose-config-absence.test';
import {releaseDigest,releaseComposeConfigAbsenceEvidenceError}from'../modules/agent-runtime/governed-release-contract';
const migration='20261005003000_compose_config_absence_closure',source=(n:string)=>readFileSync(`prisma/migrations/${n}/migration.sql`,'utf8');
test('forward closure migration preserves every prior row, applied migration and key lifecycle guard',()=>{const s=source(migration);assert.ok(s.startsWith('BEGIN;')&&s.trim().endsWith('COMMIT;'));assert.doesNotMatch(s,/\b(?:DELETE FROM|UPDATE [a-z_]+ SET|INSERT INTO|DROP|TRUNCATE|ALTER TABLE)\b/i);assert.match(s,/RENAME TO governed_release_failed_baseline_git_set_v1/);assert.match(s,/RENAME TO governed_release_published_git_set_v1/);assert.doesNotMatch(s,/agent_credential_guard|credential_version\s*:=/);});
test('PostgreSQL full migration chain: no-effect qualifier matches shared contract and retains old functions/rows',()=>{const database='roost_test_absence_'+randomUUID().replaceAll('-',''),args=['compose','exec','-T','postgres','psql','-X','-qAt','-v','ON_ERROR_STOP=1','-U','companycore','-d',database],q=(s:string)=>`'${s.replaceAll("'","''")}'`,json=(v:any)=>`${q(JSON.stringify(v))}::jsonb`,sql=(input:string)=>execFileSync('docker',args,{input,encoding:'utf8',windowsHide:true,maxBuffer:32*1024*1024}).trim();let created=false;
 try{execFileSync('docker',['compose','exec','-T','postgres','createdb','-U','companycore',database],{windowsHide:true});created=true;sql(readdirSync('prisma/migrations').filter(n=>/^\d/.test(n)&&n<migration).sort().map(source).join('\n'));
 const originals=['agent_credential_guard()','governed_release_insert_guard()','governed_release_operation_guard()','governed_release_failed_closure_guard()'].map(fn=>sql(`SELECT pg_get_functiondef(${q(fn)}::regprocedure);`));const oldFunctions=['governed_release_failed_baseline_proven(uuid,uuid,jsonb)','governed_release_published_git_basis(uuid,jsonb)'].map(fn=>sql(`SELECT prosrc FROM pg_proc WHERE oid=${q(fn)}::regprocedure;`));const before=sql('SELECT count(*) FROM governed_releases;SELECT count(*) FROM api_keys;SELECT count(*) FROM governed_release_operations;');
 sql('BEGIN;'+source(migration).replace(/^BEGIN;\s*/,'').replace(/COMMIT;\s*$/,'')+'ROLLBACK;');assert.equal(sql('SELECT count(*) FROM pg_proc WHERE proname=\'governed_release_compose_config_absence_valid\';'),'0');sql(source(migration));assert.equal(sql('SELECT count(*) FROM governed_releases;SELECT count(*) FROM api_keys;SELECT count(*) FROM governed_release_operations;'),before);
 for(const [i,fn]of ['agent_credential_guard()','governed_release_insert_guard()','governed_release_operation_guard()','governed_release_failed_closure_guard()'].entries())assert.equal(sql(`SELECT pg_get_functiondef(${q(fn)}::regprocedure);`),originals[i]);for(const [i,fn]of ['governed_release_failed_baseline_git_set_v1(uuid,uuid,jsonb)','governed_release_published_git_set_v1(uuid,jsonb)'].entries())assert.equal(sql(`SELECT prosrc FROM pg_proc WHERE oid=${q(fn)}::regprocedure;`),oldFunctions[i]);
 const f=configAbsenceFixture(),s={...f.s,releaseId:f.state.release.id},op=f.operation;const check=(e:any,o:any=op)=>{const a=releaseComposeConfigAbsenceEvidenceError(s,e,o)===null,b=sql(`SELECT governed_release_compose_config_absence_valid(${json(s)},${json(e)},${json(o)});`)==='t';assert.equal(b,a);return b;};assert.equal(check(f.e),true);
 const cases=[(e:any)=>e.composeConfigAbsence.configuration.gitCommit='f'.repeat(40),(e:any)=>e.composeConfigAbsence.configuration.environmentDigest='e'.repeat(64),(e:any)=>e.composeConfigAbsence.services[0].containerId='e'.repeat(64),(e:any)=>e.composeConfigAbsence.baselineServices[0].containerId='e'.repeat(64),(e:any)=>e.composeConfigAbsence.services[0].imageDigest='sha256:'+'e'.repeat(64),(e:any)=>e.composeConfigAbsence.services[0].mountDigest='e'.repeat(64),(e:any)=>e.composeConfigAbsence.services[0].createdAt='2026-10-04T13:00:00.000Z',(e:any)=>e.composeConfigAbsence.services[0].exitCode=1,(e:any)=>e.composeConfigAbsence.services[0].health='unhealthy',(e:any)=>e.composeConfigAbsence.noCandidateQueue=false,(e:any)=>e.composeConfigAbsence.controlPlaneQuiescent=false,(e:any)=>e.composeConfigAbsence.migrationSchemaVerified=false,(e:any)=>e.dataDigest='e'.repeat(64),(e:any)=>e.schemaDigest='e'.repeat(64),(e:any)=>e.healthDigest='e'.repeat(64),(e:any)=>e.absenceVerified=false,(e:any)=>e.deploymentIds=[{targetId:'composeapp',deploymentId:'fake'}],(e:any)=>delete e.schemaDigest,(e:any)=>e.untrusted=true];for(const mutate of cases){const e=structuredClone(f.e);mutate(e);assert.equal(check(e),false);}assert.equal(check(f.e,{...op,operation:'deploy'}),false);
 // Seed synthetic historical prerequisites only in this disposable database.
 // All closure/outcome/restart guards under test are enabled for assertions.
 const workspace=randomUUID(),user=randomUUID(),r=f.state.release,snap=structuredClone(f.s),since=new Date(Date.now()-60000).toISOString();
 f.e.composeConfigAbsence.since=since;f.e.observedAt=new Date(Date.now()-1000).toISOString();op.createdAt=since;op.outcome.evidence=f.e;
 const insertRelease=(id:string,snapshot:any)=>`INSERT INTO governed_releases(id,workspace_id,task_id,application_id,host_id,release_execution_id,review_id,releaser_agent_id,releaser_credential_id,credential_version,issuer_user_id,expires_at,manifest_digest,configuration_digest,snapshot,request_id,request_hash) VALUES(${q(id)},${q(workspace)},${q(snapshot.taskId)},${q(snapshot.applicationId)},${q(snapshot.hostId)},${q(snapshot.releaseExecutionId)},${q(snapshot.reviewId)},${q(snapshot.releaserAgentId)},${q(snapshot.releaserCredentialId)},1,${q(user)},now()+interval '1 hour',${q(snapshot.manifestDigest)},${q('d'.repeat(64))},${json(snapshot)},${q(randomUUID())},${q('e'.repeat(64))});`;
 sql(`SET session_replication_role=replica;
 INSERT INTO users(id,email,password_hash,updated_at)VALUES(${q(user)},'config-absence@example.test','synthetic-not-login',now());
 INSERT INTO workspaces(id,name,owner_user_id,updated_at)VALUES(${q(workspace)},'Synthetic absence guard',${q(user)},now());
 INSERT INTO workspace_memberships(id,workspace_id,user_id,role,updated_at)VALUES(${q(randomUUID())},${q(workspace)},${q(user)},'owner',now());
 ${insertRelease(r.id,snap)}
 ${f.state.journal.map((j:any)=>`INSERT INTO governed_release_operations(id,release_id,workspace_id,application_id,sequence,operation,intent,request_id,request_hash,created_at)VALUES(${q(j.id)},${q(r.id)},${q(workspace)},${q(snap.applicationId)},${j.sequence},${q(j.operation)},${json(j.intent)},${q(randomUUID())},'synthetic-operation',${q(since)});
 INSERT INTO governed_release_outcomes(id,release_id,operation_id,workspace_id,status,reconciled_status,observation_only,evidence,request_id,request_hash)VALUES(${q(j.outcome.id)},${q(r.id)},${q(j.id)},${q(workspace)},${q(j.outcome.status)},${j.outcome.reconciled_status?q(j.outcome.reconciled_status):'NULL'},${j.outcome.observation_only===true},${json(j.outcome.evidence)},${q(randomUUID())},'synthetic-outcome');`).join('\n')}
 SET session_replication_role=origin;`);

 const secondId=randomUUID(),secondOpId=randomUUID(),secondEvidence=structuredClone(f.e);secondEvidence.composeConfigAbsence.releaseId=secondId;secondEvidence.composeConfigAbsence.operationId=secondOpId;
 sql(`SET session_replication_role=replica;${insertRelease(secondId,snap)}
 INSERT INTO governed_release_operations(id,release_id,workspace_id,application_id,sequence,operation,intent,request_id,request_hash,created_at)VALUES(${q(secondOpId)},${q(secondId)},${q(workspace)},${q(snap.applicationId)},1,'deploy_config',${json(op.intent)},${q(randomUUID())},'synthetic-pending',${q(since)});
 INSERT INTO governed_release_outcomes(id,release_id,operation_id,workspace_id,status,observation_only,evidence,request_id,request_hash)VALUES(${q(randomUUID())},${q(secondId)},${q(secondOpId)},${q(workspace)},'uncertain',false,'{}',${q(randomUUID())},'synthetic-pending');SET session_replication_role=origin;`);
 const outcome=(e:any)=>`INSERT INTO governed_release_outcomes(id,release_id,operation_id,workspace_id,status,reconciled_status,observation_only,evidence,request_id,request_hash)VALUES(${q(randomUUID())},${q(secondId)},${q(secondOpId)},${q(workspace)},'reconciled','absent',true,${json(e)},${q(randomUUID())},'synthetic-absence');`;
 const badOutcome=structuredClone(secondEvidence);badOutcome.composeConfigAbsence.configuration.environmentDigest='0'.repeat(64);assert.throws(()=>sql(outcome(badOutcome)),/governed_release_compose_config_absence_unproven/);sql(outcome(secondEvidence));assert.equal(sql(`SELECT count(*) FROM governed_release_outcomes WHERE operation_id=${q(secondOpId)};`),'2');
const oldRows=sql(`SELECT to_jsonb(r)::text FROM governed_releases r WHERE id=${q(r.id)};SELECT to_jsonb(o)::text FROM governed_release_operations o WHERE release_id=${q(r.id)} ORDER BY sequence;SELECT to_jsonb(x)::text FROM governed_release_outcomes x WHERE release_id=${q(r.id)} ORDER BY operation_id;`);
 assert.equal(sql(`SELECT governed_release_failed_baseline_proven(${q(r.id)},${q(op.id)},${json(f.e)});`),'t');
 const altered=structuredClone(f.e);altered.composeConfigAbsence.noCandidateQueue=false;assert.equal(sql(`SELECT governed_release_failed_baseline_proven(${q(r.id)},${q(op.id)},${json(altered)});`),'f');
 const version=sql(`SELECT governed_release_successor_version(${q(r.id)});`),closureId=f.closure.id,revocationId=f.closure.revocation_id,authenticatedAt=new Date().toISOString(),native={...f.body.nativeClosure,observedAt:new Date().toISOString(),evidenceDigest:releaseDigest(f.e)};
 const receipt:any={...f.body,expectedVersion:version,evidence:f.e,nativeClosure:native,releaseId:r.id,applicationId:snap.applicationId,hostId:snap.hostId,issuerUserId:user,ownerAuthenticatedAt:authenticatedAt,failedOutcomeId:op.outcome.id,failedEvidenceDigest:releaseDigest(f.e)};
 const close=(body:any)=>`INSERT INTO governed_release_failed_closures(id,release_id,workspace_id,issuer_user_id,owner_authenticated_at,failed_operation_id,failed_outcome_id,expected_version,consent_digest,closure_digest,revocation_id,snapshot,request_id,request_hash)VALUES(${q(closureId)},${q(r.id)},${q(workspace)},${q(user)},${q(authenticatedAt)},${q(op.id)},${q(op.outcome.id)},${q(version)},${q(body.consentDigest)},${q(releaseDigest(body))},${q(revocationId)},${json(body)},${q(randomUUID())},'synthetic-closure');`;
 for(const patch of [{writerAbsent:false},{checkpointDigest:'bad'},{agentHostId:randomUUID()},{evidenceDigest:'0'.repeat(64)},{observedAt:new Date(Date.now()+120000).toISOString()}]){const bad={...receipt,nativeClosure:{...native,...patch}};assert.throws(()=>sql('BEGIN;'+close(bad)+'ROLLBACK;'),/governed_release_compose_native_closure_unproven/);}
 sql('BEGIN;'+close(receipt)+`INSERT INTO governed_release_revocations(id,release_id,workspace_id,issuer_user_id,reason,request_id,request_hash)VALUES(${q(revocationId)},${q(r.id)},${q(workspace)},${q(user)},${q('Closed FAILED; owner baseline receipt '+closureId)},${q(randomUUID())},'synthetic-revocation');COMMIT;`);
 const candidate=structuredClone(f.input);candidate.baselineRestart.expectedVersion=sql(`SELECT governed_release_successor_version(${q(r.id)});`);
 const basis=JSON.parse(sql(`SELECT governed_release_published_git_basis(${q(r.id)},${json(candidate)})::text;`));assert.equal(basis.basisKind,'compose_config_absence');assert.deepEqual(basis.baselineDeploymentIds,[]);
 for(const mutate of [(c:any)=>c.releaserCredentialId=snap.releaserCredentialId,(c:any)=>c.reviewId=snap.reviewId,(c:any)=>c.commit='f'.repeat(40),(c:any)=>c.manifest.baseline.dataDigest='f'.repeat(64),(c:any)=>c.manifest.backup.digest='0'.repeat(64),(c:any)=>c.manifest.cleanup.protectedResourceIds=[]]){const bad=structuredClone(candidate);mutate(bad);assert.equal(sql(`SELECT governed_release_published_git_basis(${q(r.id)},${json(bad)}) IS NULL;`),'t');}
 assert.equal(sql(`SELECT to_jsonb(r)::text FROM governed_releases r WHERE id=${q(r.id)};SELECT to_jsonb(o)::text FROM governed_release_operations o WHERE release_id=${q(r.id)} ORDER BY sequence;SELECT to_jsonb(x)::text FROM governed_release_outcomes x WHERE release_id=${q(r.id)} ORDER BY operation_id;`),oldRows);

 }finally{if(created)execFileSync('docker',['compose','exec','-T','postgres','dropdb','--force','-U','companycore',database],{windowsHide:true});}});
