// Source checks are inert. Opt-in DB checks require Root's already-started
// isolated local test Compose project; this file never starts a Docker project.
import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import fs from 'node:fs';import path from 'node:path';import {execFileSync} from 'node:child_process';
import shared from './lib/agent-host-release-contract.cjs';
import {compatibleContinuationPostgresFixture,continuationSeedSql} from './fixtures/release-compatible-config-continuation-postgres.mjs';
const migration='20261009230000_compatible_config_continuation',filename='prisma/migrations/'+migration+'/migration.sql',source=fs.readFileSync(filename,'utf8'),quote=v=>"'"+v.replaceAll("'","''")+"'",json=v=>quote(JSON.stringify(v))+'::jsonb';
test('fictional input keeps original failed-partial prior and separately declares exact configuration parent',()=>{const f=compatibleContinuationPostgresFixture();assert.equal(f.claimLevel,'fictional_stored_history_not_admission_authority');assert.equal(shared.compatibleConfigurationContinuationSchema.safeParse(f.input.compatibleConfigurationContinuation).success,true);assert.notEqual(f.input.compatibleConfigurationContinuation.releaseId,f.input.compatibleArtifactRecovery.prior.releaseId);assert.equal(f.operations.length,5);assert.equal(f.input.compatibleArtifactRecovery.scopeAudit.scopeDigest,shared.compatibleConfigurationContinuationScopeDigest(f.input));assert.equal(f.input.commit,f.parent.snapshot.commit);assert.deepEqual(f.input.manifest.repository,f.parent.snapshot.manifest.repository);assert(!Object.hasOwn(f.input,'compatibleContinuationBasis'));});
test('caller declaration remains exact, and new derived basis is not caller authority',()=>{const f=compatibleContinuationPostgresFixture(),v=f.input.compatibleConfigurationContinuation;for(const invalid of [{...v,verified:true},{...v,gitOperationIds:{...v.gitOperationIds,deploy_config:randomUUID()}},{...v,closureDigest:'x'}])assert.equal(shared.compatibleConfigurationContinuationSchema.safeParse(invalid).success,false);assert.ok(source.includes('s->\'compatibleContinuationBasis\' IS DISTINCT FROM basis'));assert.ok(source.includes('governed_release_compatible_config_closure_journal(parent.id,c.failed_operation_id,c.snapshot->\'evidence\') IS DISTINCT FROM TRUE'));});
test('historical fixture seed is isolated and new admission still requires normal original proof',()=>{const f=compatibleContinuationPostgresFixture(),s=continuationSeedSql(f);assert.ok(s.startsWith('BEGIN;SET LOCAL session_replication_role=replica;'));assert.ok(s.endsWith('COMMIT;'));assert(!source.includes('session_replication_role'));assert(!source.includes('DISABLE TRIGGER'));assert.ok(source.includes('governed_release_compatible_basis_pre_cfg_cont_v1(s,workspace,issuer,fresh)'));assert.ok(source.includes('governed_release_compatible_proof_pre_cfg_cont_v1(s-\'compatibleContinuationBasis\',workspace,issuer,closed_at)'));});
test('migration remains additive with bounded atomic closure consumption and existing negative/renewal guards',()=>{assert.ok(source.startsWith('BEGIN;'));assert.ok(source.trimEnd().endsWith('COMMIT;'));assert.ok(source.includes('CREATE UNIQUE INDEX governed_release_compatible_continuation_once'));assert.ok(source.includes('pg_advisory_xact_lock'));assert(!/\b(?:DELETE FROM|UPDATE governed_|DROP TABLE|TRUNCATE|ALTER TABLE.*DISABLE)\b/i.test(source));assert(!source.includes('CREATE OR REPLACE FUNCTION governed_release_outcome_guard'));assert(!source.includes('CREATE OR REPLACE FUNCTION governed_release_renewal_guard'));});

test('isolated PostgreSQL continuation migration/typed reconstruction/refusals and unchanged normal branches',
 {skip:process.env.ROOST_TEST_LOCAL_POSTGRES!=='1'},()=>{
 const project=process.env.ROOST_TEST_LOCAL_POSTGRES_PROJECT,composeFile=process.env.ROOST_TEST_LOCAL_POSTGRES_COMPOSE_FILE;
 assert.match(project??'',/^roost[-_]test[-_][a-z0-9_-]{1,40}$/);assert.ok(composeFile&&path.isAbsolute(composeFile),'Root supplies its isolated local Compose source');
 const st=fs.lstatSync(composeFile);assert(st.isFile()&&!st.isSymbolicLink()&&st.nlink===1);
 const database='roost_test_cfg_cont_'+randomUUID().replaceAll('-',''),common=['compose','--project-name',project,'--file',composeFile,'exec','-T','postgres'],args=[...common,'psql','-X','-qAt','-v','ON_ERROR_STOP=1','-U','companycore','-d',database];
 const call=(a,input)=>execFileSync('docker',a,{input,encoding:'utf8',windowsHide:true,timeout:120000,maxBuffer:32*1024*1024}),sql=s=>call(args,s).trim();let created=false;
 try{
  call([...common,'createdb','-U','companycore',database]);created=true;
  const prior=fs.readdirSync('prisma/migrations').filter(n=>/^\d/.test(n)&&n<migration).sort();sql(prior.map(n=>fs.readFileSync('prisma/migrations/'+n+'/migration.sql','utf8')).join('\n'));
  const originals=Object.fromEntries(['scope_digest','proof_valid','basis_valid','negative_lineage_valid'].map(n=>[n,sql("SELECT prosrc FROM pg_proc WHERE proname='governed_release_compatible_"+n+"';")]));
  sql('BEGIN;'+source.replace(/^BEGIN;\s*/,'').replace(/COMMIT;\s*$/,'')+'ROLLBACK;');assert.equal(sql("SELECT count(*) FROM pg_proc WHERE proname='governed_release_compatible_continuation_basis';"),'0');
  sql(source);
  for(const[name,body]of Object.entries(originals)){const alias={scope_digest:'scope',proof_valid:'proof',basis_valid:'basis',negative_lineage_valid:'negative'}[name];assert.equal(sql("SELECT prosrc FROM pg_proc WHERE proname='governed_release_compatible_"+alias+"_pre_cfg_cont_v1';"),body);}
  const f=compatibleContinuationPostgresFixture(),v=f.input;sql(continuationSeedSql(f));
  const basisFor=input=>sql('SELECT governed_release_compatible_continuation_basis(r,'+json(input)+') FROM governed_releases r WHERE id='+quote(f.parent.id)+'::uuid;');
  const basis=JSON.parse(basisFor(v));assert.equal(shared.compatibleContinuationBasisSchema.safeParse(basis).success,true);assert.equal(basis.git.length,4);assert.equal(basis.failedOperationId,f.operations[4].id);assert.equal(basis.publication.pullRequestNumber,4);
  const publicJournal=JSON.parse(sql("SELECT jsonb_agg(governed_release_compatible_camel_row((to_jsonb(o)-'request_hash')||jsonb_build_object('created_at',governed_release_compatible_iso(o.created_at)))||jsonb_build_object('outcome',governed_release_compatible_camel_row(to_jsonb(x)-'request_hash')) ORDER BY o.sequence) FROM governed_release_operations o JOIN LATERAL(SELECT * FROM governed_release_outcomes WHERE operation_id=o.id ORDER BY sequence DESC LIMIT 1)x ON TRUE WHERE o.release_id="+quote(f.parent.id)+'::uuid;'));
  assert.equal(basis.journalDigest,shared.releaseDigest(publicJournal));for(let n=0;n<4;n++){assert.equal(basis.git[n].intentDigest,shared.releaseDigest(publicJournal[n].intent));assert.equal(basis.git[n].outcomeDigest,shared.releaseDigest(publicJournal[n].outcome));assert.equal(basis.git[n].evidenceDigest,shared.releaseDigest(publicJournal[n].outcome.evidence));}
  assert.equal(sql('SELECT governed_release_compatible_scope_digest('+json(v)+');'),shared.compatibleConfigurationContinuationScopeDigest(v));
  const missingProof={...v,compatibleContinuationBasis:basis};assert.equal(sql('SELECT governed_release_compatible_basis_valid('+json(missingProof)+','+quote(f.workspace)+'::uuid,'+quote(f.issuer)+'::uuid,TRUE);'),'f','data reconstruction never bypasses original authenticated proof/native/source/owner admission');
  for(const mutate of [x=>x.commit='f'.repeat(40),x=>x.candidateTree='f'.repeat(40),x=>x.reviewId=randomUUID(),x=>x.materialVersion='f'.repeat(64),x=>x.manifest.repository.candidateBranch='codex/foreign',x=>x.compatibleConfigurationContinuation.gitOperationIds.merge=randomUUID(),x=>x.compatibleConfigurationContinuation.closureDigest='f'.repeat(64),x=>x.compatibleConfigurationContinuation.extra=true]){const x=structuredClone(v);mutate(x);assert.equal(basisFor(x),'');}
  const badOutcome={...f.outcomes[3],id:randomUUID(),sequence:99,status:'uncertain',reconciled_status:null,observation_only:false,request_id:randomUUID()};
  assert.equal(sql('BEGIN;SET LOCAL session_replication_role=replica;INSERT INTO governed_release_outcomes SELECT (jsonb_populate_record(NULL::governed_release_outcomes,'+json(badOutcome)+')).*;SET LOCAL session_replication_role=origin;SELECT governed_release_compatible_continuation_basis(r,'+json(v)+') IS NULL FROM governed_releases r WHERE id='+quote(f.parent.id)+'::uuid;ROLLBACK;'),'t','latest unknown Git outcome refuses inherited authority');
  // The unique index itself protects concurrent closure consumption even if
  // another unprivileged code path attempted to bypass the normal API check.
  const child={...f.parent,id:randomUUID(),request_id:randomUUID(),snapshot:missingProof};
  sql('BEGIN;SET LOCAL session_replication_role=replica;INSERT INTO governed_releases SELECT (jsonb_populate_record(NULL::governed_releases,'+json(child)+')).*;COMMIT;');
  assert.throws(()=>sql('BEGIN;SET LOCAL session_replication_role=replica;INSERT INTO governed_releases SELECT (jsonb_populate_record(NULL::governed_releases,'+json({...child,id:randomUUID(),request_id:randomUUID()})+')).*;COMMIT;'),/duplicate key|unique constraint/);
  assert.equal(sql('SELECT count(*) FROM governed_release_operations WHERE release_id='+quote(child.id)+'::uuid;'),'0','inherited Git rows are never copied into the child journal');
 }finally{if(created)call([...common,'dropdb','-U','companycore',database]);}
});
