// Synthetic supporting fixtures only: no API, SSH, database, credentials or native effects.
import test from'node:test';import assert from'node:assert/strict';import{randomUUID}from'node:crypto';import{createRequire}from'node:module';import{readFileSync}from'node:fs';import{fileURLToPath}from'node:url';
import contract from'./lib/agent-host-release-contract.cjs';
import{qualifyRecoveryOnlyEntryState,qualifyClosedFailedComposeEntry,qualifyFreshFailedEntryEvidence,qualifyRecoveryOnlyConfigurationPreimage,qualifyInstalledDatabaseSource,createComposeRecoveryEntryReader}from'./lib/agent-host-release-compose-worker.mjs';
const req=createRequire(import.meta.url),{require:ts}=req('tsx/cjs/api'),{recoveryOnlyFixture}=ts(fileURLToPath(new URL('../src/tests/governed-release-compose-recovery-only.test.ts',import.meta.url)),import.meta.url),now=Date.parse('2026-10-04T12:06:07.000Z');
function fixture(){const f=recoveryOnlyFixture();f.state.status='failed';return f;}
test('old closed failed scope remains immutable while complete current entry is freshly and independently checked',()=>{const f=fixture(),before=structuredClone(f.input.recoveryOnly),e=structuredClone(f.input.recoveryOnly.currentEvidence);e.observedAt='2026-10-04T12:06:06.000Z';e.healthDigest='a'.repeat(64);e.composeRecovery.partialRollbackFailure.publicHealth.healthDigest=e.healthDigest;const q=qualifyRecoveryOnlyEntryState({snapshot:f.input,previousState:f.state,currentEvidence:e,now});assert.equal(q.closureReceipt,f.closure.snapshot);assert.deepEqual(f.input.recoveryOnly,before);assert.equal(e.healthy,false);assert.equal(qualifyClosedFailedComposeEntry(f.state).closureReceipt,f.closure.snapshot);});
for(const[n,mutate]of Object.entries({healthy:x=>x.e.healthy=true,data:x=>x.e.dataDigest='a'.repeat(64),schema:x=>x.e.schemaDigest='a'.repeat(64),queue:x=>x.e.composeRecovery.queue.status='finished',container:x=>x.e.composeRecovery.services[0].containerId='a'.repeat(64),missing:x=>delete x.e.composeRecovery.partialRollbackFailure.images,stale:x=>x.e.observedAt='2026-10-04T12:00:00.000Z',future:x=>x.e.observedAt='2026-10-04T12:07:00.000Z'}))test('fresh failed-entry refuses '+n,()=>{const f=fixture(),x={e:structuredClone(f.input.recoveryOnly.currentEvidence)};mutate(x);assert.throws(()=>qualifyRecoveryOnlyEntryState({snapshot:f.input,previousState:f.state,currentEvidence:x.e,now}));});
for(const[n,mutate]of Object.entries({active:f=>f.state.status='active',version:f=>f.state.expectedVersion='a'.repeat(64),oldManifest:f=>f.state.release.snapshot.manifestDigest='a'.repeat(64),closure:f=>f.state.failedClosures=[],revocation:f=>f.state.revocations=[],outcome:f=>f.state.journal.at(-1).outcome.id=randomUUID(),wrongTask:f=>f.state.release.snapshot.taskId=randomUUID()}))test('previous-scope binding refuses '+n,()=>{const f=fixture();mutate(f);assert.throws(()=>qualifyRecoveryOnlyEntryState({snapshot:f.input,previousState:f.state}));});
function preimage(){const f=fixture(),snapshot={...f.input,releaseId:f.release.id},intent={requestId:randomUUID(),operation:'rollback_config',manifestDigest:f.input.manifestDigest,commit:f.input.commit,baseCommit:f.input.baseCommit,expectedVersion:'a'.repeat(64),observed:{commit:f.input.commit,baseCommit:f.input.commit,baseTree:f.input.candidateTree,manifestDigest:f.input.manifestDigest},parameters:{commit:f.m.rollback.commit,configDigest:f.m.rollback.configDigest,artifactSetDigest:f.m.rollback.artifactSetDigest,schemaDigest:f.m.rollback.schemaDigest}},current={release:{id:f.release.id,snapshot:f.input},status:'active',journal:[{id:randomUUID(),operation:'rollback_config',intent}]};return{snapshot,current,configuration:structuredClone(f.input.recoveryOnly.currentEvidence.composeRecovery.configuration)};}
test('only exact old failed-entry configuration is admitted beneath a sole unresolved new rollback config intent',()=>{assert.equal(qualifyRecoveryOnlyConfigurationPreimage(preimage()),true);});
for(const[n,mutate]of Object.entries({ordinary:x=>delete x.snapshot.recoveryOnly,absentIntent:x=>x.current.journal=[],wrongOp:x=>x.current.journal[0].operation='deploy_config',settled:x=>x.current.journal[0].outcome={status:'succeeded'},uncertain:x=>x.current.journal[0].outcome={status:'uncertain'},two:x=>x.current.journal.push(structuredClone(x.current.journal[0])),newConfig:x=>x.configuration=structuredClone(x.snapshot.manifest.deployment.targets[0].rollbackConfiguration),wrongArtifact:x=>x.current.journal[0].intent.parameters.artifactSetDigest='a'.repeat(64),wrongGrant:x=>x.current.release.id=randomUUID()}))test('old config exception refuses '+n,()=>{const x=preimage();mutate(x);assert.throws(()=>qualifyRecoveryOnlyConfigurationPreimage(x));});
test('protected failed-entry DB source is a recovery-only exception; healthy historical baseline is never rewritten',()=>{const f=fixture(),database=f.m.deployment.targets[0].baseline.configuration.services.find(r=>r.role==='database'),row=f.input.recoveryOnly.currentEvidence.composeRecovery.services.find(r=>r.role==='database'),baselineDatabase=f.input.recoveryOnly.currentEvidence.composeRecovery.baselineServices.find(r=>r.role==='database'),before=structuredClone(baselineDatabase);assert.equal(qualifyInstalledDatabaseSource({snapshot:f.input,baselineDatabase,database,container:row.containerId}),true);assert.deepEqual(baselineDatabase,before);const ordinary=structuredClone(f.input);delete ordinary.recoveryOnly;assert.throws(()=>qualifyInstalledDatabaseSource({snapshot:ordinary,baselineDatabase,database,container:row.containerId}));});
for(const[n,mutate]of Object.entries({writable:f=>f.input.recoveryOnly.currentEvidence.composeRecovery.partialRollbackFailure.databaseReadOnly=false,data:f=>f.input.recoveryOnly.currentEvidence.dataDigest='a'.repeat(64),image:f=>f.input.recoveryOnly.currentEvidence.composeRecovery.services.find(r=>r.role==='database').imageDigest='sha256:'+'a'.repeat(64),mount:f=>f.input.recoveryOnly.currentEvidence.composeRecovery.services.find(r=>r.role==='database').mountDigest='a'.repeat(64)}))test('DB source exception refuses '+n,()=>{const f=fixture(),row=f.input.recoveryOnly.currentEvidence.composeRecovery.services.find(r=>r.role==='database'),database=f.m.deployment.targets[0].baseline.configuration.services.find(r=>r.role==='database'),baselineDatabase=f.input.recoveryOnly.currentEvidence.composeRecovery.baselineServices.find(r=>r.role==='database');mutate(f);assert.throws(()=>qualifyInstalledDatabaseSource({snapshot:f.input,baselineDatabase,database,container:row.containerId}));});
test('standalone reader rejects non-FAILED state before acquiring any transport or effect authority',()=>{const f=fixture();f.state.status='active';assert.throws(()=>qualifyClosedFailedComposeEntry(f.state));assert.throws(()=>createComposeRecoveryEntryReader({settings:{},previousState:f.state},{nativeProcess:()=>{assert.fail('native effect');}}));});
test('installed and standalone reader share exact fixed engine; old scope recognizer is read-only and native/source clocks never relabeled',()=>{const s=readFileSync(new URL('./lib/agent-host-release-compose-worker.mjs',import.meta.url),'utf8'),factory=s.slice(s.indexOf('export function createComposeRecoveryEntryReader'),s.indexOf('export function qualifyRecoveryOnlyConfigurationPreimage')),engine=s.slice(s.indexOf('async function readFixedRecoveryEntry'),s.indexOf('/** Fixed per-installation wiring.'));assert.match(s,/recoveryPreviousManifest:sealedFile.optional/);assert.match(s,/historicalManifest=previousManifest\?\?m/);assert.match(s,/baseline.configDigest===historicalTarget.baseline.configDigest/);assert.equal((s.match(/await readFixedRecoveryEntry\(/g)||[]).length,2);assert.match(engine,/sourcePins:oldConfiguration.sourcePins/);assert.match(engine,/partial.services.*entry.services/);assert.match(engine,/fence.readOnlyFence===true/);assert.match(engine,/currentEvidence.observedAt=new Date\(now\(\)\)/);assert.doesNotMatch(engine,/nativeClosure\.observedAt\s*=|\.nativeClosure\.evidenceDigest\s*=/);assert.doesNotMatch(factory,/PATCH|\.configure\(|\.deploy\(|activitySeed|readReleaseCredential/);});

import{createHash}from'node:crypto';import{qualifyRecoveryMaterializationTemplate}from'./lib/agent-host-release-compose-worker.mjs';
test('persisted candidate build template is distinct from rollback command artifact and only the former qualifies',()=>{const f=fixture(),old=structuredClone(f.state.release.snapshot.manifest),target=old.deployment.targets[0],names=target.configuration.services.map(r=>r.name),candidate=Buffer.from(JSON.stringify({services:Object.fromEntries(names.map(name=>[name,{build:{context:'.'}}]))})),rollback=Buffer.from(JSON.stringify({services:Object.fromEntries(names.map(name=>[name,{image:'retained:fixture'}]))})),hash=b=>createHash('sha256').update(b).digest('hex');target.configuration.controllerPolicy.artifactDigest=hash(candidate);target.rollbackConfiguration.controllerPolicy.artifactDigest=hash(rollback);const before=structuredClone(old);assert.notEqual(hash(candidate),hash(rollback));assert.equal(qualifyRecoveryMaterializationTemplate({previousManifest:old,bytes:candidate,reference:{sha256:hash(candidate)}}),candidate);assert.throws(()=>qualifyRecoveryMaterializationTemplate({previousManifest:old,bytes:rollback,reference:{sha256:hash(rollback)}}));assert.deepEqual(old,before);assert.throws(()=>qualifyRecoveryMaterializationTemplate({previousManifest:old,bytes:candidate,reference:{sha256:hash(rollback)}}));});
test('old materialization packet remains strictly qualified; no template fallback or historical command rewrite',()=>{const s=readFileSync(new URL('./lib/agent-host-release-compose-worker.mjs',import.meta.url),'utf8'),engine=s.slice(s.indexOf('async function readFixedRecoveryEntry'),s.indexOf('/** Fixed per-installation wiring.'));assert.match(engine,/configurationTemplate:\{sha256:hash\(materializationTemplate\),bytesBase64:materializationTemplate/);assert.doesNotMatch(engine,/configurationTemplate:.*oldEntryTemplate/);assert.match(s,/if\(phase==='candidate'\)materializationTemplate=qualifyRecoveryMaterializationTemplate/);assert.match(s,/cfg.recoveryEntryTemplate.sha256===s.recoveryOnly.currentEvidence.composeRecovery.configuration.controllerPolicy/);assert.match(s,/materializationTemplate:recoveryMaterializationTemplate/);assert.match(s,/recoveryMaterializationTemplate:sealedFile.optional/);assert.doesNotMatch(engine,/template_unproven.*catch|templateFallback|nativeClosure.*observedAt\s*=/);});
