// Fictional protocol/journal fixtures only: no native/API/Docker/model effects.
import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {createCompatibleFailureContract} from './lib/agent-host-release-compatible-failure.cjs';
import shared from './lib/agent-host-release-contract.cjs';import compose from './lib/agent-host-release-compose-state.cjs';
import ingress from './lib/agent-host-release-compose-ingress-fence.cjs';import {fixture as originalFixture,hash as H,image as I} from './fixtures/release-compose-contract.cjs';
const d=shared.releaseDigest,clone=structuredClone;
const api=createCompatibleFailureContract({manifestSchema:shared.manifestSchema,intentSchema:shared.intentSchema,compatibleArtifactRecoverySchema:shared.compatibleArtifactRecoverySchema,
 composeConfigurationSchema:compose.composeConfigurationSchema,composeRuntimeServiceSchema:compose.composeRuntimeServiceSchema,composeIngressFenceSchema:ingress.composeIngressFenceSchema,
 releaseDigest:d,composeConfigurationDigest:compose.composeConfigurationDigest,compatibleRecoveryScopeDigest:shared.compatibleRecoveryScopeDigest,qualifyComposeIngressFence:ingress.qualifyComposeIngressFence});
export function compatibleFailureFixture(kind='deployment_failed'){
 const f=originalFixture(),m=f.m,t=f.target,s={...f.s,releaseId:randomUUID(),manifestDigest:''},clock=Date.now();
 const extra={name:'proactive',role:'cadence',source:'built',expectedState:'paused',mountDigest:H('9')};for(const cfg of [t.configuration,t.baseline.configuration,t.rollbackConfiguration])cfg.services.push(clone(extra));t.baseline.images.push({name:'proactive',imageDigest:I('4')});m.cleanup.protectedResourceIds.push(H('9'),I('4'),I('7'));
 m.postObservation={schemaVersion:'roost-release-post-observation-v1',kind:'synthetic_recent_activity',candidateCommit:s.commit,candidateTree:s.candidateTree,controllerDigest:H('1'),fixture:{fixtureId:randomUUID(),userId:randomUUID(),sessionId:randomUUID(),eventId:randomUUID(),traceId:randomUUID(),memoryId:-1,markerDigest:H('2'),summaryDigest:H('3')},baselineSequenceDigest:H('8'),budget:{providerRequests:0,externalActions:0},runtimeResume:{approved:true,databaseSettingsDigest:H('7'),ingressSettingsDigest:H('6'),observationSeconds:300,cadences:[{name:'maintenance',behavior:'restore_existing_loop',behaviorDigest:H('1')},{name:'proactive',behavior:'restore_existing_loop',behaviorDigest:H('2')}]}};
 t.configDigest=compose.composeConfigurationDigest(t.configuration);t.baseline.configDigest=compose.composeConfigurationDigest(t.baseline.configuration);t.rollbackConfigDigest=compose.composeConfigurationDigest(t.rollbackConfiguration);
 for(const[k,v]of [['deployment',t.configDigest],['baseline',t.baseline.configDigest],['rollback',t.rollbackConfigDigest]])m[k].configDigest=d([{targetId:t.targetId,configDigest:v}]);for(const[k,mode]of [['deployment',false],['baseline','baseline'],['rollback',true]])m[k].artifactSetDigest=shared.sourceArtifactDigest(m,s,mode);s.manifestDigest=d(m);
 const decl=t.configuration.services,dbDecl=decl.find(v=>v.role==='database'),db={name:dbDecl.name,role:'database',containerId:H('a'),imageDigest:dbDecl.imageDigest,mountDigest:dbDecl.mountDigest,state:'running',health:'healthy',exitCode:0,createdAt:new Date(clock-86400000).toISOString()};
 const originalAt=new Date(clock-60000).toISOString(),originalInventory={schemaVersion:'roost-compose-project-inventory-v1',targetId:t.targetId,observedAt:originalAt,projectServiceSetComplete:true,physicalServices:[db],digest:H('0')};originalInventory.digest=shared.compatibleRecoveryInventoryDigest(originalInventory);
 const entry={schemaVersion:'roost-compose-down-entry-v1',observedAt:originalAt,targetId:t.targetId,configuration:clone(t.rollbackConfiguration),projectInventory:originalInventory,
  services:t.rollbackConfiguration.services.map(v=>v.role==='database'?{...db,presence:'present',declarationDigest:d(v),inventoryDigest:originalInventory.digest,observedAt:originalAt}:{presence:'absent',name:v.name,role:v.role,source:'built',declarationDigest:d(v),mountDigest:v.mountDigest,containerId:null,imageDigest:null,state:'absent',absenceVerified:true,inventoryDigest:originalInventory.digest,observedAt:originalAt}),
  historicalServiceReferences:decl.map((v,n)=>({name:v.name,containerId:H(String(n+1)),imageDigest:v.imageDigest??I('f'),failedEvidenceDigest:H('0')})),imageAvailability:t.baseline.images.map(v=>({...v,present:false})),schemaDigest:m.baseline.schemaDigest,dataDigest:m.baseline.dataDigest,sequenceDigest:m.postObservation.baselineSequenceDigest,
  database:{containerId:db.containerId,imageDigest:db.imageDigest,mountDigest:db.mountDigest,running:true,healthy:true,readOnlyFence:true,activeOtherSessions:0,ownedTransactions:0},
  cadences:m.postObservation.runtimeResume.cadences.map(v=>({presence:'absent',name:v.name,behaviorDigest:v.behaviorDigest,held:true,containerId:null,imageDigest:null,state:'absent',absenceVerified:true,inventoryDigest:originalInventory.digest,observedAt:originalAt})),databaseSettingsDigest:H('7'),ingressSettingsDigest:H('6'),ingressBlocked:true,activeDeploymentCount:0,publicHealth:{healthy:false,healthDigest:H('0')},evidenceDigest:H('0')};entry.evidenceDigest=shared.compatibleRecoveryEntryDigest(entry);
 const images=decl.filter(v=>v.source==='built').map(v=>({name:v.name,imageDigest:I('7'),commit:s.commit,tree:s.candidateTree}));
 s.compatibleArtifactRecovery={schemaVersion:'roost-compose-compatible-artifact-recovery-v1',prior:{releaseId:randomUUID(),expectedVersion:H('1'),closureId:randomUUID(),closureDigest:H('2'),failedOperationId:randomUUID(),failedOutcomeId:randomUUID(),failedEvidenceDigest:H('3'),previousManifestDigest:H('4')},currentEntry:entry,
  nativeClosure:{schemaVersion:'roost-release-owner-native-closure-v1',releaseId:randomUUID(),operationId:randomUUID(),agentHostId:randomUUID(),evidenceDigest:entry.evidenceDigest,checkpointDigest:H('5'),controllerPid:1234,registeredChildCount:10,allChildrenClosed:true,nativeProcessesAbsent:true,writerAbsent:true,observedAt:originalAt},
  replacement:{commit:s.commit,tree:s.candidateTree,artifactSetDigest:m.deployment.artifactSetDigest,configurationDigest:m.deployment.configDigest,images,buildReceiptDigest:H('6'),compatibilityReceiptDigest:H('7'),schemaDigest:m.baseline.schemaDigest,schemaChangeAllowed:false},publication:{mode:'new_exact_commit',baseCommit:'e'.repeat(40),baseTree:'f'.repeat(40)},scopeAudit:{taskId:randomUUID(),executionId:randomUUID(),reviewId:randomUUID(),materialVersion:H('8'),scopeDigest:H('0')},failurePolicy:{mode:'freeze_protected_database',automaticHistoricalRollback:false,dataRestoreAllowed:false,volumeDeletionAllowed:false,keepIngressBlocked:true,keepCadencesHeld:true}};
 s.compatibleArtifactRecovery.scopeAudit.scopeDigest=shared.compatibleRecoveryScopeDigest(s);
 const observedAt=new Date(clock-1).toISOString(),createdAt=new Date(clock-20000).toISOString(),operationName=kind==='configuration_absent'?'deploy_config':kind==='observation_failed'?'observe':'deploy';
 const intent=op=>({requestId:randomUUID(),operation:op,manifestDigest:s.manifestDigest,commit:s.commit,baseCommit:s.baseCommit,expectedVersion:H('9'),observed:{commit:s.commit,baseCommit:s.commit,baseTree:s.candidateTree,manifestDigest:s.manifestDigest},parameters:op==='observe'?{mode:'candidate'}:{commit:s.commit,artifactSetDigest:m.deployment.artifactSetDigest,configDigest:m.deployment.configDigest,schemaDigest:m.deployment.schemaDigest,...(op==='deploy'?{targetId:t.targetId}:{})}});
 const operation={id:randomUUID(),releaseId:s.releaseId,operation:operationName,createdAt,intent:intent(operationName)};
 const deploy=kind==='observation_failed'?{id:randomUUID(),releaseId:s.releaseId,operation:'deploy',createdAt:new Date(clock-40000).toISOString(),intent:intent('deploy')}:operation;
 const currentQueue=kind.endsWith('_absent')?null:{targetId:t.targetId,deploymentId:'r'+d([s.releaseId,deploy.id,t.targetId,'candidate']).slice(0,23),commit:s.commit,status:kind==='observation_failed'?'finished':'failed',createdAt:new Date(clock-(kind==='observation_failed'?35000:15000)).toISOString(),finishedAt:new Date(clock-(kind==='observation_failed'?25000:5000)).toISOString()};
 const built=kind.endsWith('_absent')?[]:decl.filter(v=>v.source==='built').map((v,n)=>({name:v.name,role:v.role,containerId:H(String(n+1)),imageDigest:I('7'),mountDigest:v.mountDigest,state:v.role==='migration'?'exited':v.role==='app'?kind==='observation_failed'?'running':'created':'created',health:v.role==='app'&&kind==='observation_failed'?'unhealthy':null,exitCode:v.role==='migration'&&kind==='deployment_failed'?1:0,createdAt:new Date(clock-(kind==='observation_failed'?30000:10000)).toISOString()}));
 const configuration=clone(kind==='configuration_absent'?entry.configuration:t.configuration),inventory={schemaVersion:'roost-compatible-failure-project-inventory-v1',targetId:t.targetId,observedAt,projectServiceSetComplete:true,services:[clone(db),...built],absentServices:configuration.services.filter(v=>v.role!=='database'&&!built.some(q=>q.name===v.name)).map(v=>({name:v.name,role:v.role,source:'built',mountDigest:v.mountDigest,declarationDigest:d(v),containerId:null,imageDigest:null,state:'absent',absenceVerified:true})),digest:H('0')};
 const queueScan={schemaVersion:'roost-compatible-failure-queue-scan-v1',targetId:t.targetId,from:deploy.createdAt,through:observedAt,observedAt,scanComplete:true,rows:currentQueue?[clone(currentQueue)]:[],digest:H('0')};
 const fence={schemaVersion:'roost-compose-proxy-network-fence-v1',observedAt,targetId:t.targetId,networkId:H('c'),subnet:'10.42.0.0/24',proxyId:H('d'),proxyPid:1234,namespaceDigest:H('e'),databaseContainerId:db.containerId,databaseIpv4:'10.42.0.2',proxyIpv4:'10.42.0.3',port:8000,ruleComment:'roost-release-hold-'+'ab'.repeat(16),ruleDigest:H('f'),originalRulesDigest:H('1'),observedRulesDigest:H('2'),projectNetworkExclusive:true,publishedPortsAbsent:true,rulePresent:true,evidenceDigest:H('0')};fence.evidenceDigest=ingress.composeIngressFenceDigest(fence);
 entry.ingressFence=clone(fence);entry.ingressFence.observedAt=originalAt;entry.ingressFence.evidenceDigest=ingress.composeIngressFenceDigest(entry.ingressFence);entry.evidenceDigest=shared.compatibleRecoveryEntryDigest(entry);s.compatibleArtifactRecovery.nativeClosure.evidenceDigest=entry.evidenceDigest;s.compatibleArtifactRecovery.scopeAudit.scopeDigest=shared.compatibleRecoveryScopeDigest(s);
 const marker={schemaVersion:'roost-compatible-recovery-negative-v1',kind,releaseId:s.releaseId,operationId:operation.id,operation:operationName,since:createdAt,requestId:operation.intent.requestId,intentDigest:d(operation.intent),targetId:t.targetId,requestedCommit:s.commit,requestedTree:s.candidateTree,phase:kind==='configuration_absent'?'entry':'candidate',configuration,queueScan,currentQueue,projectInventory:inventory,
  imageMetadata:built.map(v=>({name:v.name,imageDigest:v.imageDigest,buildRevision:s.commit,revisionLabel:s.commit,treeLabel:s.candidateTree})),database:{containerId:db.containerId,imageDigest:db.imageDigest,mountDigest:db.mountDigest,readOnlyFence:true,activeOtherSessions:0,ownedTransactions:0},ingressFence:fence,evidenceDigest:H('0')};
 const evidence={compatibleRecoveryFailure:marker,observedAt,configDigest:d([{targetId:t.targetId,configDigest:compose.composeConfigurationDigest(configuration)}]),schemaDigest:m.baseline.schemaDigest,dataDigest:m.baseline.dataDigest,sequenceDigest:entry.sequenceDigest,healthDigest:H('0'),healthy:false,currentServiceSetDigest:api.compatibleFailureServiceSetDigest(inventory.services),deploymentIds:currentQueue?[{targetId:t.targetId,deploymentId:currentQueue.deploymentId}]:[]};
 if(kind==='observation_failed'){
  const pe={healthy:true,deployedCommit:s.commit,deployedTree:s.candidateTree,artifactSetDigest:m.deployment.artifactSetDigest,configDigest:m.deployment.configDigest,schemaDigest:evidence.schemaDigest,dataDigest:evidence.dataDigest,deploymentIds:clone(evidence.deploymentIds),composeTargets:[{targetId:t.targetId,binding:{commit:s.commit,tree:s.candidateTree,queue:clone(currentQueue),images:images.map(v=>({...v,deploymentId:currentQueue.deploymentId}))},runtime:{services:images.map(v=>({...v,deploymentId:currentQueue.deploymentId}))}}]};
  deploy.outcome={id:randomUUID(),status:'succeeded',evidence:pe};marker.successfulDeployment={operationId:deploy.id,outcomeId:deploy.outcome.id,evidenceDigest:d(pe),deploymentId:currentQueue.deploymentId};marker.observationSeconds=60;
 }
 reseal(evidence);const options={now:clock,readSuccessfulDeployment:ref=>ref.operationId===deploy.id&&ref.outcomeId===deploy.outcome?.id?deploy:null};return{s,m,t,evidence,operation,deploy,options,api};
}
function reseal(e){const v=e.compatibleRecoveryFailure;v.projectInventory.digest=api.compatibleFailureInventoryDigest(v.projectInventory);v.queueScan.digest=api.compatibleFailureQueueScanDigest(v.queueScan);v.evidenceDigest=api.compatibleFailureMarkerDigest(v);e.currentServiceSetDigest=api.compatibleFailureServiceSetDigest(v.projectInventory.services);}
test('pure factory is inert and requires fixed schema/digest functions',()=>{assert.throws(()=>createCompatibleFailureContract({}));assert(Object.isFrozen(api));});
for(const kind of ['configuration_absent','deployment_absent','deployment_failed','observation_failed'])test('exact '+kind+' qualifies only terminal negative freeze',()=>{const f=compatibleFailureFixture(kind),before=clone(f.evidence);assert.equal(api.compatibleFailureEvidenceError(f.s,f.evidence,f.operation,f.options),null);assert.deepEqual(f.evidence,before);const result=api.qualifyCompatibleFailureResult(f.s,f.evidence,f.operation,f.options);assert.equal(result.status,'reconciled');assert.equal(result.reconciledStatus,kind.endsWith('_absent')?'absent':'failed');assert(result.disposition.terminalFreeze);for(const key of ['retryAllowed','rollbackAllowed','dataRestoreAllowed','successProven','releaseAuthority'])assert.equal(result.disposition[key],false);});
test('database-only absence contains four literal missing services without phantom healthy baseline',()=>{const f=compatibleFailureFixture('deployment_absent');assert.equal(f.evidence.compatibleRecoveryFailure.projectInventory.services.length,1);assert.equal(f.evidence.compatibleRecoveryFailure.projectInventory.absentServices.length,4);for(const key of ['deployedCommit','deployedTree','artifactSetDigest','deployedSetDigest'])assert.equal(f.evidence[key],undefined);assert.equal(f.evidence.healthy,false);});
test('failed partial supports a real nonDB subset only with matching explicit absences',()=>{const f=compatibleFailureFixture(),v=f.evidence.compatibleRecoveryFailure,removed=v.projectInventory.services.pop(),decl=v.configuration.services.find(p=>p.name===removed.name);v.imageMetadata=v.imageMetadata.filter(p=>p.name!==removed.name);v.projectInventory.absentServices.push({name:decl.name,role:decl.role,source:'built',mountDigest:decl.mountDigest,declarationDigest:d(decl),containerId:null,imageDigest:null,state:'absent',absenceVerified:true});reseal(f.evidence);assert.equal(api.compatibleFailureEvidenceError(f.s,f.evidence,f.operation,f.options),null);});
const changes={unknownKind:f=>f.evidence.compatibleRecoveryFailure.kind='unknown',success:f=>f.evidence.healthy=true,healthyHistorical:f=>f.evidence.deployedCommit=f.s.baseCommit,wrongRelease:f=>f.evidence.compatibleRecoveryFailure.releaseId=randomUUID(),wrongOperation:f=>f.evidence.compatibleRecoveryFailure.operationId=randomUUID(),request:f=>f.evidence.compatibleRecoveryFailure.requestId=randomUUID(),intent:f=>f.operation.intent.parameters.configDigest=H('0'),clock:f=>f.evidence.observedAt=new Date(f.options.now+1).toISOString(),stale:f=>f.options.now+=300001,
 config:f=>f.evidence.compatibleRecoveryFailure.configuration.settingsDigest=H('0'),data:f=>f.evidence.dataDigest=H('0'),schema:f=>f.evidence.schemaDigest=H('0'),sequence:f=>f.evidence.sequenceDigest=H('0'),DBcontainer:f=>f.evidence.compatibleRecoveryFailure.database.containerId=H('0'),DBimage:f=>f.evidence.compatibleRecoveryFailure.database.imageDigest=I('0'),DBmount:f=>f.evidence.compatibleRecoveryFailure.database.mountDigest=H('0'),DBwritable:f=>f.evidence.compatibleRecoveryFailure.database.readOnlyFence=false,active:f=>f.evidence.compatibleRecoveryFailure.database.activeOtherSessions=1,transaction:f=>f.evidence.compatibleRecoveryFailure.database.ownedTransactions=1,
 missingDB:f=>f.evidence.compatibleRecoveryFailure.projectInventory.services.shift(),foreignService:f=>f.evidence.compatibleRecoveryFailure.projectInventory.services[1].name='foreign',duplicateID:f=>f.evidence.compatibleRecoveryFailure.projectInventory.services[1].containerId=f.evidence.compatibleRecoveryFailure.projectInventory.services[0].containerId,unknownImage:f=>f.evidence.compatibleRecoveryFailure.projectInventory.services[1].imageDigest=I('f'),wrongBuildRevision:f=>f.evidence.compatibleRecoveryFailure.imageMetadata[0].buildRevision=f.s.baseCommit,unknownRevision:f=>f.evidence.compatibleRecoveryFailure.imageMetadata[0].buildRevision='unknown',metadataMissing:f=>f.evidence.compatibleRecoveryFailure.imageMetadata.pop(),cadenceRunning:f=>f.evidence.compatibleRecoveryFailure.projectInventory.services.find(v=>v.role==='cadence').state='running',containerAfterQueue:f=>f.evidence.compatibleRecoveryFailure.projectInventory.services[1].createdAt=f.evidence.observedAt,
 scanIncomplete:f=>f.evidence.compatibleRecoveryFailure.queueScan.scanComplete=false,scanOtherQueue:f=>f.evidence.compatibleRecoveryFailure.queueScan.rows.push({...clone(f.evidence.compatibleRecoveryFailure.currentQueue),deploymentId:'other'}),wrongQueue:f=>{f.evidence.compatibleRecoveryFailure.currentQueue.deploymentId='other';f.evidence.compatibleRecoveryFailure.queueScan.rows[0]=clone(f.evidence.compatibleRecoveryFailure.currentQueue);},queueHEAD:f=>{f.evidence.compatibleRecoveryFailure.currentQueue.commit='HEAD';f.evidence.compatibleRecoveryFailure.queueScan.rows[0]=clone(f.evidence.compatibleRecoveryFailure.currentQueue);},unknownStatus:f=>{f.evidence.compatibleRecoveryFailure.currentQueue.status='unknown';f.evidence.compatibleRecoveryFailure.queueScan.rows[0]=clone(f.evidence.compatibleRecoveryFailure.currentQueue);},missingFence:f=>delete f.evidence.compatibleRecoveryFailure.ingressFence,unheld:f=>f.evidence.compatibleRecoveryFailure.ingressFence.rulePresent=false,foreignFence:f=>f.evidence.compatibleRecoveryFailure.ingressFence.databaseContainerId=H('0')};
for(const[name,change]of Object.entries(changes))test('negative evidence refuses '+name+' and leaves uncertainty unresolved',()=>{const f=compatibleFailureFixture();change(f);reseal(f.evidence);assert.notEqual(api.compatibleFailureEvidenceError(f.s,f.evidence,f.operation,f.options),null);const r=api.qualifyCompatibleFailureResult(f.s,f.evidence,f.operation,f.options);assert.equal(r.status,'uncertain');assert.equal(r.resolved,false);assert.equal(r.retryAllowed,false);assert.equal(r.rollbackAllowed,false);assert.equal(r.releaseAuthority,false);assert.equal(r.evidence,undefined);});
for(const kind of ['configuration_absent','deployment_absent'])test('absence refuses a late queue or nonDB physical container '+kind,()=>{for(const mutate of [v=>v.queueScan.rows.push({targetId:v.targetId,deploymentId:'late',commit:v.requestedCommit,status:'queued',createdAt:v.since,finishedAt:null}),v=>v.projectInventory.services.push({...clone(v.projectInventory.services[0]),name:'app',role:'app',containerId:H('f'),imageDigest:I('7')})]){const f=compatibleFailureFixture(kind);mutate(f.evidence.compatibleRecoveryFailure);reseal(f.evidence);assert.notEqual(api.compatibleFailureEvidenceError(f.s,f.evidence,f.operation,f.options),null);}});
test('observation failure requires the actual prior successful own normal journal row',()=>{for(const change of [f=>delete f.options.readSuccessfulDeployment,f=>f.options.readSuccessfulDeployment=()=>null,f=>f.deploy.releaseId=randomUUID(),f=>f.deploy.outcome.status='failed',f=>f.deploy.outcome.id=randomUUID(),f=>f.deploy.outcome.evidence.composeTargets[0].binding.queue.deploymentId='detached',f=>f.deploy.outcome.evidence.composeTargets[0].binding.images[0].imageDigest=I('f'),f=>f.deploy.outcome.evidence.composeTargets[0].runtime.services[0].imageDigest=I('f')]){const f=compatibleFailureFixture('observation_failed');change(f);assert.notEqual(api.compatibleFailureEvidenceError(f.s,f.evidence,f.operation,f.options),null);}});
test('a partial observation marker cannot claim success, normal failure, absence or effectful reconciliation',()=>{const f=compatibleFailureFixture('observation_failed'),valid={status:'reconciled',reconciledStatus:'failed',observationOnly:true,evidence:f.evidence};assert.equal(api.compatibleFailureOutcomeError(f.s,f.operation,valid,f.options),null);for(const body of [{...valid,status:'succeeded'},{...valid,status:'failed'},{...valid,reconciledStatus:'succeeded'},{...valid,reconciledStatus:'absent'},{...valid,observationOnly:false}])assert.notEqual(api.compatibleFailureOutcomeError(f.s,f.operation,body,f.options),null);});
test('SDK/OS/signed claims and executable fields never become authority in this evidence',()=>{for(const key of ['osAttested','signedNativeVerified','command']){const f=compatibleFailureFixture();f.evidence.compatibleRecoveryFailure[key]=key==='command'?'private':true;reseal(f.evidence);assert.equal(api.compatibleFailureEvidenceSchema.safeParse(f.evidence).success,false);assert.notEqual(api.compatibleFailureEvidenceError(f.s,f.evidence,f.operation,f.options),null);}});
for(const name of ['revisionLabel','treeLabel'])test('accepted replacement metadata requires actual exact '+name+' without null fallback',()=>{for(const value of [null,'0'.repeat(40)]){const f=compatibleFailureFixture();f.evidence.compatibleRecoveryFailure.imageMetadata[0][name]=value;reseal(f.evidence);assert.notEqual(api.compatibleFailureEvidenceError(f.s,f.evidence,f.operation,f.options),null);}});
test('a fresh but different proxy/network rule cannot borrow the admitted ingress hold',()=>{const f=compatibleFailureFixture(),p=f.evidence.compatibleRecoveryFailure.ingressFence;p.namespaceDigest=H('0');p.evidenceDigest=ingress.composeIngressFenceDigest(p);reseal(f.evidence);assert.notEqual(api.compatibleFailureEvidenceError(f.s,f.evidence,f.operation,f.options),null);});
