// Counterfactual source/typed native observations only. No native/Docker/API effects.
import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {readFileSync} from 'node:fs';
import {renderActivityPythonStdin,activityRestorationDigests,activityCompatibleIngressInstallationSchema,qualifyActivityCompatibleIngressObservation} from './lib/agent-host-release-activity-installed.mjs';
import fence from './lib/agent-host-release-compose-ingress-fence.cjs';
const H=x=>x.repeat(64),hash=b=>createHash('sha256').update(b).digest('hex'),digest=v=>hash(JSON.stringify(Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b)))));
const source=readFileSync(new URL('./lib/agent-host-release-compose-ingress-runtime.py',import.meta.url),'utf8'),sourceDigest=hash(source),now=Date.parse('2026-10-06T12:00:00.000Z');
function fixture(present=true){const policy={schemaVersion:'roost-compose-proxy-network-fence-policy-v1',targetId:'example-app',networkId:H('1'),subnet:'172.20.0.0/24',proxyId:H('2'),proxyPid:4096,namespaceDigest:H('3'),databaseContainerId:H('4'),databaseIpv4:'172.20.0.12',proxyIpv4:'172.20.0.10',ruleComment:'roost-release-hold-'+'a'.repeat(32),originalRulesDigest:H('5'),controllerProgramDigest:sourceDigest};
 const args=['-d',policy.subnet,'-p','tcp','--dport','8000','-m','comment','--comment',policy.ruleComment,'-j','REJECT','--reject-with','tcp-reset'];
 const {schemaVersion:_,controllerProgramDigest:_d,...fields}=policy,receipt={schemaVersion:'roost-compose-proxy-network-fence-v1',observedAt:new Date(now).toISOString(),...fields,port:8000,ruleDigest:hash(JSON.stringify(args)),observedRulesDigest:present?H('6'):policy.originalRulesDigest,projectNetworkExclusive:true,publishedPortsAbsent:true,rulePresent:present};receipt.evidenceDigest=fence.composeIngressFenceDigest(receipt);
 return{policy,receipt,value:{schemaVersion:'roost-activity-compatible-ingress-observation-v1',controllerProgramDigest:sourceDigest,policyDigest:digest(policy),historicalIngressRuleChecked:false,originalIngressSettingsUnchanged:true,receipt}};
}
test('separate compatible installed seal does not change the original settings schema',()=>{const descriptor={policy:{file:'C:/Private/example-fence.json',sha256:H('1')},controllerProgramDigest:sourceDigest};assert(activityCompatibleIngressInstallationSchema.safeParse(descriptor).success);for(const p of['../escape.json','bad\npath','relative.json'])assert.equal(activityCompatibleIngressInstallationSchema.safeParse({...descriptor,policy:{...descriptor.policy,file:p}}).success,false);assert.equal(activityCompatibleIngressInstallationSchema.safeParse({...descriptor,module:'arbitrary'}).success,false);});
test('trusted wrapper embeds only hash-qualified fixed guard source outside native JSON input',()=>{const{policy}=fixture(),request={operation:'read_runtime_settings',compatibleIngress:{schemaVersion:'roost-activity-compatible-ingress-v1',policy,controllerProgramDigest:sourceDigest}},program=renderActivityPythonStdin('def main(): pass\n',request,{compatibleIngressSource:source});assert(program.includes("_scope['TRUSTED_COMPATIBLE_INGRESS_SOURCE']"));assert(!program.includes('172.20.0.0/24'));assert.throws(()=>renderActivityPythonStdin('def main(): pass\n',request));assert.throws(()=>renderActivityPythonStdin('def main(): pass\n',request,{compatibleIngressSource:source+'#changed'}));assert.throws(()=>renderActivityPythonStdin('def main(): pass\n',{operation:'read'},{compatibleIngressSource:source}));});
test('genuine-shaped current hold and removal observations preserve explicit historical-rule nonclaim',()=>{for(const [present,operation]of[[true,'hold_ingress'],[false,'restore_runtime']]){const f=fixture(present);const q=qualifyActivityCompatibleIngressObservation(f.value,{policy:f.policy,controllerProgramDigest:sourceDigest,operation,ingressPresent:present,now});assert.equal(q.historicalIngressRuleChecked,false);assert.equal(q.originalIngressSettingsUnchanged,true);assert.equal(q.receipt.rulePresent,present);}});
for(const [name,change]of Object.entries({proxy:f=>f.value.receipt.proxyPid++,namespace:f=>f.value.receipt.namespaceDigest=H('0'),network:f=>f.value.receipt.networkId=H('0'),database:f=>f.value.receipt.databaseContainerId=H('0'),comment:f=>f.value.receipt.ruleComment='roost-release-hold-'+'b'.repeat(32),port:f=>f.value.receipt.port=443,shared:f=>f.value.receipt.projectNetworkExclusive=false,published:f=>f.value.receipt.publishedPortsAbsent=false,stale:f=>f.value.receipt.observedAt='2026-10-06T11:00:00.000Z',future:f=>f.value.receipt.observedAt='2026-10-06T13:00:00.000Z',source:f=>f.value.controllerProgramDigest=H('0'),policy:f=>f.value.policyDigest=H('0'),oldRuleClaim:f=>f.value.historicalIngressRuleChecked=true,restamp:f=>f.value.originalIngressSettingsUnchanged=false}))test('installed native observation refuses '+name+' even after receipt reseal',()=>{const f=fixture();change(f);f.value.receipt.evidenceDigest=fence.composeIngressFenceDigest(f.value.receipt);assert.throws(()=>qualifyActivityCompatibleIngressObservation(f.value,{policy:f.policy,controllerProgramDigest:sourceDigest,operation:'read_runtime_settings',ingressPresent:true,now}));});
test('remove readback requires exact old unowned rules and cannot run under hold',()=>{const f=fixture(false);assert.throws(()=>qualifyActivityCompatibleIngressObservation(f.value,{policy:f.policy,controllerProgramDigest:sourceDigest,operation:'hold_ingress',ingressPresent:false,now}));f.value.receipt.observedRulesDigest=H('0');f.value.receipt.evidenceDigest=fence.composeIngressFenceDigest(f.value.receipt);assert.throws(()=>qualifyActivityCompatibleIngressObservation(f.value,{policy:f.policy,controllerProgramDigest:sourceDigest,operation:'restore_runtime',ingressPresent:false,now}));});
test('separate proxy policy leaves database/ingress/cadence restoration hashes byte-identical',()=>{const raw={schemaVersion:'roost-activity-runtime-settings-private-v1',targetId:'example-app',database:{containerId:H('4'),adminUser:'admin',adminDatabase:'postgres',applicationUser:'appuser',applicationDatabase:'appdb',originalRoleConfig:['search_path=public']},ingress:{chain:'INPUT',port:8000,protocol:'tcp',appContainerId:H('7'),networkId:H('1'),originalOwnedRuleAbsent:true,originalRulesDigest:H('8'),namespace:{proxyContainerId:H('9'),proxyImageDigest:'sha256:'+H('a'),proxyNetworkDigest:H('b')}},cadences:['maintenance_cadence','proactive_cadence'].map((name,i)=>({name,containerId:H(String(i+1)),imageDigest:'sha256:'+H('c'),mountDigest:H('d'),originalState:'running',originalExitCode:0,behavior:'restore_existing_loop',behaviorDigest:H('e')}))};const before=structuredClone(raw),original=activityRestorationDigests(raw);const request={runtimeSettings:raw,compatibleIngress:{policy:fixture().policy}};assert.deepEqual(activityRestorationDigests(request.runtimeSettings),original);assert.deepEqual(raw,before);assert.throws(()=>activityRestorationDigests({...raw,compatibleIngress:request.compatibleIngress}));});
