// Executable counterfactual fixed-channel fixtures, not native/effect proof.
import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash,randomUUID} from 'node:crypto';
import {fixture,hash,image} from './fixtures/release-compose-contract.cjs';
import {prepareComposePhaseConfiguration,qualifyInstalledComposePhaseIntent} from './lib/agent-host-release-compose-worker.mjs';
import {composePhaseArtifactFile,composePhaseChecksumBytes,composeReplacementImagesDigest,composePhasePolicySchema} from './lib/agent-host-release-compose-controller.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');
function setup(mode){const f=fixture(),snapshot={...structuredClone(f.s),releaseId:randomUUID()},m=snapshot.manifest,t=m.deployment.targets[0],commit=mode==='rollback'?t.baseline.commit:snapshot.commit,tree=mode==='rollback'?t.baseline.tree:snapshot.candidateTree;
 t.configuration.services.push({...structuredClone(t.configuration.services.find(r=>r.role==='cadence')),name:'scheduler'});
 const services=t.configuration.services.map(r=>({name:r.name,role:r.role,source:r.source,mountDigest:r.mountDigest,imageDigest:r.source==='image'?r.imageDigest:image('7'),imageRef:r.source==='image'?'postgres:15':image('7')})),artifactBytes=Buffer.from(JSON.stringify({services:Object.fromEntries(services.map(r=>[r.name,{image:r.imageRef}]))}));
 const policy={schemaVersion:'roost-compose-phase-policy-v1',releaseId:snapshot.releaseId,policyId:randomUUID(),targetId:t.targetId,phase:mode,commit,tree,composePath:t.composePath,baseDirectory:'/',rawCompose:false,preserveRepository:false,useBuildServer:false,originalConfigDigest:t.baseline.configDigest,phaseConfigDigest:mode==='rollback'?t.rollbackConfigDigest:t.configDigest,artifactDigest:sha(artifactBytes),rendererDigest:hash('1'),settingsInvariantDigest:hash('2'),runtimeInvariantDigest:hash('3'),sourcePins:{queueHelper:hash('4'),deploymentJob:hash('5'),applicationModel:hash('6'),composeParser:hash('7'),dockerHelper:hash('8'),applicationsController:hash('9'),controllerRenderer:hash('1')},services,...(mode==='candidate'?{candidateExecution:{mode:'qualified_immutable_images',buildProofDigest:hash('a'),replacementImagesDigest:composeReplacementImagesDigest(services.filter(r=>r.source==='built').map(r=>({name:r.name,imageDigest:r.imageDigest,commit,tree})))}}:{})};
 assert.equal(composePhasePolicySchema.safeParse(policy).success,true);
 const expected=mode==='rollback'?m.rollback:m.deployment,intent={id:randomUUID(),createdAt:'2026-10-01T12:00:00.000Z',operation:mode==='rollback'?'rollback_config':'deploy_config',intent:{parameters:{commit,configDigest:expected.configDigest,artifactSetDigest:expected.artifactSetDigest,schemaDigest:m.deployment.schemaDigest}}},current={release:{id:snapshot.releaseId,snapshot:structuredClone(Object.fromEntries(Object.entries(snapshot).filter(([k])=>k!=='releaseId')))},status:'active',journal:[intent]},calls=[];
 const checkIntent=async(options,configuration)=>{calls.push({kind:'intent',rollback:options.rollback,configuration});return qualifyInstalledComposePhaseIntent({snapshot,current,options,configuration});};
 const php=async(program,payload)=>{calls.push({kind:'stage',payload});return{staged:true};},apply=async p=>{calls.push({kind:'apply',phase:p.phase});return{route:'counterfactual_fixed_transport'};};
 return{snapshot,current,intent,policy,artifactBytes,mode,commit,checkIntent,php,stagePhp:'fixed staged artifact program fixture',apply,calls};}
for(const mode of ['candidate','rollback'])test(`actual configuration preparation stages artifact+checksum with ${mode} durable intent`,async()=>{const f=setup(mode),r=await prepareComposePhaseConfiguration(f);assert.equal(r.route,'counterfactual_fixed_transport');assert.equal(f.calls.at(-1).kind,'apply');const stages=f.calls.filter(v=>v.kind==='stage');assert.equal(stages.length,2);assert.equal(stages[0].payload.name,composePhaseArtifactFile(f.policy));assert.equal(stages[0].payload.sha256,sha(f.artifactBytes));assert.equal(stages[1].payload.name,composePhaseArtifactFile(f.policy)+'.sha256');assert.equal(Buffer.from(stages[1].payload.bytes,'base64').toString(),composePhaseChecksumBytes(f.policy).toString());assert.equal(stages[1].payload.sha256,sha(composePhaseChecksumBytes(f.policy)));assert(f.calls.filter(v=>v.kind==='intent').every(v=>v.configuration===true&&v.rollback===(mode==='rollback')));});
for(const mode of ['candidate','rollback'])test(`actual ${mode} preparation refuses opposite intent before any stage/apply`,async()=>{const f=setup(mode);f.current.journal[0].operation=mode==='rollback'?'deploy_config':'rollback_config';await assert.rejects(prepareComposePhaseConfiguration(f),/phase_intent_unproven/);assert.equal(f.calls.filter(v=>v.kind!=='intent').length,0);});
for(const when of ['artifact','checksum'])test(`changed durable intent after ${when} is refused before model CAS`,async()=>{const f=setup('candidate'),php=f.php;f.php=async(...args)=>{const r=await php(...args);if((when==='artifact')===!args[1].name.endsWith('.sha256'))f.current.journal[0]={...f.current.journal[0],id:randomUUID()};return r;};await assert.rejects(prepareComposePhaseConfiguration(f),/phase_intent_changed/);assert.equal(f.calls.some(v=>v.kind==='apply'),false);assert.equal(f.calls.filter(v=>v.kind==='stage').length,when==='artifact'?1:2);});
test('unproven checksum stage and changed artifact are never followed by apply',async()=>{const f=setup('candidate'),php=f.php;f.php=async(program,payload)=>payload.name.endsWith('.sha256')?{staged:false}:php(program,payload);await assert.rejects(prepareComposePhaseConfiguration(f),/artifact_stage_unproven/);assert.equal(f.calls.some(v=>v.kind==='apply'),false);const changed=setup('candidate');changed.artifactBytes=Buffer.from('{}');await assert.rejects(prepareComposePhaseConfiguration(changed),/phase_binding_changed/);assert.equal(changed.calls.length,0);});
test('actual durable validator refuses already uncertain, foreign scope and changed configuration tuple',async()=>{for(const change of [f=>f.current.journal[0].outcome={status:'uncertain'},f=>f.current.release.id=randomUUID(),f=>f.current.journal[0].intent.parameters.configDigest=hash('f'),f=>f.current.release.snapshot.commit='f'.repeat(40)]){const f=setup('candidate');change(f);await assert.rejects(prepareComposePhaseConfiguration(f),/phase_intent_unproven/);assert.equal(f.calls.some(v=>v.kind==='stage'||v.kind==='apply'),false);}});
