// Fictional metadata only: no API, native, model or installation effects.
import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {projectApplicationSharedRecords,restoreApplicationSharedRecords,assertApplicationSharedRecords,applicationSharedRecordsSchema,projectApplicationSharedRecordValues,restoreApplicationSharedRecordValues} from './lib/agent-host-application-shared-records.mjs';
const canonical=v=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;
const digest=v=>createHash('sha256').update(JSON.stringify(canonical(v))).digest('hex');
function fixture(descriptions=true){const domain=Array.from({length:7},(_,i)=>({id:'domain-'+i,name:'Fictional domain '+i,details:'Complete domain detail. '.repeat(8),observedAt:'2026-01-01T00:00:00.000Z'})),dimension=Array.from({length:6},(_,i)=>({id:'dimension-'+i,name:'Fictional dimension '+i,details:'Complete readiness detail. '.repeat(8)}));return{schemaVersion:'application-agent-context-v2',generatedAt:'2026-01-01T00:00:01.000Z',application:{id:'fictional-app'},targetCapabilities:Array.from({length:42},(_,i)=>({id:'capability-'+i,applicability:'required',targetState:'healthy',definition:{id:'definition-'+i,domainId:domain[i%7].id,readinessDimensionId:dimension[i%6].id,domain:structuredClone(domain[i%7]),readinessDimension:structuredClone(dimension[i%6])}})),observedCapabilities:[],gaps:[],companyRecords:descriptions?[{id:'company-1',description:'Complete fictional company details. '.repeat(10)},{id:'company-2',description:'Complete fictional company details. '.repeat(10)}]:[],authority:{releaseGranted:false},sourceClock:'2026-01-01T00:00:00.000Z'};}
function projected(){const original=fixture(),v2=projectApplicationSharedRecords(original),v3=projectApplicationSharedRecordValues(v2,v2);return{original,v2,v3};}
test('seven domains/six dimensions/one description preserve all full values, pointers, clocks and exact v2 inverse',()=>{const{original,v2,v3}=projected(),before=structuredClone(v2);assert.equal(v2.applicationSharedRecords.schemaVersion,'roost-application-shared-records-v2');assert.deepEqual([v3.applicationSharedRecords.domain.length,v3.applicationSharedRecords.readinessDimension.length,v3.applicationSharedRecords.companyDescription.length],[7,6,1]);assert.equal(v3.applicationSharedRecords.sourceTableVersion,'v2');assert.equal(v3.applicationSharedRecords.valueDigestAlgorithm,'canonical-json-sha256');assert.equal(v3.applicationSharedRecords.originalDigest,v2.applicationSharedRecords.originalDigest);for(const field of ['domain','readinessDimension','companyDescription']){assert.deepEqual(v3.applicationSharedRecords[field],v2.applicationSharedRecords[field].map(({value})=>({value})));for(const row of v3.applicationSharedRecords[field])assert.deepEqual(Object.keys(row),['value']);}assert.deepEqual(v2,before);assert.deepEqual(restoreApplicationSharedRecordValues(v3,v2),v2);assert.deepEqual(restoreApplicationSharedRecords(v3),original);assert.equal(assertApplicationSharedRecords(v3),true);assert.deepEqual(projectApplicationSharedRecordValues(v3,v2),v3);});
test('14-row model projection saves enough bytes without changing any value or original digest',()=>{const{v2,v3}=projected(),saved=Buffer.byteLength(JSON.stringify(v2))-Buffer.byteLength(JSON.stringify(v3));assert.equal(saved,991);assert(saved>850);});
test('v1 literal table is restored exactly; existing v1/v2 projectors remain unchanged',()=>{const original=fixture(false),v1=projectApplicationSharedRecords(original);assert.equal(v1.applicationSharedRecords.schemaVersion,'roost-application-shared-records-v1');const v3=projectApplicationSharedRecordValues(v1,v1);assert.equal(v3.applicationSharedRecords.sourceTableVersion,'v1');assert.deepEqual(restoreApplicationSharedRecordValues(v3,v1),v1);assert.deepEqual(restoreApplicationSharedRecords(v3),original);assert.deepEqual(projectApplicationSharedRecords(v1),v1);const{v2}=projected();assert.deepEqual(projectApplicationSharedRecords(v2),v2);});
test('unshared full context stays inline with caller equality and no mutation',()=>{const original=fixture();original.targetCapabilities=original.targetCapabilities.slice(0,1);original.companyRecords=[];const inline=projectApplicationSharedRecords(original);assert.equal(inline.applicationSharedRecords,undefined);assert.deepEqual(projectApplicationSharedRecordValues(inline,inline),inline);});
test('projection requires caller-held original and rejects stale original or altered source digest',()=>{const{v2,v3}=projected();assert.throws(()=>projectApplicationSharedRecordValues(v2));assert.throws(()=>projectApplicationSharedRecordValues(v3));const wrong=structuredClone(v2);wrong.sourceClock='2026-01-02T00:00:00.000Z';assert.throws(()=>projectApplicationSharedRecordValues(v2,wrong));assert.throws(()=>restoreApplicationSharedRecordValues(v3,wrong));v2.applicationSharedRecords.domain[0].digest='f'.repeat(64);assert.throws(()=>projectApplicationSharedRecordValues(v2,v2));});
const bad={unknownMetadata:x=>x.applicationSharedRecords.extra=true,wrongAlgorithm:x=>x.applicationSharedRecords.valueDigestAlgorithm='sha256',missingAlgorithm:x=>delete x.applicationSharedRecords.valueDigestAlgorithm,missingVersion:x=>delete x.applicationSharedRecords.sourceTableVersion,unknownVersion:x=>x.applicationSharedRecords.sourceTableVersion='v4',wrongVersion:x=>x.applicationSharedRecords.sourceTableVersion='v1',literalDerivedHash:x=>x.applicationSharedRecords.domain[0].digest='a'.repeat(64),extraEntry:x=>x.applicationSharedRecords.domain[0].extra=true,missingEntry:x=>x.applicationSharedRecords.domain.pop(),alteredRecord:x=>x.applicationSharedRecords.domain[0].value.name+=' changed',alteredDescription:x=>x.applicationSharedRecords.companyDescription[0].value+=' changed',staleOriginalDigest:x=>x.applicationSharedRecords.originalDigest='b'.repeat(64),wrongIndex:x=>x.targetCapabilities[0].definition.domain.sharedRecord=6,unknownIndex:x=>x.targetCapabilities[0].definition.domain.sharedRecord=999,extraPointer:x=>x.targetCapabilities[0].definition.domain.extra=true,duplicateIdentity:x=>x.applicationSharedRecords.domain.push(structuredClone(x.applicationSharedRecords.domain[0])),duplicateDescription:x=>x.applicationSharedRecords.companyDescription.push(structuredClone(x.applicationSharedRecords.companyDescription[0])),changedUnshared:x=>x.authority.releaseGranted=true,nonJsonValue:x=>x.applicationSharedRecords.domain[0].value.invalid=undefined};
for(const[name,mutate]of Object.entries(bad))test('v3 refuses '+name+' without accepting regenerated per-entry hashes',()=>{const{v2,v3}=projected();mutate(v3);assert.throws(()=>restoreApplicationSharedRecordValues(v3,v2));assert.throws(()=>restoreApplicationSharedRecords(v3));});
test('singleton table and all-inline partial sharing refuse before original-context equality',()=>{for(const edit of [x=>{x.targetCapabilities=x.targetCapabilities.filter((row,i)=>i===0||i%7!==0);},x=>{x.targetCapabilities[0].definition.domain=structuredClone(x.applicationSharedRecords.domain[0].value);}]){const{v2,v3}=projected();edit(v3);assert.throws(()=>restoreApplicationSharedRecordValues(v3,v2));}});
test('strict public table schema accepts value-only v3 and refuses original entry digests/unknown fields',()=>{const{v3}=projected();assert.equal(applicationSharedRecordsSchema.safeParse(v3.applicationSharedRecords).success,true);v3.applicationSharedRecords.domain[0].digest='a'.repeat(64);assert.equal(applicationSharedRecordsSchema.safeParse(v3.applicationSharedRecords).success,false);});
test('caller original rejects a fully self-consistent substituted context even when full source digest is recalculated',()=>{const{v2}=projected(),substituted=restoreApplicationSharedRecords(v2);substituted.authority.releaseGranted=true;const forged=projectApplicationSharedRecords(substituted),v3=projectApplicationSharedRecordValues(forged,forged);assert.equal(digest(restoreApplicationSharedRecords(v3)),v3.applicationSharedRecords.originalDigest);assert.throws(()=>projectApplicationSharedRecordValues(v3,v2));assert.throws(()=>restoreApplicationSharedRecordValues(v3,v2));});
