// Synthetic normal API/native metadata and owned temporary repository only.
// No model, API, real app, native Job or external Git/network operation occurs.
import test from 'node:test';import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import childProcess from 'node:child_process';
import {createHash} from 'node:crypto';import {syncBuiltinESMExports} from 'node:module';
import {isPrimaryReadOnlyReview,qualifyPrimaryReadOnlyReviewMaterial,verifiedCodeReviewerPriorAudit,
  primaryReadOnlyReviewedSchema} from './lib/agent-host-code-reviewer-prior-audit.mjs';
import {collectReadOnlyRepositoryEvidence} from './lib/agent-host-readonly-boundary.mjs';
import {nativeDigest} from './lib/agent-host-native-footprint.mjs';
import {prepareProviderInput,providerInputSchema,measureProviderInput} from './lib/agent-host-provider-input.mjs';
import {codeReviewReferenceMatches,validateCodeReviewView,prepareCodeReviewDecision} from './lib/agent-host-code-reviewer.mjs';
import {validPacketFixture,pinReadyFixture} from './fixtures/execution-packet.mjs';
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,h=n=>String(n).repeat(64),sha=b=>createHash('sha256').update(b).digest('hex'),head='a'.repeat(40);
function fixture({commit=head,branch='codex/readonly-primary',tree=h(2),evidenceDigest=h(3),mapped=false}={}){
 const access={sandbox:'read-only',externalWrites:false,tools:['repository_read'],permissions:['repository_read']},previous={access,assignment:{agentId:id(6)},taskRoles:{executor:{id:id(6)},verifier:{id:id(14)}},modelSelection:{schemaVersion:'roost-managed-hermes-backend-v1',backend:'codex_responses'},singleTask:{branch},context:{company:[{id:id(7),revision:'v1'}],product:[],technical:[]},nativeBoundary:{profile:'inspect-readonly',runtime:{required:false,ports:[]},inspectReadOnly:{kind:'auditor'},readPaths:['audit.md']}};
 const receipt={schemaVersion:'roost-readonly-audit-v1',verdict:'verified',evidenceDigest,preTree:tree,postTree:tree,processState:'unchanged',dockerState:'unchanged',gitState:'unchanged',nativeTools:[],processCoverage:'listening_tcp_plus_owned_job_zero_processes',dockerCoverage:'running_container_list'};receipt.digest=sha(JSON.stringify(receipt));
 const prior={id:id(1),taskId:id(2),workspaceId:id(3),applicationId:id(4),agentHostId:id(5),status:'completed',attempt:1,checkpointVersion:3,completedAt:'2026-01-01T00:00:00.000Z',contextInvalidatedAt:null,errorState:null,leaseToken:null,leaseExpiresAt:null,changedFiles:[],finalResponse:'CHANGES_REQUIRED\nThe exact controlled recovery scope needs its remaining runtime proof; this source does not grant release authority.',metadata:{executionContract:previous,readyContextPin:{pinId:id(80),revision:h(3),compositionSeal:h(4),riskAdmissionSeal:h(5),riskAdmissionCommit:commit},resultRevision:{schemaVersion:'roost-result-revision-v1',id:id(9),executionId:id(1),hostId:id(5),attempt:1,checkpointVersion:3,observedAt:'2026-01-01T00:00:00.000Z',branch,commit,workingTree:'clean'}},verification:{readOnlyAudit:receipt,managedAdmission:{revision:3,decisionId:id(10),qualification:'signed_native_v1',evidenceDigest:h(6),jobSourceDigest:h(7)},ownedTreeReceipt:{version:'roost-windows-job-v2',attempt:id(1),type:'receipt',job:id(11),assignedBeforeResume:true,killOnClose:true,breakaway:false,controllerInJob:true,inheritedJob:true,rootPid:100,rootCreationTime:'123456789012345678',launcherPid:101,launcherCreationTime:'123456789012345677',resumed:true,rootExit:0,activeProcesses:0,jobClosed:true,cleanup:true,cleanupMs:0,stdoutBytes:100,stderrBytes:0,terminationReason:'root_exit',resumeReceipt:h(8),executableDigest:h(9),launcherSha256:'b'.repeat(64),sourceSha256:h(7)}}};
 const inspection={kind:'code-reviewer',verifiedTaskId:prior.taskId,verifiedExecutionId:prior.id,verifiedEvidenceDigest:'c'.repeat(64),baselineCommit:commit,reviewedCommit:commit,priorAudit:{executionId:prior.id,receiptDigest:receipt.digest}},repositoryEvidence={schemaVersion:'roost-readonly-repository-evidence-v1',head:commit,branch,tree,processDigest:h(4),dockerDigest:h(5),files:[{path:'audit.md',mimeType:'text/plain',content:'Scoped own-source fixture.\n',sha256:sha('Scoped own-source fixture.\n')}]};repositoryEvidence.digest=nativeDigest(repositoryEvidence);
 const result={executionId:prior.id,taskId:prior.taskId,applicationId:prior.applicationId,attempt:prior.attempt,checkpointVersion:prior.checkpointVersion,completedAt:prior.completedAt,finalResponse:prior.finalResponse,changedFiles:[],verification:structuredClone(prior.verification),contract:structuredClone(previous),pin:structuredClone(prior.metadata.readyContextPin),resultRevision:structuredClone(prior.metadata.resultRevision)},view={task:{id:prior.taskId,workspaceId:prior.workspaceId},result,canReview:true,reason:'verifier_required',roleIssues:[],basisCurrent:false,materialVersion:inspection.verifiedEvidenceDigest,approvalCommit:commit,expectedVersion:h(6),grantAccess:{review_decision:{status:'active',grantId:id(19)}}};
 if(mapped){view.basisCurrent=true;view.materialVersion='d'.repeat(64);result.basisRevalidation={id:id(20),originalPinId:result.pin.pinId,originalRevision:result.pin.revision,originalMaterialVersion:inspection.verifiedEvidenceDigest,readyPinId:id(21),readyRevision:h(4),readyPinDigest:h(5),commit,actorUserId:id(22),createdAt:'2026-01-02T00:00:00.000Z'};}
 return{prior,inspection,repositoryEvidence,view};
}
test('explicit existing-contract tuple qualifies readonly primary with no coding receipts or fake diff',()=>{const f=fixture(),out=qualifyPrimaryReadOnlyReviewMaterial(f.view,f.inspection,f.repositoryEvidence);assert.equal(isPrimaryReadOnlyReview(f.inspection),true);assert.equal(out.resultKind,'readonly-audit');assert.equal(out.diff,'');assert.equal(out.diffDigest,sha(''));assert.deepEqual(out.changedFiles,[]);for(const key of['codingTests','localCommit','nativeReview','diffCertificate'])assert.equal(Object.hasOwn(out,key),false);assert.equal(primaryReadOnlyReviewedSchema.safeParse(out).success,true);});
test('mapped primary preserves original reference while normal decision binds current material',()=>{const f=fixture({mapped:true}),out=qualifyPrimaryReadOnlyReviewMaterial(f.view,f.inspection,f.repositoryEvidence);assert.equal(codeReviewReferenceMatches(f.view,f.inspection),true);validateCodeReviewView(f.view,f.inspection,id(14));assert.equal(out.originalMaterialVersion,f.inspection.verifiedEvidenceDigest);assert.equal(out.materialVersion,f.view.materialVersion);assert.notEqual(out.materialVersion,out.originalMaterialVersion);const finalResponse=JSON.stringify({decision:'approve',reviewedCommit:f.inspection.reviewedCommit,evidenceDigest:f.view.materialVersion,summary:'Independently assessed actual read-only evidence',evidence:[{kind:'test',reference:'Supplied readonly native receipt',result:'Observed closed unchanged source receipt',verdict:'pass'}]});const decision=prepareCodeReviewDecision({finalResponse,view:f.view,review:f.inspection,config:{agentId:id(14),grantId:id(19)},readOnlyAudit:{verifiedExecutionId:f.prior.id,reviewedCommit:f.inspection.reviewedCommit,verifiedEvidenceDigest:f.view.materialVersion}});assert.equal(decision.materialVersion,out.materialVersion);});
for(const[name,mutate]of[
 ['no pinned prior',f=>delete f.inspection.priorAudit],['supplementary other audit',f=>f.inspection.priorAudit.executionId=id(99)],['different baseline',f=>f.inspection.baselineCommit='b'.repeat(40)],['wrong normal execution',f=>f.view.result.executionId=id(99)],['wrong normal task',f=>f.view.result.taskId=id(99)],['not current reviewer',f=>f.view.canReview=false],['stale result',f=>f.view.reason='stale_result'],['blocked grant',f=>f.view.grantAccess.review_decision.status='blocked'],['coding source profile',f=>f.view.result.contract.nativeBoundary.profile='coding-local'],['verifier source kind',f=>f.view.result.contract.nativeBoundary.inspectReadOnly.kind='verifier'],['changed files',f=>f.view.result.changedFiles=['audit.md']],['fake coding tests',f=>f.view.result.verification.codingTests={passed:true}],['fake local commit',f=>f.view.result.verification.localCommit={commit:head}],['fake coding native review',f=>f.view.result.verification.nativeReviewReceipt={verdict:'verified_candidate'}],['boundary failure',f=>f.view.result.verification.outcome='boundary_violation'],['unsigned managed source',f=>f.view.result.verification.managedAdmission.qualification='boolean'],['managed source digest changed',f=>f.view.result.verification.managedAdmission.jobSourceDigest=h(8)],['job still active',f=>f.view.result.verification.ownedTreeReceipt.activeProcesses=1],['job exit failure',f=>f.view.result.verification.ownedTreeReceipt.rootExit=1],['changed tree',f=>f.view.result.verification.readOnlyAudit.postTree=h(4)],['changed original receipt',f=>f.view.result.verification.readOnlyAudit.evidenceDigest=h(4)],['wrong pinned receipt',f=>f.inspection.priorAudit.receiptDigest=h(4)],['wrong source repository tree',f=>f.repositoryEvidence.tree=h(4)],['wrong result commit',f=>f.view.result.resultRevision.commit='b'.repeat(40)],['wrong original Ready commit',f=>f.view.result.pin.riskAdmissionCommit='b'.repeat(40)],['result attempt substituted',f=>f.view.result.attempt=2],['result checkpoint substituted',f=>f.view.result.checkpointVersion=4]
])test('readonly primary refuses '+name,()=>{const f=fixture();mutate(f);assert.throws(()=>qualifyPrimaryReadOnlyReviewMaterial(f.view,f.inspection,f.repositoryEvidence),/code_reviewer_prior_audit_invalid/);});
function providerFixture(mapped=false){const f=fixture({mapped}),packet=validPacketFixture(),c=packet.packet.contract;const original=structuredClone(c.access);c.nativeBoundary={profile:'inspect-readonly',readPaths:['audit.md'],runtime:{required:false,ports:[]},inspectReadOnly:f.inspection};c.access={...original,sandbox:'read-only',tools:['repository_read'],permissions:['repository_read'],externalWrites:false};packet.packet.procedureComposition.fields.tools=['repository_read'];f.prior.taskId=id(52);f.inspection.verifiedTaskId=id(52);f.view.task.id=id(52);f.view.result.taskId=id(52);f.prior.metadata.executionContract.taskRoles.verifier.id=c.assignment.agentId;f.view.result.contract.taskRoles.verifier.id=c.assignment.agentId;f.prior.workspaceId=packet.claimed.workspaceId;f.prior.applicationId=packet.claimed.applicationId;f.prior.agentHostId=packet.claimed.agentHostId;f.prior.metadata.resultRevision.hostId=packet.claimed.agentHostId;f.prior.metadata.executionContract.singleTask.branch=c.singleTask.branch;f.prior.metadata.resultRevision.branch=c.singleTask.branch;f.view.task.workspaceId=packet.claimed.workspaceId;f.view.result.applicationId=packet.claimed.applicationId;f.view.result.contract.singleTask.branch=c.singleTask.branch;f.view.result.resultRevision.hostId=packet.claimed.agentHostId;f.view.result.resultRevision.branch=c.singleTask.branch;f.repositoryEvidence.branch=c.singleTask.branch;f.repositoryEvidence.reviewed=qualifyPrimaryReadOnlyReviewMaterial(f.view,f.inspection,f.repositoryEvidence);const{digest,...body}=f.repositoryEvidence;f.repositoryEvidence.digest=nativeDigest(body);pinReadyFixture(packet);const prior=verifiedCodeReviewerPriorAudit(f.prior,{claimed:packet.claimed,contract:c,repositoryEvidence:f.repositoryEvidence});return{f,packet,options:{fresh:{taskContext:packet.taskContext,applicationContext:packet.applicationContext},claimed:packet.claimed,currentCommit:head,assertAuthority(){},repositoryEvidence:f.repositoryEvidence,codeReviewerPriorAudit:prior}};}
test('provider joins compact primary pointer to full independently verified source packet and emits truthful readonly rules',()=>{for(const mapped of[false,true]){const x=providerFixture(mapped),input=prepareProviderInput(x.options),r=input.evidence.repositoryInspection.value.reviewed;assert.equal(r.resultKind,'readonly-audit');assert.equal(r.primaryAudit.packetDigest,input.evidence.codeReviewerPriorAudit.value.digest);assert.equal(input.evidence.codeReviewerPriorAudit.value.finalResponse,x.f.prior.finalResponse);assert.equal(input.rules.some(s=>s.includes('diff, tests and coding receipt')),false);assert(input.rules.some(s=>s.includes('No coding tests, local commit')));assert.equal(measureProviderInput(x.options).withinLimit,true);assert.equal(input.evidence.codeReviewerPriorAudit.value.authority,false);}});
for(const[name,mutate]of[
 ['missing full prior',i=>delete i.evidence.codeReviewerPriorAudit],['wrong primary packet digest',i=>i.evidence.repositoryInspection.value.reviewed.primaryAudit.packetDigest=h(9)],['wrong receipt pointer',i=>i.evidence.repositoryInspection.value.reviewed.primaryAudit.receiptDigest=h(9)],['wrong material direct',i=>i.evidence.repositoryInspection.value.reviewed.materialVersion=h(9)],['empty diff changed',i=>i.evidence.repositoryInspection.value.reviewed.diff='invented patch'],['empty diff digest wrong',i=>i.evidence.repositoryInspection.value.reviewed.diffDigest=h(9)],['fake coding in primary',i=>i.evidence.repositoryInspection.value.reviewed.codingTests={passed:true}],['nonprimary contract',i=>i.contract.nativeBoundary.inspectReadOnly.baselineCommit='b'.repeat(40)],['same reviewer task',i=>i.identity.taskId=i.evidence.codeReviewerPriorAudit.value.identity.taskId],['same audit actor',i=>i.contract.assignment.agentId=i.evidence.codeReviewerPriorAudit.value.identity.auditorAgentId]
])test('provider primary rejects '+name,()=>{const i=structuredClone(prepareProviderInput(providerFixture().options));mutate(i);assert.equal(providerInputSchema.safeParse(i).success,false);});
test('mapped primary packet binds immutable original Ready, not just any mapping UUID',()=>{const base=prepareProviderInput(providerFixture(true).options);for(const mutate of[r=>r.basisRevalidation.originalPinId=id(99),r=>r.basisRevalidation.originalRevision=h(9),r=>r.basisRevalidation.createdAt='2025-01-01T00:00:00Z',r=>r.originalMaterialVersion=h(9),r=>r.basisCurrent=false]){const input=structuredClone(base);mutate(input.evidence.repositoryInspection.value.reviewed);assert.equal(providerInputSchema.safeParse(input).success,false);}});
function repositoryFixture(t){const parent=fs.realpathSync.native(os.tmpdir()),root=fs.mkdtempSync(path.join(parent,'roost-readonly-primary-')),original=childProcess.execFileSync,git=(...args)=>original('git',['-c','core.hooksPath=','-c','core.autocrlf=false','-c','user.name=Synthetic','-c','user.email=fixture@example.invalid',...args],{cwd:root,windowsHide:true,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();fs.writeFileSync(path.join(root,'audit.md'),'Scoped own-source fixture.\n');git('init','-b','codex/readonly-primary');git('add','.');git('commit','-m','Synthetic own source');git('remote','add','origin','https://github.com/example/readonly-primary');const expected={head:git('rev-parse','HEAD'),branch:'codex/readonly-primary',origin:'https://github.com/example/readonly-primary'};let diffCalls=0;childProcess.execFileSync=(command,args,options)=>{if(command==='docker'&&args?.[0]==='ps')return '';if(command==='powershell'&&args?.at(-1)?.startsWith('Get-NetTCPConnection -State Listen'))return '';if(command==='git'&&args.includes('diff'))diffCalls++;return original(command,args,options);};syncBuiltinESMExports();t.after(()=>{childProcess.execFileSync=original;syncBuiltinESMExports();assert.equal(path.dirname(fs.realpathSync.native(root)),parent);assert(path.basename(root).startsWith('roost-readonly-primary-'));fs.rmSync(root,{recursive:true,force:false});});return{root,expected,diffCalls:()=>diffCalls};}
test('native collector integrates readonly primary without parent/diff/coding finalization, leaving actual owned repository untouched',t=>{const r=repositoryFixture(t),before=fs.readFileSync(path.join(r.root,'audit.md')),baseline=collectReadOnlyRepositoryEvidence({repositoryPath:r.root,expected:r.expected,paths:['audit.md']}),f=fixture({commit:r.expected.head,branch:r.expected.branch,tree:baseline.tree,evidenceDigest:baseline.digest}),e=collectReadOnlyRepositoryEvidence({repositoryPath:r.root,expected:r.expected,paths:['audit.md'],reviewMaterial:f.view,review:f.inspection});assert.equal(e.reviewed.resultKind,'readonly-audit');assert.equal(e.reviewed.diff,'');assert.equal(e.reviewed.diffDigest,sha(''));assert.equal(r.diffCalls(),0);assert.deepEqual(fs.readFileSync(path.join(r.root,'audit.md')),before);assert.equal(e.tree,baseline.tree);});
test('ordinary coding collector still refuses absent coding tests/local commit and does not fallback to primary',t=>{const r=repositoryFixture(t),baseline=collectReadOnlyRepositoryEvidence({repositoryPath:r.root,expected:r.expected,paths:['audit.md']}),f=fixture({commit:r.expected.head,branch:r.expected.branch,tree:baseline.tree,evidenceDigest:baseline.digest});delete f.inspection.priorAudit;assert.throws(()=>collectReadOnlyRepositoryEvidence({repositoryPath:r.root,expected:r.expected,paths:['audit.md'],reviewMaterial:f.view,review:f.inspection}),e=>e.message==='readonly_boundary_unproven'&&e.details.reason==='review_material_mismatch');});
