// Static source review only. No PostgreSQL connection/DDL, API or native effect.
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';
const sql=readFileSync(new URL('../prisma/migrations/20261006213000_compose_compatible_artifact_recovery/migration.sql',import.meta.url),'utf8');
const source=readFileSync(new URL('./lib/agent-host-release-compatible-failure.cjs',import.meta.url),'utf8');
const body=name=>{const start=sql.indexOf('CREATE FUNCTION '+name+'(');assert(start>=0,name);const end=sql.indexOf('END $$;',start);assert(end>start,name);return sql.slice(start,end);};
test('negative migration adds no data mutation or old-function replacement and remains one transaction',()=>{assert.match(sql,/^BEGIN;/);assert.match(sql,/COMMIT;\s*$/);assert.doesNotMatch(sql.replace(/--[^\n]*/g,''),/\b(?:DROP|TRUNCATE|ALTER|INSERT\s+INTO|UPDATE\s+\w+\s+SET|DELETE\s+FROM)\b/i);assert.doesNotMatch(sql,/CREATE\s+OR\s+REPLACE/i);assert.equal((sql.match(/CREATE TRIGGER/g)||[]).length,4);assert.equal((sql.match(/\$\$/g)||[]).length%2,0);});
test('negative branch is opt-in and independently qualified before unchanged positive/current basis block',()=>{const b=body('governed_release_compatible_outcome_guard');assert(b.indexOf("IF r.snapshot?'compatibleArtifactRecovery'")<b.indexOf("IF e?'compatibleRecoveryFailure'"));assert(b.indexOf('negative_valid(r,o,e,NEW.status,NEW.reconciled_status,NEW.observation_only)')<b.indexOf('governed_release_compatible_basis_valid'));assert.match(b,/negative_valid[^;]+IS DISTINCT FROM TRUE/);assert.match(b,/RAISE EXCEPTION 'governed_release_compatible_negative_unproven';END IF;\s+RETURN NEW;/);assert(b.includes("IF NEW.status='succeeded' OR NEW.status='reconciled' AND NEW.reconciled_status='succeeded'"));});
test('negative outcome is read-only reconciled absent/failed only, no success/uncertainty or NULL escape',()=>{const b=body('governed_release_compatible_negative_contents_valid');for(const marker of["status IS DISTINCT FROM 'reconciled'",'observation_only IS DISTINCT FROM TRUE',"reconciled_status IS NULL OR reconciled_status NOT IN ('absent','failed')",'EXCEPTION WHEN OTHERS THEN RETURN FALSE'])assert(b.includes(marker),marker);assert(!b.includes('RETURN NULL'));assert(b.includes("reconciled_status IS DISTINCT FROM 'absent'"));assert(b.includes("reconciled_status IS DISTINCT FROM 'failed'"));});
test('frozen CJS marker fields and four kinds have explicit SQL joins and no historical success substitute',()=>{const b=body('governed_release_compatible_negative_contents_valid');for(const name of['configuration_absent','deployment_absent','deployment_failed','observation_failed']){assert(source.includes("'"+name+"'"));assert(b.includes("'"+name+"'"));}for(const marker of['intentDigest','requestId','requestedCommit','requestedTree','configuration','projectInventory','queueScan','currentQueue','imageMetadata','ingressFence','successfulDeployment','observationSeconds'])assert(b.includes("'"+marker+"'"),marker);assert(b.includes('governed_release_compose_queue_digest(o.intent)'));assert(b.includes('o.request_id::text'));assert(b.includes('governed_release_compatible_iso(o.created_at)'));assert(b.includes("e->'healthy' IS DISTINCT FROM 'false'::jsonb"));assert(!b.includes('healthyRollbackProven'));});
test('historical lineage remains bound but current review/credential/backup lifetime does not block a negative read',()=>{const b=body('governed_release_compatible_negative_lineage_valid');for(const marker of['requestDigest','recordDigest','metadataDigest','privateSignedRecordDigest','sourceBasisDigest','scopeBasisDigest','governed_release_failed_closures','governed_release_revocations','governed_release_compose_failed_rollback_partial_closure_valid','task_review_decisions','source_review.material_version','scope_review.material_version'])assert(b.includes(marker),marker);assert.doesNotMatch(b,/governed_release_compatible_execution_current|completed_result_basis_current|task_review_material\(|workspace_memberships|owner_user_id=|24 hours|expires_at|api_keys/);assert(b.includes("p->'serverOperatingSystemAttestation' IS DISTINCT FROM 'false'::jsonb"));assert(b.includes("p->'serverPrivateSignatureVerification' IS DISTINCT FROM 'false'::jsonb"));});
test('complete actual inventory and explicit absences reject borrowed/missing identities and active cadences',()=>{const b=body('governed_release_compatible_negative_contents_valid');for(const marker of['jsonb_array_length(inv->\'services\')+jsonb_array_length(inv->\'absentServices\')<>5','cardinality(names)<>5',"row->'containerId' IS DISTINCT FROM 'null'::jsonb","row->'imageDigest' IS DISTINCT FROM 'null'::jsonb","row->'absenceVerified' IS DISTINCT FROM 'true'::jsonb",'declarationDigest',"row->>'state' NOT IN ('created','paused','exited')","row->'health' IS DISTINCT FROM 'null'::jsonb","row->'exitCode' IS DISTINCT FROM '0'::jsonb"])assert(b.includes(marker),marker);assert(b.includes("row->>'name'=ANY(names)"));assert(b.includes('count(DISTINCT value->>\'containerId\')'));});
test('protected DB/data/sequence and exact current proxy fence are independently required',()=>{const b=body('governed_release_compatible_negative_contents_valid');for(const marker of["v->'database'->'readOnlyFence' IS DISTINCT FROM 'true'::jsonb","v->'database'->'activeOtherSessions' IS DISTINCT FROM '0'::jsonb","v->'database'->'ownedTransactions' IS DISTINCT FROM '0'::jsonb",'schemaDigest','dataDigest','sequenceDigest','governed_release_compatible_fence_valid',"(v->'ingressFence')-ARRAY['observedAt','evidenceDigest'] IS DISTINCT FROM (c->'currentEntry'->'ingressFence')-ARRAY['observedAt','evidenceDigest']"])assert(b.includes(marker),marker);assert(b.includes("db->key IS DISTINCT FROM c->'currentEntry'->'database'->key"));});
test('complete queue scan permits exactly zero for ABSENT or one exact terminal target queue for FAILED',()=>{const b=body('governed_release_compatible_negative_contents_valid');for(const marker of["scan->'scanComplete' IS DISTINCT FROM 'true'::jsonb","jsonb_array_length(scan->'rows')>32","jsonb_array_length(scan->'rows')<>0","jsonb_array_length(scan->'rows')<>1","scan->'rows'->0 IS DISTINCT FROM q",'negative_queue_valid(row,target',"q->>'status' IS DISTINCT FROM 'failed'","q->>'status' IS DISTINCT FROM 'finished'",'deployment_op_id::text'])assert(b.includes(marker),marker);assert(b.includes("jsonb_build_array(r.id::text,deployment_op_id::text,target,'candidate')"));assert(b.includes("scan->>'from' IS DISTINCT FROM governed_release_compatible_iso"));});
test('new image metadata requires exact SHA/tree; observation failure joins genuine earlier latest deployment evidence twice',()=>{const b=body('governed_release_compatible_negative_contents_valid');for(const marker of["metadata->'buildRevision' IS DISTINCT FROM s->'commit'","metadata->'revisionLabel' IS DISTINCT FROM s->'commit'","metadata->'treeLabel' IS DISTINCT FROM s->'candidateTree'",'prior_op.sequence>=o.sequence','prior_x.id IS DISTINCT FROM (SELECT id FROM governed_release_outcomes','prior_op.intent->\'parameters\'->\'artifactSetDigest\'','prior_x.evidence','bound IS DISTINCT FROM images','live IS DISTINCT FROM images',"pe->'composeTargets'->0->'binding'->'queue' IS DISTINCT FROM q"])assert(b.includes(marker),marker);});
test('all new clocks are finite explicit ISO timestamps; inventory/scan/fence/output bounded to five-minute actual reads',()=>{const b=body('governed_release_compatible_negative_contents_valid'),t=body('governed_release_compatible_negative_time');assert(t.includes('isfinite'));assert(t.includes('EXCEPTION WHEN OTHERS THEN RETURN FALSE'));assert(b.includes("through_at>now() OR through_at<now()-interval '5 minutes'"));for(const field of["inv->'observedAt'","scan->'from'","scan->'observedAt'","row->'createdAt'","v->'ingressFence'->'observedAt'"])assert(b.includes('negative_time('+field+') IS DISTINCT FROM TRUE'));});
test('applied recovery-only predecessor is unchanged and review labels SQL extension unverified',()=>{const sha=b=>createHash('sha256').update(b).digest('hex');assert.equal(sha(readFileSync(new URL('../prisma/migrations/20261006203000_compose_recovery_only/migration.sql',import.meta.url))),'9762315cd0b92684a7e6157edaa57ddc5e0a0164f234063b00210b5b08ab23e5');const review=readFileSync(new URL('../prisma/migrations/20261006213000_compose_compatible_artifact_recovery/loss-review.md',import.meta.url),'utf8');assert(review.includes('not yet rehearsed'));assert(review.includes('Earlier 14 PostgreSQL probes'));assert(review.includes('They do **not** verify this extension'));});

test('final validator always ANDs admitted lineage and fresh contents; component cannot authorize a stored outcome',()=>{const b=body('governed_release_compatible_negative_valid');assert(b.includes('governed_release_compatible_negative_lineage_valid(r) IS DISTINCT FROM TRUE'));assert(b.includes('governed_release_compatible_negative_contents_valid(r,o,e,status,reconciled_status,observation_only) IS DISTINCT FROM TRUE'));assert(b.includes('EXCEPTION WHEN OTHERS THEN RETURN FALSE'));assert(!body('governed_release_compatible_outcome_guard').includes('IF governed_release_compatible_negative_contents_valid'));});
