// Pure and source-scope tests only: no PHP, database, network or native effects.
import test from 'node:test';
import assert from 'node:assert/strict';
import {composeConfigurationSchemaFields as fields,qualifyComposeConfigurationSchema as qualify,
 composeConfigurationSchemaReadPhp as readPhp,composeConfigurationSchemaInstallationPhp as installationPhp,
 qualifyComposeConfigurationSchemaInstallationReceipt as receipt,
 prepareComposeConfigurationSchemaInstallationRequest as request} from './lib/agent-host-release-compose-config-schema.mjs';
const schema=type=>fields.map(name=>({name,type,maxLength:type==='text'?null:255}));
const data=()=>({count:3,digest:'a'.repeat(64)});
function proof(operation='rehearse',before=schema('character varying')){return{operation,changed:before[0].type==='character varying',rolledBack:operation==='rehearse',committed:operation==='apply',beforeSchema:before,testedSchema:schema('text'),finalSchema:operation==='rehearse'?before:schema('text'),before:data(),after:data(),final:data(),queueIdle:true,ownedFields:fields.slice(),rawRowsIncluded:false};}
test('exact two TEXT columns qualify capacity, legacy255 needs explicit installation',()=>{assert.equal(qualify(schema('text')).capacityQualified,true);assert.throws(()=>qualify(schema('character varying')),/capacity_insufficient/);assert.equal(qualify(schema('character varying'),{requireText:false}).installationChangeRequired,true);});
for(const mutate of [x=>x.pop(),x=>x.push({...x[0]}),x=>x[0].name='git_commit_sha',x=>x[0].type='jsonb',x=>x[0].maxLength=256,x=>x[0].maxLength='255',x=>x[0].table='other',x=>x[0]={name:fields[0],type:'text',maxLength:null}])test('missing, unsupported, extra, mixed or wrong column metadata refused',()=>{const s=schema('character varying');mutate(s);assert.throws(()=>qualify(s,{requireText:false}));});
test('rollback rehearsal proves TEXT temporarily but preserves original schema/data',()=>{const p=proof(),q=receipt(p,{operation:'rehearse',expectedSchema:schema('character varying')});assert.equal(q.rolledBack,true);assert.equal(q.committed,false);assert.equal(q.capacityQualified,false);assert.equal(q.automaticRuntimeMigration,false);assert.equal(q.dataCount,3);});
test('apply requires prior successful exact rollback rehearsal and pins full data preimage',()=>{assert.deepEqual(request({operation:'rehearse',expectedSchema:schema('character varying')}),{operation:'rehearse',expectedSchema:schema('character varying'),expectedData:null});assert.deepEqual(request({operation:'apply',expectedSchema:schema('character varying'),rehearsalReceipt:proof()}),{operation:'apply',expectedSchema:schema('character varying'),expectedData:data()});assert.equal(receipt(proof('apply'),{operation:'apply',expectedSchema:schema('character varying')}).capacityQualified,true);});
test('already TEXT is idempotent and receipt claims no DDL change',()=>{const p=proof('rehearse',schema('text'));assert.equal(p.changed,false);assert.equal(receipt(p,{operation:'rehearse',expectedSchema:schema('text')}).capacityQualified,true);const a=proof('apply',schema('text'));assert.equal(receipt(a,{operation:'apply',expectedSchema:schema('text')}).committed,true);});
for(const mutate of [x=>x.before.count++,x=>x.after.digest='b'.repeat(64),x=>x.final.count++,x=>x.queueIdle=false,x=>x.rawRowsIncluded=true,x=>x.rolledBack=false,x=>x.committed=true,x=>x.changed=false,x=>x.testedSchema=schema('character varying'),x=>x.finalSchema=schema('text'),x=>x.ownedFields=['git_commit_sha'],x=>x.rows=[],x=>x.before.count=-1,x=>x.before.digest='raw'])test('changed data/schema, missing rollback or forged extra receipt fields cannot authorize apply',()=>{const p=proof();mutate(p);assert.throws(()=>request({operation:'apply',expectedSchema:schema('character varying'),rehearsalReceipt:p}));});
test('uncertain or missing rehearsal outcome is never retried or treated as authorization',()=>{for(const p of [undefined,null,{}, {...proof(),operation:'uncertain'}])assert.throws(()=>request({operation:'apply',expectedSchema:schema('character varying'),rehearsalReceipt:p}));assert.throws(()=>request({operation:'retry',expectedSchema:schema('character varying')}));});
test('fixed readonly metadata query emits only owned name/type/max',()=>{assert.match(readPhp,/table_name='applications'/);assert.match(readPhp,/table_schema=current_schema\(\)/);assert.match(readPhp,/column_name AS name,data_type AS type,character_maximum_length/);assert.doesNotMatch(readPhp,/ALTER TABLE|UPDATE |DELETE |INSERT /);});
test('explicit installation locks and widens ONLY exact two existing columns, without arbitrary SQL selectors',()=>{const alter=[...installationPhp.matchAll(/ALTER TABLE applications ALTER COLUMN ([a-z_]+) TYPE text/g)].map(x=>x[1]);assert.deepEqual(alter,fields);assert.match(installationPhp,/lock_timeout='5s'/);assert.match(installationPhp,/statement_timeout='30s'/);assert.match(installationPhp,/LOCK TABLE applications IN ACCESS EXCLUSIVE MODE/);assert.match(installationPhp,/LOCK TABLE application_deployment_queues IN SHARE MODE/);assert.match(installationPhp,/schema_preimage/);assert.match(installationPhp,/if\(\$changed\)/);assert.match(installationPhp,/if\(\$p\['operation'\]==='rehearse'\)\$connection->rollBack\(\);else \$connection->commit\(\)/);assert.match(installationPhp,/rehearsal_data_changed/);assert.doesNotMatch(installationPhp,/DROP |TRUNCATE |ADD COLUMN|UPDATE applications|DELETE FROM|INSERT INTO/);});
test('full application row fingerprints cover before/tested/final states with no raw row output',()=>{assert.match(installationPhp,/SELECT to_jsonb\(a\)::text AS row FROM applications a ORDER BY id/);assert.match(installationPhp,/hash_init\('sha256'\)/);assert.match(installationPhp,/\$before!==\$after/);assert.match(installationPhp,/\$before!==\$final/);assert.match(installationPhp,/'rawRowsIncluded'=>false/);assert.match(installationPhp,/if\(\$connection->transactionLevel\(\)>0\)\$connection->rollBack\(\)/);assert.doesNotMatch(installationPhp,/getMessage\(\)|echo \$r->row/);});
test('views, missing tables, nonPostgreSQL connections and nested transactions are not installation targets',()=>{assert.match(readPhp,/table_type='BASE TABLE'/);assert.match(readPhp,/schema_table/);assert.match(installationPhp,/installation_tables/);assert.match(installationPhp,/getDriverName\(\)!=='pgsql'/);assert.match(installationPhp,/transactionLevel\(\)!==0/);});
