import test from 'node:test';import assert from 'node:assert/strict';
import{mkdtempSync,readFileSync,writeFileSync,rmSync,readdirSync}from'node:fs';import{tmpdir}from'node:os';import path from'node:path';
import{createCipheriv,createDecipheriv,randomBytes}from'node:crypto';
import{createTerminalCompletionStore,createTerminalCompletionIntent,loadTerminalCompletionIntent,submitTerminalCompletion,reconcileTerminalCompletion,terminalCompletionMatches,terminalCompletionTimeoutMs}from'./lib/agent-host-terminal-completion.mjs';
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
function sample(){const execution={id:id(1),workspaceId:id(2),taskId:id(3),applicationId:id(4),agentHostId:id(5),attempt:1,checkpointVersion:4,status:'running',leaseToken:'fictional-lease-value',leaseExpiresAt:new Date(Date.now()+60000).toISOString(),codexThreadId:null,contextInvalidatedAt:null,cancelRequestedAt:null};const payload={leaseToken:execution.leaseToken,summary:'Bounded readonly review completed.',finalResponse:'A finite model result.',changedFiles:[],verification:{ownedTreeReceipt:{jobClosed:true,rootExit:0,activeProcesses:0},readOnlyAudit:{verdict:'verified',preTree:'a'.repeat(64),postTree:'a'.repeat(64)},codeReviewDecision:{id:id(7),decision:'approve'}},usage:{inputTokens:10,outputTokens:2},resultRevision:{commit:'a'.repeat(40),branch:'codex/task-'+id(3),workingTree:'clean'},metadata:{repositoryPathLabel:'example',transportAccounting:{retries:0}}};return{execution,payload};}
function completed({execution,payload}){return{...execution,status:'completed',leaseToken:null,leaseExpiresAt:null,completedAt:new Date().toISOString(),summary:payload.summary,finalResponse:payload.finalResponse,changedFiles:payload.changedFiles,verification:payload.verification,usage:payload.usage,metadata:{...payload.metadata,resultRevision:{schemaVersion:'roost-result-revision-v1',id:id(9),executionId:execution.id,attempt:execution.attempt,hostId:execution.agentHostId,checkpointVersion:execution.checkpointVersion,observedAt:new Date().toISOString(),...payload.resultRevision},resultRevisionReviewVersion:'1'}};}
function expected(x){const e=x.execution;return{scope:{executionId:e.id,workspaceId:e.workspaceId,taskId:e.taskId,applicationId:e.applicationId,agentHostId:e.agentHostId,attempt:e.attempt,checkpointVersion:e.checkpointVersion},payload:x.payload,previousThreadId:null};}
function setup(t){const directory=mkdtempSync(path.join(tmpdir(),'roost-terminal-test-'));t.after(()=>rmSync(directory,{recursive:true,force:true}));const key=randomBytes(32);const store=createTerminalCompletionStore({protect:async(b,e)=>{const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',key,iv);c.setAAD(e);return Buffer.concat([iv,c.update(b),c.final(),c.getAuthTag()]);},unprotect:async(b,e)=>{const c=createDecipheriv('aes-256-gcm',key,b.subarray(0,12));c.setAAD(e);c.setAuthTag(b.subarray(-16));return Buffer.concat([c.update(b.subarray(12,-16)),c.final()]);}});return{directory,store};}
test('exact completed proof permits harmless JSON object key ordering',()=>{const x=sample(),actual=completed(x);actual.verification={codeReviewDecision:actual.verification.codeReviewDecision,readOnlyAudit:actual.verification.readOnlyAudit,ownedTreeReceipt:actual.verification.ownedTreeReceipt};assert.equal(terminalCompletionMatches(actual,expected(x)),true);assert.equal(terminalCompletionTimeoutMs,30000);});
for(const[field,edit]of[
 ['FAILED',e=>e.status='failed'],['active',e=>e.status='running'],['wrong execution',e=>e.id=id(10)],['wrong workspace',e=>e.workspaceId=id(10)],['wrong host',e=>e.agentHostId=id(10)],['attempt',e=>e.attempt=2],['checkpoint',e=>e.checkpointVersion++],['lease retained',e=>e.leaseToken='retained'],['lease expiry retained',e=>e.leaseExpiresAt=new Date().toISOString()],['context invalidated',e=>e.contextInvalidatedAt=new Date().toISOString()],['summary',e=>e.summary='different'],['final response',e=>e.finalResponse='different'],['changed files',e=>e.changedFiles=['changed.ts']],['native receipt',e=>e.verification.ownedTreeReceipt.rootExit=1],['readOnly proof',e=>e.verification.readOnlyAudit.postTree='b'.repeat(64)],['review decision',e=>e.verification.codeReviewDecision.id=id(10)],['usage',e=>e.usage.outputTokens++],['branch',e=>e.metadata.resultRevision.branch='wrong'],['commit',e=>e.metadata.resultRevision.commit='b'.repeat(40)],['tree status',e=>e.metadata.resultRevision.workingTree='dirty'],['generated revision host',e=>e.metadata.resultRevision.hostId=id(10)],['generated revision checkpoint',e=>e.metadata.resultRevision.checkpointVersion++],['missing native metadata',e=>delete e.metadata.transportAccounting],['revision review protocol',e=>delete e.metadata.resultRevisionReviewVersion]
])test('completion rejects '+field,()=>{const x=sample(),actual=structuredClone(completed(x));edit(actual);assert.equal(terminalCompletionMatches(actual,expected(x)),false);});
test('encrypted durable intent contains no lease, summary, model text or native receipt plaintext',async t=>{const{directory,store}=setup(t),x=sample(),intent=await store.create({directory,...x});const bytes=readFileSync(path.join(directory,readdirSync(directory)[0]));for(const secret of[x.payload.leaseToken,x.payload.summary,x.payload.finalResponse,'ownedTreeReceipt'])assert.ok(!bytes.includes(secret));assert.equal(Object.hasOwn(intent,'payload'),false);const loaded=await store.load({directory,executionId:x.execution.id});assert.equal(loaded.intentDigest,intent.intentDigest);});
test('intent precedes the only POST and exact ack does not need another GET',async t=>{const{directory,store}=setup(t),x=sample(),intent=await store.create({directory,...x});let calls=0;const result=await submitTerminalCompletion({intent,api:async(route,o)=>{calls++;assert.match(route,/actions\/complete$/);assert.equal(o.method,'POST');assert.deepEqual(JSON.parse(o.body),x.payload);assert.ok(o.signal instanceof AbortSignal);assert.equal(readdirSync(directory).length,2);return completed(x);}});assert.equal(calls,1);assert.equal(result.verified,true);assert.equal(result.source,'normal_completion_ack');await assert.rejects(submitTerminalCompletion({intent,api:async()=>{throw Error('must not call');}}),e=>e.terminalCompletionUncertain&&e.retryable===false);});
test('lost POST response reconciles committed proof by GET without replay',async t=>{const{directory,store}=setup(t),x=sample(),intent=await store.create({directory,...x}),calls=[];const result=await submitTerminalCompletion({intent,api:async(route,o)=>{calls.push(o?.method??'GET');if(o?.method==='POST')throw Object.assign(Error('aborted'),{name:'TimeoutError'});assert.ok(!o.body);return completed(x);}});assert.deepEqual(calls,['POST','GET']);assert.equal(result.source,'normal_readback');});
test('completion ack beyond the former ten-second limit remains qualified by thirty-second signal',async t=>{const{directory,store}=setup(t),x=sample(),intent=await store.create({directory,...x});const result=await submitTerminalCompletion({intent,api:async(_,o)=>{assert.equal(o.method,'POST');await new Promise(resolve=>setTimeout(resolve,10100));assert.equal(o.signal.aborted,false);return completed(x);}});assert.equal(result.source,'normal_completion_ack');});
test('loaded DPAPI-bound scope supports GET-only observation and retains exact completion proof',async t=>{const{directory,store}=setup(t),x=sample();await store.create({directory,...x});const loaded=await store.load({directory,executionId:x.execution.id});let calls=0;const r=await reconcileTerminalCompletion({intent:loaded,api:async(route,o)=>{calls++;assert.equal(route,'/v1/agent-runtime/executions/'+x.execution.id);assert.equal(o.method,undefined);return completed(x);}});assert.equal(calls,1);assert.equal(r.verified,true);});
test('definite context invalidation preserves ordinary context-stop acknowledgement without GET',async t=>{const{directory,store}=setup(t),x=sample(),intent=await store.create({directory,...x}),error=Object.assign(Error('agent_execution_context_invalidated'),{contextStop:true});let calls=0;await assert.rejects(submitTerminalCompletion({intent,api:async(_,o)=>{calls++;assert.equal(o.method,'POST');throw error;}}),e=>e===error&&e.contextStop===true&&!e.terminalCompletionUncertain);assert.equal(calls,1);});
test('uncertain active result remains retained and never triggers fail or second complete',async t=>{const{directory,store}=setup(t),x=sample(),intent=await store.create({directory,...x}),calls=[];await assert.rejects(submitTerminalCompletion({intent,api:async(route,o)=>{calls.push(route);if(o?.method==='POST')throw Error('network');return x.execution;}}),e=>e.terminalCompletionUncertain&&e.details.phase==='terminal_completion'&&!e.retryable);assert.equal(calls.length,2);assert.ok(calls.every(r=>!r.includes('/fail')));});
test('readback-only recovery cannot promote FAILED, and sends no POST',async t=>{const{directory,store}=setup(t),x=sample(),intent=await store.create({directory,...x});let calls=0;await assert.rejects(reconcileTerminalCompletion({intent,api:async(_,o)=>{calls++;assert.equal(o.method,undefined);return{...completed(x),status:'failed'};}}),e=>e.terminalCompletionUncertain);assert.equal(calls,1);});
test('wrong ack requires bounded GET and unresolved proof fails closed',async t=>{const{directory,store}=setup(t),x=sample(),intent=await store.create({directory,...x});let calls=0;await assert.rejects(submitTerminalCompletion({intent,api:async()=>{calls++;return{...completed(x),verification:{}};}}),e=>e.terminalCompletionUncertain);assert.equal(calls,2);});
test('unavailable readback cannot become success or invoke fail',async t=>{const{directory,store}=setup(t),x=sample(),intent=await store.create({directory,...x});await assert.rejects(reconcileTerminalCompletion({intent,api:async()=>{throw Error('unavailable');}}),e=>e.details.reason==='completion_readback_unavailable');});
test('tampered sealed file prevents any POST or GET',async t=>{const{directory,store}=setup(t),x=sample(),intent=await store.create({directory,...x}),f=path.join(directory,readdirSync(directory)[0]);const r=JSON.parse(readFileSync(f));r.payloadDigest='0'.repeat(64);writeFileSync(f,JSON.stringify(r));let called=false;await assert.rejects(submitTerminalCompletion({intent,api:async()=>{called=true;}}));assert.equal(called,false);await assert.rejects(store.load({directory,executionId:x.execution.id}));});
test('same scope cannot overwrite original intent',async t=>{const{directory,store}=setup(t),x=sample();await store.create({directory,...x});await assert.rejects(store.create({directory,...x}));assert.equal(readdirSync(directory).length,1);});
for(const[reason,edit]of[['lease mismatch',x=>x.payload.leaseToken='other'],['expired lease',x=>x.execution.leaseExpiresAt='2020-01-01T00:00:00Z'],['terminal status',x=>x.execution.status='completed'],['protected metadata',x=>x.payload.metadata.readyContextPin={forged:true}],['extra field',x=>x.payload.apiKey='fictional-key']])test('store refuses '+reason,async t=>{const{directory,store}=setup(t),x=sample();edit(x);await assert.rejects(store.create({directory,...x}));assert.equal(readdirSync(directory).length,0);});
test('fixed Windows DPAPI CurrentUser roundtrip is private and loadable',{skip:process.platform!=='win32'},async t=>{const directory=mkdtempSync(path.join(tmpdir(),'roost-terminal-dpapi-test-'));t.after(()=>rmSync(directory,{recursive:true,force:true}));const x=sample(),intent=await createTerminalCompletionIntent({directory,...x}),loaded=await loadTerminalCompletionIntent({directory,executionId:x.execution.id});assert.equal(loaded.intentDigest,intent.intentDigest);const b=readFileSync(path.join(directory,readdirSync(directory)[0]));assert.ok(!b.includes(x.payload.leaseToken));});
