import test from 'node:test';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {configureComposeWithQualifiedModelCas,composeConfigurationCasPhp,composeConfigurationProductionPhp,isExplicitConfigurationValidationRejection} from './lib/agent-host-release-compose-config.mjs';
import {renderComposePhaseCommands,composeMountDigest} from './lib/agent-host-release-compose-controller.mjs';
const h=c=>c.repeat(64),sha=c=>c.repeat(40),digest=b=>createHash('sha256').update(b).digest('hex');
function fixture(phase='candidate'){
 const policy={schemaVersion:'roost-compose-phase-policy-v1',releaseId:'12345678-1234-1234-1234-123456789abc',policyId:'22345678-1234-1234-1234-123456789abc',targetId:'fixtureapp',phase,commit:sha('c'),tree:sha('e'),composePath:'/docker-compose.yml',baseDirectory:'/',rawCompose:false,preserveRepository:false,useBuildServer:false,originalConfigDigest:h('1'),phaseConfigDigest:h('2'),artifactDigest:h('3'),rendererDigest:h('f'),settingsInvariantDigest:h('a'),runtimeInvariantDigest:h('b'),sourcePins:{queueHelper:h('3'),deploymentJob:h('4'),applicationModel:h('5'),composeParser:h('6'),dockerHelper:h('7'),applicationsController:h('8'),controllerRenderer:h('f')},services:[{name:'app',role:'app',source:'built',imageDigest:`sha256:${h('a')}`,imageRef:`fixtureapp_app:${sha('c')}`,mountDigest:composeMountDigest([])},{name:'migrate',role:'migration',source:'built',imageDigest:`sha256:${h('b')}`,imageRef:`fixtureapp_migrate:${sha('c')}`,mountDigest:composeMountDigest([])},{name:'db',role:'database',source:'image',imageDigest:`sha256:${h('d')}`,imageRef:'postgres:15',mountDigest:composeMountDigest([])}]};
 const commands=renderComposePhaseCommands(policy),scope={targetId:'fixtureapp',repositoryPath:'fictional/repository',branch:'main'},before={uuid:'fixtureapp',git_commit_sha:sha('0'),docker_compose_custom_build_command:'',docker_compose_custom_start_command:''},desired={git_commit_sha:policy.commit,docker_compose_custom_build_command:commands.build,docker_compose_custom_start_command:commands.start};
 return {policy,scope,before,desired,payload:{targetId:policy.targetId,composePath:policy.composePath,repositoryPath:scope.repositoryPath,branch:scope.branch,expectedFields:{git_commit_sha:before.git_commit_sha,docker_compose_custom_build_command:'',docker_compose_custom_start_command:''},fields:desired,sourcePins:policy.sourcePins,settingsInvariantDigest:policy.settingsInvariantDigest,runtimeInvariantDigest:policy.runtimeInvariantDigest,buildCommandDigest:digest(commands.build),startCommandDigest:digest(commands.start)}};
}
const rejected=()=>Object.assign(Error('release_coolify_response_unproven'),{httpStatus:422});
function harness(f=fixture()){
 let state=structuredClone(f.before);const calls=[];
 return {...f,calls,change:v=>{state={...state,...v};},readApplication:async()=>{calls.push('read');return {...state};},patchApplication:async body=>{calls.push('patch');assert.deepEqual(body,f.desired);throw rejected();},beforeEffect:async()=>{calls.push('guard');},php:async(source,p)=>{assert.equal(source,composeConfigurationProductionPhp);calls.push(p.operation);assert.deepEqual(p.fields,f.desired);if(p.operation==='qualify')return {validationRejected:true,rejectedFields:['docker_compose_custom_build_command','docker_compose_custom_start_command']};state={uuid:'fixtureapp',...p.fields};return {applied:true,targetId:'fixtureapp'};}};
}
test('normal HTTPS success never invokes the installed CAS route',async()=>{const f=harness();f.patchApplication=async()=>{f.calls.push('patch');};assert.deepEqual(await configureComposeWithQualifiedModelCas(f),{route:'normal_https'});assert.deepEqual(f.calls,['read','guard','patch']);});
for(const phase of ['candidate','rollback'])test(`new exact 422 qualifies ${phase} fixed commands and one transaction`,async()=>{const f=harness(fixture(phase));assert.deepEqual(await configureComposeWithQualifiedModelCas(f),{route:'qualified_installed_model_cas',validationRulesChanged:false});assert.deepEqual(f.calls,['read','guard','patch','read','qualify','guard','apply','read']);});
for(const error of [Error('timeout'),Object.assign(Error('release_coolify_response_unproven'),{httpStatus:500}),Object.assign(Error('release_coolify_response_unproven'),{httpStatus:403}),Object.assign(Error('other'),{httpStatus:422}),Object.assign(Error('release_coolify_response_unproven'),{transportDiagnostic:'response_unproven_http_422'})])test(`uncertain or unqualified error does not enter CAS: ${error.message}/${error.httpStatus}`,async()=>{const f=harness();f.patchApplication=async()=>{throw error;};await assert.rejects(configureComposeWithQualifiedModelCas(f),e=>e===error);assert.deepEqual(f.calls,['read','guard']);assert.equal(isExplicitConfigurationValidationRejection(error),false);});
test('changed normal HTTPS preimage after rejection refuses any installed operation',async()=>{const f=harness();f.patchApplication=async()=>{f.change({git_commit_sha:sha('9')});throw rejected();};await assert.rejects(configureComposeWithQualifiedModelCas(f),/result_uncertain/);assert(!f.calls.includes('qualify'));});
test('readonly validator qualification is mandatory before apply',async()=>{const f=harness();f.php=async()=>({validationRejected:false});await assert.rejects(configureComposeWithQualifiedModelCas(f),/identity_invalid/);assert(!f.calls.includes('apply'));});
test('current intent must still hold immediately before model transaction',async()=>{const f=harness();let count=0;f.beforeEffect=async()=>{if(++count===2)throw Error('intent_changed');};await assert.rejects(configureComposeWithQualifiedModelCas(f),/intent_changed/);assert(!f.calls.includes('apply'));});
test('unknown transaction outcome preserves cause and cannot replay',async()=>{const f=harness();const original=f.php,err=Error('bounded_failure');f.php=async(s,p)=>{if(p.operation==='apply')throw err;return original(s,p);};await assert.rejects(configureComposeWithQualifiedModelCas(f),e=>e.message==='release_compose_controller_result_uncertain'&&e.cause===err&&e.uncertain===true&&e.retryable===false);});
test('posttransaction HTTPS verification rejects inconsistent actual fields',async()=>{const f=harness();const original=f.php;f.php=async(s,p)=>{const v=await original(s,p);if(p.operation==='apply')f.change({docker_compose_custom_start_command:''});return v;};await assert.rejects(configureComposeWithQualifiedModelCas(f),/result_uncertain/);assert.equal(f.calls.filter(c=>c==='apply').length,1);});
function runPhp(mode){
 const f=fixture(),input=Buffer.from(JSON.stringify({payload:f.payload,mode})).toString('base64');
 const program=composeConfigurationCasPhp+String.raw`
 class FixtureApplication {public $data;public $saves=0;public $mode;function __construct($d,$m){$this->data=$d;$this->mode=$m;}function __get($k){return $this->data[$k]??null;}function __set($k,$v){$this->data[$k]=$v;}function attributesToArray(){return $this->data;}function save(){$this->saves++;$this->data['updated_at']='later';if($this->mode==='save_other')$this->data['protected']='changed';}}
 $input=json_decode(base64_decode('`+input+String.raw`'),true);$p=$input['payload'];$mode=$input['mode'];$a=new FixtureApplication(array_merge($p['expectedFields'],['uuid'=>$p['targetId'],'build_pack'=>'dockercompose','docker_compose_location'=>$p['composePath'],'git_repository'=>$p['repositoryPath'],'git_branch'=>$p['branch'],'protected'=>'unchanged','updated_at'=>'before']),$mode);$original=$a->data;
 if($mode==='target')$a->data['uuid']='unrelated';if($mode==='preimage')$a->data['git_commit_sha']=str_repeat('9',40);if($mode==='command')$p['buildCommandDigest']=str_repeat('9',64);
 $readSource=function($path)use($p,$mode){return $mode==='source'?str_repeat('9',64):$p['sourcePins'][str_contains($path,'Models')?'applicationModel':'applicationsController'];};
 $validate=function($body)use($mode){if($mode==='passed')return []; $f=[];foreach(['docker_compose_custom_build_command','docker_compose_custom_start_command']as$k){$f[$k]=['Regex'=>[]];if(strlen($body[$k])>1000)$f[$k]['Max']=[1000];}if($mode==='unknown_rule')$f['docker_compose_custom_build_command']['Other']=[];return $f;};
 $invariants=fn($a)=>['settingsInvariantDigest'=>$mode==='invariant'?str_repeat('9',64):$p['settingsInvariantDigest'],'runtimeInvariantDigest'=>$p['runtimeInvariantDigest']];
 $transaction=function($run)use($a){$snapshot=$a->data;try{return $run();}catch(Throwable$e){$a->data=$snapshot;throw $e;}};
 $load=function($id)use($a,$mode){if($mode==='race')$a->data['git_commit_sha']=str_repeat('7',40);return $a;};
 try{$r=roost_compose_config_cas($p,$readSource,$validate,$invariants,$transaction,$load);echo json_encode(['passed'=>true,'applied'=>$r['applied'],'saves'=>$a->saves,'fieldsExact'=>roost_compose_config_fields($a)===$p['fields'],'protectedUnchanged'=>$a->data['protected']===$original['protected']]);}catch(Throwable$e){echo json_encode(['passed'=>false,'reason'=>$e->getMessage(),'saves'=>$a->saves,'protectedUnchanged'=>$a->data['protected']===$original['protected']]);}`;
 return JSON.parse(execFileSync('php',['-r',program],{encoding:'utf8',timeout:10000,maxBuffer:65536}));
}
test('actual PHP transaction changes exactly the three owned model fields',()=>{assert.deepEqual(runPhp('positive'),{passed:true,applied:true,saves:1,fieldsExact:true,protectedUnchanged:true});});
for(const mode of ['target','source','preimage','command','invariant','passed','unknown_rule','race'])test(`actual PHP denies ${mode} before save`,()=>{const r=runPhp(mode);assert.equal(r.passed,false);assert.equal(r.saves,0);assert.equal(r.protectedUnchanged,true);});
test('actual PHP transaction rolls back any protected field mutation',()=>{const r=runPhp('save_other');assert.equal(r.passed,false);assert.equal(r.reason,'other_field');assert.equal(r.protectedUnchanged,true);});
test('fixed production gateway uses normal model row lock and actual Laravel validator',()=>{assert.match(composeConfigurationProductionPhp,/lockForUpdate\(\)->firstOrFail/);assert.match(composeConfigurationProductionPhp,/DB::transaction/);assert.match(composeConfigurationProductionPhp,/Validator::make\(\$body,\$rules\)/);assert.match(composeConfigurationProductionPhp,/\$validator->passes\(\);return \$validator->failed\(\)/);assert.doesNotMatch(composeConfigurationProductionPhp,/DB::statement|ALTER TABLE|UPDATE applications|validator.*remove/);});
test('production PHP executes lazy validation before reading failed rules',()=>{
 const definitions=composeConfigurationProductionPhp.slice(0,composeConfigurationProductionPhp.indexOf("if($p['operation']==='qualify')"));
 const program=String.raw`namespace Illuminate\Support\Facades {class Validator {public $validated=false;static function make($body,$rules){return new self;}function passes(){$this->validated=true;return false;}function failed(){return $this->validated?['docker_compose_custom_build_command'=>['Regex'=>[]],'docker_compose_custom_start_command'=>['Regex'=>[]]]:[];}}}namespace {function sharedDataApplications(){$r=['nullable','string','max:1000','regex:/^safe$/'];return ['docker_compose_custom_build_command'=>$r,'docker_compose_custom_start_command'=>$r];}`+definitions+String.raw`echo json_encode($validate([]));}`;
 const failures=JSON.parse(execFileSync('php',['-r',program],{encoding:'utf8',timeout:10000,maxBuffer:65536}));
 assert.deepEqual(Object.keys(failures),['docker_compose_custom_build_command','docker_compose_custom_start_command']);
});
