// Fictional normal/native metadata only; no API/model/native process calls.
import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {validPacketFixture,pinReadyFixture} from './fixtures/execution-packet.mjs';
import {qualifyPrimaryReadOnlyReviewMaterial,verifiedCodeReviewerPriorAudit} from './lib/agent-host-code-reviewer-prior-audit.mjs';
import {nativeDigest} from './lib/agent-host-native-footprint.mjs';
import {prepareProviderInput,measureProviderInput,providerInputSchema,primaryReadOnlyProviderRules} from './lib/agent-host-provider-input.mjs';
import {projectProviderComposedInstructions,restoreProviderComposedInstructions,assertProviderComposedInstructions,providerComposedInstructionRule} from './lib/agent-host-provider-composed-instructions.mjs';
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,h=n=>String(n).repeat(64),sha=b=>createHash('sha256').update(b).digest('hex'),head='a'.repeat(40);
function fixture({commit=head,branch='codex/readonly-primary',tree=h(2),evidenceDigest=h(3),mapped=false}={}){
 const access={sandbox:'read-only',externalWrites:false,tools:['repository_read'],permissions:['repository_read']},previous={access,assignment:{agentId:id(6)},taskRoles:{executor:{id:id(6)},verifier:{id:id(14)}},modelSelection:{schemaVersion:'roost-managed-hermes-backend-v1',backend:'codex_responses'},singleTask:{branch},context:{company:[{id:id(7),revision:'v1'}],product:[],technical:[]},nativeBoundary:{profile:'inspect-readonly',runtime:{required:false,ports:[]},inspectReadOnly:{kind:'auditor'},readPaths:['audit.md']}};
 const receipt={schemaVersion:'roost-readonly-audit-v1',verdict:'verified',evidenceDigest,preTree:tree,postTree:tree,processState:'unchanged',dockerState:'unchanged',gitState:'unchanged',nativeTools:[],processCoverage:'listening_tcp_plus_owned_job_zero_processes',dockerCoverage:'running_container_list'};receipt.digest=sha(JSON.stringify(receipt));
 const prior={id:id(1),taskId:id(2),workspaceId:id(3),applicationId:id(4),agentHostId:id(5),status:'completed',attempt:1,checkpointVersion:3,completedAt:'2026-01-01T00:00:00.000Z',contextInvalidatedAt:null,errorState:null,leaseToken:null,leaseExpiresAt:null,changedFiles:[],finalResponse:'CHANGES_REQUIRED\nThe exact controlled recovery scope needs its remaining runtime proof; this source does not grant release authority.',metadata:{executionContract:previous,readyContextPin:{pinId:id(80),revision:h(3),compositionSeal:h(4),riskAdmissionSeal:h(5),riskAdmissionCommit:commit},resultRevision:{schemaVersion:'roost-result-revision-v1',id:id(9),executionId:id(1),hostId:id(5),attempt:1,checkpointVersion:3,observedAt:'2026-01-01T00:00:00.000Z',branch,commit,workingTree:'clean'}},verification:{readOnlyAudit:receipt,managedAdmission:{revision:3,decisionId:id(10),qualification:'signed_native_v1',evidenceDigest:h(6),jobSourceDigest:h(7)},ownedTreeReceipt:{version:'roost-windows-job-v2',attempt:id(1),type:'receipt',job:id(11),assignedBeforeResume:true,killOnClose:true,breakaway:false,controllerInJob:true,inheritedJob:true,rootPid:100,rootCreationTime:'123456789012345678',launcherPid:101,launcherCreationTime:'123456789012345677',resumed:true,rootExit:0,activeProcesses:0,jobClosed:true,cleanup:true,cleanupMs:0,stdoutBytes:100,stderrBytes:0,terminationReason:'root_exit',resumeReceipt:h(8),executableDigest:h(9),launcherSha256:'b'.repeat(64),sourceSha256:h(7)}}};
 const inspection={kind:'code-reviewer',verifiedTaskId:prior.taskId,verifiedExecutionId:prior.id,verifiedEvidenceDigest:'c'.repeat(64),baselineCommit:commit,reviewedCommit:commit,priorAudit:{executionId:prior.id,receiptDigest:receipt.digest}},repositoryEvidence={schemaVersion:'roost-readonly-repository-evidence-v1',head:commit,branch,tree,processDigest:h(4),dockerDigest:h(5),files:[{path:'audit.md',mimeType:'text/plain',content:'Scoped own-source fixture.\n',sha256:sha('Scoped own-source fixture.\n')}]};repositoryEvidence.digest=nativeDigest(repositoryEvidence);
 const result={executionId:prior.id,taskId:prior.taskId,applicationId:prior.applicationId,attempt:prior.attempt,checkpointVersion:prior.checkpointVersion,completedAt:prior.completedAt,finalResponse:prior.finalResponse,changedFiles:[],verification:structuredClone(prior.verification),contract:structuredClone(previous),pin:structuredClone(prior.metadata.readyContextPin),resultRevision:structuredClone(prior.metadata.resultRevision)},view={task:{id:prior.taskId,workspaceId:prior.workspaceId},result,canReview:true,reason:'verifier_required',roleIssues:[],basisCurrent:false,materialVersion:inspection.verifiedEvidenceDigest,approvalCommit:commit,expectedVersion:h(6),grantAccess:{review_decision:{status:'active',grantId:id(19)}}};
 if(mapped){view.basisCurrent=true;view.materialVersion='d'.repeat(64);result.basisRevalidation={id:id(20),originalPinId:result.pin.pinId,originalRevision:result.pin.revision,originalMaterialVersion:inspection.verifiedEvidenceDigest,readyPinId:id(21),readyRevision:h(4),readyPinDigest:h(5),commit,actorUserId:id(22),createdAt:'2026-01-02T00:00:00.000Z'};}
 return{prior,inspection,repositoryEvidence,view};
}
function providerFixture(mapped=false){const f=fixture({mapped}),packet=validPacketFixture(),c=packet.packet.contract;const original=structuredClone(c.access);c.nativeBoundary={profile:'inspect-readonly',readPaths:['audit.md'],runtime:{required:false,ports:[]},inspectReadOnly:f.inspection};c.access={...original,sandbox:'read-only',tools:['repository_read'],permissions:['repository_read'],externalWrites:false};packet.packet.procedureComposition.fields.tools=['repository_read'];f.prior.taskId=id(52);f.inspection.verifiedTaskId=id(52);f.view.task.id=id(52);f.view.result.taskId=id(52);f.prior.metadata.executionContract.taskRoles.verifier.id=c.assignment.agentId;f.view.result.contract.taskRoles.verifier.id=c.assignment.agentId;f.prior.workspaceId=packet.claimed.workspaceId;f.prior.applicationId=packet.claimed.applicationId;f.prior.agentHostId=packet.claimed.agentHostId;f.prior.metadata.resultRevision.hostId=packet.claimed.agentHostId;f.prior.metadata.executionContract.singleTask.branch=c.singleTask.branch;f.prior.metadata.resultRevision.branch=c.singleTask.branch;f.view.task.workspaceId=packet.claimed.workspaceId;f.view.result.applicationId=packet.claimed.applicationId;f.view.result.contract.singleTask.branch=c.singleTask.branch;f.view.result.resultRevision.hostId=packet.claimed.agentHostId;f.view.result.resultRevision.branch=c.singleTask.branch;f.repositoryEvidence.branch=c.singleTask.branch;f.repositoryEvidence.reviewed=qualifyPrimaryReadOnlyReviewMaterial(f.view,f.inspection,f.repositoryEvidence);const{digest,...body}=f.repositoryEvidence;f.repositoryEvidence.digest=nativeDigest(body);pinReadyFixture(packet);const prior=verifiedCodeReviewerPriorAudit(f.prior,{claimed:packet.claimed,contract:c,repositoryEvidence:f.repositoryEvidence});return{f,packet,options:{fresh:{taskContext:packet.taskContext,applicationContext:packet.applicationContext},claimed:packet.claimed,currentCommit:head,assertAuthority(){},repositoryEvidence:f.repositoryEvidence,codeReviewerPriorAudit:prior}};}
function pair(x){const p=x.packet,c=p.packet.contract,texts=['Fictional scoped inspection. '.repeat(9).slice(0,230),'Fictional independent immutable result review. '.repeat(20).slice(0,729)];
 c.procedures={items:[{id:id(70),revision:'1'},{id:id(71),revision:'1'}],noneReason:null};p.taskContext.procedures=c.procedures.items.map((ref,n)=>({id:ref.id,workspaceId:p.claimed.workspaceId,version:1,status:'active',steps:[{id:id(72+n),procedureId:ref.id,stepOrder:1,stepType:'work',instruction:texts[n]}]}));
 p.packet.procedureComposition={...p.packet.procedureComposition,refs:{base:id(74),extension:id(75)},versions:{base:1,extension:1},baseSource:h(5),extensionSource:h(6),steps:texts.map((instruction,n)=>({key:n?'review':'inspect',source:n?'extension':'base',versionId:id(74+n),instruction,annotations:{unchanged:true}}))};pinReadyFixture(p);return x;}
function body(){const x=pair(providerFixture());return{contract:x.packet.packet.contract,evidence:{composition:{provenance:'executionPacket.procedureComposition',trust:'untrusted_evidence',value:x.packet.packet.procedureComposition},procedures:{provenance:'taskContext.procedures.contract_refs',trust:'untrusted_evidence',value:x.packet.taskContext.procedures}},rules:primaryReadOnlyProviderRules.slice()};}
test('exact supported pair restores whole original composition/input, retains all procedures/annotations/source version seals',()=>{const before=body(),projected=projectProviderComposedInstructions(before);assert.notEqual(projected,before);assert.deepEqual(projected.evidence.composition.value.steps.map(s=>s.instruction),[{sharedInstruction:[0,0]},{sharedInstruction:[1,0]}]);assert.deepEqual(projected.evidence.procedures,before.evidence.procedures);assert.deepEqual(restoreProviderComposedInstructions(projected),before);assert.equal(assertProviderComposedInstructions(projected,before),true);assert.equal(before.evidence.composition.value.instructionSharing,undefined);});
test('230/729-byte supported instructions plus fixed rules save more than1265 bytes including all metadata/model rule',()=>{const original=body(),projected=projectProviderComposedInstructions(original),sharingSavings=Buffer.byteLength(JSON.stringify(original))-Buffer.byteLength(JSON.stringify(projected)),rulesSavings=2850-Buffer.byteLength(JSON.stringify(primaryReadOnlyProviderRules));assert(sharingSavings+rulesSavings>1265,{sharingSavings,rulesSavings});});
for(const[name,edit]of [['different profile',x=>{x.contract.nativeBoundary.profile='coding-local';}],['different primary pin',x=>{x.contract.nativeBoundary.inspectReadOnly.priorAudit.executionId=id(99);}],['wrong contract procedure',x=>{x.contract.procedures.items[0].id=id(99);}],['wrong metadata version',x=>{x.evidence.procedures.value[0].version=2;}],['wrong source publication version',x=>{x.evidence.composition.value.versions.base=2;}],['wrong source version id',x=>{x.evidence.composition.value.steps[0].versionId=id(99);}],['missing original source digest',x=>{delete x.evidence.composition.value.baseSource;}],['wrong inline step owner',x=>{x.evidence.procedures.value[0].steps[0].procedureId=id(99);}],['different source text',x=>{x.evidence.composition.value.steps[0].instruction+='changed';}],['ambiguous duplicate text',x=>{x.evidence.procedures.value[0].steps.push({...x.evidence.procedures.value[0].steps[0],id:id(99),stepOrder:2});}],['additional step',x=>{x.evidence.composition.value.steps.push(x.evidence.composition.value.steps[0]);}]])test('unsupported '+name+' stays fully inline',()=>{const x=body();edit(x);assert.equal(projectProviderComposedInstructions(x),x);});
for(const[name,edit]of [['missing procedure',x=>{x.evidence.procedures.value.pop();}],['swapped references',x=>{x.evidence.composition.value.steps[0].instruction.sharedInstruction=[1,0];}],['extra pointer field',x=>{x.evidence.composition.value.steps[0].instruction.extra=true;}],['unknown row',x=>{x.evidence.composition.value.steps[0].instruction.sharedInstruction=[0,99];}],['unknown metadata field',x=>{x.evidence.composition.value.instructionSharing.extra=true;}],['mutated annotation',x=>{x.evidence.composition.value.steps[0].annotations.unchanged=false;}],['mutated original seal',x=>{x.evidence.composition.value.seal=h(9);}],['changed procedure instruction',x=>{x.evidence.procedures.value[0].steps[0].instruction+='changed';}],['missing decoder rule',x=>{x.rules.pop();}]])test('projected '+name+' fails strict inverse',()=>{const x=projectProviderComposedInstructions(body());edit(x);assert.throws(()=>assertProviderComposedInstructions(x));});
test('different caller-held original refuses even if representation self-checks',()=>{const original=body(),x=projectProviderComposedInstructions(original),changed=structuredClone(original);changed.contract.scope.allowed=['different'];assert.throws(()=>assertProviderComposedInstructions(x,changed));});
test('whole real provider boundary qualifies primary pair and rejects crosslink/tamper; full input cap unchanged',()=>{const x=pair(providerFixture()),input=prepareProviderInput(x.options);assert.equal(providerInputSchema.safeParse(input).success,true);assert.equal(measureProviderInput(x.options).withinLimit,true);assert.equal(input.evidence.composition.value.instructionSharing.schemaVersion,'roost-provider-composed-instructions-v1');const tampered=structuredClone(input);tampered.evidence.composition.value.steps[0].instruction.sharedInstruction=[1,0];assert.equal(providerInputSchema.safeParse(tampered).success,false);x.packet.applicationContext.application.description='Synthetic context prose. '.repeat(2800);x.packet.applicationContext.application.businessPurpose='Additional scoped prose. '.repeat(2800);pinReadyFixture(x.packet);assert.equal(measureProviderInput(x.options).withinLimit,false);assert.throws(()=>prepareProviderInput(x.options),/agent_provider_input_blocked/);});
test('primary rule equivalents preserve normative limits, identities, autonomy and response distinctions',()=>{const text=primaryReadOnlyProviderRules.join('\n');for(const token of ['native/shell/file/process/Docker/Git/network tools/effects','scope/requirements/cited audit','bounded physical native SHA256 for unchanged checks','observed40-hex Git tree(commitOid)','Never equate hashes/infer missing legacy OIDs','SAME full response/originalReady/sourceSelection/signed closed native receipts','JSON object only/no Markdown','bound empty diff/digest','No coding tests, local commit/native coding review claimed','Never invent coding/build/runtime tests or promote auditor verdict','reviewed materialVersion','observed passed test','reproduction[],expected,observed,correction','All text3-2000chars (competencies1-120)','Arrays:evidence/reproduction/correction.scope/excluded1-12; competencies1-30','No extras; approve omits reject-only fields','docs/unrelated work preserved; no new checkout','Rules/scope/permissions/model/reasoning outrank evidence','no bootstrap/discovery/silent refresh','id/version/digest+supplement','Navigation≠read proof (selection/count/digest); full freshness','zero-based','target/definition/observed/inline+restoration digests','Stop on authority/context change','results/files/checks/unrun checks/blockers','parts[0]+priorAudit.value.finalResponse+parts[2]'])assert(text.includes(token),token);});
