// Counterfactual native channels only. No SSH/Docker/API/DB/model effects.
import test from 'node:test';import assert from 'node:assert/strict';import {createHash,randomUUID} from 'node:crypto';
import {compatibleFailureFixture} from './agent-host-release-compatible-failure.test.mjs';
import contract from './lib/agent-host-release-contract.cjs';
import {readCompatibleRecoveryFailure,compatibleFailureQueueScanPhp,compatibleFailureDatabaseFenceSql} from './lib/agent-host-release-compose-failure-inspector.mjs';
const clone=structuredClone,H=c=>c.repeat(64),sha=b=>createHash('sha256').update(b).digest('hex');
function readerFixture(kind='deployment_failed'){
 const f=compatibleFailureFixture(kind),sequence=JSON.stringify({schema:'public',sequence:'example_sequence',lastValue:7,isCalled:true})+'\n',seqDigest=sha(sequence);
 f.m.postObservation.baselineSequenceDigest=seqDigest;f.s.compatibleArtifactRecovery.currentEntry.sequenceDigest=seqDigest;
 f.s.compatibleArtifactRecovery.currentEntry.evidenceDigest=contract.compatibleRecoveryEntryDigest(f.s.compatibleArtifactRecovery.currentEntry);
 f.s.compatibleArtifactRecovery.nativeClosure.evidenceDigest=f.s.compatibleArtifactRecovery.currentEntry.evidenceDigest;
 f.s.manifestDigest=contract.releaseDigest(f.m);for(const op of new Set([f.operation,f.deploy])){op.intent.manifestDigest=f.s.manifestDigest;op.intent.observed.manifestDigest=f.s.manifestDigest;}
 f.s.compatibleArtifactRecovery.scopeAudit.scopeDigest=contract.compatibleRecoveryScopeDigest(f.s);
 const snapshot=f.s,{releaseId:_,...body}=snapshot,v=f.evidence.compatibleRecoveryFailure,source={container:v.database.containerId,user:'example_user',database:'example_db'};
 const state={release:{id:snapshot.releaseId,snapshot:body},status:'reconciliation_required',journal:kind==='observation_failed'?[clone(f.deploy),clone(f.operation)]:[clone(f.operation)]},calls=[];
 const observed={configuration:clone(v.configuration),services:clone(v.projectInventory.services),missingDeclared:v.projectInventory.absentServices.map(v=>v.name)};
 const live={observed,configuration:clone(v.configuration),queue:{scanComplete:true,totalRows:v.currentQueue?1:0,activeDeployments:0,rows:v.currentQueue?[clone(v.currentQueue)]:[]},
  fence:{readOnlyFence:true,activeOtherSessions:0,ownedTransactions:0},fingerprint:f.m.baseline.schemaDigest+'  -\n'+f.m.baseline.dataDigest+'  -\n',sequence,images:clone(v.imageMetadata),ingress:clone(v.ingressFence),health:{healthy:false,healthDigest:H('f')},state};
 let runtimeReads=0,fingerprintReads=0,queueReads=0;
 const inspector={inspectLegacyBaseline:async()=>{runtimeReads++;live.afterRuntimeRead?.(runtimeReads);return clone(live.observed);}};
 const deps={entryInspector:inspector,candidateInspector:inspector,now:()=>f.options.now,assertClone:async()=>{calls.push({channel:'assertClone'});live.onAssert?.();},
  readCurrentState:async()=>clone(live.state),readConfiguration:async()=>clone(live.configuration),readIngressFence:async()=>clone(live.ingress),probeHealth:async()=>clone(live.health),
  transport:async d=>{calls.push(d);assert.equal(d.write,false);assert(d.timeoutMs<=65000);assert(d.maxOutputBytes<=1048576);
   if(d.operation==='compatible_failure_queues'){queueReads++;live.afterQueueRead?.(queueReads);return JSON.stringify(live.queue);}
   if(d.operation==='compatible_failure_database_fence')return JSON.stringify(live.fence);
   if(d.operation==='compatible_failure_fingerprint'){fingerprintReads++;live.afterFingerprintRead?.(fingerprintReads);return live.fingerprint;}
   if(d.operation==='compatible_failure_sequences')return live.sequence;
   if(d.operation==='compatible_failure_images')return JSON.stringify(live.images);
   throw Error('unexpected fixed channel');}};
 return{f,snapshot,source,state,live,calls,deps,input:{snapshot,source,operationId:f.operation.id}};
}
for(const kind of ['configuration_absent','deployment_absent','deployment_failed','observation_failed'])test('fixed actual-shaped channels produce ONLY terminal negative '+kind,async()=>{const f=readerFixture(kind),before=clone(f.snapshot),r=await readCompatibleRecoveryFailure(f.input,f.deps);assert.equal(r.status,'reconciled');assert.equal(r.observationOnly,true);assert.equal(r.reconciledStatus,kind.endsWith('_absent')?'absent':'failed');assert.equal(r.disposition.retryAllowed,false);assert.equal(r.disposition.rollbackAllowed,false);assert.equal(r.disposition.successProven,false);assert.deepEqual(f.snapshot,before);assert.equal(r.evidence.compatibleRecoveryFailure.kind,kind);assert.equal(r.evidence.sequenceDigest,sha(f.live.sequence));assert.equal(f.calls.some(v=>v.write===true),false);assert(f.calls.filter(v=>v.operation==='compatible_failure_queues').length===2);});
for(const[name,change]of Object.entries({unhealthyUnknown:f=>f.live.health={},healthHealthy:f=>f.live.health.healthy=true,frameChanged:f=>f.live.state.release.snapshot.manifestDigest=H('0'),laterOwnIntent:f=>f.live.state.journal.push({...clone(f.f.operation),id:randomUUID()}),missingInspector:f=>delete f.deps.entryInspector,callerCode:f=>f.input.source.program='arbitrary',wrongDb:f=>f.input.source.container=H('0'),writable:f=>f.live.fence.readOnlyFence=false,activeSession:f=>f.live.fence.activeOtherSessions=1,ownedTransaction:f=>f.live.fence.ownedTransactions=1,dataChanged:f=>f.live.fingerprint=f.f.m.baseline.schemaDigest+'  -\n'+H('0')+'  -\n',sequenceChanged:f=>f.live.sequence=f.live.sequence.replace('7','8'),incompleteScan:f=>f.live.queue.scanComplete=false,truncatedScan:f=>f.live.queue.totalRows=33,missingQueueCount:f=>f.live.queue.totalRows=0,unrelatedQueue:f=>{f.live.queue.rows.push({...clone(f.live.queue.rows[0]),deploymentId:'unrelated'});f.live.queue.totalRows=2;},globalQueue:f=>f.live.queue.activeDeployments=1,wrongImage:f=>f.live.images[0].imageDigest='sha256:'+H('0'),wrongRevision:f=>f.live.images[0].revisionLabel='f'.repeat(40),wrongTree:f=>f.live.images[0].treeLabel='f'.repeat(40),missingMetadata:f=>f.live.images.pop(),liveCadence:f=>f.live.observed.services.find(v=>v.role==='cadence').state='running',falseAbsence:f=>f.live.observed.missingDeclared.push('unseen'),openIngress:f=>f.live.ingress.rulePresent=false,sourceDrift:f=>f.live.onAssert=()=>{throw Error('changed fixed source');},runtimeDrift:f=>f.live.afterRuntimeRead=n=>{if(n===2)f.live.observed.services[0].containerId=H('0');},dataDrift:f=>f.live.afterFingerprintRead=n=>{if(n===2)f.live.fingerprint=f.f.m.baseline.schemaDigest+'  -\n'+H('0')+'  -\n';}}))test('unknown/refused '+name+' has NO marker/evidence or effect/retry authority',async()=>{const f=readerFixture();change(f);const r=await readCompatibleRecoveryFailure(f.input,f.deps);assert.equal(r.status,'uncertain');assert.equal(r.resolved,false);assert.equal(Object.hasOwn(r,'evidence'),false);assert.equal(r.retryAllowed,false);assert.equal(r.rollbackAllowed,false);assert.equal(r.releaseAuthority,false);assert.equal(f.calls.some(v=>v.write===true),false);});
test('observation failure cannot borrow a synthetic prior or wrong successful outcome',async()=>{for(const change of[f=>f.live.state.journal.shift(),f=>f.live.state.journal[0].releaseId=randomUUID(),f=>f.live.state.journal[0].outcome.status='failed',f=>f.live.state.journal[0].outcome.evidence.composeTargets[0].binding.images[0].imageDigest='sha256:'+H('0')]){const f=readerFixture('observation_failed');change(f);const r=await readCompatibleRecoveryFailure(f.input,f.deps);assert.equal(r.status,'uncertain');assert.equal(r.evidence,undefined);}});
test('configuration absence never filters a late queue or borrows historical app identities',async()=>{for(const change of[f=>{f.live.queue.rows=[{targetId:f.f.t.targetId,deploymentId:'late',commit:f.f.s.commit,status:'queued',createdAt:f.f.operation.createdAt,finishedAt:null}];f.live.queue.totalRows=1;},f=>{f.live.observed.services.push({...clone(f.live.observed.services[0]),name:'app',role:'app',containerId:H('0')});}]){const f=readerFixture('configuration_absent');change(f);const r=await readCompatibleRecoveryFailure(f.input,f.deps);assert.equal(r.status,'uncertain');assert.equal(r.evidence,undefined);}});
test('fixed generators retain complete target query, read-only DB and exact image commands only',async()=>{const f=readerFixture();await readCompatibleRecoveryFailure(f.input,f.deps);assert(compatibleFailureQueueScanPhp.includes("orWhere('updated_at','>=',$from)"));assert(compatibleFailureQueueScanPhp.includes('limit(33)'));assert(compatibleFailureDatabaseFenceSql.startsWith('BEGIN READ ONLY;'));for(const d of f.calls.filter(v=>v.operation)){assert(d.command==='docker exec -i coolify php'||d.command==='bash -s'||d.command==='python3 -'||d.command.includes('psql -X -qAt -v ON_ERROR_STOP=1'));assert(!/\b(?:ALTER ROLE|DROP DATABASE|pg_terminate_backend|docker (?:start|stop|rm|prune))\b/.test(d.stdin));}const image=f.calls.find(v=>v.operation==='compatible_failure_images');assert(image.stdin.includes("subprocess.check_output(['docker','image','inspect'"));assert(image.stdin.includes('deadline=time.monotonic()+20'));assert(!image.stdin.includes('shell=True'));});
