"""Bounded package-identity diagnostic, not a Hermes/desktop entry point.

Use the qualification harness with -I -S -B. Site hooks never execute. The
audit hook constrains reviewed Python code; it is not an OS/native sandbox.
Only relative identities and fixed diagnostics may leave this process.
"""
import contextlib
import importlib.metadata as metadata
import importlib.machinery
import importlib.util
import io
import json
import os
from pathlib import Path
import sys

VERSION = "roost-hermes-backend-identity-v1"


class Guard:
    def __init__(self, source, base):
        self.source = Path(source).resolve()
        self.base = Path(base).resolve()
        self.site = self.source / "venv" / "Lib" / "site-packages"
        self.init = self.source / "hermes_cli" / "__init__.py"
        self.denied = False

    def reject(self):
        self.denied = True
        raise RuntimeError("identity_probe_denied")

    def location(self, value):
        if not isinstance(value, (str, bytes, os.PathLike)):
            self.reject()
        return Path(os.fsdecode(value)).resolve()

    def __call__(self, event, values):
        if event == "open":
            target = self.location(values[0])
            if values[2] & (os.O_WRONLY | os.O_RDWR | os.O_CREAT | os.O_TRUNC | os.O_APPEND):
                self.reject()
            if target.name.lower() in {"auth.json", ".env", "cookies", "credentials"}:
                self.reject()
            if target == self.init or target.is_relative_to(self.base):
                return
            # Read distribution declarations, never execute installed .pth code.
            if target.is_relative_to(self.site) and target.name in {"METADATA", "entry_points.txt"}:
                return
            self.reject()
        elif event in {"os.listdir", "os.scandir"}:
            target = self.location(values[0])
            if target in {self.source, self.init.parent} or target.is_relative_to(self.site) or target.is_relative_to(self.base):
                return
            self.reject()
        elif event == "import":
            name, filename = values[:2]
            if name == "hermes_cli":
                return
            if name.startswith(("hermes", "agent", "tools", "gateway", "providers", "run_agent", "site", "ctypes")):
                self.reject()
            if filename and Path(filename).suffix.lower() in {".pyd", ".dll", ".so"}:
                self.reject()
        elif event in {"exec", "compile"}:
            filename = values[0].co_filename if event == "exec" else values[1]
            if isinstance(filename, str) and filename.startswith("<frozen "):
                return
            target = self.location(filename)
            if target != self.init and not target.is_relative_to(self.base):
                self.reject()
        elif event not in {"marshal.loads", "sys._getframe", "sys._getframemodulename", "object.__getattr__", "builtins.id"}:
            # Includes sockets, process creation, ctypes and all mutations.
            self.reject()


def run():
    if not (sys.flags.isolated and sys.flags.no_site and sys.dont_write_bytecode):
        raise ValueError("flags")
    args = json.loads(sys.stdin.read(8193))
    if set(args) != {"sourceRoot", "pythonBase", "syntheticRoot"}:
        raise ValueError("input")
    source, base, synthetic = (Path(args[k]).resolve() for k in ("sourceRoot", "pythonBase", "syntheticRoot"))
    interpreter = source / "venv" / "Scripts" / "python.exe"
    if Path(sys.executable).resolve() != interpreter or Path(sys.base_prefix).resolve() != base:
        raise ValueError("interpreter")
    if Path(os.environ["HERMES_HOME"]).resolve() != synthetic or list(synthetic.iterdir()):
        raise ValueError("home")
    site = source / "venv" / "Lib" / "site-packages"
    sys.path[:0] = [str(source), str(site)]
    # Resolve the package normally on this explicit search path, then execute
    # only its attested source, never unqualified generated bytecode.
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")
    guard = Guard(source, base)
    sys.addaudithook(guard)
    with contextlib.redirect_stdout(io.StringIO()) as captured:
        spec = importlib.machinery.PathFinder.find_spec("hermes_cli", sys.path)
        if not spec or Path(spec.origin).resolve() != source / "hermes_cli" / "__init__.py":
            raise ValueError("origin")
        hermes_cli = importlib.util.module_from_spec(spec)
        sys.modules["hermes_cli"] = hermes_cli
        exec(compile(Path(spec.origin).read_bytes(), spec.origin, "exec"), hermes_cli.__dict__)
        distributions = list(metadata.distributions(path=[str(site)]))
        found = [d for d in distributions if d.metadata.get("Name", "").lower().replace("_", "-") == "hermes-agent"]
        selected = metadata.distribution("hermes-agent")
        entries = [e.value for e in selected.entry_points if e.group == "console_scripts" and e.name == "hermes"]
        result = {
            "schemaVersion": VERSION, "result": "measured",
            "mechanism": "isolated_no_site_source_import",
            "pythonVersion": ".".join(map(str, sys.version_info[:3])),
            "interpreter": Path(sys.executable).resolve().relative_to(source).as_posix(),
            "moduleOrigin": Path(hermes_cli.__file__).resolve().relative_to(source).as_posix(),
            "moduleVersion": hermes_cli.__version__, "metadataVersion": metadata.version("hermes-agent"),
            "distributions": sorted([{"path": Path(d._path).resolve().relative_to(source).as_posix(),
                                      "version": d.version} for d in found], key=lambda d: d["path"]),
            "entrypoint": entries[0] if len(entries) == 1 else None,
            "mainImported": "hermes_cli.main" in sys.modules,
            "siteHooksExecuted": False, "protocolQualified": False,
        }
    if guard.denied or captured.getvalue() or result["mainImported"]:
        raise RuntimeError("unexpected_effect")
    return result


if __name__ == "__main__":
    try:
        answer = run()
        encoded = json.dumps(answer, separators=(",", ":"), sort_keys=True)
        if len(encoded.encode()) > 8192:
            raise ValueError("output")
    except BaseException:
        encoded = json.dumps({"schemaVersion": VERSION, "result": "blocked", "reason": "identity_probe_failed_closed"})
    print(encoded)
