import assert from "node:assert/strict";
import { createServer } from "node:http";
import { once } from "node:events";
import { mkdir, readFile, readdir } from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { createRequire } from "node:module";
import { build } from "esbuild";
import { chromium } from "playwright";
const { reviewDecisionSchema, reviewActionSchema } = createRequire(import.meta.url)("../dist/modules/agent-runtime/task-review-contract.js");
const output=path.join(os.tmpdir(),"roost-review-ui");await mkdir(output,{recursive:true});
const bundle=await build({stdin:{contents:`import React from 'react';import{createRoot}from'react-dom/client';import{LanguageProvider}from'./web/src/i18n/i18n';import{TaskReviewModal}from'./web/src/features/departments/task-review';createRoot(document.getElementById('root')).render(<LanguageProvider><TaskReviewModal taskId="00000000-0000-4000-8000-000000000001" onClose={()=>window.closedReview=true}/></LanguageProvider>);`,resolveDir:process.cwd(),loader:"tsx"},bundle:true,write:false,jsx:"automatic",define:{"process.env.NODE_ENV":'"test"'}});
const cssName=(await readdir("public/react/assets")).find(n=>/^index-.*\.css$/.test(n)),css=await readFile(path.join("public/react/assets",cssName));
const server=createServer(async(req,res)=>{if(req.url.startsWith("/vendor/phosphor/bold/")){const name=path.basename(req.url);try{const data=await readFile(path.join("node_modules/@phosphor-icons/web/src/bold",name));res.setHeader("Content-Type",name.endsWith("css")?"text/css":"font/woff2");return res.end(data);}catch{res.writeHead(404);return res.end();}}if(req.url==="/app.js"){res.setHeader("Content-Type","text/javascript");return res.end(bundle.outputFiles[0].contents);}if(req.url==="/style.css"){res.setHeader("Content-Type","text/css");return res.end(css);}res.setHeader("Content-Type","text/html");res.end('<!doctype html><html data-theme="roost"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/vendor/phosphor/bold/style.css"><body><div id="root"></div><script src="/app.js"></script></body></html>');});
server.listen(0,"127.0.0.1");await once(server,"listening");const browser=await chromium.launch({headless:true});let checked=0;
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const correction={scope:["Handle empty parser input"],excluded:["No unrelated parser changes"],outcome:"Empty input returns a validation message",competencies:["javascript"]};
const proof={summary:"Empty input throws",reproduction:["Run the empty parser fixture"],expected:"A validation message",observed:"An exception is thrown",evidence:[{kind:"test",reference:"npm test -- parser",result:"Empty input fails"}],correction};
const reviewed={id:id(3),executionId:id(2),materialVersion:"b".repeat(64),decision:"reject",evidence:proof,verifierLabel:"Independent reviewer",actorUserId:id(4),createdAt:"2026-09-08T10:00:00Z",action:null};
function fixture(mode){return {task:{id:id(1),title:"Repair the fixture parser"},expectedVersion:"a".repeat(64),materialVersion:"b".repeat(64),result:mode==="empty"?null:{executionId:id(2),attempt:1,completedAt:"2026-09-08T09:45:00Z",summary:"Parser correction submitted",finalResponse:"Changed empty-input validation.",changedFiles:["src/parser.ts"],verification:{command:"npm test -- parser",result:"one failed assertion"},contract:{assignment:{agentId:id(5)}}},labels:{verifier:"Independent reviewer",manager:"Accountable manager"},decision:["manager","history"].includes(mode)?structuredClone(reviewed):mode==="approved"?{...reviewed,decision:"approve"}:null,canReview:mode==="review",canManage:mode==="manager",reason:{empty:"no_result",stale:"stale_result",roles:"roles_need_context",viewer:"verifier_required",history:"manager_required",approved:"approved"}[mode]??null,history:["manager","history","approved"].includes(mode)?[{...reviewed,...(mode==="approved"?{decision:"approve"}:{})}]:[],nextCursor:null,specialists:[{id:id(6),label:"Parser specialist",revision:"2026-09-08T09:00:00Z",role:"developer",competencies:["javascript"]}],specialistsTruncated:false};}
async function pageFor(locale,mode,width=1440){const page=await browser.newPage({viewport:{width,height:960},reducedMotion:"reduce"});await page.addInitScript(v=>localStorage.setItem("companycoreLocale",v),locale);const packet=fixture(mode==="retry"?"review":mode==="agent-history"?"approved":mode);if(mode==="agent-history"){Object.assign(packet.history[0],{verifierLabel:null,actorUserId:null,actorAgentId:id(4),actorCredentialId:id(9),actorCredentialPrefix:"cc_v1_fixture"});}let posts=[];
await page.route("**/v1/**",async route=>{if(mode==="loading")return;if(mode==="error")return route.fulfill({status:500,json:{error:{code:"fixture_error"}}});if(route.request().method()==="POST"){const body=route.request().postDataJSON();posts.push(body);if(mode==="retry" && posts.length===1)return route.fulfill({status:503,json:{error:"temporary_failure"}});const isAction=route.request().url().endsWith("review-return");const parsed=(isAction?reviewActionSchema:reviewDecisionSchema).safeParse(body);assert.ok(parsed.success,JSON.stringify(parsed));packet.canReview=false;packet.canManage=false;packet.reason=isAction?"action_recorded":body.decision==="approve"?"approved":"manager_required";packet.history=[{...reviewed,decision:body.decision??"reject",action:isAction?{...body,managerLabel:"Accountable manager",actorUserId:id(7),correction,childTaskId:body.action==="create_specialist_task"?id(8):null}:null}];return route.fulfill({json:{data:{}}});}return route.fulfill({json:{data:packet}});});await page.goto(`http://127.0.0.1:${server.address().port}`);return {page,packet,posts};}
try{
for(const locale of ["pl","en"])for(const width of [390,834,1440])for(const mode of ["review","manager","approved","empty","stale","roles","viewer","error","loading","agent-history"]){const {page}=await pageFor(locale,mode,width);await page.getByRole("dialog").waitFor();if(!["error","loading"].includes(mode))await page.getByRole("heading",{name:"Repair the fixture parser",exact:true}).waitFor();else await page.waitForTimeout(100);await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(output,`${locale}-${mode}-${width}.png`),fullPage:true});await page.close();checked++;}
for(const locale of ["pl","en"]){
 const label=locale==="pl"?{decision:"Decyzja oceny",summary:"Uzasadnienie oceny",reference:"Odnośnik do dowodu lub testu",testResult:"Wynik dowodu lub testu",reproduction:"Kroki reprodukcji",expected:"Oczekiwane zachowanie",observed:"Zaobserwowane zachowanie",scope:"Wymagany zakres korekty",excluded:"Wykluczone zmiany",outcome:"Jeden wymagany wynik korekty",competencies:"Wymagane kompetencje specjalisty",review:"Zapisz decyzję oceny",action:"Zapisz sposób korekty",disposition:"Decyzja managera",specialist:"Kompetentny specjalista",saved:"Decyzja została zapisana w historii zadania."}:{decision:"Review decision",summary:"Assessment",reference:"Evidence or test reference",testResult:"Evidence or test result",reproduction:"Reproduction steps",expected:"Expected behavior",observed:"Observed behavior",scope:"Required correction scope",excluded:"Excluded changes",outcome:"One required correction outcome",competencies:"Required specialist competencies",review:"Record review decision",action:"Record correction disposition",disposition:"Manager decision",specialist:"Competent specialist",saved:"Decision recorded in task history."};
 for(const decision of ["approve","reject"]){const {page,posts}=await pageFor(locale,"review",390);await page.getByLabel(label.decision,{exact:true}).selectOption(decision);await page.getByRole("button",{name:label.review,exact:true}).click();assert.equal(posts.length,0);const values={summary:proof.summary,reference:proof.evidence[0].reference,testResult:proof.evidence[0].result,...(decision==="reject"?{reproduction:proof.reproduction.join("\n"),expected:proof.expected,observed:proof.observed,scope:correction.scope.join("\n"),excluded:correction.excluded.join("\n"),outcome:correction.outcome,competencies:"javascript"}:{})};for(const[key,value]of Object.entries(values))await page.getByLabel(label[key],{exact:false}).fill(value);await page.getByRole("button",{name:label.review,exact:true}).click();await page.getByText(label.saved,{exact:true}).waitFor();assert.equal(posts.length,1);assert.equal(posts[0].decision,decision);await page.close();checked++;}
 const retry=await pageFor(locale,"retry",1440);await retry.page.getByLabel(label.decision,{exact:true}).selectOption("approve");for(const key of ["summary","reference","testResult"])await retry.page.getByLabel(label[key],{exact:false}).fill("Reviewed synthetic evidence");await retry.page.getByRole("button",{name:label.review,exact:true}).click();await retry.page.getByRole("alert").waitFor();await retry.page.getByRole("button",{name:label.review,exact:true}).click();await retry.page.getByText(label.saved,{exact:true}).waitFor();assert.equal(retry.posts.length,2);assert.deepEqual(retry.posts[0],retry.posts[1]);await retry.page.close();checked++;
 for(const action of ["return_to_executor","create_specialist_task"]){const {page,posts}=await pageFor(locale,"manager",834);await page.getByLabel(label.disposition,{exact:true}).selectOption(action);if(action==="create_specialist_task")await page.getByLabel(label.specialist,{exact:false}).selectOption(id(6));await page.getByRole("button",{name:label.action,exact:true}).click();await page.getByText(label.saved,{exact:true}).waitFor();assert.equal(posts.length,1);assert.equal(posts[0].action,action);await page.screenshot({path:path.join(output,`${locale}-${action}-accepted.png`),fullPage:true});await page.close();checked++;}
}
console.log(JSON.stringify({checked,output}));
}finally{await browser.close();server.close();}
